### ISSUE TITLE
Issue scraping messages

### ISSUE THREAD

**Issue by dpsbrdi** [sim0n00ps/OF-DL#1]
Input string '15.5' is not a valid integer. Path 'list[2].price', line 1, position 10706.

happened during scraping of free messages - didn't download anything just said it found 0 messages, went on to scrape paid messages fine

edit: using latest commit

**Comment by sim0n00ps** [comment]
Please try the latest release, hopefully it will be fixed. If it does let me know and I'll close the issue.
