### ISSUE TITLE
Program opens and then closes immediately 

### ISSUE THREAD

**Issue by Wolfeman0101** [sim0n00ps/OF-DL#10]
I see the Welcome... and then it just closes.  I followed all the instructions.

**Comment by MillerTimeJones** [comment]
Same issue here

**Comment by undream22** [comment]
Been messing with this for a while. Stupid simple issue, lol. I had to change my `\` to `/`.


> I would recommend copying all 3 of the .exe files somewhere safe where you can then add the path of each file to auth.json file. You can do this easily by holding shift when right clicking on the .exe file which should give you the option to copy as path, this will include \ so you will need to replace them with /. In the auth.json file the lines should look something like this "YTDLP_PATH": "C:/yt-dlp.exe", "FFMPEG_PATH": "C:/ffmpeg.exe" and "MP4DECRYPT_PATH": "C:/mp4decrypt.exe"

**Comment by Wolfeman0101** [comment]
> Had this issue too and it took me way too long to figure it out. Stupid simple issue, lol. I had to change my `\` to `/`.
> 
> > I would recommend copying all 3 of the .exe files somewhere safe where you can then add the path of each file to auth.json file. You can do this easily by holding shift when right clicking on the .exe file which should give you the option to copy as path, this will include \ so you will need to replace them with /. In the auth.json file the lines should look something like this "YTDLP_PATH": "C:/yt-dlp.exe", "FFMPEG_PATH": "C:/ffmpeg.exe" and "MP4DECRYPT_PATH": "C:/mp4decrypt.exe"

This fixed it for me.  I guess I didn't read the fucking manual.  This can be closed.
