### ISSUE TITLE
Can't download DRM videos - id blob problem

### ISSUE THREAD

**Issue by MartinSLI** [sim0n00ps/OF-DL#100]
He hecho todo como en el tutorial pero al intentar descargar los videos comprados de una modelo me sale esto:
"No Client ID blob found" como resuemn del error que está mejor explicado aquí:
![image](https://github.com/sim0n00ps/OF-DL/assets/122678532/e8a279af-5ea8-4735-a913-e336c6a3ec70)

**Comment by Puk0** [comment]
> "No Client ID blob found"

¿ Tienes dentro de \cdm\devices\chrome_1610 los archivos device_private_key y device_client_id_blob (asi sin extensión)?

Checa en el "explorador" que este marcado en > vista > extensiones de nombre de archivo

**Comment by MartinSLI** [comment]
Efectivamente uno de los 2 archivos device_private_key y device_client_id_blob tenia la extension escondida, hasta que no se lo quité no funcionó, gracias, a dia 23 de julio ya puedo descargar videos con DREM de OF.
Una última duda: ¿hace falta tener abierto siempre todos esos programas del emulador de android y las 2 terminales que mantiene el server de android cada vez que quiera ripear contenido de OF (todo eso me sirvio para conseguir los 2 archivos del private key e id blob?
![image](https://github.com/sim0n00ps/OF-DL/assets/122678532/b4050ee5-80ed-4d1e-9de8-7225ff8d717f)

**Comment by sim0n00ps** [comment]
> Efectivamente uno de los 2 archivos device_private_key y device_client_id_blob tenia la extension escondida, hasta que no se lo quité no funcionó, gracias, a dia 23 de julio ya puedo descargar videos con DRM de OF.
> Una última duda: ¿hace falta tener abierto siempre todos esos programas del emulador de android y las 2 terminales que mantiene el server de android cada vez que quiera ripear contenido de OF (todo eso me sirvio para conseguir los 2 archivos del private key e id blob)? O una vez ya conseguí esos 2 archivos ya puedo cerrar todo y solamente tener abierto el OF-DL y ya?
> ![image](https://github.com/sim0n00ps/OF-DL/assets/122678532/b4050ee5-80ed-4d1e-9de8-7225ff8d717f)
> 

Once you get the keys you can close everything
