### ISSUE TITLE
Feature request: Make content automatically sorted into folders by date of post during download.

### ISSUE THREAD

**Issue by KingVitto** [sim0n00ps/OF-DL#101]
Hey!
Thanks for the script. I just tried it, and it successfully scraped a profile.
1 thing is missing to make it perfect though =)
It would've been nice if the downloaded media was automatically sorted into folders by date of post.
Having a folder with 2000+ images is kind of a mess, cause the creator was posting those pics in "sets", and now I have to manually assemble these sets by moving photos to separate folders by date...
I'm sure it's not too difficult to implement such a thing.
Thanks in advance ^^

**Comment by sim0n00ps** [comment]
It can be done and just added as an option in the Auth.json

**Comment by T3rminat0r** [comment]
I am assuming that this is not yet merged or even pushed? ;) (can't seem to find any mention of that option anywhere in the last released app, nor in the sourcecode on main branch? ;) )

**Comment by sim0n00ps** [comment]
Yes because I haven't got around to making this yet

**Comment by sim0n00ps** [comment]
Just coming back to this, would you not want this to be by Post/Message Id so a folder would be created for each post/message and then within that folder is the media
Examples:
{POSTID} -> {Image 1}, {Image 2}, {Video 1} etc
{MESSAGEID} -> {Image 1}, {Image 2}, {Video 1} etc

or have a folder for each date where post(s) have been made
Examples:
{2023-08-08} -> {POSTID} -> {Image 1}, {Image 2}, {Video 1} etc
{2023-08-01} -> {MESSAGEID} -> {Image 1}, {Image 2}, {Video 1} etc

I am only asking because obviously multiple posts/messages are going made each day.

**Comment by KingVitto** [comment]
> or have a folder for each date where post(s) have been made
> {2023-08-08} -> {POSTID} -> {Image 1}, {Image 2}, {Video 1} etc
> {2023-08-01} -> {MESSAGEID} -> {Image 1}, {Image 2}, {Video 1} etc

Yeah, something like this! Looks perfect.

**Comment by T3rminat0r** [comment]
I'd love to see date + PostID as the foldername, actually, so one folder per post, but also have the date first, so they're sorted by post-date, if that makes sense?

**Comment by sim0n00ps** [comment]
> I'd love to see date + PostID as the foldername, actually, so one folder per post, but also have the date first, so they're sorted by post-date, if that makes sense?

So an example would be 2023-08-08 123456789?

**Comment by T3rminat0r** [comment]
> So an example would be 2023-08-08 123456789?

yea, or 2023-08-08_123456789 or something ... :)

**Comment by sim0n00ps** [comment]
> > So an example would be 2023-08-08 123456789?
> 
> yea, or 2023-08-08_123456789 or something ... :)

That's definitely the one I think is better, mainly because making the folder for each date that has posts/messages and then populating that folder with all of the posts/messages on that date might get messy so it would be easier for me to just create a folder per post/message. Hopefully @KingVitto is fine with that format and that fits what he wants.

**Comment by KingVitto** [comment]
Yeah, that's fine.
Thank you ;)

**Comment by T3rminat0r** [comment]
For the file_naming (not folders, but filenaming, as per https://github.com/sim0n00ps/OF-DL/wiki/Custom-Filename-Formats), there's a mistake on that wiki page. It lists the attribute `postedAt` for MessageFileNameFormat, where it should actually say `createdAt`, there too. So, Messages are created, Posts are posted ;) @sim0n00ps 
Apart from that minor typo, that feature works great, and even sorts the preview-pictures (from the free folder) correctly between the paid ones when using the  name format of `{createdAt}_{username}_{id}_{filename}` for messages (paid and free) and `{postedAt}_{username}_{id}_{filename}` for posts. :) (maybe also Link to that Wiki-Page at the end of the README.md? )

**Comment by sim0n00ps** [comment]
> For the file_naming (not folders, but filenaming, as per https://github.com/sim0n00ps/OF-DL/wiki/Custom-Filename-Formats), there's a mistake on that wiki page. It lists the attribute `postedAt` for MessageFileNameFormat, where it should actually say `createdAt`, there too. So, Messages are created, Posts are posted ;) @sim0n00ps Apart from that minor typo, that feature works great, and even sorts the preview-pictures (from the free folder) correctly between the paid ones when using the name format of `{createdAt}_{username}_{id}_{filename}` for messages (paid and free) and `{postedAt}_{username}_{id}_{filename}` for posts. :) (maybe also Link to that Wiki-Page at the end of the README.md? )

Edited the wiki. Will start working on this soon, shouldn't be too difficult to add

**Comment by sim0n00ps** [comment]
Coming back to this again, I can either make the paths 1 of 2 options:
{username}->Posts->Free->Images->{Post/Message Id}->Post Images
{username}->Posts->Free->Videos->{Post/Message Id}->Post Videos

or

{username}->Posts->Free->{Post/Message Id}->Post Images
{username}->Posts->Free->{Post/Message Id}->Post Videos

Let me know which one you think is better

**Comment by T3rminat0r** [comment]
@sim0n00ps neither of those options contains the posting date? (My personal usecase is, to a)sort the media by post, AND b) by post date, so it's cronological...) Generally, I'd prefer the Free/Paid folder to be further in front of the folder structure, but the post-folders should still contain the date?

**Comment by sim0n00ps** [comment]
Yes I forgot to include the date in the folder name. Which one would be best for you then?

**Comment by T3rminat0r** [comment]
For me, definitly the second option you listed. All media from a post in a single folder. Whether it's images or Videos.

**Comment by sim0n00ps** [comment]
I have now added the code and config values for this feature. It is 4 bools for Paid Posts, Posts, Paid Messages and Messages. The output folders will now be Posts/Free/{Post/Message ID} {yyyy-mm-dd hh:mm:ss}/Images or Posts/Free/{Post/Message ID} {yyyy-mm-dd hh:mm:ss}/Videos. I still included the Images and Videos folders just to keep it consistent and also to keep the structure neat. I haven't created a release with these changes yet as I am waiting on a pull request with some other features, once I've got those I will create a new release.

**Comment by chadfrank74** [comment]
For the FileNameFormat options in the config file, using the field {text} seems to work, but for certain text, it fails and reverts to the default file format. Would it be possible to filter out invalid characters to ensure a valid filename while still using the {text} field option? If possible, it would also be helpful to add a "max length" option for the text.

**Comment by sim0n00ps** [comment]
Now included in latest release

**Comment by sim0n00ps** [comment]
> For the FileNameFormat options in the config file, using the field {text} seems to work, but for certain text, it fails and reverts to the default file format. Would it be possible to filter out invalid characters to ensure a valid filename while still using the {text} field option? If possible, it would also be helpful to add a "max length" option for the text.

I strongly advise against using the text field as it will cause you nothing but problems when it comes to filenames, trying to filter out the invalid characters is very annoying as I've tried before but gave up in the end as there are so many different possible combinations

**Comment by chadfrank74** [comment]
> > For the FileNameFormat options in the config file, using the field {text} seems to work, but for certain text, it fails and reverts to the default file format. Would it be possible to filter out invalid characters to ensure a valid filename while still using the {text} field option? If possible, it would also be helpful to add a "max length" option for the text.
> 
> I strongly advise against using the text field as it will cause you nothing but problems when it comes to filenames, trying to filter out the invalid characters is very annoying as I've tried before but gave up in the end as there are so many different possible combinations

I really would like to use {text} as it gives some idea of what the content in the files is about. If you'd be willing to put in a bit more time, something like this should work:
`public static string RemoveInvalidFileNameChars(string fileName)
{
    return string.Concat(fileName.Split(System.IO.Path.GetInvalidFileNameChars()));
}`

**Comment by sim0n00ps** [comment]
Just tried that and sort of worked but still did not strip out the html tags and hrefs etc, try and do it yourself and if its successful then create a pull request

**Comment by chadfrank74** [comment]
> Just tried that and sort of worked but still did not strip out the html tags and hrefs etc, try and do it yourself and if its successful then create a pull request

Done!
