### ISSUE TITLE
Progress bar does not show remaining time and amount downloaded

### ISSUE THREAD

**Issue by Puk0** [sim0n00ps/OF-DL#103]
Llevaba 200mb y no marco nada 
![2023-07-24 00-43-22](https://github.com/sim0n00ps/OF-DL/assets/138377242/79eacf2a-76c6-40f4-9dda-9f10f4b5c6d3)
![2023-07-24 00-43-48](https://github.com/sim0n00ps/OF-DL/assets/138377242/058a934c-8517-49e8-b002-41adb939a4e5)

Solo cuando finalizo marco 100% 239mb/239mb 
![2023-07-24 00-48-24](https://github.com/sim0n00ps/OF-DL/assets/138377242/06e5c293-09be-4795-8021-59beb29d12b9)

En archivo con drm
Con un solo archivo mp4
Windows 10
Versión 1.7.25.exe

**Comment by sim0n00ps** [comment]
I can't show progress because it's being downloaded with yt-dlp so I can't reference it anywhere in the code, once it has been downloaded the progress will increment by the file size
