### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#105]
Hello, I wanted to ask before I mess anything up all the folders and software that were used to get the [client_id_blob and device_private_key] once I get the code and have verified download successful and scrap do i need to still keep the android software and other folders or can I remove them?

**Comment by sim0n00ps** [comment]
Once you've got the keys and you know they work, yes you can remove android studio and the rest of it. If they stop working then you'll just have to repeat the process and re-download everything again.
