### ISSUE TITLE
Have Trouble Dumping Keys

### ISSUE THREAD

**Issue by Higgis39** [sim0n00ps/OF-DL#108]
Sorry for posting here! I stuck in dumping keys step. I cannot play the drm video from bitmovin.com/demos/drm, it always shows:
![image](https://github.com/sim0n00ps/OF-DL/assets/18494359/86cbc5e8-d9ed-44ae-8731-814e914bf0af)

And here are the avd properties:
Properties
avd.ini.displayname              Pixel 6 API 28
avd.ini.encoding                 UTF-8
AvdId                            Pixel_6_API_28
disk.dataPartition.size          6442450944
fastboot.chosenSnapshotFile
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     2
hw.device.hash2                  MD5:3db3250dab5d0d93b29353040181c7e9
hw.device.manufacturer           Google
hw.device.name                   pixel_6
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            Portrait
hw.keyboard                      yes
hw.lcd.density                   420
hw.lcd.height                    2400
hw.lcd.width                     1080
hw.mainKeys                      no
hw.ramSize                       1536
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         28
image.sysdir.1                   system-images\android-28\google_apis\x86\
PlayStore.enabled                false
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google APIs
tag.id                           google_apis
vm.heapSize                      228

Is there anyone meeting the same issue and tell me how to solve it? Thanks in advance!!

**Comment by sim0n00ps** [comment]
Well you're not connected to the internet hence why you can't play the video

**Comment by Higgis39** [comment]
Finally it worked!!! By setting proxy for avd!
