### ISSUE TITLE
FeatureRequest: Multiple OF-Accounts

### ISSUE THREAD

**Issue by T3rminat0r** [sim0n00ps/OF-DL#109]
Hi!
Love the tool, apart from automatically sorting files into folders by post/post-date, I'd love to see an option to keep multiple OF-Accounts in the tool, and either switch between them, or even scrape them after each other/at the same time? (Like, have multiple cdms, or on the same cdm, but different cookies/userids (b-xc and user-agent do stay identical, for me, when I switch users in my actual browser) .. :) Just a thought to make things less of a hassle to get things from the other account (cause, otherwise, i have to manually edit the file, each time I want to switch, cause the cookie does change each time, but you COULD get valid cookies from two different browsers / profiles, which then both would still work for of-dl?)

**Comment by sim0n00ps** [comment]
I know this has been sat here awhile but I'm just going to suggest if you ever want to have 2 or more accounts then use an instance of OF-DL per account and you could set the DownloadLocation to the same directory in the config.json.
