### ISSUE TITLE
Program open then Closes Immediately

### ISSUE THREAD

**Issue by MazdaLaw** [sim0n00ps/OF-DL#11]
I looked at the other issue that was created, and I made sure to look over every thing that was said in the other one, and I made sure that there errors weren't on my end, and they aren't.

**Comment by sim0n00ps** [comment]
Ensure you've followed all of the steps correctly, usually if it's crashing on startup it's down to something you've done as the program runs fine if set up correctly on my machine and other people's machines as well.

**Comment by MazdaLaw** [comment]
Would using Opera GX have anything to do with it?

**Comment by sim0n00ps** [comment]
I can't imagine that being the issue. As long as you've logged into OF on that browser and the session information you've used is from your login session within that browser then it should be fine. Might be worth opening where you have the .exe located in command prompt and typing "OF DL.exe" should run the program the same way as double clicking on it , hopefully that will display the error you're getting instead of the windows disappearing.

**Comment by MazdaLaw** [comment]
It keeps doing the same thing, and I've made sure that it's all correct. Would the issue be that it's on a separate drive from the windows installation drive?

**Comment by MazdaLaw** [comment]
Also, do I need to keep the whole zip folder, or can I just extract the exe from the zip?

**Comment by sim0n00ps** [comment]
No I have my exe located on a separate drive so that also isn't the issue. Does your zip file have an auth.json and OF DL.exe?

**Comment by MazdaLaw** [comment]
It does, but for the other exe files, do I need to keep them in those folders and what not, and make the path to that after I unzip them?

**Comment by MazdaLaw** [comment]
![image_2023-05-19_034733234](https://github.com/sim0n00ps/OF-DL/assets/134043921/cd093df3-014c-4cec-8011-f7416817cfe9)

**Comment by sim0n00ps** [comment]
No you can move ffmpeg, yt-dlp and mp4decrypt to another folder. I would recommend you put all 3 files in a single folder somewhere safe. If you've done it correctly then you should have 3 files, ffmpeg.exe, yt-dlp.exe and mp4decrypt.exd. Then you need to put the path for each of them in the auth.json. So my folder is called DRMEXES and it's on my E: drive so in my auth.json the file path for ffmpeg would be E:/DRMEXES/ffmpeg.exe, same for the other 2 you just need to change ffmpeg.exe to mp4decrypt.exe yt-dlp.exe.

**Comment by MazdaLaw** [comment]
Okay, I've done all of that, and it still opens then closes, it says everything is located successfully, it just closes right after that and doesn't do anything else

**Comment by sim0n00ps** [comment]
That indicates that the auth is failing then, you don't see it say Logged in successfully as {Username} {User-Id} ?

**Comment by MazdaLaw** [comment]
I do not

**Comment by sim0n00ps** [comment]
I would double check your Auth file then, it might be because your Auth file is missing properties that it needs to run the latest version.

**Comment by MazdaLaw** [comment]
The newest version is 1.6.1, correct?

**Comment by sim0n00ps** [comment]
> The newest version is 1.6.1, correct?

Yes, newer release will be released later today hopefully.

**Comment by sim0n00ps** [comment]
> ![image](https://github.com/sim0n00ps/OF-DL/assets/134043921/c8b2d6f1-2598-41d7-89c4-47ae5573e016)
> This is what I have from the 1.6.1 download, if there is anything missing, let me know.
> 

Looks fine to me, as long as the auth.json file is from the 1.6.1 zip file then should be good.

**Comment by Wonton77** [comment]
Same issue.

- Installed and verified .NET runtime
- Downloaded ytdlp, ffmpeg, and Bento
- Downloaded and extracted OF-DL
- added 3 file directories to auth.json
- filled in USER_ID, USER_AGENT, X_BC, and COOKIE fields

Now OF DL.exe launches, I see the "Welcome to OF DL" red ascii text for a brief second, and it immediately closes.

**Comment by Wonton77** [comment]
> Same issue.
> 
>     * Installed and verified .NET runtime
> 
>     * Downloaded ytdlp, ffmpeg, and Bento
> 
>     * Downloaded and extracted OF-DL
> 
>     * added 3 file directories to auth.json
> 
>     * filled in USER_ID, USER_AGENT, X_BC, and COOKIE fields
> 
> 
> Now OF DL.exe launches, I see the "Welcome to OF DL" red ascii text for a brief second, and it immediately closes.

Jesus christ, missed the instruction to replace "\" with "/" in the URLs, and now it runs perfectly.
Alright then.

**Comment by Wandererinchaos007** [comment]
BUMP.

I'm having the exact same issue. Followed everything to a tee. updated to the latest version an hour ago and program still doesnt stay open. please help.

**Comment by sim0n00ps** [comment]
Do you see anything at all?

**Comment by Wandererinchaos007** [comment]
> Do you see anything at all?

The red welcome message pops up with the window but it closes straight away.

**Comment by Wandererinchaos007** [comment]
Just to clarify, when replacing \ with  /  is it just the ones in the paths for the 3 exe files or is it for all the ones in the entire file?

do we include the " " or no? like the example you put "USER_ID": "123456789" 

For the COOKIE option is it just auth and sess like the example or all of it "COOKIE": "auth_id=123456789; sess=k3s9tnzdc8vt2h47ljxpmwqy5r;"

I'm trying to do it with them and without.

**Comment by sim0n00ps** [comment]
Yes the paths to the .exe files need to have /, they shouldn't contain any \.
Yes the only 2 fields you need are auth_id and sess in the COOKIE everything else can be ignored, so it should look like this - "COOKIE": "auth_id=123456789; sess=k3s9tnzdc8vt2h47ljxpmwqy5r;" obviously change them to your own auth_id and sess values

**Comment by Wandererinchaos007** [comment]
tried it again, redownloaded it as well with a fresh one. still not working man :/

**Comment by sim0n00ps** [comment]
Send me your auth.json file here, remove the sess, auth_id stuff etc

**Comment by Wandererinchaos007** [comment]
No need for that bro, goodness I somehow managed to fix it. Started with a fresh file again and filled it in. Third time's the charm. Logged in successfully. Will let you know if anything else pops up. Appreciate the help for now.

**Comment by sim0n00ps** [comment]
> No need for that bro, goodness I somehow managed to fix it. Started with a fresh file again and filled it in. Third time's the charm. Logged in successfully. Will let you know if anything else pops up. Appreciate the help for now.

No problem glad you fixed it, any further issues you have make a new issue on here and I'll be more than happy to try and help
