### ISSUE TITLE
Bug: Missing the "free" media from paidMessages

### ISSUE THREAD

**Issue by T3rminat0r** [sim0n00ps/OF-DL#110]
Hi, when downloading a paidMessage, it seems that OF-DL is missing the "free" picture(s)/video(s) in that post. (i.e. the teaser(s)/first (few) images, that are shown even before you pay for it.) (I just noticed, when downloading imagesets, that there was consistenly one misisng, but not always at the same spot, until I noticed it was always the free image shown before I bought them)

**Comment by sim0n00ps** [comment]
Yes the paid folder will only include the media that you've paid for, the previews will always be classed as Free media

**Comment by T3rminat0r** [comment]
I had paid and free media enabled, the images were in neither of the folders, though ... i.e. the "free messages" download skipped them, cause they're part of the paid message, I guess? And the paid message skipped cause not paid media?

**Comment by sim0n00ps** [comment]
Well only the Paid Message media will be scraped when it gets to downloading Paid Messages, Free Message media will be scraped  when it gets to downloading Messages

**Comment by T3rminat0r** [comment]
As I said. I have all 4 of "Messages", "PaidMessages", "Images" and "Videos" enabled. I even deleted the metadata for that subscription to make sure it wasn't previously marked as downloaded, or something... still missing one image per paid set... the one that was the teaser image.... (I got 3 free images, 67 paid, but checking online, I see a total of 74 images (4 paid sets, one cover image each...)

**Comment by Puk0** [comment]
> As I said. I have all 4 of "Messages", "PaidMessages", "Images" and "Videos" enabled. I even deleted the metadata for that subscription to make sure it wasn't previously marked as downloaded, or something... still missing one image per paid set... the one that was the teaser image.... (I got 3 free images, 67 paid, but checking online, I see a total of 74 images (4 paid sets, one cover image each...)

Si tiene 2 imagenes repetidas (con el mismo nombre) solo baja una 

Me imagino que en la pagina sumas 74 y solo te bajo 70 (67+3) y ... 4 repetidas que no bajo/omitio

**Comment by T3rminat0r** [comment]
> > As I said. I have all 4 of "Messages", "PaidMessages", "Images" and "Videos" enabled. I even deleted the metadata for that subscription to make sure it wasn't previously marked as downloaded, or something... still missing one image per paid set... the one that was the teaser image.... (I got 3 free images, 67 paid, but checking online, I see a total of 74 images (4 paid sets, one cover image each...)
> 
> Si tiene 2 imagenes repetidas (con el mismo nombre) solo baja una
> 
> Me imagino que en la pagina sumas 74 y solo te bajo 70 (67+3) y ... 4 repetidas que no bajo/omitio

No, there were 4 unique images, that were not downloaded. the four cover images of the 4 paid messages. Those images were not identical, in name or otherwise, to other images.

**Comment by sim0n00ps** [comment]
> > > As I said. I have all 4 of "Messages", "PaidMessages", "Images" and "Videos" enabled. I even deleted the metadata for that subscription to make sure it wasn't previously marked as downloaded, or something... still missing one image per paid set... the one that was the teaser image.... (I got 3 free images, 67 paid, but checking online, I see a total of 74 images (4 paid sets, one cover image each...)
> > 
> > 
> > Si tiene 2 imagenes repetidas (con el mismo nombre) solo baja una
> > Me imagino que en la pagina sumas 74 y solo te bajo 70 (67+3) y ... 4 repetidas que no bajo/omitio
> 
> No, there were 4 unique images, that were not downloaded. the four cover images of the 4 paid messages. Those images were not identical, in name or otherwise, to other images.

I think I managed to uncover what was going wrong for them not to be downloaded. Any paid messages are skipped which meant the previews were also skipped, I've now made it go through the preview media if the message has been purchased. This will be included in the next release hopefully.

**Comment by T3rminat0r** [comment]
That makes sense, yeap :) thanks for checking on it :)

**Comment by sim0n00ps** [comment]
If you want to try the latest release and see if your preview media now gets downloaded, you might need to delete the metadata folder

**Comment by T3rminat0r** [comment]
Can confirm, it worked, after deleting the metadata for that creator :) So, this is solved, now :)
