### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by dakram8** [sim0n00ps/OF-DL#112]
So i was following the steps to get these 2 files :
device_client_id_blob
device_private_key

And i was able to perform the steps for the Android studio part, and managed to create a phone, but once I got to the pip install part, I just cant get past it.

I'm new to programming, so when i did the pip install frida in cmd, i got a "'pip' is not recognized as an internal or external command, operable program or batch file." error, and I can't seem to figure out a solution (tried installing python as well as adjusting the path of the python script as well as running a python -m pip install pip etc to no avail).

Can someone please help me out?

**Comment by Puk0** [comment]
usas windows?
tienes python 3.11.4?
cuando instalaste python 
- seleccionaste la opción que agregara el path a "variables del entorno"
- seleccionaste la opción "instalar pip"

Abre "el simbolo del sistema" y pon : python --version
Luego : pip  --version
![2023-07-30 03-44-36](https://github.com/sim0n00ps/OF-DL/assets/138377242/387c052e-61a2-41ef-a93c-27cfa33e0a6f)

**Comment by megaabc1** [comment]
This issue is quite generic (not related to OF-DL) and google should help you fix it in no time. If you're still having trouble after googling just write a follow up comment!

**Comment by dakram8** [comment]
> 

Thanks! The "seleccionaste la opción que agregara el path a "variables del entorno"" was the part that i missed out

**Comment by dakram8** [comment]
But now i seem to have an issue trying to run the dump_keys.py when i opened a second cmd. It is now saying that they cannot find the frida module even though i have not closed the first cmd

![Screenshot 2023-07-31 103622](https://github.com/sim0n00ps/OF-DL/assets/140937135/5922008c-038a-4896-b3b0-2c5dc4549cb7)

**Comment by Puk0** [comment]
si pusiste lo siguiente no debería darte el "no module named frida"

pip install frida

pip install frida-tools

El frida-server-16.1.3-android-x86.xz (descomprimido) de github dentro de \Android\Sdk\platform-tools

cd "C:\Users\yourname\AppData\Local\Android\Sdk\platform-tools"
adb.exe devices

adb.exe push frida-server-16.1.3-android-x86 /sdcard

adb.exe shell
su
mv /sdcard/frida-server-16.1.3-android-x86 /data/local/tmp
chmod  +x /data/local/tmp/frida-server-16.1.3-android-x86
/data/local/tmp/frida-server-16.1.3-android-x86

Bajas -> github.com/wvdumper/dumper

Despues abres otra consola
cd path del dumper + enter 
Python dump_keys.py

**Comment by dakram8** [comment]
why do i have this error now haha:

C:\Users\HX\Downloads\dumper-main\dumper-main>python dump_keys.py
Traceback (most recent call last):
  File "C:\Users\HX\Downloads\dumper-main\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "C:\Users\HX\Downloads\dumper-main\dumper-main\Helpers\Scanner.py", line 3, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'

**Comment by Puk0** [comment]
> why do i have this error now haha:
ModuleNotFoundError: No module named 'Crypto'

pip install pycryptodome

**Comment by dakram8** [comment]
omg, i think it works now.

Do i have to open the android studio and the 2 cmds everytime? Or would this just be for the initial set up to get the 2 files?

**Comment by Puk0** [comment]
> omg, i think it works now.
> 
> Do i have to open the android studio and the 2 cmds everytime? Or would this just be for the initial set up to get the 2 files?

Ya que tienes los 2 archivos cdm puedes cerrar todo

**Comment by dakram8** [comment]
> > omg, i think it works now.
> > Do i have to open the android studio and the 2 cmds everytime? Or would this just be for the initial set up to get the 2 files?
> 
> Ya que tienes los 2 archivos cdm puedes cerrar todo

Buena, muchas gracias por todo!
