### ISSUE TITLE
Having Issues with OF-DL with a WARNING No device_private_key found

### ISSUE THREAD

**Issue by JayHyphenB** [sim0n00ps/OF-DL#113]
Hey everyone. Sort of new to this but I got everything working it seemed. Followed all the steps. Tested without the device_client_id_blob and the device_private_key and the download works except for the DRM protected files.

Followed these steps here https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio
to extract the 2 files renamed and added to cdm/devices/chrome_1610/ https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio

it detects the id_blob but not the private key. 

Help would be appreciated!

**Comment by JayHyphenB** [comment]
oh also wanted to mention the frida version I used was 16.1.3 if that makes a difference

**Comment by Puk0** [comment]
¿Que dice en "tipo de archivo"?
![2023-07-30 03-30-24](https://github.com/sim0n00ps/OF-DL/assets/138377242/a6efd8c6-0195-4268-88c2-8617daef8b27)

Abre device_private_key con el "bloc de notas", tiene que tener una "BEGIN RSA PRIVATE KEY"

**Comment by Puk0** [comment]
> oh also wanted to mention the frida version I used was 16.1.3 if that makes a difference

frida-server-16.1.3-android-x86

**Comment by JayHyphenB** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/0a46683b-399e-41c7-a92f-b7053c7b2289)

**Comment by JayHyphenB** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/1cbdc96e-21aa-47c3-b62b-674ff9a3a83a)
this is the type of what mine says

**Comment by sim0n00ps** [comment]
> ![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/1cbdc96e-21aa-47c3-b62b-674ff9a3a83a)
> this is the type of what mine says

You need to remove the file extension from the device_private_key, as you can see it's recognised as a pem file, it just needs to be a raw file with no extension at the end of the filename

**Comment by JayHyphenB** [comment]
oh okay, how am I able to do that?

**Comment by megaabc1** [comment]
> oh okay, how am I able to do that?

![image](https://github.com/sim0n00ps/OF-DL/assets/55576837/9b3aea32-dd73-4d18-8a23-04a1352b42aa)

Check the "File name extensions" and then remove the ".pem" from the file name

**Comment by JayHyphenB** [comment]
That did it! It seemed like the videos downloaded but is there something else Im missing? It seems like Im unable to view them somehow? Thanks in advance again btw

![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/df63b1ed-ce6e-4962-b66f-dab7cef9a0fc)

**Comment by JayHyphenB** [comment]
nvm Im looking into how to decrypt them. Obviously open for suggestions as well :)

Looking into Bento4 and mp4decrypt hopefully they still work

**Comment by Puk0** [comment]
> nvm Im looking into how to decrypt them. Obviously open for suggestions as well :)
> 
> Looking into Bento4 and mp4decrypt hopefully they still work

El mismo of-dl lo hace si funcionan tus 2 archivos cdm 
(que esten dentro de \cdm\devices\chrome_1610 y sin extensión)
extraen el kid:key y con mp4decrypt lo desencripta
y después se borran los archivos encriptados 
y con el ffpmeg los une en uno solo

Si te salen en .part algo te fallo en el auth.json

**Comment by JayHyphenB** [comment]
Oh yeah thats strange here's the ffmpeg and mp4decrypt
![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/f15b05b6-5e6a-4e41-bf0c-b900dec9f878)
and this is in the auth.json file 
![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/4953ee26-0728-4959-9009-4f98181e2422)

**Comment by sim0n00ps** [comment]
> Oh yeah thats strange here's the ffmpeg and mp4decrypt ![image](https://user-images.githubusercontent.com/140591136/257336461-f15b05b6-5e6a-4e41-bf0c-b900dec9f878.png) and this is in the auth.json file ![image](https://user-images.githubusercontent.com/140591136/257336620-4953ee26-0728-4959-9009-4f98181e2422.png)

Well I can see your issue straight away, you have mp4**en**crypt.exe, you need mp4**de**crypt. The .exe you have is used to encrypt videos which is the opposite of what you want to do!

**Comment by JayHyphenB** [comment]
possibly what I did was moved those specific files into the same folder where the yt-dlp was. But only those individual files. I'll move the whole extracted zipped file. Maybe that was the issue

**Comment by sim0n00ps** [comment]
> possibly what I did was moved those specific files into the same folder where the yt-dlp was. But only those individual files. I'll move the whole extracted zipped file. Maybe that was the issue

You just need to copy mp4decrypt.exe from the bento4 folder you would of downloaded to your folder where your exe files, I explained above what you've done wrong

**Comment by JayHyphenB** [comment]
oof wow. How did I just miss that.. corrected it and testing it now! Thanks again! Will update and possibly close the issue once its done!

**Comment by JayHyphenB** [comment]
weird. It's still not doing it. I'll reboot my PC and try again if that'll make a difference

**Comment by Puk0** [comment]
> weird. It's still not doing it. I'll reboot my PC and try again if that'll make a difference

no ocupas reiniciar
 
- borra esos archivos encriptdos 
- si los conto como "descargados" guarda los datos en  `\__user_data__\sites\OnlyFans\..\Metadata`
borra la carpeta Metadata
vuelve a descargalos
Si usas el of-drm prueba descargar solo un video hasta que te salga

**Comment by JayHyphenB** [comment]
okay yeah I deleted the whole foldter so it creates a new one. Deleting the metadata folder is a bit unclear to me. How do I find it?

**Comment by JayHyphenB** [comment]
oh wait is it the one that comes with each account's folder? Yeah I do that too and retry it

**Comment by JayHyphenB** [comment]
oh man.. its still doing it even with the proper decrypt and deleted older downloads
![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/cf5f5b52-2cf0-420d-9531-998d9dd5337e)

![image](https://github.com/sim0n00ps/OF-DL/assets/140591136/5acb5395-14ab-4782-8355-96f137be012e)

**Comment by EntrepreneurVE** [comment]
> > oh also wanted to mention the frida version I used was 16.1.3 if that makes a difference
> 
> frida-server-16.1.3-android-x86, igual que el que instala en pip frida

Puk0, podrias generarme los dos archivos mas importantes? 

mi actual pc no tiene para virtualizar y estoy trancado

**Comment by SenrPicante** [comment]
I downloaded the android studio but i never got past the initial screen. I can't see where to select "select device" i feel so stupid and really frustrated, its not even included on the link!  https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio its so annoying how OF now have these DRM thing

**Comment by Puk0** [comment]
> I downloaded the android studio but i never got past the initial screen. I can't see where to select "select device" i feel so stupid and really frustrated, its not even included on the link! https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio its so annoying how OF now have these DRM thing

- Abres el programa
- Menu > Tool > AVD Manager 
![2023-08-05 21-16-42](https://github.com/sim0n00ps/OF-DL/assets/138377242/5ce53b42-3f6f-4b16-b3bb-70b5e0a0aec6)
- Create Virtual Device.
![2023-08-05 21-18-10](https://github.com/sim0n00ps/OF-DL/assets/138377242/6a9f9082-3909-4833-ba61-86ce79f1f44f)
- Tipo : Phone - Resolución : Pixel 6 
![2023-08-05 21-21-46](https://github.com/sim0n00ps/OF-DL/assets/138377242/89ce7a77-c6b8-4574-8eba-7cffb3cc912e)
- Sistema Pie (API 28)
![2023-08-05 21-23-15](https://github.com/sim0n00ps/OF-DL/assets/138377242/6095d680-2c21-4987-b935-5952c405a6ae)
- Orientacion . Esperas a que instale ... 
![2023-08-05 21-26-22](https://github.com/sim0n00ps/OF-DL/assets/138377242/44e2b89d-1b7b-47fc-b7b1-5a458fbac28b)
- Terminar 
![2023-08-05 21-30-01](https://github.com/sim0n00ps/OF-DL/assets/138377242/6a3c94f3-ac75-4da6-98d6-b242c69e73ff)
- Menu > Tool > AVD Manager y ... listo
![2023-08-05 21-31-12](https://github.com/sim0n00ps/OF-DL/assets/138377242/396053bd-6a8d-4e01-926a-aee1215da17f)
![2023-07-29 04-57-31](https://github.com/sim0n00ps/OF-DL/assets/138377242/a87c4d23-1ca4-4e22-b03f-fb183951e5bc)

**Comment by dzhiyaulhaq** [comment]
![a](https://github.com/sim0n00ps/OF-DL/assets/81297649/706a517e-875a-4db1-bc28-b1b43211d060)

I have a problem when running OF-DL, everything is successful and gets green writing, but suddenly white writing appears and it closes the cmd, what should I do?

**Comment by dzhiyaulhaq** [comment]
![a](https://github.com/sim0n00ps/OF-DL/assets/81297649/9a47d956-3180-44ab-afa6-ad272d4b6e19)
I have a problem when running OF-DL, everything is successful and gets green writing, but suddenly white writing appears and it closes the cmd, what should I do?

and this is the log
![b](https://github.com/sim0n00ps/OF-DL/assets/81297649/edb4ad36-e4a4-4015-9aa8-8fe92d4861b5)
