### ISSUE TITLE
App closes immediately when executing

### ISSUE THREAD

**Issue by sslist** [sim0n00ps/OF-DL#114]
![WindowsTerminal_3r1sHzXjgV](https://github.com/sim0n00ps/OF-DL/assets/140969439/f2fb3afb-e586-420f-9c07-813f303252d4)
I have tried adding a "," at the end, same thing. My auth.json is filled correctly, i have also added the 3 executables in the same folder and linked them in it. I don't know what to do anymore.

**Comment by sslist** [comment]
Here's my full auth.json if that helps : 
![Notepad_8XbirLxdEJ](https://github.com/sim0n00ps/OF-DL/assets/140969439/ac13ff06-992a-4def-8f59-3b80e6084f8d)

**Comment by sim0n00ps** [comment]
Remove the comma at the end of the DownloadPath

**Comment by sslist** [comment]
Same issue :/ except it's line 22 instead of 23 (from the 1st screenshot)

**Comment by megaabc1** [comment]
Could it be from missing closing braces? i don't see a } character

**Comment by sslist** [comment]
> Could it be from missing closing braces? i don't see a } character

It was the solution, thank you so much ! I feel so dumb currently lol, i've been at it for like an hour !
