### ISSUE TITLE
an issue with a DRM decrypt? 

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#12]
To confirm I am using 1.6.1 just the folder is still renamed to the 1.5.1

Receiving the following error when trying to download - also the drm video previously only the video downloaded and not the audio

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/0e7f4d7a-2ac0-4a9c-ad8b-b842947ed2c9)

I am seeing the separate video and separate audio files 

and seems to be happening with only one creator 

Received this on another creator - however this did decrypt and download correct

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/6ee19e66-ba4f-4c49-9f5c-2f9a7bd61486)

**Comment by sim0n00ps** [comment]
I have a potential fix for your first issue ready to release later today, just got to do some more testing and refinements first.
Your 2nd issue is something I've faced before, not 100% sure why it happens but I imagine its some sort of rate limit being hit, could be something completely different.

**Comment by deadbeatdandylyon** [comment]
Gotcha, yeah it seems the downloading is working on everyone else, but this one creator so far I've tested with is running into this problem. 

the second issue, not sure what happened but that did vanish the second time I ran it but we will see. 

As you saw also posted on the other site just in case others may have the same problem is the only reason i do it. but thank you, I'll keep an eye out

**Comment by sim0n00ps** [comment]
Well if you try again on the one that keeps failing, tell me the filenames that are being downloaded

**Comment by deadbeatdandylyon** [comment]
Okay so in the script command it shows that it's getting suck on the following file that it can't find "0he0sk3zv5bdfpmv63x1i_source.mp4"

When I go to the directory of where the files are downloaded this is what I see

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/0647e62f-457d-4d77-851d-38d162c54901)

Okay so after double checking this is the situation the very first video on the far left is the newest DRM which is working. it is the DRM video before it that is not downloading/decrypting correctly 

0he0sk3zv5bdfpmv63x1i_vdec - Mp4 Video file 
0he0sk3zv5bdfpmv63x1i.f1 < Mp4 video file 
0he0sk3zv5bdfpmv63x1i.f3 <-- appears to be the M4A audio file

**Comment by sim0n00ps** [comment]
Yeah the new release will fix this. I'll try and explain, originally when I set this up I was only getting the m4a files downloaded with .f4 at the end but you can also get ones with .f3 which I didn't accommodate for in my code. So in your case the code is expecting an m4a file with .f4 at the end but instead an .f3 is downloaded and the code can't find the file so the ffmpeg command will fail and then carry on, thats why you see the error that the file cannot be found.

**Comment by deadbeatdandylyon** [comment]
Ahh thanks for the info, understood completely, Thank you

**Comment by sim0n00ps** [comment]
Made a new release if you want to try it, added some values to auth.json so make sure you transfer them across and also make sure you include the .dll file in the same directory as OF Dl.exe

**Comment by deadbeatdandylyon** [comment]
_Awesome sauce, everything downloaded amazingly with the new update. Idk if it's possible, I do know that the script already skips the already downloaded content, so how come it still takes like 15 minutes to just download the new videos. I would assume that the process would go so much more faster._

**Comment by sim0n00ps** [comment]
Glad it worked. Yes I realise that I need to make some small changes now I've added the metadata support. It will probably be trying to download everything again because it can't find it in the DB, it does check if the file exists as well but I do need to refactor it. If you run it again on that account it will probably be quite quick.
