### ISSUE TITLE
FileNameFormat options?

### ISSUE THREAD

**Issue by Puk0** [sim0n00ps/OF-DL#120]
How do you put the FileNameFormat?

Si lo pongo asi 
- "MessageFileNameFormat": "{date}.{filename}.{ext}" = {date}.3024x4032_6a...9bc5.{ext}.jpg
- "MessageFileNameFormat": "YYYY-MM-DD" = YYYY-MM-DD.jpg (todas con el mismo nombre y se sobreescribe el archivo)
- "MessageFileNameFormat": "Name.{filename}" = Name.3024x4032_6a...9bc5.jpg

**Comment by sim0n00ps** [comment]
All details here https://github.com/sim0n00ps/OF-DL/wiki/Custom-Filename-Formats

**Comment by szlunek** [comment]
So my auth.json file looks like this:

    "PaidPostFileNameFormat": "{postedAt}_{filename}_{username}",
    "PostFileNameFormat": "{postedAt}_{filename}_{username}",
    "PaidMessageFileNameFormat": "{postedAt}_{filename}_{username}",
    "MessageFileNameFormat": "{postedAt}_{filename}_{username}"

Pictures and videos from posts have dates in file name but from video don't. Any ideas?
![post](https://github.com/sim0n00ps/OF-DL/assets/142259967/ea701d0b-2b85-42a6-be87-50e591118411)
![messages](https://github.com/sim0n00ps/OF-DL/assets/142259967/00347c45-e47a-41cd-8de6-e61c50d62951)

**Comment by sim0n00ps** [comment]
Maybe try postedAt

**Comment by szlunek** [comment]
No changes
![msg](https://github.com/sim0n00ps/OF-DL/assets/142259967/d8a73324-ea28-4db3-b7a7-0b67d88ff3d4)

**Comment by sim0n00ps** [comment]
What are you trying to download, Paid Message, Paid Post etc?
What value are you trying to get, when the media was created or when the post or message was created?

**Comment by szlunek** [comment]
I'm scrapping the whole profile: Post, Paid Post, Messages and Paid Messages. For example the highlighted pic is from message send on July 23th.
![msg1](https://github.com/sim0n00ps/OF-DL/assets/142259967/d0852cc2-0c10-48a4-9176-a20e4856e91d)

**Comment by sim0n00ps** [comment]
The messages response does not return the media createdAt so you can't have that in the filename at the moment

**Comment by szlunek** [comment]
Ok, so for now there is no way to have dates in file name?

**Comment by sim0n00ps** [comment]
You can have the date of the message but just not the date of when the media was created

**Comment by szlunek** [comment]
That will be fine but {postedAt} don't work.
