### ISSUE TITLE
Can't download preview media paid post

### ISSUE THREAD

**Issue by SakerLy** [sim0n00ps/OF-DL#121]
It can't download preview media paid post after I update ver 1.7.26

**Comment by sim0n00ps** [comment]
Okay I can look into this, have you paid for the post or is it still locked?

**Comment by SakerLy** [comment]
yes,I've paid it
It only download other file but don't download file preview

**Comment by sim0n00ps** [comment]
Try the latest release, hopefully it should fix the issue.

**Comment by SakerLy** [comment]
It've download it but it's not in the paid folder,it's in the free folder

**Comment by sim0n00ps** [comment]
> It has download it but it's not in the paid folder,it's in the free folder

That is the correct behaviour
