### ISSUE TITLE
where is cdm/devices/chrome_1610

### ISSUE THREAD

**Issue by Nido21100** [sim0n00ps/OF-DL#123]
Hi everyone, this is probably the most stupid question but once you've got the 2 files that will become device_client_id_blob and device_private_key where do i copy them to on the pc, been racking my brain over it for a few hours and still cant figure this out.

any help would be greatly appreciated.

**Comment by sim0n00ps** [comment]
It is in the folder where OF DL.exe is located

**Comment by Nido21100** [comment]
the one and only place i didn't look. Thank you so much
