### ISSUE TITLE
A question about "device_client_id_blob" and "device_private_key" files 

### ISSUE THREAD

**Issue by KingVitto** [sim0n00ps/OF-DL#124]
Hey!
Maybe it's a silly question.. but, why not generate the "device_client_id_blob" and "device_private_key" files and post them to a file host for everyone to download? 
Are there security risks? Or they work only once and then they need to be generated again?
Does every user really have to extract these files from Android Studio by themselves following the IMHO pretty complicated procedure?
Thanks in advance.

**Comment by sim0n00ps** [comment]
If I did that then they would get revoked pretty quickly and I would be endlessly generating them. I encourage people to make them because then you know that you are the only one using those keys and so they should last for a long time. As I have stated on simpcity a few times I am happy to generate the files for people and send them to you privately just as long as you've actually had a go and not just asking me to do it because you can't be bothered.

**Comment by KingVitto** [comment]
I see, thanks for the clarification. I am trying it now with your simplified script. I'm currently at the editing frida.bat stage :)

**Comment by sim0n00ps** [comment]
> I see, thanks for the clarification. I am trying it now with your simplified script.
> 
> EDIT: double-clicking run.bat does nothing. a cmd window appears for 0.01 second and disappears. I launch the DRM thing in chrome in the virtual device, but the 2 files don't appear in the dumper-main folder. (everything is done correctly in the editing part). Do I need to have Python installed?

Yes

**Comment by KingVitto** [comment]
So, I installed Python, and retried everything from scratch, following your instructions precisely, but it didn't work.
Then I found this guide: https://simpcity.su/threads/guide-for-getting-drm-content-wip.181199/ and it worked.

**Comment by KingVitto** [comment]
So, I installed Python, and retried everything from scratch, following your instructions precisely, but it didn't work.
Then I found this guide: https://simpcity.su/threads/guide-for-getting-drm-content-wip.181199/ and it worked for me.
Finally got the 2 files. :)

**Comment by ezmrdy** [comment]
could you please help me with the last part ( 2 files, device_client_id_blob and device_private_key.) I'm stuck and can't get the files.

**Comment by sim0n00ps** [comment]
> could you please help me with the last part ( 2 files, device_client_id_blob and device_private_key.) I'm stuck and can't get the files.

Drop your telegram or discord and I can send them to you

**Comment by ezmrdy** [comment]
I really do appreciate it. my discord is: ezmrdy

**Comment by sim0n00ps** [comment]
> I really do appreciate it. my discord is: ezmrdy

Sent you a friend request

**Comment by chucky10206** [comment]
Hi, Could you help me with files, i am stuck at generating the 2 files. My discord is chucky10206
Thanks.

**Comment by sim0n00ps** [comment]
> @sim0n00ps Hi, Could you please help me with files, i am stuck at generating the 2 files. My discord is chucky10206
> Thanks.

Sent you a request

**Comment by ashishnbhatia** [comment]
> > @sim0n00ps Hi, Could you please help me with files, i am stuck at generating the 2 files. My discord is chucky10206
> > Thanks.
> 
> Sent you a request

can i also get cdm bro plz i an unable to get my telegram id is ashishnbhatia

**Comment by jamesonquarters2** [comment]
Please, I've been banging my head against the wall for hours because even though I tried everything, the adb.exe just doesnt register for me. Please help me out discord: infinityfukaimori

**Comment by sim0n00ps** [comment]
> Please, I've been banging my head against the wall for hours because even though I tried everything, the adb.exe just doesnt register for me. Please help me out discord: infinityfukaimori

Sent you a request

**Comment by xtmnoob** [comment]
I don't get the key_dumps folder it only generated license_request.bin file

**Comment by Bobertbrown** [comment]
> In the latest versions of OF-DL the 2 files are not a requirement, if you don't have them you will still be able to download DRM videos, cdrm-project will be used instead.

Can i ask what that is and how to get it? im sorry if this is annoying

**Comment by sim0n00ps** [comment]
> > In the latest versions of OF-DL the 2 files are not a requirement, if you don't have them you will still be able to download DRM videos, cdrm-project will be used instead.
> 
> Can i ask what that is and how to get it? im sorry if this is annoying

It's just a free website that allows you to send the licence requests that get the decryption keys, so basically you don't need to do anything, just run the program and hopefully it should download them

**Comment by h014hi** [comment]
> > could you please help me with the last part ( 2 files, device_client_id_blob and device_private_key.) I'm stuck and can't get the files.
> 
> Drop your telegram or discord and I can send them to you

Hi dear sim0n00ps please can you help me getting the device_client_id_blob and device_private_key files, I don't know How and I'm following the cdm project, discord: zephirtah

**Comment by sim0n00ps** [comment]
> > > could you please help me with the last part ( 2 files, device_client_id_blob and device_private_key.) I'm stuck and can't get the files.
> > 
> > 
> > Drop your telegram or discord and I can send them to you
> 
> Hi dear sim0n00ps please can you help me getting the device_client_id_blob and device_private_key files, I don't know How and I'm following the cdm project, discord: zephirtah

Sent you a friend request

**Comment by plunkman** [comment]
Does this script work for videos i purchased in the DMs?  When i click on the script it only seems to offer to scrape DRM videos from wall posts.

**Comment by melithine** [comment]
> Does this script work for videos i purchased in the DMs? When i click on the script it only seems to offer to scrape DRM videos from wall posts.

Yes, it does.

Also, commenting on closed issues is a good way to not get answers. I just happened to be subscribed to this one, but new issues are a much more reliable way to get answers.

**Comment by rgsrepo** [comment]
Hi there, also stuck with the device_client_id_blob and device_private_key files, could you help me? My Telegram is @maths743, thanks a lot!

**Comment by gitsome12** [comment]
Hi, would you mind sending me both files (device_client_id_blob and device_private_key files), I am also stuck at generating them. Thanks a lot! My discord is rest34512_86927. Thanks!

**Comment by bezaaas** [comment]
Please help me with both files because i spend two days and i don't know what to do. my telegram abdullahm00re. a cup of coffee from me. :)

**Comment by Gremlin2206** [comment]
Can i please have both files device_client_id_blob and device_private_key files, tried my best but cant manage to generate them. Discord Gremlin2206, thanks.

**Comment by pllkss** [comment]
@sim0n00ps Hi, can you pls help me too to get the 2 files (device_client_id_blob and device_private_key). My discord: tks0066 tysm

**Comment by AlessioM88** [comment]
> @sim0n00ps Hi, can you pls help me too to get the 2 files (device_client_id_blob and device_private_key). My discord: tks0066 tysm

Hi @sim0n00ps  , thanks for this tool! can you please help me too? My >Telegram is: @alessiom88

**Comment by kabob83** [comment]
Hi, I've been trying to get the 2 files with no luck after a few attempts. My discord is archer5843. Thanks!

**Comment by melithine** [comment]
> Hi, I've been trying to get the 2 files with no luck after a few attempts. My discord is archer5843. Thanks!

Sent you a friend request.

**Comment by TrashSome** [comment]
I went trough the entire guide and got the pixel 6 with teverything but i dont know how to continue after that. My discord name is trashsome

**Comment by fearoftheflesh** [comment]
@melithine Can you add me on Discord @/uruseiyatsura and send the files over ?

**Comment by Sud1101** [comment]
HI..can anyone share those 2 files..BLOB and private key files with me..My telegram is Sud1101...please

**Comment by vanontom** [comment]
Just FYI: Simply check the Discord for help with keys, you won't be disappointed. (And thanks to y'all over there!)

**Comment by Sud1101** [comment]
Hi @vanontom I just joined discord for this purpose..can you help me to get these files or let me know whom to request?

**Comment by koko11211132** [comment]
Hey sorry to bother u, i cant generate these files. Can you help?

**Comment by DFlow69** [comment]
Hello sorry for troubling you but I can't get those files no matter how hard I try can someone send them to me? Discord: ._.d_d._.

**Comment by melithine** [comment]
There is a bot on the Discord server to get keys now. Locking this issue that was closed months ago.
