### ISSUE TITLE
The tutorial for drm protected videos isnt working 

### ISSUE THREAD

**Issue by ItsKing-32** [sim0n00ps/OF-DL#126]
When I follow this tutorial https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio i follow the steps until i get to [here](https://gyazo.com/f919e96a0f209e26554e570974fbd7db) then when i get to this step i downloaded the file but i never see the frida-server file

**Comment by sim0n00ps** [comment]
Head to the GitHub link and you need to download frida-server from the latest release, you might need to click on show more assets as each release has a lot of different versions, also use ctrl+ f to search for frida-server

**Comment by ItsKing-32** [comment]
> Head to the GitHub link in the guide and you need to download frida-server from the latest release, you might need to click on show more assets as each release has a lot of different versions, also use ctrl+ f to search for frida-server

Ok that worked but now i got to [here](https://gyazo.com/cb83c3c62f3f60c579dc45732c7a0398) and it says no module named crypto but even on the github link for dumper-main it doesnt show anything named crypto

**Comment by sim0n00ps** [comment]
You need to actually put frida-server onto your virtual device and make sure its running by leaving the command prompt you use to push the file to the phone and run the other commands open.

**Comment by ItsKing-32** [comment]
i had that other command prompt open

**Comment by asdsadsaasd12312132** [comment]
I'm having the same issue. There's an error with this step.

`/system/bin/sh: /data/local/tmp/frida-server-16.0.2-android-x86: No such file or directory`
