### ISSUE TITLE
It doesn't download Archive post

### ISSUE THREAD

**Issue by SakerLy** [sim0n00ps/OF-DL#127]
It doesn't download archive even though I see profile I'm downloading has 23 archives but it doesn't find any

**Comment by freeketamine** [comment]
Can confirm. The app says  - Found 0 Archived Posts - when there are actual archived posts.
I only just updated to OF DL V1.7.29 but It used to work as I can see archived images from a previous version so maybe something changed on the OF side?

**Comment by beensean** [comment]
It seems that archived posts stopped downloading with V1.7.26, still works for me with V1.7.25

**Comment by sim0n00ps** [comment]
It will most likely be on the OF side, I can look into it
