### ISSUE TITLE
crash on large creator

### ISSUE THREAD

**Issue by stanzel** [sim0n00ps/OF-DL#129]
im trying to DL a creator with >2000 post and >12000 Media.  the application crashes   is there any logging that would help trace this problem ?

**Comment by MisterDiggy** [comment]
I have this problem too with the newest version. I'm trying to download an OF with over 4,000 posts and it just closes after downloading only 30.

**Comment by stanzel** [comment]
I ran the program from the shell and got this error.
![ofld_snip](https://github.com/sim0n00ps/OF-DL/assets/21038097/7c51df91-5a24-461e-addc-08045e09fb9c)
