### ISSUE TITLE
possible to get title/name/date of post please?

### ISSUE THREAD

**Issue by superfan12345** [sim0n00ps/OF-DL#13]
thank you very much for making this.

I have one request.

would it be possible to get the names of the posts and dates if possible instead of random numbers/letters_source , please? 

digitalcrim for his had this  "filename_format": "{date} - {text}#{filename}.{ext}", as an option for ppl to use.

if that's something you would be willing to add that would be amazing. thank you.

**Comment by sim0n00ps** [comment]
This can be done and has been asked for a few times, at this moment I have no idea if it would be possible with my current setup and how easy it would be to implement. Once I have ironed out a few small issues I will begin working on the custom file format.

**Comment by superfan12345** [comment]
> This can be done and has been asked for a few times, at this moment I have no idea if it would be possible with my current setup and how easy it would be to implement. Once I have ironed out a few small issues I will begin working on the custom file format.

oh okay thanks.

**Comment by M-rcus** [comment]
Just want to start with thanks for this project!

Figured I'd chime in and mention that if/when this gets implemented, that I would also like to see `post_id` and `media_id` supported. With the DC project I prefer using: `{date}_{post_id}_{media_id}_{filename}.{ext}` - `media_id` helps keeping photosets in the correct order as well, from my experience.

For messages, I believe `post_id` "falls back" to being `message_id`.

**Comment by peddanet** [comment]
@sim0n00ps Anything new here? I have seen that the code divides two sorts of filenames custom local ones and server file names and you rename it to this local file name in one case of existence. So for my understanding so far I would have to change the database and the filename accordingly to set a custom file name? Does there already exist code or a project for this? Or must I code read more and my assumptions are wrong?

**Comment by sim0n00ps** [comment]
> @sim0n00ps Anything new here? I have seen that the code divides two sorts of filenames custom local ones and server file names and you rename it to this local file name in one case of existence. So for my understanding so far I would have to change the database and the filename accordingly to set a custom file name? Does there already exist code or a project for this? Or must I code read more and my assumptions are wrong?

What are you wanting to do exactly?
