### ISSUE TITLE
GPT chat connecting to a website

### ISSUE THREAD

**Issue by doctorregina** [sim0n00ps/OF-DL#132]
Hiii,

I have an OnlyFans agency and I would be happy to build Python script to automate chatting with costumers via GPT chat.
Could you please help me to create this code? As far as I know there are some difficulties with API in Onlyfans website so the data could only be transferred by data scrapping, am I right?

**Comment by sim0n00ps** [comment]
I'd be willing to help, I can discuss further if you drop your discord or telegram
