### ISSUE TITLE
Need help with OF DRM paid content

### ISSUE THREAD

**Issue by wildhacker741** [sim0n00ps/OF-DL#137]
Hey mate needa some help with downloading OF DRM Paid content
Ive manage to grab the client_id and private_key from android studio using pixel XL.
But for some reason it didnt download the paid drm content. Im not sure what went wrong. Any kind soul able to help me out?
Error: at WidevineClient.Widevine.CDM.ProvideLicense(String sessionId, Byte[] license) |  Exception caught: Unable to parse license
Heres the error image 
https://ibb.co/bvtmpp0

Cheers!

**Comment by sim0n00ps** [comment]
Log out of OF and log back in, re copy the new sess value you get from logging back in, see if that helps

**Comment by wildhacker741** [comment]
Hi. Have tried still the same error

**Comment by sim0n00ps** [comment]
The keys you had already were fine, it's just that you need to get a new session from Onlyfans and see if that changes anything, you don't need to generate the keys again once you've got them.

**Comment by wildhacker741** [comment]
Since i already have the keys. Do i need to launch android studio and do the same command again? or i can just launch the OF scrapper without having android studio on?

**Comment by sim0n00ps** [comment]
Once you've got the keys you are ready to go. You don't need to have Android Studio or any of the other commands prompt windows open, you should just be able to run OF-DL.exe. Make sure you place them in the cdm/devices/chrome_1610 folder and make sure both files don't have file extensions.

**Comment by JC02023** [comment]
@sim0n00ps is it possible for you to create a detailed video like the one for OF - DL on how to get the 2 keys :( i am completely lost. Please kind sir.
