### ISSUE TITLE
Auth not being accepted

### ISSUE THREAD

**Issue by JackGitit** [sim0n00ps/OF-DL#14]
Hello I have tried maybe 6 times and double checked and reread everything but no matter what I cant keep this auth to go through I am not a coder or used this type of program before so help would be much appreciated. I am confident the user ID and auth is the same used cookie helper to help me... Could it be I'm signing through onlyfans through google? and is the X_BC suppose to be grabbed from the guide or am i suppose to use the one i grabbed on cookie helper? I used the one it suggested in the guide which is "2a9b28a68e7c03a9f0d3b98c28d70e8105e1f1df"
![notepad_NUCCcAljyD](https://github.com/sim0n00ps/OF-DL/assets/134113475/141afb1a-7ba1-48ec-a87f-430e73a784ce)

**Comment by JackGitit** [comment]
Okay I think the problem was the X_BC..... wow Well the guide says to use the one you provided that was a little confusing to understand also ran as admin and renamed the file to OFDL.exe you may disregard this post.

**Comment by sim0n00ps** [comment]
I mean it does say to set the x-bc to your x-bc value not the one I included as an example which is a made up one
