### ISSUE TITLE
DRM video android studio files

### ISSUE THREAD

**Issue by smorgisborg1** [sim0n00ps/OF-DL#141]
Hi there, is it possible to use device_client_id_blob and device_private_key files from other people or do they have to be made for each person? Tried getting android studio to run and it wouldn't install the emulator and actually ended up corrupting my windows, luckily it managed to revert. The guide you put up is great for installing your tool but getting the ability to download the DRM videos is quite a bit harder.

**Comment by sim0n00ps** [comment]
Drop your telegram or discord and I can make them for you

**Comment by smorgisborg1** [comment]
Thanks, my discord is smorgisborg1

**Comment by sim0n00ps** [comment]
Sent you a request

**Comment by devdeviant** [comment]
hey, can I get in on this @sim0n00ps ?? I haven't been able to download the decryption keys either. discord is abeg4567

**Comment by sim0n00ps** [comment]
> hey, can I get in on this @sim0n00ps ?? I haven't been able to generate the decryption keys either. discord is **abeg4567**. thanks for your awesome work on this project! 

Sent you a friend request
