### ISSUE TITLE
the mdeiakey objest could not be created/initialized  when play DRM 

### ISSUE THREAD

**Issue by Tg00174** [sim0n00ps/OF-DL#143]
the mdeiakey objest could not be created/initialized 

play video on https://bitmovin.com/demos/drm

**Comment by Tg00174** [comment]
i can play with chrome,but use android studio can't open

**Comment by sim0n00ps** [comment]
Drop your discord or telegram here and I can generate the 2 files for you

**Comment by Tg00174** [comment]
discord
Wseller#5636

thanks,i want to pay it if it works
