### ISSUE TITLE
OF DL.exe closes instantly

### ISSUE THREAD

**Issue by Keksztekercs211** [sim0n00ps/OF-DL#145]
Hi!
My OF DL.exe is closing instantly when i try to open it.
I did everything like in the video, nothing is missing, could anyone help?
Thanks!

**Comment by deadbeatdandylyon** [comment]
Hello, I am also experiencing this issue. I did double check all settings with the inital installation processes, I also double checked my Auth file to make sure everything is working. but when I double click on OF DL.exe it just opens

The only changes I made was in the config file - changed download avatar/header photo to false and includeexpiredsubscrions to false. however the first time when I received the error I used a capitol "F" for both false, after changing it to lower case - it worked without any issues. 

I am attaching the image of the "Exception Caught Error" 
![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/a5758ff8-5193-49d1-b5ce-74252c38d180)

**Comment by sim0n00ps** [comment]
> Hello, I am also experiencing this issue. I did double check all settings with the inital installation processes, I also double checked my Auth file to make sure everything is working. but when I double click on OF DL.exe it just opens
> 
> The only changes I made was in the config file - changed download avatar/header photo to false and includeexpiredsubscrions to false. however the first time when I received the error I used a capitol "F" for both false, after changing it to lower case - it worked without any issues. 
> 
> I am attaching the image of the "Exception Caught Error" 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/a5758ff8-5193-49d1-b5ce-74252c38d180)
> 

You don't use a capital F when you want something to be false. The value should be all lowercase, either true or false not True or False

**Comment by deadbeatdandylyon** [comment]
Yes I did realize that after the fact, maybe the original poster could have done something similar so maybe it might help maybe not
