### ISSUE TITLE
It is not getting any messages

### ISSUE THREAD

**Issue by Meeeeeeeeeeeeh** [sim0n00ps/OF-DL#148]
It shows me 0 messages and 0 paid messages.

**Comment by Meeeeeeeeeeeeh** [comment]
I get this 

Getting Messages
Found 0 Messages
Getting Paid Messages
Found 0 Paid Messages

????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

■ Paid Posts 0     ■ Posts 0    ■ Archived 0     ■ Stories 0    ■ Highlights 0     ■ Messages 0    ■ Paid Messages 0

Scrape Completed in 0.78 minutes

**Comment by sim0n00ps** [comment]
Are you actually subscribed to this user? Because to me it seems like you're scraping a user that you aren't currently subscribed to or a user that simply has no messages

**Comment by Meeeeeeeeeeeeh** [comment]
I am subscribed to that user. I tried even other users. But not working. I even chose user that I am subscribed but it is scraping any messages. It scrapes posts, videos, pictures and audios. But not messages .

**Comment by Meeeeeeeeeeeeh** [comment]
I also tried log off and log in again. But it doesn't work.

**Comment by sim0n00ps** [comment]
Can you actually view any of the media you are trying to download? Also are you sure you are using OF-DL and not OF-DRM which is not up to date

**Comment by deadbeatdandylyon** [comment]
Idk if it helps to have the information, but I just tested on a user that I am subscribed to and have purchased videos and does have DRM turned on. And was able to download from the messages perfectly fine.

**Comment by Meeeeeeeeeeeeh** [comment]
I can view the media. The user sent me medias. I am using OF-DL. I tried even different users that I am subscribed to and purchased media from them. But it doesn't work only messages. Their post and DRM video posts works fine without any issue. 

Maybe I will try to delete and try to re-do the whole process

**Comment by Meeeeeeeeeeeeh** [comment]
I found a problem. I had to select download everything with posts, videos , pictures , and messages.
As in I couldn't scrape messaged only.

**Comment by sim0n00ps** [comment]
If you want to download Messages only then you set DownloadPaidPosts, DownloadPosts, DownloadArchived, DownloadStories, DownloadHighlights and DownloadPaidMessages to false, leaving DownloadMessages set to true. Because I imagine you also set DownloadImages, DownloadVideos and DownloadAudios to false you were telling the downloader to download nothing.

**Comment by Meeeeeeeeeeeeh** [comment]
I tried it to put them in false except DownloadMessages was set to true and DownloadPaidMessages was set to true and it didn't work. To me I had to set up everything true and SkipAds was set to false and it worked.
