### ISSUE TITLE
Support downloading streams

### ISSUE THREAD

**Issue by ryansilversun** [sim0n00ps/OF-DL#149]
Some creators have a Streams section, but this tool currently doesn't have an option to download videos on that section. Please add the function to download those videos. Many thanks.

**Comment by sim0n00ps** [comment]
Do you have any examples of this? Screenshot's would be helpful.

**Comment by sim0n00ps** [comment]
If you want to drop that persons username and I can delete your comment afterwards or if you know any free users that have that tab that I can test with

**Comment by ryansilversun** [comment]
@sim0n00ps Sure `onlyfans.com/dibarros1`

**Comment by sim0n00ps** [comment]
> @sim0n00ps Sure `onlyfans.com/dibarros1`

Thanks I will take a look when I get a chance

**Comment by sim0n00ps** [comment]
The posts that are in the streams tab can be found on the regular feed so they will be picked up anyway
