### ISSUE TITLE
OF DL doesn't download archived posts.

### ISSUE THREAD

**Issue by 7evenlxrd** [sim0n00ps/OF-DL#151]
On profile are 7 archived posts, OF DL detected 0.

**Comment by randomfapper** [comment]
Actually came here to post about this... I'm having the same issue.

**Comment by sim0n00ps** [comment]
Will be fixed in next release

**Comment by sim0n00ps** [comment]
https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.33
