### ISSUE TITLE
Tutorial video on how to get Decryption Keys

### ISSUE THREAD

**Issue by JC02023** [sim0n00ps/OF-DL#154]
Hi @sim0n00ps ,

IS it possible for you to make a tutorial video on how to get the decryption keys via the android studio? I am stuck on that part of the OF - DL

**Comment by JC02023** [comment]
Hi I was just reading through some of the closed cases and I saw that you created the DRM decryption files for someone are you able to do the same for me?

**Comment by sim0n00ps** [comment]
Yes, if you have discord or telegram drop your username and I can get in touch with you

**Comment by JC02023** [comment]
Hello @sim0n00ps my discord is thatoneasiankid. Thank you.

**Comment by sim0n00ps** [comment]
> Hello @sim0n00ps my discord is thatoneasiankid. Thank you.

Sent you a friend request

**Comment by pawners** [comment]
can i get decryption files too please? dump_keys gives me errors. telegram  @that_guyaa
thanks

**Comment by sim0n00ps** [comment]
> can i get decryption files too please? dump_keys gives me errors. telegram @that_guyaa thanks

Sent to you

**Comment by twist3dimages** [comment]
> > can i get decryption files too please? dump_keys gives me errors. telegram @that_guyaa thanks
> 
> Sent to you

Am I able to get one
