### ISSUE TITLE
Not Downloading All Videos? 

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#155]
To start off I just downloaded and configured the latest version download 

Secondly, I have an account that I am currently subscribed to No DRM at all. 

I ran the scrape and the results I got were as follows 

![Screenshot 2023-09-12 174426](https://github.com/sim0n00ps/OF-DL/assets/59564520/c2c10050-95d2-4d3f-80b7-459c1c3106bd)

The videos are posted to their timeline 

when I go to the download directory after it is finished scraping this is the results I see. All the videos listed up till the one that says 00:00:05 are not working. in any video player. I don't know if some of these videos are the videos that are not downloading. 

When I used another scraping program prior to that one shutting down it did find the files that are not downloading with this scraper 

Any thoughts? 

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/32dd12c9-9ace-4bfd-9ffb-dd18d271b45e)

**Comment by sim0n00ps** [comment]
I've had this today, fixed it by deleting videos that were 0KB in size and deleted metadata folder then re-ran the scrape and the missing vids were downloaded. I can look into what might be happening.

**Comment by deadbeatdandylyon** [comment]
Okay so I went and deleted all contents that were 0KB in size and also delete the metadata folder as suggested. 

I re-ran the scrape / This time it did download all the videos that were missing / however it did get stuck at 99% instead of the 80% so I guess there is still something going on but it did download everything that I can see at least 

Thank you for the help

**Comment by sim0n00ps** [comment]
No problem, a lot of the code has been refactored so I imagine during that process something has been missed/broken

**Comment by deadbeatdandylyon** [comment]
Understandable. as Always I appreciate your help and swift response. This is now resolved
