### ISSUE TITLE
How works downloads by date

### ISSUE THREAD

**Issue by vaxtermat** [sim0n00ps/OF-DL#156]
Hi! This tool is amazing and I would like to know how to use the next fields located in config.json (nomenclature and how to introduce them).

"DownloadOnlySpecificDates": false,
 "DownloadDateSelection": "after",
 "CustomDate": null

Thanks for your help.

**Comment by sim0n00ps** [comment]
DownloadOnlySpecificDates - set this to true if you want to use the feature
DownloadDateSelection - this can only be set to after or before
CustomDate - this can be set to any date in the format yyyy-mm-dd

Once you've selected a date, if you've got the selection set to "after" then it will get all posts from that point onwards up until the current date and if you've set it to "before" then it will get all posts from before that date so if you set it to 2023-07-30 then you would gets posts on 2023-07-29, 2023-07-28 etc

**Comment by vaxtermat** [comment]
OK, thanks!

I introduced them like this

"DownloadOnlySpecificDates": true,
 "DownloadDateSelection": "after",
 "CustomDate": "2023-04-01"

but now I get this error when searching for posts

`Exception caught: Response status code does not indicate success: 400 (Bad Request).

                                                                                    StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, Auth auth, Config config, List`1 paid_post_ids)
Found 0 Posts`

**Comment by SomeOneYouDoKnow** [comment]
I have tried several times to make this work, but it just keeps ignoring the date and grabbing everything. If I was dealing with only a few files this would not be a big deal, but I am dealing with hundreds of videos and it is just not feasible to get everything everytime I want to download the latest content.

Using OF.DL.V1.7.34

config.json:
  "DownloadOnlySpecificDates": true,
  "DownloadDateSelection": "after",
  "CustomDate": "2023-09-21"

**Comment by lerroynick** [comment]
@SomeOneYouDoKnow this is very strange. I wrote this particular section of the code and it works as expected when running from source. in fact i use it all the time. I will check with the Released executable and will get back to you in the next couple of days

**Comment by SomeOneYouDoKnow** [comment]
> @SomeOneYouDoKnow this is very strange. I wrote this particular section of the code and it works as expected when running from source. in fact i use it all the time. I will check with the Released executable and will get back to you in the next couple of days

To recreate, I used the custom menu option to select a specific account. The following is my entire config.json:
{
  "DownloadAvatarHeaderPhoto": false,
  "DownloadPaidPosts": false,
  "DownloadPosts": false,
  "DownloadArchived": false,
  "DownloadStories": false,
  "DownloadHighlights": false,
  "DownloadMessages": false,
  "DownloadPaidMessages": true,
  "DownloadImages": false,
  "DownloadVideos": true,
  "DownloadAudios": false,
  "IncludeExpiredSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "C:/Users/SomeOneYouDoKnow/Downloads/SCRAPED",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 12,
  "DownloadOnlySpecificDates": true,
  "DownloadDateSelection": "after",
  "CustomDate": "2023-09-21"
}

**Comment by BitDeluxe** [comment]
Whenever I use the dates option I get a "400 Bad Request" exception for posts and archived posts.
Tried Versions 1.7.34 and 1.7.35
(I don't have the DRM files, but it's working fine with the date option disabled)

```
Getting Posts
Exception caught: Response status code does not indicate success: 400 (Bad Request).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, Auth auth, Config config, List`1 paid_post_ids)
Found 0 Posts
Getting Archived Posts
Exception caught: Response status code does not indicate success: 400 (Bad Request).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetArchived(String endpoint, String folder, Auth auth, Config config)
Found 0 Archived Posts
```
```

{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "{postedAt}__{id}__{mediaId}__{filename}",
  "PostFileNameFormat": "{postedAt}__{id}__{mediaId}__{filename}",
  "PaidMessageFileNameFormat": "{createdAt}__{id}__{mediaId}__{filename}",
  "MessageFileNameFormat": "{createdAt}__{id}__{mediaId}__{filename}",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 100,
  "DownloadOnlySpecificDates": true,
  "DownloadDateSelection": "after",
  "CustomDate": "2023-09-01"
}
```

**Comment by lerroynick** [comment]
@BitDeluxe Thanks friend.
I tested that a few times and it was working normally, and honestly i had no clue what the issue may, since everything here works as expected. interpolated strings are fairly new, and i didn't know that it would use the OS properties for localization. In any case, i will push a commit today so i suppose on the next release this will be fixed. . The c# idiomatic solution is `ConvertToUnixTimestampWithMicrosecondPrecision(dt.Value).ToString("0.000000", CultureInfo.InvariantCulture)` btw. Again thanks.

**Comment by sim0n00ps** [comment]
I have created the release with the changes, if you could try them and verify if they work or not. Then I can close this issue if everything is working ok.
