### ISSUE TITLE
device_client_id_blob not found

### ISSUE THREAD

**Issue by darkknight7171** [sim0n00ps/OF-DL#159]
Hello,

I generated device_client_id_blob and device_private_key, and stored in cdm/devices/chrome_1610/
![imagen](https://github.com/sim0n00ps/OF-DL/assets/145024933/369b8c38-e37d-4777-9790-800e62a15be5)

But when I run the program I get the following warnings
![imagen](https://github.com/sim0n00ps/OF-DL/assets/145024933/470599dd-cbd5-413c-ad78-a5e890a3668d)

Any idea of what I'm doing wrong?
Thanks!

**Comment by sim0n00ps** [comment]
Remove .bin and .pem from the filenames, should be all good after that

**Comment by IchYoIo** [comment]
Can anyone help me with an description to generate this files?

**Comment by melithine** [comment]
https://of-dl.gitbook.io/of-dl/requirements talks about it.
