### ISSUE TITLE
Getting 0 Paid Messages, Same Key Exception 

### ISSUE THREAD

**Issue by PleasantWasabi** [sim0n00ps/OF-DL#16]
This error pops up with a number of creators. OF-DL fails to find any paid messages on these creators (of which there are quite a few paid videos). If it helps, it seems that DRM protection is enabled. This error occurs on both releases 1.7.3 and 1.7.2.

Getting Paid Messages
Exception caught: An item with the same key has already been added. Key: 2125435227

                                                                                   StackTrace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OF_DL.Helpers.APIHelper.GetMedia(MediaType mediatype, String endpoint, String username, String folder)
Found 0 Paid Messages

**Comment by sim0n00ps** [comment]
Yep this is easily fixable, will make another release soon.

**Comment by knightedbynature** [comment]
Getting the same error but with a different key.
Key: 2240408780

StackTrace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OF_DL.Helpers.APIHelper.GetMedia(MediaType mediatype, String endpoint, String username, String folder)

**Comment by sim0n00ps** [comment]
If you try the latest release hopefully this will be fixed, let me know if it does and I can close this issue.
