### ISSUE TITLE
DownloadPath Issue

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#161]
Hello, 

I attempted for the first time to change the download path on where to save the scrape since my main drive is full. 

I first had the DownloadPath set to  "DownloadPath": "E:\Content Creators", 
however after that change the screen just opens and closes - I pasted the error capture below. 
I have even changed the DownloadPath to just "E:\" 
and the window just opens and closes. 

I guess my question is do I have to transfer the whole Zip contents of the OF DL to the other drive to just be able to scrape in another drive. or am I doing something incorrectly?

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/bb6a952f-f0a5-40d2-b49c-8ec6edbdec9e)

**Comment by sim0n00ps** [comment]
Try E:/Content Creators

**Comment by deadbeatdandylyon** [comment]
Thank you, that seemed to have resolved the issue, I guess going forward in any change of any pathing it has to stick with " / " instead of " \ "  so i will be mindful of that going forward and try that before posting an issue. 

Thank you again as always.
