### ISSUE TITLE
Not sure if this is an issue.

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#162]
Okay so here is what is happening now. Not sure if this is an issue or if its like the same thing that happened last time. i think it completes successfully but not entirely sure. 

I am attempting a scrape of an account, the first time around I got the following issue. 

![Screenshot 2023-09-14 213032](https://github.com/sim0n00ps/OF-DL/assets/59564520/88926c82-d626-4c42-9e5b-694a7c59a904)

So I attempted to delete the whole folder and all scraping and it happened again. 

![Screenshot 2023-09-14 213631](https://github.com/sim0n00ps/OF-DL/assets/59564520/5ed734ac-1e70-4d87-a3f8-aef8ad6063a9)

**Comment by JC02023** [comment]
u see how ur on 1.7.30 when we are on 1.7.34

**Comment by deadbeatdandylyon** [comment]
I am currently on 1.7.34 - I just don't always rename the main folder every time i copy over the OF DL.exe

**Comment by sim0n00ps** [comment]
I imagine it's probably returning a bad request due to you being rate limited, might want to leave it a bit before trying again and see if that helps

**Comment by deadbeatdandylyon** [comment]
Never heard of Rate Limited before interesting

**Comment by sim0n00ps** [comment]
It's just a way to control how many requests you can make to OF's API in a certain time frame, if you exceed that limit then you'll be blocked for a short space of time.
