### ISSUE TITLE
how would i set the file format to give file names like this please?

### ISSUE THREAD

**Issue by superfan12345** [sim0n00ps/OF-DL#163]
how would I set the file format to give file names like this please.
01-02-2022 - Pornhub Scene #6  Look Into My Eyes While You Watch Me Get Fucked
ON the DC ripper I had it like so
{date} - {text}#{filename}.{ext}
and if i use the same way with this one i get
{date} - Look Into My Eyes!

**Comment by sim0n00ps** [comment]
Use "postedAt" for the date of the post

**Comment by superfan12345** [comment]
i would still like all a creator's posts. but just in that format. not a specific post I'm after. (apologies if I'm reading your post wrong)

**Comment by sim0n00ps** [comment]
No I mean the format should be {postedAt} - {text}. That would give you the date of the post and the caption, be careful using the text field as sometimes emojis and other random characters can fuck up the filenames which will give you errors

**Comment by superfan12345** [comment]
that worked. I was thinking where the heck is the posted at section in the config file :) ahahah thank you very much for the help.

**Comment by sim0n00ps** [comment]
More info here https://github.com/sim0n00ps/OF-DL/wiki/Custom-Filename-Formats

**Comment by superfan12345** [comment]
wonderful thank you very much. and thanks for the quick replies. great program too.

**Comment by superfan12345** [comment]
> No I mean the format should be {postedAt} - {text}. That would give you the date of the post and the caption, be careful using the text field as sometimes emojis and other random characters can fuck up the filenames which will give you errors

is it possible to fix that issue with the emojis and random characters ?

**Comment by superfan12345** [comment]
ok thanks yep thats fine no rush on it.

**Comment by tobin28** [comment]
There seems to be a problem with the file name formatter, when the file needs to go through the DRM pipeline?
With this format   `"PaidPostFileNameFormat": "{mediaCreatedAt}_{username}_{mediaId}"`
the download will fail for DRM protected file (format string works for non DRM files), but download of the same DRM protected file will work if "PaidPostFileNameFormat" is set to "".

`StackTrace:    at System.Object.GetType()`
   `at OF_DL.Helpers.FileNameHelper.GetNestedPropertyValue(Object source, String propertyPath)`
  `at OF_DL.Helpers.FileNameHelper.GetFilename(Object obj1, Object obj2, Object obj3, List'1 selectedProperties, Dictionary'2 users)`
  `at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String`

**Comment by sim0n00ps** [comment]
> There seems to be a problem with the file name formatter, when the file needs to go through the DRM pipeline? With this format `"PaidPostFileNameFormat": "{mediaCreatedAt}_{username}_{mediaId}"` the download will fail for DRM protected file (format string works for non DRM files), but download of the same DRM protected file will work if "PaidPostFileNameFormat" is set to "".
> 
> `StackTrace: at System.Object.GetType()` `at OF_DL.Helpers.FileNameHelper.GetNestedPropertyValue(Object source, String propertyPath)` `at OF_DL.Helpers.FileNameHelper.GetFilename(Object obj1, Object obj2, Object obj3, List'1 selectedProperties, Dictionary'2 users)` `at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String`

Paid Posts and Messages did not support mediaCreatedAt as per the info here https://github.com/sim0n00ps/OF-DL/wiki/Custom-Filename-Formats but I have now got it to work now after spending a few hours looking into it, I will create a new release with this included and after you've tried it you can close this issue if it works or tell me if anything goes wrong.

**Comment by sim0n00ps** [comment]
@tobin28 try this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.35

**Comment by tobin28** [comment]
Thanks a lot!

**Comment by sim0n00ps** [comment]
Am I alright to close this now?
