### ISSUE TITLE
GetPosts issue

### ISSUE THREAD

**Issue by darkrebel08** [sim0n00ps/OF-DL#165]
Having an issue with a specific creator, cannot find any posts with the following error:

_Exception caught: Object reference not set to an instance of an object.
StackTrace:    at OF_DL.Helpers.APIHelper.<>c__DisplayClass19_0.<GetPosts>b__0(List p)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, Auth auth, Config config, List`1 paid_post_ids)_

Its not having any issues with anything else except posts. This is also not happening with like 20 other creators, just this specific creator.
On the latest version 1.7.34 and double checked the auth.json

![image](https://github.com/sim0n00ps/OF-DL/assets/100237823/5cb83b80-fe83-4700-9b7f-3f82decd74bd)

**Comment by sim0n00ps** [comment]
I've rejigged the code that uses SkipAds to filter the posts I imagine in some cases the text will be null which is something that wasn't being taken into consideration currently hence why you get the null reference

**Comment by sim0n00ps** [comment]
@darkrebel08 try this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.35

**Comment by sim0n00ps** [comment]
Which creator is this, if you comment quickly I can delete it afterwards.

**Comment by sim0n00ps** [comment]
Noted, you can delete now

**Comment by Aythami-I-G** [comment]
got the same problem

**Comment by sim0n00ps** [comment]
I have found this issue with this, some posts didn't have text so that's why you see the null reference exception, will create a new release with the fix

**Comment by sim0n00ps** [comment]
Finally got around to making the release so this should now be fixed

**Comment by Escopy88** [comment]
> I have found the issue with this, some posts didn't have text so that's why you see the null reference exception, will create a new release with the fix

I think this issue is present for messages now. I can't download free media messages that don't have text, I get the same error message as darkrebel08.
