### ISSUE TITLE
is there a way to avoid downloading duplicate videos while using the filename formatting feature?

### ISSUE THREAD

**Issue by rakuko1** [sim0n00ps/OF-DL#166]
previously it was pretty sweet that the program checks whether the file has been downloaded before but i assume that was based on the filename. 

now that filename formatting is enabled, we're getting every version of the video that has been sent in messages, etc, at least when using something like "{createdAt}_{mediaId}"

Is there anything that can be done as another check to avoid dupes, like filesize or date modified? if not no worries, just thought it worth asking as the filename formatting is cash.

**Comment by sim0n00ps** [comment]
Well I'm not sure how that can happen as the metadata stores the media id which is unique and the downloaded flag will be set to true so it won't be downloaded. Can you screenshot what has happened?

**Comment by rakuko1** [comment]
![nina](https://github.com/sim0n00ps/OF-DL/assets/86748783/058020bc-8e88-4d02-97d6-8532b6095c3a)

ah when i expanded out the filename the last few digits were off. i suppose they may have uploaded the same video twice within a very quick timeframe, it just seemed odd as the Date, filesize, and length are all identical.

TBF i hadn't seen any other dupes when going through the other videos downloaded when testing the filenames so hopefully it was just a fluke.

if it comes up again i'll reshare details, will close for now.

**Comment by sim0n00ps** [comment]
To me that seems like normal behaviour, anything uploaded to OF goes into a creators vault which is basically like a camera roll. They clearly uploaded the video and then when they came to use it again they didn't use the already uploaded version instead they uploaded the same video again hence the different Id's.
