### ISSUE TITLE
Error getting file size for URL --- The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by Nostalgus** [sim0n00ps/OF-DL#167]
Whenever the downloader tries to download an image, the message "Error getting file size for URL (-link leading to image-) The SSL connection could not be established, see inner exception" appears. Everything else seems to work. It successfully downloaded the header from a profile, loaded for 2 minutes and then started downloading posts, but with no success. What can I do? Appreciate the help!

**Comment by sim0n00ps** [comment]
Maybe set it to only download images or videos only first, let them all download and then do the rest. This error usually occurs when you're IP has been rate limited due to the amount of requests you've made in a certain time frame. I'd recommend you leave it for a bit before trying to scrape again.

**Comment by sim0n00ps** [comment]
Yes the downloads in that video are still valid and what you've downloaded sounds correct (they are only needed for DRM videos). I'm not sure then, I'd probably wait a few hours then just to make sure that you actually have been rate limited and it's not another issue.

**Comment by Nostalgus** [comment]
Is there anything else I should perhaps change or fill in? Otherwise, I'll wait a bit for now.

{
  "DownloadAvatarHeaderPhoto": false,
  "DownloadPaidPosts": false,
  "DownloadPosts": true,
  "DownloadArchived": false,
  "DownloadStories": false,
  "DownloadHighlights": false,
  "DownloadMessages": false,
  "DownloadPaidMessages": false,
  "DownloadImages": true,
  "DownloadVideos": false,
  "DownloadAudios": false,
  "IncludeExpiredSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": ""

**Comment by sim0n00ps** [comment]
No I would just wait, don't change anything

**Comment by Nostalgus** [comment]
Thanks. I will wait a few hours then. :)
