### ISSUE TITLE
Exception Bad JSON escape sequence

### ISSUE THREAD

**Issue by naobug** [sim0n00ps/OF-DL#169]
I got the auth json file and everything setup but, when running OF_DL I get the following JSON error, see attached screenshot.
I think my path is correct in the auth file. But why the error then?

![grafik](https://github.com/sim0n00ps/OF-DL/assets/12033198/23f7b04f-f401-472a-abb8-ef18fcf5d963)

**Comment by 22none** [comment]
Hey bro when copying the path it think's you're trying to use escapes which are started with \ so I ended up switching all the \ in my path with / and that worked for me try that.

**Comment by naobug** [comment]
Thank you, that solved this part of the problem. But now, I got a new error code:
![grafik](https://github.com/sim0n00ps/OF-DL/assets/12033198/d5dea195-0d93-4589-be41-937ecdc4845f)

**Comment by sim0n00ps** [comment]
I will close this issue now as your problem is now fixed, for the other issue please look at issue #170
