### ISSUE TITLE
Unable to find helper paths

### ISSUE THREAD

**Issue by qvdm** [sim0n00ps/OF-DL#172]
My auth.json has paths to the helpers in the required format (forward slashes, no trailing slash) : 

  "YTDLP_PATH": "C:/ytdlp",
  "FFMPEG_PATH": "C:/ffmpeg",
  "MP4DECRYPT_PATH": "C:/mp4decrypt"

However, when I run OF-DL, I get an error message: 

"Specified path C:/ytdlp does not match the required format, please remove any \ from the path and replace them with / and make sure the path does not have a / at the end, press any key to exit"

I have tried moving the helpers around, adding/removing dashes in the filenames, etc, but nothing seems to work.

**Comment by alexeinkere** [comment]
Hello Mate ! 

It's working on my project with this setup : 

```
  "YTDLP_PATH": "./drms/yt-dlp.exe",
  "FFMPEG_PATH": "./drms/ffmpeg.exe",
  "MP4DECRYPT_PATH": "./drms/mp4decrypt.exe"
```

I hope it helps you !

**Comment by sim0n00ps** [comment]
Put them in a folder within C:/ and hopefully that should work

**Comment by qvdm** [comment]
I was stupid, added the directories but not the executables. Works now.
