### ISSUE TITLE
Where do I have to put those files to be found : device_client_id_blob & device_private_key

### ISSUE THREAD

**Issue by alexeinkere** [sim0n00ps/OF-DL#173]
Hello !

Can someone help me ?
I have setup everything good and I created both "**device_client_id_blob**" and "**device_private_key**" with dumper-main and frida-server, but I don't know where to put them ? 
Where do I specify the path to those files ? Or where do I need to put those files ?

Thanks for you help !

**Comment by sim0n00ps** [comment]
Put them in the cdm/devices/chrome_1610 folder which is included with the release you would of downloaded from GitHub
