### ISSUE TITLE
{mediacreatedAt} doesn't work in MessageFileNameFormat/PaidMessageFileNameFormat

### ISSUE THREAD

**Issue by oOD4rkL0rdOo** [sim0n00ps/OF-DL#175]
PostFileNameFormat and PaidPostFileNameFormatwork fine.
config:
  "PaidPostFileNameFormat": "{id}-{mediaid}-{mediacreatedAt}-{filename}",
  "PostFileNameFormat": "{id}-{mediaid}-{mediacreatedAt}-{filename}",
  "PaidMessageFileNameFormat": "{id}-{mediaid}-{mediacreatedAt}-{filename}",
  "MessageFileNameFormat": "{id}-{mediaid}-{mediaCreatedAt}-{filename}",

filename example:
7733333300-244448951-{mediacreatedAt}-434435kidfsfrflniy_source.mp4

**Comment by oOD4rkL0rdOo** [comment]
thx, works for me now. messages with {mediaCreatedAt}

**Comment by St4ndardDev1anT** [comment]
@sim0n00ps just fyi, the examples in the wiki erroneously use {mediacreatedAt}. That might have been the source for the confusion.

**Comment by BluesFanUK** [comment]
Can files only be renamed once?

**Comment by sim0n00ps** [comment]
> Can files only be renamed once?

What are you intending to do?

**Comment by BluesFanUK** [comment]
> > Can files only be renamed once?
> 
> What are you intending to do?

Realised i was renaming by Media created date rather than date posted on the feed. I prefer the latter.

**Comment by sim0n00ps** [comment]
> > > Can files only be renamed once?
> > 
> > What are you intending to do?
> 
> Realised i was renaming by Media created date rather than date posted on the feed. I prefer the latter. 

I would set your file name formats to what you want them to be and then set RenameExistingFilesWhenCustomFormatIsSelected to true in the config and see what that does.

**Comment by BluesFanUK** [comment]
Tried that last night but unfortunately didn't update. Wondered if it was a one time thing.

**Comment by sim0n00ps** [comment]
Probably the only option is then is to re-do the whole scrape sadly

**Comment by sim0n00ps** [comment]
Probably the only option is then is to re-do the whole scrape sadly
