### ISSUE TITLE
Paid Messages not being found during scrape

### ISSUE THREAD

**Issue by Speaker4TheD3ad** [sim0n00ps/OF-DL#176]
Running into an issue where paid messages are not being found. Using either OF-DL or OF-DRM any ideas sim0n00ps? No errors are returned just finds 0 posts.

**Comment by sim0n00ps** [comment]
Have you told it you want to download Paid Messages?

**Comment by NigelOhhhhh** [comment]
Yea i have this issue too even with the paid messages/posts being selected. It does scrape ones that i have paid for before but not those that locked behind the paywall. I tested this with a new of user with paid posts and was also unable to detect any paid ones

![image](https://github.com/sim0n00ps/OF-DL/assets/52035576/d2cdbf36-36bb-4f50-81b3-35f27246bace)

abt posts that have been scrapped before. they wont be scrapped again is that correct?

**Comment by deadbeatdandylyon** [comment]
From as long as I have been using this app, for some reason it always has showed "Found 0 Paid Posts" however the paid posts do get downloaded

**Comment by sim0n00ps** [comment]
> Yea i have this issue too even with the paid messages/posts being selected. It does scrape ones that i have paid for before but not those that locked behind the paywall. I tested this with a new of user with paid posts and was also unable to detect any paid ones
> 
> ![image](https://user-images.githubusercontent.com/52035576/271244808-d2cdbf36-36bb-4f50-81b3-35f27246bace.png)
> 
> abt posts that have been scrapped before. they wont be scrapped again is that correct?

I think you are getting confused. Paid Posts are posts that you have paid to unlock, so any media that was unlocked by purchasing the post will be included in that scrape. The regular posts will pick up any paid posts that you haven't unlocked and that have preview media. 

Yes anything that has been downloaded will not be downloaded again.

**Comment by Speaker4TheD3ad** [comment]
Yes paid all paid options enabled in the config. It just finds 0 posts.

**Comment by erodegs** [comment]
it works for me

**Comment by boivinx7** [comment]
So, i had a bundle sent to me by a creator, like 5 vids for X amount, and OF-DL with paid messages would only see 4 of them. 
I enabled the free post option and it found it.
Mentioning it in case someone has a similar issue.

**Comment by sim0n00ps** [comment]
> So, i had a bundle sent to me by a creator, like 5 vids for X amount, and OF-DL with paid messages would only see 4 of them. 
> I enabled the free post option and it found it.
> Mentioning it in case someone has a similar issue.

That will be because one of them is the free preview, so 4 paid media is correct

**Comment by Smiiikes** [comment]
I'm trying to download a video message that I purchased. I'm getting the following error in the log file:

```
2024-01-13 01:58:52.275 -05:00 [ERR] Exception caught: Could not find file 'C:\Utilities\OF.DL.V1.7.48\__user_data__\sites\OnlyFans\<redacted>\Messages\Paid\Videos\0hkle8nhvtefw19myhfdd_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize)
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedMessageDRMVideo(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users, Config config, Boolean showScrapeSize)
```

**Comment by papishampooo** [comment]
im having this issue too, the creator sent me 2 videos via DM to stall me out from making me the custom video I paid her for and the scraper doesn't get to them any more info on this? I want to at least get these videos before I report this creator for scamming me, if I report her and she blocks me I won't have access to watching the videos I already paid for.. kinda sucks
