### ISSUE TITLE
device client id/private key not found

### ISSUE THREAD

**Issue by BarelyLiterateWriter** [sim0n00ps/OF-DL#177]
Hey folks I'm barely able to keep up with all of this but I managed to use the tutorial to grab my device_client_id_blob and device_private_key files. I've put them into the chrome_1610 folder, but when I run the application I'm getting these two errors:

**WARNING No device_client_id_blob found, you will not be able to download DRM protected videos without this
WARNING No device_private_key found, you will not be able to download DRM protected videos without this**

Some help would be greatly appreciated.

**Comment by deadbeatdandylyon** [comment]
How exactly did you label the files? 

They should read like this in the chrome_1610 folder
`device_client_id_blob`
`device_private_key`

Also when you run the OF DL.exe - are you getting green across the board or what is it showing exactly?

**Comment by BarelyLiterateWriter** [comment]
Yep so the files are labeled exactly like that in the folder: 
![image](https://github.com/sim0n00ps/OF-DL/assets/146388016/c49a07d4-2cb9-4642-b06f-15551a5f708a)

Then when I run OF DL this is what I see:
![image](https://github.com/sim0n00ps/OF-DL/assets/146388016/fdea6a2c-6347-4132-803a-f4fa0a68fb0d)

**Comment by sim0n00ps** [comment]
You need to remove the .bin and .pem

**Comment by BarelyLiterateWriter** [comment]
Amazing! Thank you! This is my first time doing anything with the command line, python, or anything like this.
