### ISSUE TITLE
Is it safe to delete all the prerequisite software/files after I've obtained the two decryption keys?

### ISSUE THREAD

**Issue by Eltofu** [sim0n00ps/OF-DL#178]
Hi, I've successfully obtained the two keys, and the OF-DL is working fine so far. Thank you for your tool and hard work.  

Is it now safe to remove all the files that were installed/downloaded as per the Android Studio instructions (the software, dumper-main, Intel HAXM, frida, python, files such as .gradle, .m2, etc)? Cuz they take up a lot of space.

**Comment by sim0n00ps** [comment]
You can delete everything, the only thing that I would keep is python as yt-dlp I believe requires it so I would keep it just in case, shouldn't take up too much space.

**Comment by Eltofu** [comment]
Got it, thx!
