### ISSUE TITLE
auth.json authentication error

### ISSUE THREAD

**Issue by fantablikje** [sim0n00ps/OF-DL#179]
![image](https://github.com/sim0n00ps/OF-DL/assets/69599663/d08052dc-e03c-4648-abf4-f8a7c45d011e)
i keep getting this error even though i followed all the steps in the tutorial. anyone know what to do?

**Comment by jbdaman247** [comment]
I've just encountered the same problem today, it worked a couple days ago so they must've changed something on their end.
![image](https://github.com/sim0n00ps/OF-DL/assets/146885160/5880a0db-098b-4aa9-bc0b-f5ef481d4d23)

**Comment by deadbeatdandylyon** [comment]
Sometimes when I get this I just have to update the sess: cookies and it usually works after that

**Comment by sim0n00ps** [comment]
Make sure you update your user-agent

**Comment by fantablikje** [comment]
I always update everything but it doesnt seem to work, idk what kind of things come into play here?
Idk if it doesnt work because im on windows 11 instead of 10 since the binary download is for windows 10. Also already tried turning off my anti virus clients but that also didnt help

**Comment by fantablikje** [comment]
> Sometimes when I get this I just have to update the sess: cookies and it usually works after that

Could you send me your auth.json file on like discord or something? Idk if im putting the info in in a wrong way or whatever. Im also using the newest version of the OF.DL so i dont know if theres an error or if there are version that do and dont work due to bugs?

**Comment by sim0n00ps** [comment]
Well the latest release and all other releases include a sample auth.json file which is correct for that version and includes all of the correct fields, all you need to do is fill them in. I would copy the sample one across and then fill it in.

**Comment by jbdaman247** [comment]
okay I got mine fixed by also updating user-agent, thanks simon!
