### ISSUE TITLE
Exception caught for regular nonpayable posts

### ISSUE THREAD

**Issue by naobug** [sim0n00ps/OF-DL#180]
Getting this error when selecting the category to download the regular non-paid for posts: (paid messages for example do work though)
![grafik](https://github.com/sim0n00ps/OF-DL/assets/12033198/5e99a9a6-31a7-43e9-a260-df1792e5738c)

**Comment by deadbeatdandylyon** [comment]
I'm receiving the same error message as well when attempting to run a scrape, it also appears not to be downloading any new posts either? 

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/788875d5-00cd-46b6-b748-8eddc45c1fab)
