### ISSUE TITLE
Key error then crash of application

### ISSUE THREAD

**Issue by mediaburnwayne** [sim0n00ps/OF-DL#188]
Exception caught: An item with the same key has already been added. Key: toystoryandiee

                                                                                       StackTrace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at OF_DL.Helpers.APIHelper.GetSubscriptions(String endpoint, Boolean includeExpiredSubscriptions, Auth auth)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Program.Main()

i tried deleting userdatadb and still crashes

**Comment by sim0n00ps** [comment]
Please update, the method the code is calling was removed many versions ago and the way it gets subscriptions has changed
