### ISSUE TITLE
Unable to download videos from one creator

### ISSUE THREAD

**Issue by BluesFanUK** [sim0n00ps/OF-DL#189]
I'm not sure if there's a limit on this?

I was able to download the images by selected images only, but it just seems to stall on videos, i've been faced with this for the last 20 mins - it's found the post but refuses to download them:

![image](https://github.com/sim0n00ps/OF-DL/assets/126352869/484b4956-0b5c-4604-8c1e-e2ffc55369e9)

**Comment by superfan12345** [comment]
I get to 2 percent. (2.2/108.6GB) it then just stops. and the timer is frozen. (DRM content. none DRM profile downloads fine)

**Comment by BluesFanUK** [comment]
Interesting, it's like the system is detecting a large data pull? The 2nd largest i've done is 70GB without an issue. Perhaps it doesn't like anything over 100GB?

I've also tried it with just videos only, same issue. Seems to be a problem with this content creator only, I don't think any of the vids are DRM protected either.

![image](https://github.com/sim0n00ps/OF-DL/assets/126352869/0ada06c6-8f87-4d80-a628-4c171623c60d)

**Comment by sim0n00ps** [comment]
Is this using the latest version?

**Comment by BluesFanUK** [comment]
I did note there was 1 video in the folder that had downloaded but it was unwatchable, when I tried to delete it I got a message saying ffmpeg was in use. I ended that via Task Manager, ran it again, and managed to get to 4% before it stalled and the timer disappeared, same as @superfan12345

I rebooted, tried again, and got 1% extra before it did the same. Very strange. All DRM protected content has downloaded fine elsewhere. Perhaps OF have something new in the works to annoy their customers?

**Comment by BluesFanUK** [comment]
> Is this using the latest version?

Yep latest version from here (3 weeks ago?)

**Comment by sim0n00ps** [comment]
The process hasn't changed at all in terms of downloading DRM content, it might not seem like anything is happening but in fact there is. Because yt-dlp is used I cannot track the progress of a download from the code so once the video has been downloaded and decrypted then the size of that video will be reflected onto the progress bar. If the creators are free to sub to I can sub to them myself and have a play.

**Comment by BluesFanUK** [comment]
It's personaltrainersxxx, unfortunately not free. 

My PC has just upgraded to Windows 11 as of this evening (fantastic...). I've redownloaded the latest version, and am currently trying in Opera with a new session created, previously have used Chrome.

Seems to be the same. Immediately picked up where it left off at 5%, but everything appears static, no movement on the percentage or the time:
![image](https://github.com/sim0n00ps/OF-DL/assets/126352869/668f1d6b-86c8-4031-8108-69988d5c3659)

A few minutes later it updated to 6%:
![image](https://github.com/sim0n00ps/OF-DL/assets/126352869/8d91988a-371f-4c47-8061-aff8bedff8ab)

Five minutes later updatd to 7%
![image](https://github.com/sim0n00ps/OF-DL/assets/126352869/881c1925-95a6-4956-b1a6-236c53d0932c)

Two minutes later went to 8% and gave up:
![image](https://github.com/sim0n00ps/OF-DL/assets/126352869/b3d5fcd3-0b64-4ae4-a78b-9efbe0379a94)

**Comment by sim0n00ps** [comment]
If you leave it in that state, check the Videos folder and see if any files have .f1.mp4 at the end. That would indicate that yt-dlp is downloaded something and it is actually doing stuff.

**Comment by BluesFanUK** [comment]
> If you leave it in that state, check the Videos folder and see if any files have .f1.mp4 at the end. That would indicate that yt-dlp is downloaded something and it is actually doing stuff.

Appears to be the case. Just observed the folder and there is something happening, but it's much slower than usual. I'll leave it for another hour and see how it gets on, so far i'm at 20 videos.

**Comment by sim0n00ps** [comment]
That's good, all depends on your internet speed and the size of the videos of course but could also be down to OF's servers being absolute dogshit.

**Comment by BluesFanUK** [comment]
> That's good, all depends on your internet speed and the size of the videos of course but could also be down to OF's servers being absolute dogshit.

Wouldn't surprise me. I'm on a 500Mbps connection but have the default settings of the latest version, vids tend to be around 1.5GB each.

**Comment by BluesFanUK** [comment]
Guess this one can be marked as done - all videos downloaded, it was working in the background, by the 25th vid the timer sprung back into life. No idea what was causing it on this specific user though.

**Comment by BluesFanUK** [comment]
Guess this one can be marked as done - all videos downloaded, it was working in the background, by the 25th vid the timer sprung back into life. No idea what was causing it on this specific user though.
