### ISSUE TITLE
_source.mp4 could not be found

### ISSUE THREAD

**Issue by b4320991** [sim0n00ps/OF-DL#19]
Getting

```
Exception caught: Could not find file 'C:\Users\u1\OF DL V1.7.3\__user_data__\sites\OnlyFans\xxx\Posts\Free\Videos\0he13zmjt0inu417x0el1_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                   sess, String url, String decryptionKey, String folder
```

I did found file in folder

- 0he13zmjt0inu417x0el1.f1
- 0he13zmjt0inu417x0el1.f4

Using arm window 11 if that helps

**Comment by sim0n00ps** [comment]
Make sure you've get all of the correct .exe files downloaded and make sure the path you've set doesn't include any \, if they do then replace them with / and make sure the end of the path doesn't have / at the end.

**Comment by dagr8boy** [comment]
I'm seeing this same error and I've followed your instructions. :/

**Comment by sim0n00ps** [comment]
Could you tell me what type of media this is that you are trying to scrape, is it from Posts, Messages, Paid Messages?

**Comment by dagr8boy** [comment]
It's was for a post. I'm pretty sure it's failing the `mp4decryptVideoProcess` step..?

**Comment by sim0n00ps** [comment]
Well when that post tries to be downloaded, does anything at all get downloaded at all. If it's failing to decrypt them then you should be left with 2 files with either .f1.mp4 and f3.m4a or .f1.mp4 and f4.m4a

**Comment by b4320991** [comment]
Is this commit bede14ee387a8c17080027a1ca514a099731e579 a potential fix for this issue?

Don't think its available at OFDLV1.7.9 release.

**Comment by sim0n00ps** [comment]
It is available, I updated the zip file. No point creating a new release for a change that small that's why it's 1 commit behind.

**Comment by b4320991** [comment]
i manage to resolve it, i'm missing vs c++ redistributable needed for one one of the tool. and downloading that resolved it for me.
