### ISSUE TITLE
doesn't download all images/videos

### ISSUE THREAD

**Issue by superfan12345** [sim0n00ps/OF-DL#190]
I've had this for a while now. but a creator I follow has 1790 media 1282 images and 508 videos. but I can only download 150 images and 450 videos. but when i use the ripper it does show found 1789 posts. and after it finishes downloading it says posts already downloaded 1789.

**Comment by deadbeatdandylyon** [comment]
It could very well be that most of those images / videos may be duplicates, and the scraper will automatically not download duplicates.

**Comment by superfan12345** [comment]
nah they aren't

**Comment by superfan12345** [comment]
I'm sure it had downloaded those files in an earlier version. but I believe I deleted those. but it still won't get those missing images/videos.

**Comment by superfan12345** [comment]
could it be because it has already been downloaded in the past? (not duplicate as I no longer have those files it downloaded before)

**Comment by sim0n00ps** [comment]
Delete the metadata folder which will force it to download stuff again that doesn't already exist in the folders

**Comment by superfan12345** [comment]
I tried that and it only downloaded 457 videos and 146 images. I redownloaded .36 and tried with a new one on a different hard drive. I tried to download only images and I still get downloading 1284 posts but only download 146 images

**Comment by sim0n00ps** [comment]
To me that would indicate that they are dupes, are you 100% sure that this creator doesn't have any dupes?

**Comment by superfan12345** [comment]
are you 100% sure that this creator doesn't have any dupes? yep.

**Comment by JC02023** [comment]
@superfan12345 are you sure its not paid content that you did not buy?

**Comment by superfan12345** [comment]
yep.

**Comment by superfan12345** [comment]
anymore suggestions?

**Comment by superfan12345** [comment]
okay same issue with the new version. but this time it downloads 149 images out of 1284. I then tried to have the images download to their own folder per post but that doesn't work either. so that made me realize. it hasn't been downloading posts with multiple videos/images in them. only the first image/video.

**Comment by superfan12345** [comment]
with the new feature to download a single post, it says that the post has already been downloaded and it won't download again. so I tried the new version with a fresh download. and the same thing pops up. (this is on a different hard drive with a fresh 37 unzipped. how can it tell that the post has already been downloaded? with no metadata)

**Comment by sim0n00ps** [comment]
Which creator is this?

**Comment by superfan12345** [comment]
> Which creator is this?

princess-rae

**Comment by sim0n00ps** [comment]
Ok can I use your Auth to test? You can drop it here and I'll delete the comment after I've copied it or you can drop your telegram and discord and I can discuss it with you on that

**Comment by superfan12345** [comment]
would rather not give that. ill try with a new acc next month and see how it goes with that.

**Comment by deadbeatdandylyon** [comment]
If you want I can help test this, I'm also subscribed to this creator, other then getting that exception 404 error haven't ran into the same issue.

**Comment by superfan12345** [comment]
> If you want I can help test this, I'm also subscribed to this creator, other then getting that exception 404 error haven't ran into the same issue.

sure would be great thanks.

**Comment by deadbeatdandylyon** [comment]
Okay, I just deleted everything and starting a fresh scrape, will update once it's completed

**Comment by superfan12345** [comment]
> Okay, I just deleted everything and starting a fresh scrape, will update once it's completed

thanks

**Comment by sim0n00ps** [comment]
I don't really want to pay for the sub so would rather use one of your accounts to test with, up to you of course but would be appreciated so that I can see what's going on

**Comment by superfan12345** [comment]
> I don't really want to pay for the sub so would rather use one of your accounts to test with, up to you of course but would be appreciated so that I can see what's going on if the issue persists

yep understandable. I'll see how dead goes first and decide after.

**Comment by deadbeatdandylyon** [comment]
So I just completed the scrape of the profile 

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/90106b6c-9539-47b0-88fd-0689f2988db4)

I did get an error s seen by the image. 

So as far as downloads go, 

Total Posts: 1793
Videos: 509 - Downloaded confirmed - 507
Photos: 1284 - Downloaded Confirmed - 1,284

So for me only 2 videos unaccounted for which could be duplicate videos

**Comment by superfan12345** [comment]
okay, thank you very much for the help. I believe I may have figured it out. I just tried a new .37 and this time I didn't add "PostFileNameFormat": "{postedAt}", to the config.json and it is now downloading all the images.

**Comment by superfan12345** [comment]
was that the wrong way to have it with the { and the } ?

**Comment by sim0n00ps** [comment]
Well now I've realised what you've been trying to do, by just using the post date you're going to have lots of dupes because there might be more than 1 post on the same day so files are just going to get overwritten, hopefully that makes sense. I would probably use something else to distinct it alongside the post date

**Comment by superfan12345** [comment]
would it be possible to add it so it numbers the postedat? for example postedat-1 postedat-2 and such? or would that be hard to do?

**Comment by sim0n00ps** [comment]
I would just use the mediaId to make it distinct or the original filename alongside the post date
