### ISSUE TITLE
Inner Exception: Exception caught: No client id blob found + no paid post detected

### ISSUE THREAD

**Issue by kwar1972** [sim0n00ps/OF-DL#191]
Any help with this two?

Thanks in advance

**Comment by sim0n00ps** [comment]
Make sure that you've removed the file extensions from both of the files

**Comment by kwar1972** [comment]
It worked! Thanks mate!

**Comment by peddanet** [comment]
Maybe ut is dumb, but I did not manage to find the directory cdm/devices/chrome_1610. Do I have to create it inside working dir of this project? I am on Ubuntu 22.04 and using firefox.Is chrome_1610 a special version of chrome that has to be installed?

Everything works on my system, except the drm handling files, which I own an for sure want to download...I have read the thread but now I don't know where to put finally the renamed blob files? Please help, even this question seems to be beyond dignity!!!
