### ISSUE TITLE
Exception caught GetAllSubscriptions

### ISSUE THREAD

**Issue by AnonSpace** [sim0n00ps/OF-DL#192]
![image](https://github.com/sim0n00ps/OF-DL/assets/148527558/28771881-9f68-400a-8c78-5f6730e23e13)

**Comment by sim0n00ps** [comment]
I will take a look at this later and see what's going on

**Comment by booleangit** [comment]
Same here, this behavior started yesterday. They've probably changed something on their end.

**Comment by Kameshennyn** [comment]
Same issue here =)

**Comment by sim0n00ps** [comment]
Just having a look now and on my dev copy everything seems to be fine, subscriptions and lists loaded correctly, ran a scrape and it completed fine. If anyone else can confirm this is still happening or any other error codes are popping up it would be appreciated

**Comment by DatBoiC02** [comment]
I have been getting it for the last two days.  At first I thought maybe my DRM keys expired so got new ones still got the error.  Ended my OF login and started a new to get a new cookie.  That didn't help.  Also upgraded to the latest version that didn't help.  The Error I get is below

Exception caught: Response status code does not indicate success: 400 (Bad Request).

                                                                                    StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, Auth auth, Config config, List`1 paid_post_ids)

**Comment by sim0n00ps** [comment]
OF is really slow atm so I'm putting it down to them, nothing I can do about it sadly
