### ISSUE TITLE
Suggestion to include Streams

### ISSUE THREAD

**Issue by tbms23** [sim0n00ps/OF-DL#193]
Hi, it is a wonderful program you wrote. I was wondering whether you could include downloading the media in the tab 'Streams' to the program. Not all creators do livestreams and some of them save their livestreams in this seperate tab afterwards. That tab is next to the tabs 'Media' and 'Posts'. So far I could save these livestreams via download app in the browser but who knows how long this will be possible that way. I would really appreciate if you could include this feature to the program.
I hope you have a nice day. :)

**Comment by AnonSpace** [comment]
> Hi, it is a wonderful program you wrote. I was wondering whether you could include downloading the media in the tab 'Streams' to the program. Not all creators do livestreams and some of them save their livestreams in this seperate tab afterwards. That tab is next to the tabs 'Media' and 'Posts'. So far I could save these livestreams via download app in the browser but who knows how long this will be possible that way. I would really appreciate if you could include this feature to the program. I hope you have a nice day. :)


I had the same concern with a couple of subscriptions that had livestreams but I noticed that the livestreams saved in the tab also appear in the posts so they have been downloaded normally. I don't know if it's a coincidence or the creators have an option to save them only in the tab.

Can you check if those livestreams have been downloaded?

**Comment by sim0n00ps** [comment]
I have added this feature and it will be included in the next release

**Comment by sim0n00ps** [comment]
Feature included in this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.37
