### ISSUE TITLE
Problems with deseralizing JSON objects

### ISSUE THREAD

**Issue by tbms23** [sim0n00ps/OF-DL#194]
Hi, it seems there are problems with deseralizing JSON objects. It seems to have issues with getting archived posts.
![Screenshot 2023-10-20 170404](https://github.com/sim0n00ps/OF-DL/assets/148558274/16f6df9a-2c62-46db-a64b-055a70818fa8)

**Comment by sim0n00ps** [comment]
Should be fixed in the next release

**Comment by sim0n00ps** [comment]
Should be fine in this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.37
