### ISSUE TITLE
Private Key and Blob

### ISSUE THREAD

**Issue by BuMmR88** [sim0n00ps/OF-DL#195]
I have placed the 2 files for DRM in the respected folder, but the program is still not detecting them. What shoukd I do?

**Comment by sim0n00ps** [comment]
<html>
<body>
<span style="color: rgb(245, 245, 245); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(39, 39, 39); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Rename the files accordingly:</span><br style="box-sizing: border-box; color: rgb(245, 245, 245); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(39, 39, 39); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="bbTable" style="box-sizing: border-box; max-width: 100%; overflow: auto; color: rgb(245, 245, 245); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(39, 39, 39); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Original name | New name
-- | --
client_id.bin | device_client_id_blob
private_key.pem | device_private_key

</div>
</body>
</html>

**Comment by BuMmR88** [comment]
I just figured it out. I had to remove the extention, thanks!
