### ISSUE TITLE
Turn off DRM video downloads?

### ISSUE THREAD

**Issue by waltersoapcheck420** [sim0n00ps/OF-DL#197]
I am getting hung up with the additional 2 files for the DRM downloads. Is there a way to skip those videos so that I can still scrape all the non DRM videos from a profile?

Thanks

**Comment by sim0n00ps** [comment]
Drop your discord or telegram and I can send you them

**Comment by waltersoapcheck420** [comment]
Ok thanks. disc is waltersoapcheck420

**Comment by sim0n00ps** [comment]
> waltersoapcheck420

Sent you a friend request

**Comment by devdeviant** [comment]
> I am getting hung up with the additional 2 files for the DRM downloads. Is there a way to skip those videos so that I can still scrape all the non DRM videos from a profile?
> 
> Thanks

I believe the script does skip them if the files don't exist
