### ISSUE TITLE
unable to find .exe files

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#2]
I would recommend copying all 3 of the .exe files somewhere safe where you can then add the path of each file to auth.json file. You can do this easily by holding shift when right clicking on the .exe file which should give you the option to copy as path. In the auth.json file the lines should look something like this "YTDLP_PATH": "C:/yt-dlp.exe", "FFMPEG_PATH": "C:/ffmpeg.exe" and "MP4DECRYPT_PATH": "C:/mp4decrypt.exe"

I have the 3 unzipped folders 

Bento4-SDK-1-6-0-639.x86_64-microsoft-win32
ffmpeg-6.0-essentials_build
yt-dlp-master

and your unzipped folder 

OF DL V1.3

When I go to each of the 3 unzipped folders there is nothing that shows an .exe file - I also have filled out the auth file but the window just opens and disappears, 

Where am i doing something wrong?

**Comment by sim0n00ps** [comment]
First of all have you installed .NET runtime 7.0.4, you can check by running `dotnet --list-runtimes` from within command prompt or powershell, if none of the runtimes listed have the version number 7.0.4 then you need to go here https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.4-windows-x86-installer and run the installer.

If you cannot locate the exe files, check the `bin` folders in the folders that were created when you extracted the zip files.
It also seems you've downloaded the master branch of yt-dlp, you can just download the exe on the latest release page https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.04/yt-dlp.exe

**Comment by deadbeatdandylyon** [comment]
okay so when I run the power shell for the .net runtimes it shows this 

![image](https://user-images.githubusercontent.com/59564520/236651786-753ca462-8f66-48c3-b8ee-e224f7ee611c.png)

and I was able to find the .exe files, after some reworking I did that and i have all 3 downloaded .exe files - i have also just copied and pasted the exe files not cut them from their original locations

![image](https://user-images.githubusercontent.com/59564520/236651810-a83c233a-2c67-4834-858a-f363922014fc.png)

I have also configured the auth file 

![image](https://user-images.githubusercontent.com/59564520/236651820-b7f6a80a-e2c9-4b40-8039-934a39a718ac.png)

**Comment by deadbeatdandylyon** [comment]
Got everything to work, A few things I had to change the path directory i had to change to " / " forward slashes

I used firefox 

I had to put all the cookie information not just the session cookie
