### ISSUE TITLE
I got ANSI Escape Sequence error

### ISSUE THREAD

**Issue by badbeezy** [sim0n00ps/OF-DL#20]
![Untitled](https://github.com/sim0n00ps/OF-DL/assets/135177671/e954df15-c705-47d3-a3f6-842e80e9daa2)

Recently got this error. Is this because I am using Windows 8. Could this program work on Windows 8 at all?

**Comment by sim0n00ps** [comment]
Yes, ANSI console is not supported in Windows 8. I could take the ANSI stuff out but it might mess with the aesthetics of the app so might have to be left how it is. Right now you would have to upgrade to Windows 10 to use the app or you could make a Windows 10 VM within your current system.
