### ISSUE TITLE
Download After Custom Date Issue

### ISSUE THREAD

**Issue by Escopy88** [sim0n00ps/OF-DL#200]
Hello,

I've set the custom date per the required format in the config.json file, but when selecting a custom profile, it still downloads everything, instead of only the media after the specific date.

I have the below lines setup in config.json, so I believe it's setup properly, unless I missed something:

"DownloadOnlySpecificDates": true,
"DownloadDateSelection": "after",
"CustomDate": "2023-10-23",

Any idea what my problem is? Besides this, everything is working perfectly fine for me.

**Comment by sim0n00ps** [comment]
Are you trying to get posts from that date onwards so posts on 2023-10-24, 2023-10-25 or on 2023-10-22, 2023-10-21 etc?

**Comment by Escopy88** [comment]
> Are you trying to get posts from that date onwards so posts on 2023-10-24, 2023-10-25 or on 2023-10-22, 2023-10-21 etc?

I'm trying to get posts after that date, so 10/24, 10/25 and onwards.

**Comment by sim0n00ps** [comment]
Could you try some other dates and see if the issue persists?

**Comment by Escopy88** [comment]
> Could you try some other dates and see if the issue persists?

Just tried, still had the same issue. No matter what date I put, it still downloads everything.

Also, I'm specifically referring to content in messages, I forgot to mention that. Does this only affect regular and/or paid posts?

**Comment by sim0n00ps** [comment]
This is a posts only feature

**Comment by Escopy88** [comment]
> This is a posts only feature

Ah ok, understood. Sorry for the false alarm. Any way this feature could be added for messages as well?

**Comment by sim0n00ps** [comment]
Maybe, the way it's done for posts is using an extra parameter on the API calls which I don't know if there is something similar for messages.

**Comment by Escopy88** [comment]
Ok no problem, understood. Thanks for responding.
