### ISSUE TITLE
How does DownloadDateSelection in config.json work?

### ISSUE THREAD

**Issue by rando2347** [sim0n00ps/OF-DL#201]
Trying to choose a specific date to download from, but what do I put into that particular field? What is the format for the date?

**Comment by sim0n00ps** [comment]
It should be yyyy-mm-dd

**Comment by sim0n00ps** [comment]
Set DownloadOnlySpecificDates to true and enter a date in the CustomDate field in yyyy-mm-dd format. Once you've selected a date, if you've got the DownloadDateSelection set to "after" then it will get all posts from that point onwards up until the current date and if you've set it to "before" then it will get all posts from before that date so if you set it to 2023-07-30 then you would gets posts on 2023-07-29, 2023-07-28 etc

**Comment by rando2347** [comment]
Got it, thank you
