### ISSUE TITLE
Date Format in Downloaded File Names

### ISSUE THREAD

**Issue by oska15** [sim0n00ps/OF-DL#205]
Hi,

I recently noticed that the option to customize file names is available. However, I am not sure if it is possible to include the date format in the name. Adding the date to the filename would be immensely helpful in organizing my downloaded content. Can you please confirm if this is allowed in the configuration settings? If so, can you guide me on how to set this up

for a YYYY-MM-DD format, how should I put it on the config file?

**Comment by sim0n00ps** [comment]
You can find the info about custom file formats here https://github.com/sim0n00ps/OF-DL/wiki/Custom-Filename-Formats. Dates are formatted in YYYY-MM-DD format
