### ISSUE TITLE
Video and audio files being created separately 

### ISSUE THREAD

**Issue by St4ndardDev1anT** [sim0n00ps/OF-DL#206]
On my latest run, when the program was downloading videos, it was creating separate audio and video .mp4 files titled "0hgk699qt6zqk1hiuysx7_adec.mp4" and "0hgk699qt6zqk1hiuysx7_vdec.mp4" respectively.

I think it may have something to do with this error I'm getting every time it tries to download a video:

```
Exception caught: Could not find file 'H:\Bocce Ball 3\OnlyFans\giantessclips\Posts\Free\Videos\0hgk699qt6zqk1hiuysx7_source.mp4'.

                                                                                                    StackTrace:    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize)
```

Additional context:
- I am using the 1.7.42 release
- I am using the 2 files necessary for downloading DRM protected files. I'm pretty sure the videos I'm trying to download are DRM protected.

**Comment by sim0n00ps** [comment]
Yes that is a DRM protected video. 0hgk699qt6zqk1hiuysx7_adec.mp4 and 0hgk699qt6zqk1hiuysx7_vdec.mp4 are the decrypted versions of the video + audio. Are you able to play either of them? To me this indicates maybe an ffmpeg issue as those 2 files should be merged together.

**Comment by St4ndardDev1anT** [comment]
Yes, I can play both of them separately. I'm not sure what would be wrong with ffmpeg.

**Comment by sim0n00ps** [comment]
Try deleting the vdec and adec files and delete the metadata folder, then try again

**Comment by St4ndardDev1anT** [comment]
I tried a few different times, and it didn't seem to fix anything. Sorry :/

**Comment by sim0n00ps** [comment]
Has a logs folder been created where OF DL.exe is located? If so then check if anything has been logged. What are the paths you have put in the Auth.json?

**Comment by St4ndardDev1anT** [comment]
I'm a dumbass.

Your guess was right. I copied over the wrong path for ffmpeg to the auth.json file when I updated to the latest release of OF-DL.

I fixed that and ran it again. Once I put the "adec" and "vdec" files back where they came from, it worked fine.

Sorry about that. Thanks for your help!
