### ISSUE TITLE
OF Downloader Menu Issue

### ISSUE THREAD

**Issue by JC02023** [sim0n00ps/OF-DL#207]
When I open the downloader after it logs me in successfully it would take forever for the menu to pop up. Is there a reason this happens?

**Comment by sim0n00ps** [comment]
All depends on how many subs you have and if you've set it to include expired Subscriptions, if you have a lot then it will have to do a request per 50 subs which is why it might be slow

**Comment by JC02023** [comment]
damn that makes sense i do include expired subs :(

**Comment by sim0n00ps** [comment]
How many subs do you have including expired ones?

**Comment by JC02023** [comment]
about 275

**Comment by sim0n00ps** [comment]
Yeah that probably explains it then
