### ISSUE TITLE
Getting text from posts

### ISSUE THREAD

**Issue by vaxtermat** [sim0n00ps/OF-DL#208]
Hello! I would like to know if it is possible to download the text in the posts.

I saw that there are possible entries in the metadata files so I would like to make sure this can be obtained or showed in some way.

Thank you in advance!

**Comment by sim0n00ps** [comment]
You could try using a custom filename format and use the 'text' variable. I don't really recommend this as you'll face some problems with illegal characters which are not allowed in filenames + the length of the text might exceed the maximum filename size. I would say use it at your own risk as I still need to make something to format them correctly.

**Comment by vaxtermat** [comment]
OK, thank you. I will wait patiently until this could be implemented.

**Comment by sim0n00ps** [comment]
Try it first, in config.json set PostFileNameFormat to {text}

**Comment by amezhong1** [comment]
> Try it first, in config.json set PostFileNameFormat to {text}

The raw {text} output often contains illegal characters and messy stuff like emojis, etc. May I suggest an option to simply output the titles into a text file, along with the file name? This way, I can use external tools such as [Advanced Renamer](https://www.advancedrenamer.com/) to bulk rename the files with the titles, and handle the random characters easier. Thank you!

**Comment by Osiris3-0** [comment]
Can messages be output as text files?I'd like to save the actual conversations I have with the guys I subscribe to.How would I do that?...or does this need to be implemented later?

**Comment by sim0n00ps** [comment]
> Can messages be output as text files?I'd like to save the actual conversations I have with the guys I subscribe to.How would I do that?...or does this need to be implemented later?

All messages are saved in the metadata DB file, you can export/view them all using a tool like https://sqlitebrowser.org/
