### ISSUE TITLE
Include the DRM decryption keys in the release

### ISSUE THREAD

**Issue by devdeviant** [sim0n00ps/OF-DL#211]
I admittedly don't know much about DRM and Widevine, but given that many are having issues generating the decryption keys, why can't we just bake them into the release binary? I am assuming there is a good reason not to do this.

**Comment by melithine** [comment]
Legal liability.

**Comment by devdeviant** [comment]
is there a secure way to share them besides discord/telegram?

**Comment by sim0n00ps** [comment]
I would have but the keys will simply get revoked within a few hours/days
