### ISSUE TITLE
Exception caught: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Bearded-Beard** [sim0n00ps/OF-DL#214]
> Exception caught: Object reference not set to an instance of an object.
> 
>                                            StackTrace:    at System.Object.GetType()
>    at OF_DL.Helpers.FileNameHelper.GetNestedPropertyValue(Object source, String propertyPath)
>    at OF_DL.Helpers.FileNameHelper.GetFilename(Object obj1, Object obj2, Object obj3, List`1 selectedProperties, Dictionary`2 users)
>    at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, Stri                                                                                            List postInfo, Medium postMe 

  "PaidPostFileNameFormat": "{username} - {postedAt} - {filename}",
  "PostFileNameFormat": "{username} - {postedAt} - {filename}",
  "PaidMessageFileNameFormat": "{username} - {createdAt} - {filename}",
  "MessageFileNameFormat": "{username} - {createdAt} - {filename}",
  
  They are the settings I'm using in config.
  
  if I remove all the  "{username} - {postedAt} - {filename}" the files download, but cause I've used DC's script I want to keep the formating the same, but it seems it gives errors?

**Comment by lukaeber** [comment]
I have the same issue, but only with Paid Posts that have DRM on.
