### ISSUE TITLE
"SkipAds": Parameter not working

### ISSUE THREAD

**Issue by CodeMaster19934** [sim0n00ps/OF-DL#217]
When downloading from creators there are always posts missing. Looking future all posts with Ads aren't downloaded even when "SkipAds": is set to true or false. When I download single missing post with the url it finds and downloads it.
![1](https://github.com/sim0n00ps/OF-DL/assets/35778603/437416f8-626a-4e62-a2bb-b9198ebd1ed4)
![2](https://github.com/sim0n00ps/OF-DL/assets/35778603/5b29e144-44b5-4514-b5bb-5595a5b282f7)
![3](https://github.com/sim0n00ps/OF-DL/assets/35778603/3442ccce-ce6b-49f3-b86f-a556f1b15d84)
![4](https://github.com/sim0n00ps/OF-DL/assets/35778603/9ef46fb7-e181-4f8c-ab49-575f9548e53a)

**Comment by sim0n00ps** [comment]
The code works on media ids, if a media id already exists in the list of post media it finds then it will only appear once, so I imagine that some of the media are dupes but I could be wrong, the count you see in my tool is how many items of media it has found that doesn't included dupes, OF's count will include everything regardless of if it's a dupe or not. In regards to the skip ads, I had to re-jig the logic for it and as far as I'm aware it works fine.

**Comment by CodeMaster19934** [comment]
Can i give you my auth data? It downloads everything except for post id 489486942 which contains @*User and link onlyfans.com/@User. When i download that single post id it downloads the 26 items that were missing in addition to the 92 posts coming to a total of 118 which onlyfans shows for media items from this user.

**Comment by sim0n00ps** [comment]
> Can i give you my auth data? It downloads everything except for post id 489486942 which contains @*User and link onlyfans.com/*@User. When i download that single post id it downloads the 26 items that were missing in addition to the 92 posts coming to a total of 118 which onlyfans shows for media items from this user. 

Try deleting the metadata folder from that users folder and running it again

**Comment by CodeMaster19934** [comment]
It didn't work

**Comment by sim0n00ps** [comment]
Drop your auth details here and the url you are entering, I'll delete the auth after

**Comment by CodeMaster19934** [comment]
"USER_ID": "5758565",
  "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
  "X_BC": "a2f5429b5c10070d685d35af4516a79e896415e8",
  "COOKIE": "fp=a2f5429b5c10070d685d35af4516a79e896415e8; csrf=Nx5EoSltd970c2e365e32f8ec64c3e8f12110504; lang=en; sess=6katsbd9k4mclh4vdrmbm3p2fj; auth_id=5758565; st=f3d00133e57e16fc7ad51002ed1bcabe7cddb71f5bb0c74c792de7bd738b5ca6",

**Comment by CodeMaster19934** [comment]
https://onlyfans.com/489486942/sarothicavip

**Comment by sim0n00ps** [comment]
Thanks I'll give it a try in a bit

**Comment by sim0n00ps** [comment]
Ok found the issue, seemed to be an issue with the SkipAds if statement, it was being completely disregarded with that post as it contained a free trial link so the other conditions were true and then it was skipping that post, I've simplified the process so it only checks for '#ad' or '/trial/' if you have SkipAds set to true in the config. Hopefully in this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.44 you should see the correct amount of media

**Comment by CodeMaster19934** [comment]
Thanks for your help 😊
