### ISSUE TITLE
Getting error when trying to download free message media

### ISSUE THREAD

**Issue by Escopy88** [sim0n00ps/OF-DL#218]
![WindowsTerminal_pNBKhAjBlV](https://github.com/sim0n00ps/OF-DL/assets/79072868/2768b1a8-16a1-4103-a3ad-5b26d97afab2)

Getting this error when trying to download free message media.. I don't think I had this issue in previous versions.

**Comment by CodeMaster19934** [comment]
Try deleting the metadata folder. It fixed it for me when i was having the same issue.

**Comment by Escopy88** [comment]
That didn't work unfortunately, but thanks for the tip.

**Comment by sim0n00ps** [comment]
Put your config here, I made a change this week to do with SkipAds which needs to reference the text if you have it set to true

**Comment by Escopy88** [comment]
Thanks, here's the file dump:

{
  "DownloadAvatarHeaderPhoto": false,
  "DownloadPaidPosts": false,
  "DownloadPosts": false,
  "DownloadArchived": false,
  "DownloadStreams": false,
  "DownloadStories": false,
  "DownloadHighlights": false,
  "DownloadMessages": true,
  "DownloadPaidMessages": false,
  "DownloadImages": false,
  "DownloadVideos": true,
  "DownloadAudios": false,
  "IncludeExpiredSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": "",
  "ShowScrapeSize": false
}

**Comment by Escopy88** [comment]
I tried this with SkipAds on or off and had the same issue
