### ISSUE TITLE
V1.7.41 i will put the log here

### ISSUE THREAD

**Issue by BlazeVertex** [sim0n00ps/OF-DL#219]
[OFDL20231124.txt](https://github.com/sim0n00ps/OF-DL/files/13456180/OFDL20231124.txt)

**Comment by sim0n00ps** [comment]
What version are you running? Because I've already fixed this, probably just need to update and that should fix it.

**Comment by BlazeVertex** [comment]
> I've already fixed this, probably just need to update and that should fix it.

It's in the title ok update it is thx for Checking out still you can close this
