### ISSUE TITLE
Looks like OnlyFans Knows About the Tools?

### ISSUE THREAD

**Issue by CharlieOneLockdown** [sim0n00ps/OF-DL#220]
Getting logged out much more frequently now than before.

Anyone else experiencing this issue?

**Comment by CharlieOneLockdown** [comment]
Tried updating and I'm getting these strange 404s...

https://i.imgur.com/4HwppCC.png

**Comment by St4ndardDev1anT** [comment]
I've noticed the same thing. I update auth.json with a fresh cookie, I immediately run OF DL, and it logs in successfully. But after a 10-20 minutes of running a job, it crashes without finishing the job. If I open OF DL again without updating auth.json, OF DL won't successfully log in, so I have to get a new cookie.

I'm not saying it's an issue that should or can be fixed. Just that it seems like cookies don't last as long as they used to before they need to be refreshed.

**Comment by sim0n00ps** [comment]
If it crashes then it should log it in the logs folder, that might give you an indication as to why it happened. It could be a multitude of things that cause it like rate limiting, OF servers going down, internet dropping out etc. Nothing much I can do about it really.

**Comment by CharlieOneLockdown** [comment]
Yup understood. I think it's OF changing their cookies because of your tool.  Was simply trying to bring it to your attention.

Thanks for responding so quickly!

**Comment by Wandererinchaos007** [comment]
> Yup understood. I think it's OF changing their cookies because of your tool. Was simply trying to bring it to your attention.
> 
> Thanks for responding so quickly!

Did you manage to find a workaround? Can't login at all. :/

**Comment by CharlieOneLockdown** [comment]
No, the tool still works.

Just gotta refresh the cookies more often.

**Comment by Wandererinchaos007** [comment]
> No, the tool still works.
> 
> Just gotta refresh the cookies more often.

How do i go about doing that exactly?

**Comment by sim0n00ps** [comment]
Changing just the sess value won't solve the problem. To me that sounds like your user-agent has changed as a result of your browser updating, so you need to login and what I would do is re-copy every value again, especially the user-agent, even if you think it's correct.

**Comment by Mareckyyy** [comment]
> > Yup understood. I think it's OF changing their cookies because of your tool. Was simply trying to bring it to your attention.
> > Thanks for responding so quickly!
> 
> Did you manage to find a workaround? Can't login at all. :/

I just logged to OF from another browser and copied credentials to auth.json
Remember to not use that browser for OF
