### ISSUE TITLE
No longer works after 11 Dec Update

### ISSUE THREAD

**Issue by craigp1231** [sim0n00ps/OF-DL#224]
OF was updated 11 Dec, and the changes seem to break this tool :(

I get,

Auth failed, please check the values in auth.json are correct, press any key to exit

Even though I have ensured the cookies, X-Bc etc are correct

**Comment by Mareckyyy** [comment]
I've same issue

**Comment by sim0n00ps** [comment]
Nothing has changed and OF hasn't been updated. Your browser has most likely updated and you haven't realised, this will change the user-agent. Please make sure if you change the sess and the auth doesn't work, log in again and re-copy your sess and user-agent into auth.json!

**Comment by Mareckyyy** [comment]
Opened OF-DL again and logged me successfully without touching auth.json

**Comment by craigp1231** [comment]
It was a combination of the rule set not being updated. I changed the code to look at the updated rule set and the User-Agent string had changed like @sim0n00ps suggested
