### ISSUE TITLE
Found 0 Paid Messages

### ISSUE THREAD

**Issue by Poddi** [sim0n00ps/OF-DL#225]
Hello,
i purchased three videos from the chat/messages which i tried to download but i'm getting:

Getting Paid Messages
Found 0 Paid Messages

**Comment by deadbeatdandylyon** [comment]
It usually shows that all the time, check in your regular messages, paid sometimes it shows there or in the normal posts folder

**Comment by Poddi** [comment]
> It usually shows that all the time, check in your regular messages, paid sometimes it shows there or in the normal posts folder

No it doesnt download anything

**Comment by sim0n00ps** [comment]
Please put your config here

**Comment by wioch** [comment]
I have the same issue. 

My config:
```
{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "D:/",
  "PaidPostFileNameFormat": "{id}_{mediaid}_{filename}",
  "PostFileNameFormat": "{username}_{id}_{mediaid}_{mediaCreatedAt}",
  "PaidMessageFileNameFormat": "{id}_{mediaid}_{createdAt}",
  "MessageFileNameFormat": "{id}_{mediaid}_{filename}",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": "",
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": false
}
```

Output from the script:
```
auth.json located successfully!
config.json located successfully!
ffmpeg.exe located successfully!
device_client_id_blob located successfully!
device_private_key located successfully!
Logged In successfully as <user>

Scraping Data for <OF-account>
Folder for <OF-account> already created
Getting Paid Posts
Found 0 Paid Posts
Getting Posts
```

... and it seems script got stuck in _Getting Posts_
Or am I not patient enough ?

**Comment by WastelandSquid** [comment]
Hi, I'm having this problem too, only for messages and paid messages it looks like. Here's my config 
[config.json](https://github.com/sim0n00ps/OF-DL/files/13987017/config.json)

**Comment by sim0n00ps** [comment]
> Hi, I'm having this problem too, only for messages and paid messages it looks like. Here's my config 
> [config.json](https://github.com/sim0n00ps/OF-DL/files/13987017/config.json)
> 

You have DownloadImages, DownloadVideos and DownloadAudios set to false which essentially means you're telling the scraper you don't want to download anything, you need to set those to true if you want that type of media to be downloaded

**Comment by WastelandSquid** [comment]
Ah, for some reason I thought disabling those meant something else and having the messages as true would be good enough. Thank you so much.
