### ISSUE TITLE
I know you may not have time, but I would like to ask a favor

### ISSUE THREAD

**Issue by jon-leaker** [sim0n00ps/OF-DL#226]
Hi sim0n00ps, there is a website similar to onlyfans that is extremely popular in Brazil, whose name is privacy.com.br.

I tried to use the script on it, but I searched the entire site and didn't find the necessary data, (auth_id // cookies), and others.

I know it's a selfish request, but writing code like this is still far beyond my capabilities. Could you see if it is possible to adapt the script to work on privacy? To allow the download of videos.

Thank you so much!

**Comment by melithine** [comment]
I don't think we have time to work on a site we've never even heard of... sites like this are popping up all the time and we can't adopt them all. They all have vastly different tech and requirements. Closing as wontfix.
