### ISSUE TITLE
OF Account Banned

### ISSUE THREAD

**Issue by CharlieOneLockdown** [sim0n00ps/OF-DL#233]
Looks like OF is catching on?  They banned my account today.

Careful ya'll

https://i.imgur.com/OtkseHP.png

**Comment by deadbeatdandylyon** [comment]
Did you actually message them to find out why?

**Comment by Escopy88** [comment]
There's alot of things  you can get banned for.. How are you sure it's because of using this?

**Comment by SuperPoorMan** [comment]
Hm, I am unable to scrape without OF kicking my account and needing me to re-login

**Comment by edge-evolution** [comment]
> Hm, I am unable to scrape without OF kicking my account and needing me to re-login

Are you using Firefox. It happens to me there. On Chrome it's fine.

**Comment by sim0n00ps** [comment]
Please update your user-agent and sess. If 1 bit of information is not correct then you'll get logged out.
