### ISSUE TITLE
new bug maybe? 

### ISSUE THREAD

**Issue by charlieorwell** [sim0n00ps/OF-DL#234]
I've been trying to download or just run the program again but it keeps on saying the auth failed even though the details are 100% correct. I did notice though when trying to login and grabbing the session key from OF and then trying to run the program again, it would log me out of OF. Not sure if this is normal behaviour but with it logging me out of OF the session key obviously changes again. 
Not sure if this bascially means OF are shutting this down and we won't be able to run it anymore?

**Comment by deadbeatdandylyon** [comment]
Usually when I get this problem, I recopy and paste the sess / x_bx and user agent, and it works, also make sure your browser is updated to the latest sometimes that can cause a problem, and i do believe it is also normal sometimes when you go into get the session key it logs you out, just log back in with the window still open, that's been my experience

**Comment by charlieorwell** [comment]
actually just fixed mine now, I was missing the "X_BC" line from my auth.json for some reason. Must have accidentally deleted it when editing some pathways. 😅
