### ISSUE TITLE
device_client_id_blob and/or device_private_key missing, https://cdrm-project.com/ will be used instead for DRM protected videos

### ISSUE THREAD

**Issue by Studmuffin1134** [sim0n00ps/OF-DL#236]
What do i do to solve this i have all the right auth info?

**Comment by ogevilmike** [comment]
same... shuts down right after. also logs me out of OF. I verified info many times now.

**Comment by Becauseynot101** [comment]
if ur using the .json program to edit inside of, try using the notepad to put the information in instead. also helps a lot to use the browser extension mentioned in the installation instructions.
