### ISSUE TITLE
Feature Request - Getting Text From Messages

### ISSUE THREAD

**Issue by Osiris3-0** [sim0n00ps/OF-DL#237]
Can messages be output as text files?I'd like to save the actual conversations I have with the guys I subscribe to.How would I do that?...or does this need to be implemented later?

**Comment by sim0n00ps** [comment]
All of the messages are in the user_data.db within the messages table. You can download a tool like this https://sqlitebrowser.org/dl/ and navigate to the messages table and then highlight all of the text fields in all the rows, you should be able to copy and paste to a text file that way
