### ISSUE TITLE
A .NET application failed

### ISSUE THREAD

**Issue by pro100Hub** [sim0n00ps/OF-DL#241]
Can't start "OF_DL.exe". Help me solve the problem.
![mmc_qEW00ql88u](https://github.com/sim0n00ps/OF-DL/assets/10475278/86c559ec-aad6-496b-aab3-caa2aea42ee2)

Install
![explorer_V6gGVR9yX2](https://github.com/sim0n00ps/OF-DL/assets/10475278/3d5ac47e-fa8b-4aa0-873e-30627969a694)

Windows 10 x64 Pro, OF.DL.V1.7.47

**Comment by sim0n00ps** [comment]
You only need .NET 7, the others should be uninstalled to stop conflicts from happening. The error you've got is that the app is developed using .NET 7 but you don't have that installed apparently so that's why you see the error.

**Comment by pro100Hub** [comment]
I deleted all other versions and left only "Microsoft Windows Desktop Runtime - 7.0.14 (x64)", but this did not help solve the startup problem.
In the neighboring topic (https://github.com/sim0n00ps/OF-DL/issues/242), a person has the same problem. Closes quickly when the file is opened.

**Comment by wioch** [comment]
Try installing NET 7.0.14 x86 from this below. **Warning**: the file will auto download:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.14-windows-x86-installer?cid=getdotnetcore

**Comment by pro100Hub** [comment]
@wioch 
Thanks, this solved the startup problem. 🥇
