### ISSUE TITLE
cant open the OF DL.exe

### ISSUE THREAD

**Issue by kililua** [sim0n00ps/OF-DL#246]
just opened the exe and it closed immediately after "auth.json located successfully!"

edit:

closed immediately after device_client_id_blob blablabla
![Screenshot (554)](https://github.com/sim0n00ps/OF-DL/assets/106385047/95de68ca-12df-4a9c-ad6b-5c9cd2f7249c)

**Comment by sim0n00ps** [comment]
Check where OF DL.exe is located and has a logs folder been created? If so check the .txt files and see what the exceptions are

**Comment by kililua** [comment]
Exception caught: The SSL connection could not be established, see inner exception.

**Comment by sim0n00ps** [comment]
Could you paste the whole thing here?

**Comment by kililua** [comment]
2023-12-31 05:19:39.436 +07:00 [ERR] Exception caught: The SSL connection could not be established, see inner exception.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth)
2023-12-31 05:19:39.462 +07:00 [ERR] Inner Exception: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch

StackTrace:    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
2023-12-31 05:19:39.463 +07:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.Main()

**Comment by sim0n00ps** [comment]
So its failing trying to test your auth to see if its valid or not. Are you using a VPN or do you have any sort of Antivirus enabled?

**Comment by kililua** [comment]
I have vpn installed but I don't use it, and i only using windows security no antivirus installed. just turned off windows security and the error still remain

**Comment by sim0n00ps** [comment]
I would try with the VPN on, to me it seems like an ISP problem that they are blocking it.

**Comment by vilake123** [comment]
need help after open program OF DL.exe will be close

2024-01-04 15:55:05.582 +07:00 [ERR] Exception caught: Bad JSON escape sequence: \[. Path 'FFMPEG_PATH', line 6, position 22.

StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at OF_DL.Program.Main()

**Comment by sim0n00ps** [comment]
> need help after open program OF DL.exe will be close
> 
> 2024-01-04 15:55:05.582 +07:00 [ERR] Exception caught: Bad JSON escape sequence: \[. Path 'FFMPEG_PATH', line 6, position 22.
> 
> StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
>    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
>    at Newtonsoft.Json.JsonTextReader.ReadAsString()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    at OF_DL.Program.Main()

Show me what you have put in the FFMPEG_PATH

**Comment by vilake123** [comment]
> > need help after open program OF DL.exe will be close
> > 2024-01-04 15:55:05.582 +07:00 [ERR] Exception caught: Bad JSON escape sequence: [. Path 'FFMPEG_PATH', line 6, position 22.
> > StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
> > at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
> > at Newtonsoft.Json.JsonTextReader.ReadAsString()
> > at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
> > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
> > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> > at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
> > at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
> > at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
> > at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
> > at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
> > at OF_DL.Program.Main()
> 
> Show me what you have put in the FFMPEG_PATH

![Screenshot_1](https://github.com/sim0n00ps/OF-DL/assets/121279476/6ea90548-ad12-48e1-936c-b4adb75b7c2c)

**Comment by sim0n00ps** [comment]
> > > need help after open program OF DL.exe will be close
> > > 2024-01-04 15:55:05.582 +07:00 [ERR] Exception caught: Bad JSON escape sequence: [. Path 'FFMPEG_PATH', line 6, position 22.
> > > StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
> > > at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
> > > at Newtonsoft.Json.JsonTextReader.ReadAsString()
> > > at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
> > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
> > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> > > at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
> > > at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
> > > at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
> > > at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
> > > at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
> > > at OF_DL.Program.Main()
> > 
> > Show me what you have put in the FFMPEG_PATH
> 
> ![Screenshot_1](https://github.com/sim0n00ps/OF-DL/assets/121279476/6ea90548-ad12-48e1-936c-b4adb75b7c2c)
> 
> ![Screenshot_2](https://github.com/sim0n00ps/OF-DL/assets/121279476/ea48049f-1147-4f09-92a3-89fb09d76583)
> 

Replace the \ with /
And you need to add /ffmpeg.exe to the end of the path as currently you are providing the folder where ffmpeg is and not the actual exe

**Comment by melithine** [comment]
Note that VSCode's syntax highlighting is explicitly warning you that what you have there isn't valid JSON, thus the red underline.

**Comment by vilake123** [comment]
> > > > need help after open program OF DL.exe will be close
> > > > 2024-01-04 15:55:05.582 +07:00 [ERR] Exception caught: Bad JSON escape sequence: [. Path 'FFMPEG_PATH', line 6, position 22.
> > > > StackTrace:    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
> > > > at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
> > > > at Newtonsoft.Json.JsonTextReader.ReadAsString()
> > > > at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
> > > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
> > > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> > > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
> > > > at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> > > > at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
> > > > at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
> > > > at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
> > > > at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
> > > > at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
> > > > at OF_DL.Program.Main()
> > > 
> > > 
> > > Show me what you have put in the FFMPEG_PATH
> > 
> > 
> > ![Screenshot_1](https://private-user-images.githubusercontent.com/121279476/294306914-6ea90548-ad12-48e1-936c-b4adb75b7c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDgyOTcsIm5iZiI6MTcwNDQ0Nzk5NywicGF0aCI6Ii8xMjEyNzk0NzYvMjk0MzA2OTE0LTZlYTkwNTQ4LWFkMTItNDhlMS05MzZjLWI0YWRiNzViN2MyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwOTQ2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGI4NzdlNTM0MWMxNDJlOGZhNWUyOTAyZTJmNmM5MDM0MjE2NjhmMjQ0MzQ2NDBmZTc0ZDczMTI1NjY2MTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SjtE0G7J0irQbujLRk19-dnQ6Rqmw2nO_cNOI7Cnwm0)
> > ![Screenshot_2](https://private-user-images.githubusercontent.com/121279476/294307212-ea48049f-1147-4f09-92a3-89fb09d76583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDgyOTcsIm5iZiI6MTcwNDQ0Nzk5NywicGF0aCI6Ii8xMjEyNzk0NzYvMjk0MzA3MjEyLWVhNDgwNDlmLTExNDctNGYwOS05MmEzLTg5ZmIwOWQ3NjU4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwOTQ2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTcxNmQ3YzZhNjg1NWE0OTExZDM0MmIzNjIwNjgxMWY2NjdjZTBiYTk1Y2U1ODQ1MDZjN2JlN2Y0OGZlMTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.en0mAe051tP3NJ8wuGAXx_VEpEC-inWElJx2-NHbDic)
> 
> Replace the \ with / And you need to add /ffmpeg.exe to the end of the path as currently you are providing the folder where ffmpeg is and not the actual exe

![Screenshot_3](https://github.com/sim0n00ps/OF-DL/assets/121279476/787ddf2f-e734-4872-9f75-2e193ac264d8)

2024-01-05 16:46:07.373 +07:00 [ERR] Auth failed

**Comment by sim0n00ps** [comment]
Your Auth information is not correct, please copy it from the browser again

**Comment by vilake123** [comment]
> Your Auth information is not correct, please copy it from the browser again

I copy it from browser again. but still the same
I'm using opera gx
