### ISSUE TITLE
Error/warning messages during scrapping

### ISSUE THREAD

**Issue by wioch** [sim0n00ps/OF-DL#247]
Scrap is now completed, but on terminal window, I noticed following messages:
```
Downloading 27423 Posts ----------------------------------------  40% An error occurred: Próba połączenia nie powiodł                                                                     onym okresie czasu lub utworzone połączenie nie
Downloading 27423 Posts ----------------------------------------  60%ns.com:443) An error occurred: Próba połączenia nie powiodł                                                                     onym okresie czasu lub utworzone połączenie nie
ns.com:443)
```

Roughly translated to:
` Connection attempt failed in specified time or created connection did not...`
...ns.com:443 suggest the OF. 

and 
`Downloading 27423 Posts ----------------------------------------  99%Media was null`

There are no other logs available. 
What could be the reason of those two and how to troubleshoot them ?

Enhancement suggestion: Add more logging (to separate file) from scrapping process.

**Comment by sim0n00ps** [comment]
To me it seems like you've been rated limited so that's why you get an exception, most likely because you're downloading 20k + media in a few hours
