### ISSUE TITLE
Scrap media not complete. 

### ISSUE THREAD

**Issue by wioch** [sim0n00ps/OF-DL#248]
First scrap completed in ~1k+ minutes. 
Second scrap completed way faster (I assume that script is checking posts against its database).
Yet, on OF page there are that many medias:
![image](https://github.com/sim0n00ps/OF-DL/assets/29070885/734b6471-c40a-46ab-9c78-bcfe488664d1)

Script's amount of posts: (this is from second run of scrapping)
`Downloading 27505 Posts ----------------------------------------  64%`

And in scrap directory I have:
- 26521 images
- 853 vids

Where does this discrepancy comes from and how to fix it ?
Again, no logs available.

**Comment by sim0n00ps** [comment]
The count on OF includes duplicates where the Media ID is the same, the script will not download duplicates because it is pointless, that is why there is a difference in count between what is downloaded and what the count is on OF
