### ISSUE TITLE
Feature request: Ability to connect to a proxy.

### ISSUE THREAD

**Issue by vnnegt** [sim0n00ps/OF-DL#25]
I think the ability to use a proxy in order to mask our (numerous) requests would be nifty.

For example - we could connect to the exposed port of a docker VPN and route our requests through the VPN whilst our other traffic is unaffected.

Thanks!

**Comment by sim0n00ps** [comment]
I appreciate the suggestion but I think for something like that I'd probably recommend you pull the code and try to implement that yourself.
