### ISSUE TITLE
Could not find file ***.mp4

### ISSUE THREAD

**Issue by ghost** [sim0n00ps/OF-DL#250]
When I try to download drm videos I get the following error:

Exception caught: Could not find file 'S:\OF DL\__user_data__\sites\OnlyFans\[author]\Posts\Free\Videos\0hf22h5ksf2oc3ays9qcl_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id,                                                                     Media, Author author, Dictionary`2 users, Config con

I have generated the blob files by myself multiple times, it never worked. I also tried to just use it with cdrm-project, in every case this error occurs. How to solve htis error?

**Comment by sim0n00ps** [comment]
What files are actually in the Videos folder?
What version are you running, if it's the latest then ensure ffmpeg is updated and the path is accessible and correct

**Comment by xjzjason** [comment]
I found the same error only when I trying to download DRM videos.

Exception caught: Could not find file 'E:\OF DL_user_data_\sites\OnlyFans[author]\Posts\Free\Videos\XXXXXX_source.mp4'.

**Comment by sim0n00ps** [comment]
I never ever get this error. Are you using a custom format and check the videos folder after the exception is thrown, does that file actually exist or is it not being created at all?

**Comment by xjzjason** [comment]
I'm sure that the file is not created.

**Comment by thethirdguy** [comment]
> I never ever get this error. Are you using a custom format and check the videos folder after the exception is thrown, does that file actually exist or is it not being created at all?

I got this error too. Seems like it's a common error when it comes to drm videos. I tried every solution I find, but I failed.

**Comment by thethirdguy** [comment]
> This is an issue with the FFMpeg binary that is being used.
> 
> Non-DRM content is downloaded from the server as a mp4 file however, DRM protected content is delivered as DASH (mpd). The FFMpeg binary that is used has to be built with DASH-demuxer enabled, otherwise it is unable to download DASH content and you'll encounter the error in question with OF-DL.
> 
> The DASH-demuxer requires FFMpeg to be built specifically with libxml2 enabled. When libxml2 is enabled, DASH-demuxer will be enabled automatically by the config. Likewise, if libxml2 isn't enabled, DASH-demuxer will be automatically disabled and will not be available.
> 
> So, if you are building your own FFMpeg binary, remember to include "--enable-libxml2" in the config. Otherwise the resulting binary will not work with OF-DL, for DRM-content.
> 
> You can easily check if the FFMpeg binary you are using has DASH-demuxer available and hence, is compatible with OF-DL: "ffmpeg.exe -demuxers" (the alphabetically sorted should include dash).
> 
> This should be mentioned in the OF-DL documentation however, even currently it does mention which FFMpeg binaries should be used (https://of-dl.gitbook.io/of-dl/requirements) and the binaries specified (ffmpeg-release-essentials) indeed do include DASH-demuxer support and hence do not feature this issue.

Thank you so much for your advice, but it doesn‘t work out (latest released version: 6.1.1).

**Comment by thethirdguy** [comment]
> This is an issue with the FFMpeg binary that is being used.
> 
> Non-DRM content is downloaded from the server as a mp4 file however, DRM protected content is delivered as DASH (mpd). The FFMpeg binary that is used has to be built with DASH-demuxer enabled, otherwise it is unable to download DASH content and you'll encounter the error in question with OF-DL.
> 
> The DASH-demuxer requires FFMpeg to be built specifically with libxml2 enabled. When libxml2 is enabled, DASH-demuxer will be enabled automatically by the config. Likewise, if libxml2 isn't enabled, DASH-demuxer will be automatically disabled and will not be available.
> 
> So, if you are building your own FFMpeg binary, remember to include "--enable-libxml2" in the config. Otherwise the resulting binary will not work with OF-DL, for DRM-content.
> 
> You can easily check if the FFMpeg binary you are using has DASH-demuxer available and hence, is compatible with OF-DL: "ffmpeg.exe -demuxers" (the alphabetically sorted should include dash).
> 
> This should be mentioned in the OF-DL documentation however, even currently it does mention which FFMpeg binaries should be used (https://of-dl.gitbook.io/of-dl/requirements) and the binaries specified (ffmpeg-release-essentials) indeed do include DASH-demuxer support and hence do not feature this issue.

Thank you so much for your advice, but it doesn‘t work out (latest released version: 6.1.1).

**Comment by Arschmole** [comment]
> Thank you so much for your advice, but it doesn‘t work out (latest released version: 6.1.1).

The FFMpeg 6.1.1 binary from the "release essentials" [ffmpeg-release-essential.7z](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z) package together with the latest release binary of [OF-DL 1.7.48](https://github.com/sim0n00ps/OF-DL/releases/download/OFDLV1.7.48/OF.DL.V1.7.48.zip) work perfectly fine together for both DRM and non-DRM downloads. As does any other FFMpeg binary that has been built with "--enable-libxml2" configure flags (i.e., DASH-demuxer available).

Make sure your "auth.json" file has the full path pointing to THIS ffmpeg binary and that you don't have an another ffmpeg binary (without the DASH support) in anywhere in your path (in any directory pointed by the PATH environment-variable.

I guess it would be technically possible for there to be an another issue which causes this error, but I'm 99.5% sure it is the same one.

**Comment by frownfork** [comment]
> What files are actually in the Videos folder? What version are you running, if it's the latest then ensure ffmpeg is updated and the path is accessible and correct

This solved the error for me (updating ffmpeg). Thank you.

**Comment by fidelio959** [comment]
I have the same issue. I cannot download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas?

**Comment by Higgis39** [comment]
> I have the same issue. I can download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas? I have the latest version of OF DL and the 6.1.1 version of FFMPEG suggested above.

Same. I reverted back to 1.7.44, which still works well with DRM videos.

**Comment by fidelio959** [comment]
> > I have the same issue. I can download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas? I have the latest version of OF DL and the 6.1.1 version of FFMPEG suggested above.
> 
> Same. I reverted back to 1.7.44, which still works well with DRM videos.

Which version of ffmpeg you used in the version 1.7.44? Is it the same as in the 1.7.48?

**Comment by Higgis39** [comment]
> > > I have the same issue. I can download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas? I have the latest version of OF DL and the 6.1.1 version of FFMPEG suggested above.
> > 
> > 
> > Same. I reverted back to 1.7.44, which still works well with DRM videos.
> 
> Which version of ffmpeg you used in the version 1.7.44? Is it the same as in the 1.7.48?

Yes, 6.1.1

**Comment by xjzjason** [comment]
> > > > I have the same issue. I can download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas? I have the latest version of OF DL and the 6.1.1 version of FFMPEG suggested above.
> > > 
> > > 
> > > Same. I reverted back to 1.7.44, which still works well with DRM videos.
> > 
> > 
> > Which version of ffmpeg you used in the version 1.7.44? Is it the same as in the 1.7.48?
> 
> Yes, 6.1.1

Current docunments do not match to version1.7.44. Can you tell me how to complete YTDLP_PATH and MP4DECRYPT_PATH in auth.json?

**Comment by Higgis39** [comment]
> > > > > I have the same issue. I can download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas? I have the latest version of OF DL and the 6.1.1 version of FFMPEG suggested above.
> > > > 
> > > > 
> > > > Same. I reverted back to 1.7.44, which still works well with DRM videos.
> > > 
> > > 
> > > Which version of ffmpeg you used in the version 1.7.44? Is it the same as in the 1.7.48?
> > 
> > 
> > Yes, 6.1.1
> 
> Current docunments do not match to version1.7.44. Can you tell me how to complete YTDLP_PATH and MP4DECRYPT_PATH in auth.json?

![image](https://github.com/sim0n00ps/OF-DL/assets/18494359/484458f1-c96a-49c6-b7fa-0341a08a0ff3)

**Comment by xjzjason** [comment]
> > > > > > I have the same issue. I can download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas? I have the latest version of OF DL and the 6.1.1 version of FFMPEG suggested above.
> > > > > 
> > > > > 
> > > > > Same. I reverted back to 1.7.44, which still works well with DRM videos.
> > > > 
> > > > 
> > > > Which version of ffmpeg you used in the version 1.7.44? Is it the same as in the 1.7.48?
> > > 
> > > 
> > > Yes, 6.1.1
> > 
> > 
> > Current docunments do not match to version1.7.44. Can you tell me how to complete YTDLP_PATH and MP4DECRYPT_PATH in auth.json?
> 
> ![image](https://private-user-images.githubusercontent.com/18494359/298389269-484458f1-c96a-49c6-b7fa-0341a08a0ff3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTA1OTEsIm5iZiI6MTcwNTg5MDI5MSwicGF0aCI6Ii8xODQ5NDM1OS8yOTgzODkyNjktNDg0NDU4ZjEtYzk2YS00OWM2LWI3ZmEtMDM0MWEwOGEwZmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMjQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MDMyMjY5YWRmNGUyOTEyZmU2M2ZkNDA5NjA3ZDYwNjU3ZmRmZWNiMGU3ZTQyMGJlNDdmYWQ0YzNlM2NhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVUyHw3_G2CI9ptdrJd3KYU84_ciPbaJ4aFIdGB-h7g)

Thank you so much!

**Comment by sim0n00ps** [comment]
> > > > > > > I have the same issue. I can download all the videos with no DRM but get an error on paid ones. I update ffmpeg with no luck. Any ideas? I have the latest version of OF DL and the 6.1.1 version of FFMPEG suggested above.
> > > > > > 
> > > > > > 
> > > > > > Same. I reverted back to 1.7.44, which still works well with DRM videos.
> > > > > 
> > > > > 
> > > > > Which version of ffmpeg you used in the version 1.7.44? Is it the same as in the 1.7.48?
> > > > 
> > > > 
> > > > Yes, 6.1.1
> > > 
> > > 
> > > Current docunments do not match to version1.7.44. Can you tell me how to complete YTDLP_PATH and MP4DECRYPT_PATH in auth.json?
> > 
> > ![image](https://private-user-images.githubusercontent.com/18494359/298389269-484458f1-c96a-49c6-b7fa-0341a08a0ff3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTA1OTEsIm5iZiI6MTcwNTg5MDI5MSwicGF0aCI6Ii8xODQ5NDM1OS8yOTgzODkyNjktNDg0NDU4ZjEtYzk2YS00OWM2LWI3ZmEtMDM0MWEwOGEwZmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAyMjQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MDMyMjY5YWRmNGUyOTEyZmU2M2ZkNDA5NjA3ZDYwNjU3ZmRmZWNiMGU3ZTQyMGJlNDdmYWQ0YzNlM2NhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVUyHw3_G2CI9ptdrJd3KYU84_ciPbaJ4aFIdGB-h7g)
> 
> Thank you so much!

mp4decrypt and yt-dlp are no longer needed, just ffmpeg is needed

**Comment by idontknowatalll** [comment]
i have this issue too when i trying to donwload drm videos, tried update ffmpeg version metioned above, didn‘t work.

**Comment by bezaaas** [comment]
I'm using the latest version of OFDL, + latest version of ffmpeg, libxml2 enabled, DRM videos downloading fine, but some of videos nope. This doesn't always happen, but it drives me crazy when I realize I can't download everything.
