### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by fidelio959** [sim0n00ps/OF-DL#252]
Hello,
I tried many times to log in my OF account but every times I launch of-dl.exe it automatically log me out from onlyfans. Thus, I must login again generating a new session id.
I think it could be a new security measure to avoid scraping.
Any solutions?
thank you.

**Comment by sim0n00ps** [comment]
If you're being logged out then one of the bits of information is wrong. I would recommend you check the user-agent as they can change after a browser update and you might not realise it

**Comment by fidelio959** [comment]
This works!! Thank you mate.

**Comment by fidelio959** [comment]
This works!! Thank you mate.
