### ISSUE TITLE
Path to mp4decrypt is not valid filepath or does not exists

### ISSUE THREAD

**Issue by dvkrav** [sim0n00ps/OF-DL#253]
I downloaded Bento4-SDK-1-6-0-641.universal-apple-macosx.zip and extracted it on my Mac. When I am adding the path to mp4decrypt
? mp4decrypt path:  ~/Downloads/Bento4-SDK-1-6-0-641.universal-apple-macosx/bin/mp4decrypt 
it keeps giving the error
Path to mp4decrypt is not valid filepath or does not exists
What am I missing ?

**Comment by sim0n00ps** [comment]
Unfortunately the script doesn't support Mac OSX.

**Comment by melithine** [comment]
As a follow-up to this, we now have Docker support, so you can run OFDL in Docker on your Mac.
