### ISSUE TITLE
Permanently stuck on "Getting posts"

### ISSUE THREAD

**Issue by gabeinthewater** [sim0n00ps/OF-DL#257]
Auth goes through, account to scrape gets chosen, but I'm permanently stuck on "getting posts". Any advice, potential glitch? App has worked in the past for profiles larger than this, but now it isn't worked for anything, I've updated the auth information and everything,

**Comment by Darkpte** [comment]
Same Problem Stuck on getting posts and nothing starts or download. Please help

**Comment by deadbeatdandylyon** [comment]
I've been scraping all night into the morning without any issues. sometimes it does take awhile for it to move past "Getting Posts" but it has all gone through for me.
