### ISSUE TITLE
I started OF.DL.V1.7.48 but it cannot locate ffmpeg.exe On windows 11

### ISSUE THREAD

**Issue by sulicad** [sim0n00ps/OF-DL#258]
Hello,
I have just downloaded the program.
When I start it the following message appears:

"auth.json located successfully!
config.json located successfully!
The provided path  does not exist or is not accessible.
Cannot locate ffmpeg.exe; please modify auth.json with the correct path. Press any key to exit."

I downloaded ffmpeg.exe from another site an I placed it under the same folder but the same message continues.

**Comment by sim0n00ps** [comment]
What is the path you have provided?

**Comment by sulicad** [comment]
I didn't provide any paths. I just downloaded the last release, extracted it. I placed ffmpeg.exe on the extracted folder and clicked on the executable.

**Comment by sim0n00ps** [comment]
You need to provide the path to ffmpeg.exe in the auth.json file
