### ISSUE TITLE
Cannot locate FFMPeg even after I added it to the JSON file?

### ISSUE THREAD

**Issue by githubuser9542** [sim0n00ps/OF-DL#263]
First I tried to enter the auth json file information manual using dev tools, and upon executing the OF DL file, the black command prompt thing would open up and then immediately closed.

So I downloaded the firefox extension to copy past the information and then pasted it over the auth json file. And then after this it loaded the black box fine and said auth and config loaded succesfully but that it could not locate the ffmpeg file. I tried to manually input this under one of the lines as "    "ffmpeg_path": "C:\Users\YYY\Downloads\Compressed\ffmpeg.exe" and then when I ran it again, I got the first issue where it would immediately close.

That firefox extension does not include the path in its copy paste, so I spent like an hour trying to add the path to ffmpeg but i cant because of the described issues. Not everyone is tech savvy so its hard to understand that for some people even adding a path to the file can be difficult. 

Any tips? if you can show me an example of how you manually added the path line under the cookie copy/paste extension's autogenerated text, that could help me.

**Comment by fidelio959** [comment]
Use the / in the path in the auth.json. Like this "C:/Users/YYY/Downloads/Compressed/ffmpeg.exe"

**Comment by githubuser9542** [comment]
> Use the / in the path in the auth.json. Like this "C:/Users/YYY/Downloads/Compressed/ffmpeg.exe"

Did that and it still cant locate the ffmpeg

https://prnt.sc/z4Rgmov-kSTY

I pasted the entire file here in this screenshot, because I know i probably made some rookie mistake. Im not sure if the line for ffmpeg_path has to be pasted somewhere else or if it has to be indented. I tried indenting it to allign with x_bc , user agent etc, and then after I do that it says "You are about to save the document in a text only format which will remove all formatting"

I can also try pasting the information the extension that grabs the OF info for you into the template file thats on the original OF-DL

Appreciate your help

**Comment by sim0n00ps** [comment]
> > Use the / in the path in the auth.json. Like this "C:/Users/YYY/Downloads/Compressed/ffmpeg.exe"
> 
> Did that and it still cant locate the ffmpeg
> 
> https://prnt.sc/z4Rgmov-kSTY
> 
> I pasted the entire file here in this screenshot, because I know i probably made some rookie mistake. Im not sure if the line for ffmpeg_path has to be pasted somewhere else or if it has to be indented. I tried indenting it to allign with x_bc , user agent etc, and then after I do that it says "You are about to save the document in a text only format which will remove all formatting"
> 
> I can also try pasting the information the extension that grabs the OF info for you into the template file thats on the original OF-DL
> 
> Appreciate your help

Your file is totally wrong, you've copied the whole thing from the browser extension which is not what you need to do. The auth.json file included in the release is what you need, all you need to do is fill in the values. So you'll need to re-download the latest release and copy the auth.json file from that to where you currently have OF DL.exe and then take the information from the browser extension and copy the values from the browser extension into each field in the auth.json file.
