### ISSUE TITLE
Can OF-DL be used on the MAC side?

### ISSUE THREAD

**Issue by lucacham** [sim0n00ps/OF-DL#266]
Currently I'm using it on Windows and everything works fine. 
Since I will be traveling for a few days, I would like to ask if OF-DL can be used on Mac?

**Comment by whimsical-c4lic0** [comment]
It's probably too late for your traveling plans, but OF-DL can now be ran on macOS using Docker. If you do not have Docker installed, you can install it by following their [installation directions](https://docs.docker.com/desktop/install/mac-install/). Afterwards, use your terminal app to run the [OF-DL docker commands](https://of-dl.gitbook.io/of-dl/install#running-via-docker).
