### ISSUE TITLE
Error while downloading content

### ISSUE THREAD

**Issue by greyhat94** [sim0n00ps/OF-DL#268]
I was trying to download content, and I've got this error:  "**An error occurred: Unable to read data from the trans
Downloading 907 Posts ----------------------------------------  62%host remoto**". 

How can I fix this? Should I start again the process? I'm doing this operation through VPN and, so far, I didn't experience any issue. If I re-start the process, will the software download the same content or does it have a memory of the previous downloaded file? Thanks in advance for your suggestion.

**Comment by melithine** [comment]
It tracks what was downloaded previously, yes.

**Comment by JohnMascript** [comment]
How to fix this? I keep getting the same issue. First download worked fine, every new attempt shows this error. Thanj you very much in advance
