### ISSUE TITLE
A Few Concerns.

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#27]
_Hello, I'm not sure if this is a bug or if this happens from time to time. but I ran a scrape on an account I think it does download everything from the page but for some reason it stops at 99% I have another one but that one stops at 80% so i'm not sure what's going on._

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/3393270b-aeae-449b-b5e7-042576f12a47)

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/6edd17c0-c0df-4de8-921e-37bdfc09daa0)

The above are the only two that seem to be stopping at these percentages 

This is a secondary issue I am running into and it only happens on one account 

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/272fdafd-5323-4fc3-9301-68b8d8d10c0e)

Any thoughts on these? should I be concerned about anything?

**Comment by sim0n00ps** [comment]
> _Hello, I'm not sure if this is a bug or if this happens from time to time. but I ran a scrape on an account I think it does download everything from the page but for some reason it stops at 99% I have another one but that one stops at 80% so i'm not sure what's going on._
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/3393270b-aeae-449b-b5e7-042576f12a47)
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/6edd17c0-c0df-4de8-921e-37bdfc09daa0)
> 
> The above are the only two that seem to be stopping at these percentages 
> 
> This is a secondary issue I am running into and it only happens on one account 
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/272fdafd-5323-4fc3-9301-68b8d8d10c0e)
> 
> Any thoughts on these? should I be concerned about anything? 

Okay, regarding the first thing you mentioned, it probably is downloading everything but probably when it's checking for files that are already downloaded it might not be increasing the progress bar by the size of the file already downloaded hence why it isn't reaching 100%. I have had this happen to me but I never got around to looking into it. 

The second thing is an easy fix.
