### ISSUE TITLE
Download does not start

### ISSUE THREAD

**Issue by Sialarson** [sim0n00ps/OF-DL#272]
I created a list with one Account in it and when i select the list and confirm nothing happens. Just Downloading from List(s): SubScrape Completed in 2,57 minutes
Scrape Completed in 0,72 minutes
Select Accounts to Scrape | Select All = All Accounts | List = Download content from users on List | Custom = Specific
Account(s)

pops up afterwards.

**Comment by melithine** [comment]
Try with the latest release.
