### ISSUE TITLE
Slow downloading

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#273]
Hello. how can I speed it up? I have 1 gbit, but the script downloads 600 files with total weight 4 GB about half an hour. thanks

**Comment by lucacham** [comment]
my home is 200M bandwidth, the download speed with OF-DL is usually around 300mbps~<400mbps/s

**Comment by bezaaas** [comment]
Maybe i need to change some settings? Because other scripts working much faster...

**Comment by Crimsoonhack** [comment]
If you go to the config.json file, you can change the value of `DownloadLimitInMbPerSec`

**Comment by bezaaas** [comment]
thank you so much!
