### ISSUE TITLE
Question about DRM and cdrm-project

### ISSUE THREAD

**Issue by waltersoapcheck420** [sim0n00ps/OF-DL#274]
What is the difference with using the default cdrm-project instead of generating the device_client_id_blob and device_private_key files? If it's the same then why go through the extra trouble to generate the files?

**Comment by sim0n00ps** [comment]
cdrm-project is used to save time and makes it easier for people to use the tool. It saves you having to generate your own keys but that also means that if the site goes down for whatever reasons then you'll be sort of screwed until it comes back up. If you've got your own keys then you'll be able to make requests to get the decryption keys all of the time. So essentially generate the keys if you want and can be bothered but you can just use the default cdrm-project for ease of use and face the issue of cdrm-project going down for whatever reason when it happens.
