### ISSUE TITLE
ffmpeg : Unrecognized option 'cenc_decryption_key' on Ubuntu 22.04 with internal ffmpeg lib

### ISSUE THREAD

**Issue by peddanet** [sim0n00ps/OF-DL#276]
Hi,

I am using OF DL v1.7.48 on an ubuntu system 22.o4 and generally it works brilliantly.I only have issues with decrypted files. 
The videos could not manually be downloade with JDownloader2 or Video Downloadhelper. Context menu of firefox is greyed out.

```
Downloading 5 Paid Messages ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  20%s:line 1004
                                                                         ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: 
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
Unrecognized option 'cenc_decryption_key'.
Error splitting the argument list: Option not found

Exception caught: Could not find file '~/of/da[..]30_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize) in ~/Projects/OF_DL_1.7.48/OF DL/Helpers/DownloadHelper.cs:line 628
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedMessageDRMVideo(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String                                                                          filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users, Config config, Boolean showScrapeSizDownloading 5 Paid Messages ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  20%s:line 1004

```
So far done:

- followed installation steps, especially [ffmpeg and CDM requirements](https://of-dl.gitbook.io/of-dl/requirements). Use default solution with web page regarding CDM as I was not able to install CDM so far....

After the error first occured 3 weeks before (or at least I was aware because my file was not downloaded), I

- downloaded and build the actual n.6.1.1 build and installed it in `/usr/bin/ffmpeg` as well as ffprobe and ffplay

The error stays as unrecognized. Google did not much help here related to ffmpeg.

Debugging:
In the man page of ffmpeg I did not find any hint regarding that option and also in general for decryption there was only a hint to VOB decryption (totally different context seems)

In `./helper/DownloadHelper.cs`in line 596 this option is nevertheless instantiated and in line 604 it is called then in method `DownloadDrmMedia()`. The exception "file not found" (a successor error I guess) refers to line 628 which is funnily the end of this function.

I found on [stackoverflow](https://stackoverflow.com/questions/42532106/ffmpeg-error-splitting-the-argument-list-option-not-found#answer-57247316) this solution suggestion putting the args not into a single string but in a list of args. But if the option is simply unknown to ffmpeg?? 

I was calling very simply:
```
~/Projects/OF_DL_1.7.48/OF DL/bin/release/net7.0/linux-x64/publish$ ffmpeg -cenc_decryption_key
ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: 
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
Unrecognized option 'cenc_decryption_key'.
Error splitting the argument list: Option not found
```

I assume an issue here. But if not, any help is appreciated!

**Comment by peddanet** [comment]
I add a ```
Log.Debug("ProcessStartInfo ffmpeg Arguments: $ffmpeg {0}", ffmpegStartInfo.Arguments);
```
in line 599 after `ProcessStartInfo` and it just prints a incomplete call:
```
2024-02-10 16:53:50.172 +01:00 [DBG] ProcessStartInfo ffmpeg Arguments: $ffmpeg -cenc_decryption_key 3[..]74db -headers "Cookie:CloudFront-                                          Policy=ey[..]fQ__; CloudFront-Signature=p[..]__;            CloudFront-Key-Pair-Id=K[..]3; auth_id=12[..]5; sess=ipk[..]9qk^M
 Origin: https://onlyfans.com^M
 Referer: https://onlyfans.com^M
 User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0^M
 ^M
 " -i "https://cdn3.onlyfans.com/dash/files/9/9c/9[..]9.mpd" -codec copy "/home/xxx/[..]/0h[..]99_source.mp4"
```

**Comment by peddanet** [comment]
BTW how do I enabling verbose debug prints to the console instead of the log file? Why is a Log.Info category missing ?

**Comment by peddanet** [comment]
Ok, I found now out that this option is only available with gyan.dev builds of ffmpeg. I overread this in the requitrements cause Ithought I had this package already in Ubuntu, but not from gyan.dev!! Now I am looking for the github project to rebuild the source for linux...if this is the case I will close this issue...

**Comment by peddanet** [comment]
I have rebuild the FFMpeg project gyan.dev in version n6.1.1 from [github](https://github.com/GyanD/codexffmpeg/releases).
Then I found out that the option `cenc_decryption_key` is provided without the dash (-) before. Simply running it from command shell gives the deviating result, no "splitting error" anymore. It is documented like this in `FFmpeg/doc/ffmpeg-all.html`.

Now I got subsequent errors:
```
Downloading 5 Paid Messages ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  20%s:line 1004
                                                                         ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: 
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
[in#0 @ 0x56290cc7e9c0] Error opening input: Protocol not found
[in#0 @ 0x56290cc7e9c0] Did you mean file:https://cdn3.onlyfans.com/dash/files/8/88/88ed70ac68ef915b2ef5cbfd99c2a46e/0hmabspr63ohkfulcme30.mpd?
Error opening input file https://cdn3.onlyfans.com/dash/files/8/88/88ed70ac68ef915b2ef5cbfd99c2a46e/0hmabspr63ohkfulcme30.mpd.
Error opening input files: Protocol not found
Exception caught: Could not find file '~/Desktop/heisser_Scheiss/fuck/of/danielknight/Messages/Paid/2557362198945 2024-01-29 04-22-16/Videos/0hmabspr63ohkfulcme30_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path, Boolean showScrapeSize) in ~/Projects/OF_DL_1.7.48/OF DL/Helpers/DownloadHelper.cs:line 628
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedMessageDRMVideo(String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String                                                                          filenameFormat, List messageInfo, Medium messageMedia, FromUser fromUser, Dictionary`2 users, Config config, Boolean showScrapeSiz
```

**Comment by peddanet** [comment]
Can nobody help, please? Did I something wrong?

**Comment by whimsical-c4lic0** [comment]
@peddanet I found that I needed to use the latest version of ffmpeg. Ubuntu and most linux distros ship a much older version of ffmpeg in their default package repositories. If you check the open PRs, I've written a working Dockerfile you can either use directly or as a reference for the required dependencies.

**Comment by peddanet** [comment]
I

> @peddanet I found that I needed to use the latest version of ffmpeg. Ubuntu and most linux distros ship a much older version of ffmpeg in their default package repositories. If you check the open PRs, I've written a working Dockerfile you can either use directly or as a reference for the required dependencies.

I did it by building ffmpeg myself with every possible feature, which was either available from github or the ubuntu apt repositories:
[ffmpeg_configure_enable_all.txt](https://github.com/sim0n00ps/OF-DL/files/14234984/ffmpeg_configure_enable_all.txt)

**Comment by peddanet** [comment]
Test with this build successfully tested! Thanks for the audience.
