### ISSUE TITLE
Docker instructions can be simplified

### ISSUE THREAD

**Issue by whimsical-c4lic0** [sim0n00ps/OF-DL#280]
Now that the docker branch has been merged, the GitHub repository can be referenced directly in the `docker build` command. This means that users won't need to run `git clone`. [The documentation](https://of-dl.gitbook.io/of-dl/install) can be updated to use `docker build -t of-dl https://github.com/sim0n00ps/OF-DL.git`

**Comment by sim0n00ps** [comment]
Change made, thanks

**Comment by Lebowski89** [comment]
Hi Sim,

will you add Docker compose documentation?

I've got it working fine on UnRaid using Docker Compose with the following:

of-dl:
    image: ghcr.io/sim0n00ps/of-dl:latest
    container_name: of-dl
    network_mode: <network>
    environment:
        - TZ=<timezone>
        - PUID=99
        - PGID=100
        - UMASK=022
    ports: 
        - <port>:<port>/tcp
    volumes:
        - /path/to/data:/data:rw
        - /path/to/config:/config:rw
    restart: unless-stopped

Don't know if I needed any of the extra environmental values, etc. But it's all working good.

**Comment by whimsical-c4lic0** [comment]
Docker compose is unnecessary since no other services are required. It would be better to use docker run directly, or on unraid, to create a container using the UI.

**Comment by Lebowski89** [comment]
Some people prefer compose. You thinking one or another is better is simply your opinion for your situation. I personally only run docker compose stacks on UnRaid. Don't have a single docker container from the UnRaid app store. Allows me to easily deploy entire stacks on other servers. Either way, documentation for these apps usually include both docker and docker compose, and it's not dependent on whether another service relies on it or not.

**Comment by whimsical-c4lic0** [comment]
I'm sorry if I came across as confrontational. That was not my intention. You can definitely use whichever works best for you. I only meant that since OF-DL is not dependent on other containers, compose doesn't add value.

My biggest concern with documenting a docker compose setup, is dealing with additional user messages/issues. Most of the docker users posting in discord in the past month or so have been been non-technical users that are looking for a way to run OF-DL on macOS or Linux. I'd prefer to avoid an additional pain point (whitespace dependent YAML formatting) to non-technical users when it wouldn't add a benefit over the existing config. When so many issues are already related to building valid JSON auth/config files, adding YAML seems unwise.

Something that would be useful to unraid users specifically would be an unraid service (XML) file that could be installed from the Community Apps tab. I haven't created one yet because I don't consider the OF-DL logging or config documentation to be comprehensive enough yet to recommend running OF-DL automated. For instance, `ShowScrapeSize` should never be used and `DownloadPostsIncrementally` should always be used in an automated setup. An actual log file with logging levels would be useful for diagnosing errors in a non-interactive setup.

Although it's unrelated to the current discussion, I think the best solution going forward would be to create a GUI that most users would use. A lot of the values in `config.json` would be moved the UI. Docker users and technical users could then use OF-DL as a CLI application and control behavior with CLI arguments. I'm in the very early stages of working on a GUI, but it's slow going since I'm only working on it when I feel like it and haven't done desktop .NET development in years.
