### ISSUE TITLE
says 0 paid posts when i have paid for content

### ISSUE THREAD

**Issue by natedog78456** [sim0n00ps/OF-DL#286]
I paid for the content through messages and I have all of the boxes checked that say paid content but it still says 0 paid posts.

**Comment by deadbeatdandylyon** [comment]
Check under Posts > Free > and Videos i don't know why but the same thing happens with me. If I buy a PPV it will show up in the paid folder, but If I tip on something and then the creator sends the video it will show up in the free videos under posts

**Comment by melithine** [comment]
Items will only show up in the `Paid` folders if it was tipped directly on a PPV post that you unlocked, or tipped directly on a PPV message that you unlocked. If the model sent it to you after you tipped, it will not be considered a `Paid` post, because OF-DL has no way of knowing about that.

**Comment by rakuko1** [comment]
additionally, there are two types of paid content: paid posts which are locked posts on the creator's main wall, and paid messages which are locked messages in the creator's messages page.

so yeah if you paid in messages, you will not see any paid posts, but you will see paid messages (assuming you have it marked for downloads in your config.json).
