### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by FuchsFunny** [sim0n00ps/OF-DL#287]
There was no path in the original auth template code and I added it myself. I'm getting error  right now. Can you explain why?
)
  n : solved

**Comment by melithine** [comment]
At a guess, you probably have an error in your JSON syntax. If you open the file in something like VSCode, the syntax highlighting would probably show you where the error is. Outside of that, you'd need to post a censored version of the file (like take out several characters from the middle of the `X_BC` value and the middle of the `sess=` portion of the `COOKIE` value), but leave all the formatting and such intact.

**Comment by FuchsFunny** [comment]
still same

**Comment by melithine** [comment]
If you're still having issues, try using the browser extension. The current release will point you to it.
