### ISSUE TITLE
I have filled everything out but OF downloader shows red font then closes soon as I open

### ISSUE THREAD

**Issue by letixxa** [sim0n00ps/OF-DL#29]
I have filled out the auth jason

**Comment by sim0n00ps** [comment]
Must be something wrong with what you have entered into the auth.json file, make sure the paths to the exes don't contain any \ and if they do then replace them with /. Also make sure the last character of each path is not a /.

**Comment by deadbeatdandylyon** [comment]
also the first mistake i made was when i copied the path there was double quotations so make sure each path name only has 1 beginning and end quotation mark

**Comment by letixxa** [comment]
> also the first mistake i made was when i copied the path there was double quotations so make sure each path name only has 1 beginning and end quotation mark

I removed the quotations and fixed the / issue and still the same thing. I ended up uninstalling the app altogether. I couldnt run it. Is there another way? This is way too advanced for me

**Comment by sim0n00ps** [comment]
Well what could you see for a start, you can obviously see Welcome to OF-DL at the start, do you see any green text to say any of the exe files were found?

**Comment by letixxa** [comment]
> Well what could you see for a start, you can obviously see Welcome to OF-DL at the start, do you see any green text to say any of the exe files were found?

I saw the red text saying welcome to OF and then suddenly the program shut itself off. Happened every time

**Comment by sim0n00ps** [comment]
> > Well what could you see for a start, you can obviously see Welcome to OF-DL at the start, do you see any green text to say any of the exe files were found?
> 
> I saw the red text saying welcome to OF and then suddenly the program shut itself off. Happened every time

What I would recommend then is re-download the latest release and unzip it. In the auth.json don't mess with any of the commas etc just put your values within the "" and make sure the paths are how I mentioned further up

**Comment by sim0n00ps** [comment]
This is going to sound obvious but have you restarted your computer and tried again. After installing the .NET runtime it might not be able to be used until you restart hence why it's just closing straight away. In regards to the cookie the auth_id and sess is the only thing needed in the cookie.

**Comment by BluesFanUK** [comment]
> This is going to sound obvious but have you restarted your computer and tried again. After installing the .NET runtime it might not be able to be used until you restart hence why it's just closing straight away. In regards to the cookie the auth_id and sess is the only thing needed in the cookie.

Damn you're quick! Thought i'd save my embarassment here by deleting the post. It was actually something quite straightforward... the "\" in my path needed to be the other way around like "/", now it opens! :)

**Comment by BluesFanUK** [comment]
... and it worked. What an absolute legend. I still unsubbed from the users site though, anyone who has DRM enabled should be named and shamed.

**Comment by sim0n00ps** [comment]
Glad you fixed it

**Comment by moneymansui** [comment]
Im having the same issue, i can see the red letter and the green ones saying successful but the program wont stay open

**Comment by Flacco1834** [comment]
Hey sim0n00ps, its been 3 days now and i cannot get OF DL.exe to open without closing. WHen i add the pathway of mp4decrypt.exe it crashes everytime. I deactivated my kaspersky that didnt nothing, and i checked all the characters and it still doesnt work. 
![Screenshot 2023-06-21 175426](https://github.com/sim0n00ps/OF-DL/assets/137343886/f38ec00d-b79f-4b1a-ba5c-826f83507dbf)

**Comment by Flacco1834** [comment]
> Hey sim0n00ps, its been 3 days now and i cannot get OF DL.exe to open without closing. WHen i add the pathway of mp4decrypt.exe it crashes everytime. I deactivated my kaspersky that didnt nothing, and i checked all the characters and it still doesnt work.

Hey sim0n00ps, its been 3 days now and i cannot get OF DL.exe to open without closing. WHen i add the pathway of mp4decrypt.exe it crashes everytime. I deactivated my kaspersky that didnt nothing, and i checked all the characters and it still doesnt work.
![Screenshot 2023-06-21 175426](https://github.com/sim0n00ps/OF-DL/assets/137343886/1df6743b-75ff-42e8-86e9-9fe1cbab249d)

**Comment by sim0n00ps** [comment]
> Hey sim0n00ps, its been 3 days now and i cannot get OF DL.exe to open without closing. WHen i add the pathway of mp4decrypt.exe it crashes everytime. I deactivated my kaspersky that didnt nothing, and i checked all the characters and it still doesnt work. 
> ![Screenshot 2023-06-21 175426](https://github.com/sim0n00ps/OF-DL/assets/137343886/f38ec00d-b79f-4b1a-ba5c-826f83507dbf)
> 

Try moving the exe files into 1 folder, I have mine called "DRMEXES" so my paths are "E:/OnlyFans/DRMEXES/yt-dlp.exe"

**Comment by Flacco1834** [comment]
Is it ok for me to get the user id and cookie from a video that is DRM protected. What i do is press f12 then go to purchases and get the info from the link in red text which is the drm video.

**Comment by Flacco1834** [comment]
![Screenshot 2023-06-21 175426](https://github.com/sim0n00ps/OF-DL/assets/137343886/35cb78b0-6eca-4b92-a909-29586ef7e81c)
Does this look correct? Cause it still crashes it says all 3 is loaded successfully but still crashes

**Comment by sim0n00ps** [comment]
Just deleted that as it has all your information in, to me it looked correct, what version are you running, make sure you're on this one https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.12

**Comment by deadbeatdandylyon** [comment]
I had a similar issue, downloaded the latest version, and literally copied and pasted the information from the old version to the new version as far as the config file goes, which i've been doing since day one, and it wouldn't work, I even rebooted the computer didn't work, what helped is logging out of OF and then logged back in and then recopied the sess cookie and all is good again. maybe this might help

**Comment by Flacco1834** [comment]
yes i'm running the current OF DL.exe. And i disabled firewall and anti virus. and I cant make out whats wrong. I have 2 computers 1 windows 11 (the one i'm currently using) and the other windows 10. And it doesnt work on either.

**Comment by sim0n00ps** [comment]
`{
    "USER_ID": "YOUR USER_ID HERE",
    "USER_AGENT": "YOUR USER_AGENT HERE",
    "X_BC": "YOUR X_BC HERE",
    "COOKIE": "auth_id=YOUR USER_ID HERE; sess=YOUR SESS HERE;",
    "YTDLP_PATH": "YOUR YT-DLP PATH HERE",
    "FFMPEG_PATH": "YOUR FFMPEG PATH HERE",
    "MP4DECRYPT_PATH": "YOUR MP4ECRYPT PATH HERE",
    "DownloadAvatarHeaderPhoto": "true",
    "DownloadPaidPosts": "true",
    "DownloadPosts": "true",
    "DownloadArchived": "true",
    "DownloadStories": "true",
    "DownloadHighlights": "true",
    "DownloadMessages": "true",
    "DownloadPaidMessages": "true",
    "DownloadImages": "true",
    "DownloadVideos": "true",
    "DownloadAudios": "true",
    "IncludeExpiredSubscriptions": "false"
}`

**Comment by Flacco1834** [comment]
THANK FUCCCCCKING GOD......lol  i FINALLY Fixed it ....LOL and it was the stupiest issue known to man..lol I had the folder with the OF DL.exe in it. On a separate hard drive of the other .exe files. I put the folder on the same hard drive with the others and now it works. MY LIFE IS COMPLETE................LOL Thanks for the help.

**Comment by sim0n00ps** [comment]
> THANK FUCCCCCKING GOD......lol  i FINALLY Fixed it ....LOL and it was the stupiest issue known to man..lol I had the folder with the OF DL.exe in it. On a separate hard drive of the other .exe files. I put the folder on the same hard drive with the others and now it works. MY LIFE IS COMPLETE................LOL Thanks for the help. 

Glad you fixed it lol, we all make silly mistakes

**Comment by Flacco1834** [comment]
I have a question. Does this software download videos i bought that r behind DRM?? IF so, how do i do that. So far its only downloading the drm free videos which i already have a method to download those.

**Comment by sim0n00ps** [comment]
> I have a question. Does this software download videos i bought that r behind DRM?? IF so, how do i do that. So far its only downloading the drm free videos which i already have a method to download those. 
> 

It should, check your auth.json to see if you have the flag for Paid Posts or Paid Messages set to false.

**Comment by KwlAid** [comment]
Hey there, sim0n00ps, I really appreciate the work and support you've put into this project, first and foremost!

I'm having a similar issue to the OP of this chain. On startup, I get an error stating that my paths are not setup in the proper syntax. However, after meticulously looking them over, as well as re-copying (and formatting) them just to be safe, I cannot deduce my error:

![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/ec792017-3a6b-4b2a-8d3d-c015b76a0993)

**Comment by sim0n00ps** [comment]
> Hey there, sim0n00ps, I really appreciate the work and support you've put into this project, first and foremost!
> 
> I'm having a similar issue to the OP of this chain. On startup, I get an error stating that my paths are not setup in the proper syntax. However, after meticulously looking them over, as well as re-copying (and formatting) them just to be safe, I cannot deduce my error:
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/ec792017-3a6b-4b2a-8d3d-c015b76a0993)
> 

Are those file paths valid?

**Comment by KwlAid** [comment]
> > Hey there, sim0n00ps, I really appreciate the work and support you've put into this project, first and foremost!
> > I'm having a similar issue to the OP of this chain. On startup, I get an error stating that my paths are not setup in the proper syntax. However, after meticulously looking them over, as well as re-copying (and formatting) them just to be safe, I cannot deduce my error:
> > ![image](https://user-images.githubusercontent.com/96799131/252603538-ec792017-3a6b-4b2a-8d3d-c015b76a0993.png)
> 
> Are those file paths valid?

Yes, those paths are directly from clicking "Copy Path" in file explorer for each of the .exe files, and changing the slashes to the proper ones. Do you think I need to put them in a different directory?

![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/8fdd29c9-b48e-4cce-b852-abb989d18b95)

**Comment by sim0n00ps** [comment]
> > > Hey there, sim0n00ps, I really appreciate the work and support you've put into this project, first and foremost!
> > > I'm having a similar issue to the OP of this chain. On startup, I get an error stating that my paths are not setup in the proper syntax. However, after meticulously looking them over, as well as re-copying (and formatting) them just to be safe, I cannot deduce my error:
> > > ![image](https://user-images.githubusercontent.com/96799131/252603538-ec792017-3a6b-4b2a-8d3d-c015b76a0993.png)
> > 
> > Are those file paths valid?
> 
> Yes, those paths are directly from clicking "Copy Path" in file explorer for each of the .exe files, and changing the slashes to the proper ones. Do you think I need to put them in a different directory?
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/8fdd29c9-b48e-4cce-b852-abb989d18b95)
> 

Yes, maybe place them somewhere in the C drive. The program might not be able to access the drive they are currently on.

**Comment by KwlAid** [comment]
I have moved all the exe files to the C: drive, and attempted to run the OF-DL application both in it's original directory on the A: drive, and again after moving it to the C: drive as well. In both instances, I get the same error

![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/fccb44e0-6efa-4243-a6ca-39fcedafb01e)

![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/abbe86e7-14a9-475c-b5b0-886bdf890f8e)

**Comment by sim0n00ps** [comment]
> I have moved all the exe files to the C: drive, and attempted to run the OF-DL application both in it's original directory on the A: drive, and again after moving it to the C: drive as well. In both instances, I get the same error
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/fccb44e0-6efa-4243-a6ca-39fcedafb01e)
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/abbe86e7-14a9-475c-b5b0-886bdf890f8e)
> 
> 

Maybe try in the same folder where OF DL.exe is, put the folder in that.

**Comment by KwlAid** [comment]
Still a no-go for me...

![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/6d1e845a-a10b-4623-8190-8dc7ad891a34)

**Comment by sim0n00ps** [comment]
> Still a no-go for me...
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/96799131/6d1e845a-a10b-4623-8190-8dc7ad891a34)
> 

I'll change the file path validation in the next release, I have a feeling it's down to the username having spaces in it

**Comment by Advent616** [comment]
Hi,

This is the message I get before the crash.

![Error-Onlyfans-Downloader](https://github.com/sim0n00ps/OF-DL/assets/141397548/32b6a126-985a-4f8a-96a1-e4504089262b)

Here are my paths:
![Paths](https://github.com/sim0n00ps/OF-DL/assets/141397548/2104e47d-c1e0-4f7e-9b7a-159cf4b76f53)

What am I doing wrong.

Btw, I'm running Windows 7. Not 10 or even 11.

Thanks

**Comment by sim0n00ps** [comment]
> Hi,
> 
> This is the message I get before the crash.
> 
> ![Error-Onlyfans-Downloader](https://github.com/sim0n00ps/OF-DL/assets/141397548/32b6a126-985a-4f8a-96a1-e4504089262b)
> 
> Here are my paths:
> ![Paths](https://github.com/sim0n00ps/OF-DL/assets/141397548/2104e47d-c1e0-4f7e-9b7a-159cf4b76f53)
> 
> What am I doing wrong.
> 
> Btw, I'm running Windows 7. Not 10 or even 11.
> 
> Thanks
> 

Sadly this doesn't work on Windows 7, the package I used for all of the UI would have to be removed in order to get it to work on Windows 7/8. I'd recommend you upgrade to Windows 10/11 though just as a general thought.
