### ISSUE TITLE
Download Progress Bar Not Moving / Not Progressing & Message DL Error

### ISSUE THREAD

**Issue by randomfapper** [sim0n00ps/OF-DL#293]
In general I don't run into too many issues, but there are 2 accounts that are giving me trouble.

First one, the scrape starts and when it gets to the "Downloading Posts" part, the progress bar doesn't move, or it goes to 80% and then stops.  Files were downloaded from posts but it won't progress forward to messages, paid messages, etc.

Second, posts download fine but when it gets to Messages, the app spits out an error.

Screenshots attached.

These errors only happen for only 2 specific accounts.  I haven't encountered it on others.
![error](https://github.com/sim0n00ps/OF-DL/assets/138882855/0a7c9d70-8c87-4a4a-a291-7e43ef0a2e22)
![error2](https://github.com/sim0n00ps/OF-DL/assets/138882855/acfee03a-170b-454b-bcac-8350a9a77fb1)

**Comment by whimsical-c4lic0** [comment]
What version of OF-DL are you using? A recent release has fixed a bug where DRM videos could cause the program to stall.

**Comment by greyhat94** [comment]
> What version of OF-DL are you using? A recent release has fixed a bug where DRM videos could cause the program to stall.

Hi! In the last release, it's not necessary to specify the FFmpeg directory anymore?

**Comment by whimsical-c4lic0** [comment]
> > What version of OF-DL are you using? A recent release has fixed a bug where DRM videos could cause the program to stall.
> 
> Hi! In the last release, it's not necessary to specify the FFmpeg directory anymore?

It's unrelated to this issue, but if the FFmpeg can be auto-detected (e.g. `ffmpeg.exe` is in the same directory as `OF DL.exe`), then yes, the FFmpeg directory can be omitted from the config.

**Comment by whimsical-c4lic0** [comment]
> > What version of OF-DL are you using? A recent release has fixed a bug where DRM videos could cause the program to stall.
> 
> I'm using the current version, 1.7.52

I personally can't offer any suggestions then other than deleting the folders of the problematic users and trying again.

**Comment by randomfapper** [comment]
> > > What version of OF-DL are you using? A recent release has fixed a bug where DRM videos could cause the program to stall.
> > 
> > 
> > I'm using the current version, 1.7.52
> 
> I personally can't offer any suggestions then other than deleting the folders of the problematic users and trying again.

So that actually worked for the model with the status bar not moving error.  Thank you!

Kind of annoyed at myself that I didn't try that first.

Going to try it next with the model with the Message error.

**Comment by melithine** [comment]
Is this still happening on the latest release?
