### ISSUE TITLE
Immediately Get Auto Logged Out of OF

### ISSUE THREAD

**Issue by tj961120** [sim0n00ps/OF-DL#297]
Not sure if anyone else is having this issue, but this just started happening today.

I would log onto OF to get my sess, copy it over to auth.json, then launch the exe, but immediately after it launches, I would get kicked out of OF/sess info would change, so the sess I had just copied 5 seconds ago wouldn't work.

**Comment by melithine** [comment]
Your user agent probably changed due to a browser update.

**Comment by sim0n00ps** [comment]
Re-copy your user-agent as well as that can change, guarantee you that is your problem

**Comment by tj961120** [comment]
It worked, but the X-BC also changed. Thank you both so much!
