### ISSUE TITLE
Crash after "logged successfully"

### ISSUE THREAD

**Issue by sirius499** [sim0n00ps/OF-DL#298]
I did everything correctly but it closes after "logged succesfully message"

  I used windows 7 64 bits 

![Sans trtgggitre](https://github.com/sim0n00ps/OF-DL/assets/162071219/2766120b-b562-4573-b2b5-dcb13a62ed76)

**Comment by sim0n00ps** [comment]
>  I did everything correctly but it closes after "logged succesfully message"
> 
>   I used windows 7 64 bits 
> 
> ![Sans trtgggitre](https://github.com/sim0n00ps/OF-DL/assets/162071219/2766120b-b562-4573-b2b5-dcb13a62ed76)
> 
> 

One of the components used doesn't support Windows 7/8, you'll need to be on Windows 10/11 for it to work sadly
