### ISSUE TITLE
Unable to run the program; crashes and exits immediately after opening

### ISSUE THREAD

**Issue by matcha6666** [sim0n00ps/OF-DL#299]
![屏幕截图 2024-03-05 022840](https://github.com/sim0n00ps/OF-DL/assets/143941342/5f54e122-d7ca-4d38-a8a4-948146da01d1)
It crashes immediately after opening and running; the error cannot be seen;

**Comment by matcha6666** [comment]
![Uploading 屏幕截图 2024-03-05 023647.png…]()

**Comment by lucacham** [comment]
I had this problem the first time I used it, you may need to install this
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.14-windows-x86-installer?cid=getdotnetcore

**Comment by matcha6666** [comment]
> 我第一次使用它时遇到了这个问题，您可能需要安装此 https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.14-windows-x86-installer?cid=getdotnetcore

Okay, after installing it, I tried to open the software and run it, but it still crashed.

**Comment by sim0n00ps** [comment]
> ![屏幕截图 2024-03-05 022840](https://github.com/sim0n00ps/OF-DL/assets/143941342/5f54e122-d7ca-4d38-a8a4-948146da01d1)
> It crashes immediately after opening and running; the error cannot be seen;

Need to add a comma at the end of the COOKIE line, should work after that hopefully

**Comment by matcha6666** [comment]
> > ![屏幕截图 2024-03-05 022840](https://private-user-images.githubusercontent.com/143941342/309863556-5f54e122-d7ca-4d38-a8a4-948146da01d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzQ3NjAsIm5iZiI6MTcwOTczNDQ2MCwicGF0aCI6Ii8xNDM5NDEzNDIvMzA5ODYzNTU2LTVmNTRlMTIyLWQ3Y2EtNGQzOC1hOGE0LTk0ODE0NmRhMDFkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxNDE0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTQyNjQyYjdlYjVhZmI0ZjZjNjEyOWVmMWZmOTA0Yjg5OWI4MGIwYWEwZDE2YjUzOGM4ZWI0NGI1MzY1OTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PIo2x6rx9UVmePLKePmS4Cnie0MSnQtRgkyC2LEWjz8)打开运行后立即崩溃;看不到错误;
> 
> 需要在COOKIE行的末尾添加一个逗号，希望在那之后可以工作。还要检查其他行，并确保它们在末尾有逗号。

It ran successfully, very good.

**Comment by diestor** [comment]
I tried another solution and it worked finely too. In the auth file I did not put the FFMPEG line, I put this directory in the config file, I believe it's the line before the last one.
