### ISSUE TITLE
is it possible to change the download order

### ISSUE THREAD

**Issue by czuo0303** [sim0n00ps/OF-DL#3]
I only want to download paid messages, is it possible to skip all the posts?

**Comment by sim0n00ps** [comment]
Not currently, everything is downloaded no matter what. I will add a feature to let you just download posts, paid messages etc soon.

**Comment by czuo0303** [comment]
> Not currently, everything is downloaded no matter what. I will add a feature to let you just download posts, paid messages etc soon.

Thank you for the kind reply. Looking forward to it.

**Comment by sim0n00ps** [comment]
I have now added this as a feature in the latest release. You can change the values in the auth.json file to select what media you do and don't want to download.
