### ISSUE TITLE
getting log off from OF

### ISSUE THREAD

**Issue by descxz** [sim0n00ps/OF-DL#30]
was prompted to relogin into OF, copied the new cookies into the auth file but auth fail when running the program.

Notice that I get log off OF after the fail attempt with the program

**Comment by sim0n00ps** [comment]
Re-copy your user-agent along with the new sess value you get when you log in, if you think everything is correct and it keeps logging you out then it's usually down to the user-agent changing

**Comment by descxz** [comment]
thank you didnt notice there was changes in that!
