### ISSUE TITLE
Error downloading videos in messages (403)

### ISSUE THREAD

**Issue by j68asdu1** [sim0n00ps/OF-DL#301]
I'm getting an issue downloading videos sent in DM. I'm getting a "Exception caught: Response status code does not indicate success: 403 (forbidden)." This doesn't seem to be an issue for wall posts. Do I need to scrape my device_client_id_blob/device_private_key?

**Comment by sim0n00ps** [comment]
Are you using a VPN?

**Comment by j68asdu1** [comment]
Yes I am, is that likely causing the issue? I turned it off and it looks like the progress bar is working now, I will update if it fails again. Sorry for being an idiot

**Comment by j68asdu1** [comment]
It all downloaded once I was off VPN, 0 problems! Thank you!!
