### ISSUE TITLE
 [SOLVE]  Sess keep changing when I try to open the program

### ISSUE THREAD

**Issue by BuyahBonko** [sim0n00ps/OF-DL#302]
Every time I try to open the OF DL.exe, I got forces log out on the Onlyfan website then sess keeps changing every time I get forced log out.
I last used this program  2-3 weeks ago and it works just fine then.

**Comment by sim0n00ps** [comment]
Your user-agent has probably changed due to a browser update, make sure you re-copy it from browser as well as sess
