### ISSUE TITLE
Path Issue

### ISSUE THREAD

**Issue by Webx123** [sim0n00ps/OF-DL#31]
In previous versions i have put the "ffmpeg,Yt-dlp, mp4decrypt exe files in the OF-DL folder with the EXE and Set my Auth.json folder as such
```
    "YTDLP_PATH": "yt-dlp.exe",
    "FFMPEG_PATH": "ffmpeg.exe",
    "MP4DECRYPT_PATH": "mp4decrypt.exe",
```
But this latest version when i do this and run the EXE i get the error
```
Specified path yt-dlp.exe does not match the required format, please remove any \ from the path and replace them with /
and make sure the path does not have a / at the end, press any key to exit
```
any idea whats causing this? and how to fix it...

**Comment by sim0n00ps** [comment]
Probably because the regex path I used to validate the paths against were something like what I have setup `"E:/OnlyFans/DRMEXES/mp4decrypt.exe"`, I can probably easily change it so it can allow something like what you have but for now you'll have to have the full path

**Comment by Webx123** [comment]
okay so i changed it to the full path and made and moved them to a "exes" folder
```
    "YTDLP_PATH": "C:\OFDL\exes\yt-dlp.exe",
    "FFMPEG_PATH": "C:\OFDL\exes\ffmpeg.exe",
    "MP4DECRYPT_PATH": "C:\OFDL\exes\mp4decrypt.exe",
   ```
And now the exe auto closes on open any idea whats wrong with that format?

**Comment by sim0n00ps** [comment]
Because you have \, you need to use /

**Comment by Webx123** [comment]
Sweet thanks man!
