### ISSUE TITLE
Does not download the full video file

### ISSUE THREAD

**Issue by kolo0909** [sim0n00ps/OF-DL#310]
Why is it downloading about one minute of the movie instead of the entire, say 16-minute movie? This is happening from today. Previously everything worked fine. Maybe someone will suggest a solution

**Comment by fidelio959** [comment]
Hello I got the same problem from same days. Never happened before. Any ideas?

**Comment by melithine** [comment]
Is this still happening on the current release? If so, paste your config.json.
