### ISSUE TITLE
Can't login: I get logged out of OF and "sess" value immediately changes everytime I run OF-DL, resulting in auth failed error.

### ISSUE THREAD

**Issue by gigacastelo** [sim0n00ps/OF-DL#311]
As soon as I run OF-DL I immediatelly get logged out of OF, and then I get the "auth failed" error because the sess expires.

Basically when I run OF-DL something triggers Onlyfans and they log me off.

I can't manage to make it work. It was working fine a week ago so I'm not sure if something changed or if I'm doing something wrong.

I'm using the OF Auth Helper extention to get the necessary values.

I Tried to log in and get auth values on multiple browsers. None of them worked.

**Comment by thomassandstrom** [comment]
This happens to me now as well, never happened before.

**Comment by mediaburnwayne** [comment]
have you checked your user agent. That usually happens to me when my browser updates and my user agent changes. Then I have to update config with new agent

**Comment by thomassandstrom** [comment]
> have you checked your user agent. That usually happens to me when my browser updates and my user agent changes. Then I have to update config with new agent

I check that one as well every time there is trouble with the config, so User agent is updated.

I have tried values from both Firefox and Chrome without success.
Everytime I start OF-DL you get logged out from OnlyFans and the cookies are no longer valid.

But at the same time, I can be logged in on both Firefox and Chrome without getting logged out.

**Comment by Darkpte** [comment]
I had the same issue, just updated User agent in auth.json and everything worked fine

**Comment by thomassandstrom** [comment]
User agent was correct.

But today after changing cookie/sess, it work like it should and I wasn't logged out from OF.

**Comment by Mareckyyy** [comment]
I've created second profile in chrome, logged into OF, copied auth values and switched back to my main profile. I,m logged into of-dl since november 2023 using these data

**Comment by Johntm33** [comment]
Anyone find a fix for this??? Changing all the values does not seem to work

**Comment by melithine** [comment]
The current version has specific pointers how to address the. Tldr; use the browser extension, or particularly check your USER_AGENT because it is probably slightly wrong.
