### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by wktjr93** [sim0n00ps/OF-DL#312]
i add 
what is wrong i really dont understand
i change / this and i copied some ppl write idk what is wrong

![of-dl-path-error-v0-mzqcc8r57bqc1](https://github.com/sim0n00ps/OF-DL/assets/37283817/16e0206d-5ab6-4db7-8a85-5f49c8f734a8)

**Comment by sim0n00ps** [comment]
You have a missing comma at the end of the COOKIE line.
