### ISSUE TITLE
OF DL Crashes Immediately

### ISSUE THREAD

**Issue by nu2689** [sim0n00ps/OF-DL#315]
Every time I try to open the OF DL program it crashes. I'm pretty sure I did my auth json info right

HERES MY INFO
![Screenshot_3](https://github.com/sim0n00ps/OF-DL/assets/165172467/be270764-ad9b-4b4a-85fc-e40702f2e8e9)

**Comment by sim0n00ps** [comment]
You need to put the ffmpeg path before the }, currently it is outside of the JSON object which is why you get the error. After you've done that put a , at the end of each line and that should fix it

**Comment by LittleStuart92** [comment]
Update user_agent, it was changed.

**Comment by melithine** [comment]
If you're not familiar with JSON, I'd recommend using the browser extension to create the `auth.json` file. Much simpler and easier, even for me, and I am proficient with JSON.

**Comment by nu2689** [comment]
> Update user_agent, it was changed.

What was it changed to?

**Comment by LittleStuart92** [comment]
> > Update user_agent, it was changed.
> 
> What was it changed to?

Check always 3 data marked on yellow. USER_AGENT, X_BC and COOKIE
![2024-03-28 01_50_48-auth json — Notatnik](https://github.com/sim0n00ps/OF-DL/assets/165220452/ea21d259-50f9-4052-b2cc-f03c9e685b17)

The best wa is always use the latest version. FFMPEG_PATH was moved to config file.

**Comment by nu2689** [comment]
Its fixed now. Thanks guys!
