### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden)

### ISSUE THREAD

**Issue by shapman88** [sim0n00ps/OF-DL#317]
I began seeing the below error message this morning when trying to download single posts or scrape an entire account. I confirmed that my auth information is correct and that I have not been logged out, but this seems to be happening randomly in between items that get downloaded. I am using version 1.7.52.

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp, Auth auth)
Exception caught: Response status code does not indicate success: 403 (Forbidden).

![image](https://github.com/sim0n00ps/OF-DL/assets/91422602/bf562d1f-e744-42e6-9576-0d8530ec90cc)

**Comment by banjobbw** [comment]
Im also getting a similar error

`Exception caught: Response status code does not indicate success: 500 (Internal Server Error).

                                                                                              StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetMedia(MediaType mediatype, String endpoint, String username, String folder, Auth auth, List`1 paid_post_ids)`

**Comment by MussInBootss** [comment]
I'm getting the same error: An error occurred: Response status code does not indicate success: 403 (Forbidden)
I'm using the latest version and even tried with version OF.DL.V1.7.44 which used to work before. For some reason it'll download some posts but then reaches a point where it keeps repeating this error several dozen times. 
I've got all the DRM files and it worked fine 6 weeks ago but I haven't tried it since.

**Comment by ducmic** [comment]
I've got the same in V1.7.56, but what's worth noting is that it happens **randomly**.   
  
The same URL for instance, for a single-URL download, will give this 403 error, then upon retrying it will work without trouble.
Runing a full scrape on a single account will yield, in my case, roughly 30% of the content, the rest being subjected to 403 error. Then re-running the same full scrape will yield an additionnal roughly 15% of the content.
Not sure running the full scrape repeatedly will lead to a ban, though.

**Comment by dataguy73301** [comment]
I am also getting the same as the others in this thread.  I am using version 1.7.58

**Comment by melithine** [comment]
> I am also getting the same as the others in this thread. I am using version 1.7.58

Are you using your own Wildvine keys or CDRM Project?

**Comment by ricechub** [comment]
> > I am also getting the same as the others in this thread. I am using version 1.7.58
> 
> Are you using your own Wildvine keys or CDRM Project?

I am also receiving the same error message: StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp, Auth auth)
2024-06-03 10:15:24.680 -07:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).

I tried using both CDRM Project and my own keys.

**Comment by ducmic** [comment]
Well, upon retrying later, my random issue disapeared. Since I'm using CDRM, I assume it was a temporary problem on that side.

**Comment by melithine** [comment]
> > > I am also getting the same as the others in this thread. I am using version 1.7.58
> > 
> > 
> > Are you using your own Wildvine keys or CDRM Project?
> 
> I am also receiving the same error message: StackTrace: at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp, Auth auth) 2024-06-03 10:15:24.680 -07:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).
> 
> I tried using both CDRM Project and my own keys.

Try with/without a VPN. If you have your own keys, I would always use them to remove CDRM as a potential source of problems.

**Comment by cars11** [comment]
how do you get your own keys/wildvine/whatever?
Don't know anything about DRM or how it works, just that the downloader is throwing the same error for me

**Comment by ricechub** [comment]
> > > > I am also getting the same as the others in this thread. I am using version 1.7.58
> > > 
> > > 
> > > Are you using your own Wildvine keys or CDRM Project?
> > 
> > 
> > I am also receiving the same error message: StackTrace: at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp, Auth auth) 2024-06-03 10:15:24.680 -07:00 [ERR] Exception caught: Response status code does not indicate success: 403 (Forbidden).
> > I tried using both CDRM Project and my own keys.
> 
> Try with/without a VPN. If you have your own keys, I would always use them to remove CDRM as a potential source of problems.

Also tried again. This time without VPN and it worked.

**Comment by cars11** [comment]
> > how do you get your own keys/wildvine/whatever? Don't know anything about DRM or how it works, just that the downloader is throwing the same error for me and it used to work fine on its own
> 
> https://of-dl.gitbook.io/of-dl/requirements

thanks! but that doesn't seem to be the issue. I can download the streams manually

**Comment by mingweiarthurli** [comment]
> > > how do you get your own keys/wildvine/whatever? Don't know anything about DRM or how it works, just that the downloader is throwing the same error for me and it used to work fine on its own
> > 
> > 
> > https://of-dl.gitbook.io/of-dl/requirements
> 
> thanks! but that doesn't seem to be the issue. I can download the streams manually with FetchV, but the downloader still immediately throws that error

Did you use "OF-DL Auth Helper" (that browser extension) to generate the `auth.json`? I encountered same issue, and both turn on/ turn off VPN doesn't work for me. However, I realized the `auth.json` generated by the extension includes many unnecessary fields in the `COOKIE` value which led to a failed connection.

Try to delete those unnecessary `COOKIE` fileds in your `auth.json` manually, and make the `COOKIE` pair looks like `"COOKIE": "sess=[your sess id]; auth_id=[your auth id];"`. This should fix the issue.

**Comment by melithine** [comment]
> > > > how do you get your own keys/wildvine/whatever? Don't know anything about DRM or how it works, just that the downloader is throwing the same error for me and it used to work fine on its own
> > > 
> > > 
> > > https://of-dl.gitbook.io/of-dl/requirements
> > 
> > 
> > thanks! but that doesn't seem to be the issue. I can download the streams manually with FetchV, but the downloader still immediately throws that error
> 
> Did you use "OF-DL Auth Helper" (that browser extension) to generate the `auth.json`? I encountered same issue, and both turn on/ turn off VPN doesn't work for me. However, I realized the `auth.json` generated by the extension includes many unnecessary fields in the `COOKIE` value which led to a failed connection.
> 
> Try to delete those unnecessary `COOKIE` fileds in your `auth.json` manually, and make the `COOKIE` pair looks like `"COOKIE": "sess=[your sess id]; auth_id=[your auth id];"`. This should fix the issue.

I've not seen that myself, so if it does help, it's an edge case.

**Comment by melithine** [comment]
Are you all on 1.7.59 now? It's the only release that has come out since a recent OF update that required a new release on our end.

**Comment by mingweiarthurli** [comment]
> Are you all on 1.7.59 now? It's the only release that has come out since a recent OF update that required a new release on our end.

Yes, I'm on 1.7.59 now and this issue is persisted from 1.7.57. I can also reproduce this issue and fix it again with my mentioned solution in my environment.

**Comment by melithine** [comment]
Mine looks like the following:
```json
{
  "USER_ID": "REDACTED",
  "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "X_BC": "REDACTED",
  "COOKIE": "csrf=YZe1QVva156e747ed1c791d9327931ed24cebbe8; __stripe_mid=58e47573-8d67-440d-8f41-40af27ca40822d0076; lang=en; auth_id=REDACTED; fp=1869e2a74cd6c595090f4dfbebe0e288c03492b6; sess=12ogjugrui95s73tc5evl7rubm; auth_uid_REDACTED=EN86KebL5oe2iwa5WxZHQrFgZ4ei0CDS; st=9d6d33fed82d7d3a91398053192eda9268cfc63d7f3d8ea9ffe4c37765e0cacc; __cf_bm=Dw.FJ35z4.ZifHwPRwA1tfOB_2_OyregVvMB7yMI_x4-1715904653-1.0.1.1-61XXcqLZ5RPuDAN9VfSIalVUQtz9mFUI6qbHakhT.HQVSil5rSVnnlOroMEJdOnr8veGnjUuHqJZS.xfzit.6w; _cfuvid=DzYb3ZdWvug1RduCy0BDlXCaUeBnvdz5chVSXFEg5SE-1715904654000-0.0.1.1-604800000; streams=dc1-room-7rFMwun8uXge6s1_; __stripe_sid=7db7c4a4-409d-441f-b533-c4afdd60f515b91644;"
}
```

**Comment by cars11** [comment]
> > > > how do you get your own keys/wildvine/whatever? Don't know anything about DRM or how it works, just that the downloader is throwing the same error for me and it used to work fine on its own
> > > 
> > > 
> > > https://of-dl.gitbook.io/of-dl/requirements
> > 
> > 
> > thanks! but that doesn't seem to be the issue. I can download the streams manually with FetchV, but the downloader still immediately throws that error
> 
> Did you use "OF-DL Auth Helper" (that browser extension) to generate the `auth.json`? I encountered same issue, and both turn on/ turn off VPN doesn't work for me. However, I realized the `auth.json` generated by the extension includes many unnecessary fields in the `COOKIE` value which led to a failed connection.
> 
> Try to delete those unnecessary `COOKIE` fileds in your `auth.json` manually, and make the `COOKIE` pair looks like `"COOKIE": "sess=[your sess id]; auth_id=[your auth id];"`. This should fix the issue.

no change, but getting a different error today.
                                                                                                                                                  StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path)
   
   and the ffmpeg could not save the file

**Comment by ElephanSizePenis** [comment]
I changed the cookie to only have "sess" info and it stopped giving this error. I was using the of cookie helper before.

**Comment by cars11** [comment]
seems to work now

**Comment by annazgit** [comment]
> > > > how do you get your own keys/wildvine/whatever? Don't know anything about DRM or how it works, just that the downloader is throwing the same error for me and it used to work fine on its own
> > > 
> > > 
> > > https://of-dl.gitbook.io/of-dl/requirements
> > 
> > 
> > thanks! but that doesn't seem to be the issue. I can download the streams manually with FetchV, but the downloader still immediately throws that error
> 
> Did you use "OF-DL Auth Helper" (that browser extension) to generate the `auth.json`? I encountered same issue, and both turn on/ turn off VPN doesn't work for me. However, I realized the `auth.json` generated by the extension includes many unnecessary fields in the `COOKIE` value which led to a failed connection.
> 
> Try to delete those unnecessary `COOKIE` fileds in your `auth.json` manually, and make the `COOKIE` pair looks like `"COOKIE": "sess=[your sess id]; auth_id=[your auth id];"`. This should fix the issue.

Tried this workaround, but I am still getting the same error. I have all the DRM files as well

**Comment by ElephanSizePenis** [comment]
Its back again, but this time with just auth failure. Both manually added values and browser extension.

**Comment by melithine** [comment]
The 403 Forbidden is now being tracked on #466.
