### ISSUE TITLE
the app/window closes itself right after opening

### ISSUE THREAD

**Issue by bike199999** [sim0n00ps/OF-DL#318]
I'm in windows 11
![image](https://github.com/sim0n00ps/OF-DL/assets/165507548/77b982ce-28d9-4105-acd7-0f1d30988ae5)
Am I doing something wrong?

**Comment by melithine** [comment]
You need a comma at the end of the `COOKIE` line, after the `"`.

**Comment by bike199999** [comment]
> You need a comma at the end of the `COOKIE` line, after the `"`.

OMG thank you! I added the last path line and forgot about it.

**Comment by melithine** [comment]
> > You need a comma at the end of the `COOKIE` line, after the `"`.
> 
> OMG thank you! I added the last path line and forgot about it.

That actually belongs in `config.json` now, not `auth.json`. It's just currently still supported there for backwards compatibility.

**Comment by bike199999** [comment]
> > > You need a comma at the end of the `COOKIE` line, after the `"`.
> > 
> > 
> > OMG thank you! I added the last path line and forgot about it.
> 
> That actually belongs in `config.json` now, not `auth.json`. It's just currently still supported there for backwards compatibility.

Got it. I was wondering why I didn't have the path line so I added it myself. It works now. Thank you!
