### ISSUE TITLE
the app/window closes immediately after opening 

### ISSUE THREAD

**Issue by somedude4321** [sim0n00ps/OF-DL#319]
I'm pretty sure I did as in Video Tutorial. 
Here are screenshot my auth.json edited file and I also managed pictured OF.DL app before it closed with some issue info (it's kinda out of my depth but it can be helpful to understand my problem).
![issue](https://github.com/sim0n00ps/OF-DL/assets/160610122/96220c7a-240a-4b20-a460-03a4ebefb178)
![issue_2](https://github.com/sim0n00ps/OF-DL/assets/160610122/97a30365-4d55-4884-8658-d4b88c9c557a)

**Comment by melithine** [comment]
What version of Windows are you on? That looks like Win 7 or Win 8, IIRC, you need Win 10/11.

**Comment by somedude4321** [comment]
Yeah I have Win 8,1. 
So there is no older ver. or something to run on this system?

**Comment by melithine** [comment]
Windows 8 went end of life back in January of 2023. It is very inadvisable to run an operating system that no longer receives updates of any kind, particularly no security updates.

**Comment by mainchart** [comment]
the exact same thing is happening to me but i have windows 10?
