### ISSUE TITLE
modify with correct path

### ISSUE THREAD

**Issue by mainchart** [sim0n00ps/OF-DL#321]
Hi i dont know what to put in my path

**Comment by mainchart** [comment]
the path that goes here
![Screenshot 2024-04-04 120814](https://github.com/sim0n00ps/OF-DL/assets/166007725/33d8c377-3dbf-4629-be1a-2d27a07bbc33)
is it correct? also now that i have put a path the app closes immediately after opening it

**Comment by Mareckyyy** [comment]
This is correct path:
"FFmpegPath": "D:/path/to/ffmpeg.exe"
