### ISSUE TITLE
the app/window closes itself right after opening

### ISSUE THREAD

**Issue by mainchart** [sim0n00ps/OF-DL#322]
im on windows 10
![Screenshot 2024-04-04 120742](https://github.com/sim0n00ps/OF-DL/assets/166007725/b27049ed-3aa0-499b-9d43-8d0ce6854169)
![Screenshot 2024-04-04 120814](https://github.com/sim0n00ps/OF-DL/assets/166007725/aa774d30-8e2e-4256-af69-bc0f9bdffbba)

**Comment by deadbeatdandylyon** [comment]
first off it seems like the path for your FFMpegPath is a bit not correct for example below is mine

`"FFmpegPath": "C:/Users/<username>/Downloads/OF.DL.V1.7.48/Scraper Programs/ffmpeg-6.0-essentials_build/bin/ffmpeg.exe",`

I also have the FFmpegPath located in the actual config.json file

As far as the information in your Auth.json File 

at the end of your "cookie" path you have an extra comma that shouldn't be there

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/f9e866db-4869-46e3-b735-50e9ef6d9b6c)

**Comment by mainchart** [comment]
how should i type the ffmpeg path in my auth.jason file?

**Comment by deadbeatdandylyon** [comment]
If you have the latest update of the OF.DL 

Then when you go into the Config.json file you will see an option for FFmegPath and thats where you would put the path name

you can see in the image below it already has `"FFmpegPath": ` already there then you need to paste the correct path

The steps for that is locate the actual file FFmpeg > hold down left shift and then right click on the ffmpeg file and then select copy as path and then go to the config file and paste it 

![Screenshot 2024-04-04 065908](https://github.com/sim0n00ps/OF-DL/assets/59564520/28dff7bf-f5dc-4a4d-9be9-dde488384cf6)
