### ISSUE TITLE
An error occurred: The decryption operation failed, see inner exception.

### ISSUE THREAD

**Issue by Snow-Okami** [sim0n00ps/OF-DL#326]
I am getting incomplete videos for one of the people I am subscribed to. I get the following errors:

```
An error occurred: The decryption operation failed, see inner exception.
An error occurred: The read operation failed, see inner exception.
```
The download continues however. Anyone know how to solve this?

**Comment by melithine** [comment]
Try the most recent version and with/without a VPN.
