### ISSUE TITLE
Does anybody know, how to delete one subscribed OF account from one's list, so it is not longer requested to be downloaded by this tool?

### ISSUE THREAD

**Issue by peddanet** [sim0n00ps/OF-DL#329]

**Comment by deadbeatdandylyon** [comment]
I just use the custom function and select all the creators I want to subscribe

**Comment by melithine** [comment]
If you block them, I believe it is now set up to ignore them when downloading all users. Or make a list on OF with the creators you want to scrape, and then scrape that list instead of all.
