### ISSUE TITLE
OF-DL got stuck on green text

### ISSUE THREAD

**Issue by Diana8711** [sim0n00ps/OF-DL#332]
![ofdl1](https://github.com/sim0n00ps/OF-DL/assets/160360276/e7304435-5b74-408c-8d05-12b0ec9f18a7)
I did everything correct but i cannot  move on, if i hit enter, immediately .exe is shut down and i see ''exception...'' kinda error in a milisecond.

Can anyone help ?

**Comment by melithine** [comment]
Launch a Powershell window and run it from there, you'll be able to see what the error is. It's probably authentication related, though, so double-check your `auth.json` information.
