### ISSUE TITLE
Auth failed, please check the values in auth.json are correct

### ISSUE THREAD

**Issue by MrKikiMoki** [sim0n00ps/OF-DL#336]
Auth failed, please check the values in auth.json are correct.

I successfully downloaded DRM videos a few days ago with no issues at all, now I get this message!

Any ideas?

**Comment by melithine** [comment]
Your browser probably updated and your User-Agent changed as a result.

**Comment by MrKikiMoki** [comment]
> Your browser probably updated and your User-Agent changed as a result.

This is exactly what happened 😍

Thaaaank you melithine, you are a life saver
