### ISSUE TITLE
Getting constant logouts when running script

### ISSUE THREAD

**Issue by mediaburnwayne** [sim0n00ps/OF-DL#34]
I know we had to reduce threads when running digital criminals to prevent logouts. I wonder if they are doing more throttling

**Comment by sim0n00ps** [comment]
Is this happening when stuff is downloading?

**Comment by mediaburnwayne** [comment]
Yes, but I believe I have resolved the issue. It was VPN related.

**Comment by sim0n00ps** [comment]
Alright usually any repeated log outs are down to user-agent changes so that's always something to look out for in future.
