### ISSUE TITLE
wrong file name after last update

### ISSUE THREAD

**Issue by Dex321x** [sim0n00ps/OF-DL#344]
With the latest version, I got the problem with files that have the wrong name. It appears that the folder name is added. The config was working fine before. 

My config:
  "DownloadPath": "X:/xxx/onlyfans/0_onlyfans-dl-database",
  "PaidPostFileNameFormat": "{postedAt}_{username}_{id}",
  "PostFileNameFormat": "{postedAt}_{username}_{id}",
  "PaidMessageFileNameFormat": "{createdAt}_{username}_{id}",
  "MessageFileNameFormat": "{createdAt}_{username}_{id}",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,

The file I got before:    2024-04-20_username_123456789.jpg
The file I get now:       2024-04-22_0_**onlyfans-dl-database**username_123456789.jpg

--> it adds the onlyfans-dl-database to the file name, but I don't know why.
--> another issue is that for another username, it doesn't change anything on the file name. It just downloads it with the source name:
0hozxbu3b111qoqg0qtp1_source.mp4

Any idea why this is happening? Is my config wrong?

**Comment by melithine** [comment]
I believe `id` is the id of the post/message and not the video/photo/etc. attached, so it's often not unique enough. `mediaId` should be part of the filename in case there are multiple videos/photos in the same post/message. I'm not 100% sure that's your problem, but it does jump out at me as being problematic.
