### ISSUE TITLE
As soon as I open the window disappear

### ISSUE THREAD

**Issue by dionpbms** [sim0n00ps/OF-DL#348]
Hello,
I've followed all the steps, but as soon as I launch the program, the window disappear.
I made a screenshot of it for just the half second that stay on the screen.
I have norton antivirus, don't know if it can create problem, I've tried disable both antivirus and firewall for 15 mins but still crash.
![before close](https://github.com/sim0n00ps/OF-DL/assets/168935585/622e63ab-0d9d-4a28-ae19-b4791b7b7e92)

**Comment by melithine** [comment]
You have an error in one of the JSON files, either config.json or auth.json.

**Comment by dionpbms** [comment]
thank you, how to fix?

**Comment by melithine** [comment]
I can't see which one it failed on, but I'm going 5o guess config.json. please post it here for review.

**Comment by dionpbms** [comment]
thank you, is this:

{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": "",
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": false,
  "FFmpegPath": "D:\documenti\varie\OF.DL\ffmpeg.exe",
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
}

**Comment by melithine** [comment]
The slashes in `FFmpegPath` need to be `/`, not `\`.

**Comment by dionpbms** [comment]
Ok I'll try. I've copied the path like the guide said.

**Comment by dionpbms** [comment]
Now work a little bit more, it said that I'm logged, and then disappear like before

**Comment by melithine** [comment]
Either open a powershell/terminal window and execute the exe directly in that window, or look at the log file to see what the error is.

**Comment by melithine** [comment]
Also, what OS are you using? That looks pre-Windows 10, but I could be wrong.

**Comment by dionpbms** [comment]
I'm using windows 7. 
this is a screen after opened in powershell (took time to remember how to use it lol)
![of screen](https://github.com/sim0n00ps/OF-DL/assets/168935585/064c8024-6a2b-47fa-9c0c-d5ea3b7c53fc)

**Comment by dionpbms** [comment]
so this program can't work on win 7?

**Comment by melithine** [comment]
No, it can't.
