### ISSUE TITLE
Program Crashes On Start Up

### ISSUE THREAD

**Issue by NAMCO2000** [sim0n00ps/OF-DL#349]
Program crashes as soon as i start it so can't see error messages. Have attached files in case of imput error.

Have removed some letters/numbers from info in auth file that i'm uploading here. All quoatation marks & commas are the same in the undoctored file.

[auth.json](https://github.com/sim0n00ps/OF-DL/files/15210992/auth.json)

[config.json](https://github.com/sim0n00ps/OF-DL/files/15210994/config.json)

**Comment by sim0n00ps** [comment]
You need to download ffmpeg, you have set the ffmpeg path to OF DL.exe which is not correct, it needs to be for ffmpeg.exe, also you need to replace the back slashes in the path with the forward slashes.

**Comment by melithine** [comment]
Also, the text for cookie should be immediately after the double quote in auth.json, currently it's on the next line.

**Comment by NAMCO2000** [comment]
I have already DL ffmpeg. I created a folder which has the contents of the OF Downloader. I put ffmpeg in this. I then copied path from ffmpeg & pasted this into config file.

**Comment by sim0n00ps** [comment]
Ok if you've put ffmpeg in the same folder as OF DL.exe then it will be automatically detected by the program so you can leave the ffmpeg path blank

**Comment by NAMCO2000** [comment]
I just saw that as you said i had back slashes in ffmpeg path instead of forward slashes. 

Will do as you say though. 

Old path was "FFMPEG_PATH": "C:/Program Files/OF.DL/OF DL.exe"

New path would look like this "FFMPEG_PATH":

**Comment by melithine** [comment]
If you're setting it to auto detect, use two empty quotes, not nothing after the colon, that's not valid JSON.

**Comment by jasmeralia** [comment]
Assuming that that is in `config.json` and on the line you currently have it, use:

`"FFmpegPath": "",`

If you put it on the line right before the `}`, omit the final comma. (`FFMPEG_PATH` was only valid for `auth.json`.)

**Comment by jasmeralia** [comment]
Also, for `config.json`, it's safe to paste into https://jsonlint.com/ if you need to test the syntax validity. (Less so with `auth.json`.)

**Comment by melithine** [comment]
Assuming that that is in `config.json` and on the line you currently have it, use:

`"FFmpegPath": "",`

If you put it on the line right before the `}`, omit the final comma. (`FFMPEG_PATH` was only valid for `auth.json`.)

Also, for `config.json`, it's safe to paste into https://jsonlint.com/ if you need to test the syntax validity. (Less so with `auth.json`.) That won't be OF DL specific, but will catch general JSON formatting problems.

**Comment by NAMCO2000** [comment]
Got it working now. Thx for the help.
