### ISSUE TITLE
Error downloading certain messages

### ISSUE THREAD

**Issue by poneill21** [sim0n00ps/OF-DL#352]
I am receiving this error when I'm downloading messages after a certain date.

Exception caught: Response status code does not indicate success: 500 (Internal Server Error).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, Auth auth, Config config)

Here is my config.json for reference.

{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": true,
  "IncludeRestrictedSubscriptions": true,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": true,
  "DownloadDateSelection": "after",
  "CustomDate": "2024-05-03",
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": true,
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "FFmpegPath": "./ffmpeg/bin/ffmpeg.exe"
}

Any ideas on what could be causing it?

**Comment by melithine** [comment]
If you disable the date filtering, does it then work on older content? I would think a 500 would be an OF server problem, but it somewhat sounds like it might not be. I'm not fully certain, as I haven't hit that myself before.

**Comment by poneill21** [comment]
I have tried it without the date filtering, and this error comes up more than the majority of the time for a couple of creators. I thought it was because the messages log was large, so I used the date filtering to "shorten" the search, and still no dice.

**Comment by melithine** [comment]
If you're using a VPN, try directly. If you're not, try using one.

**Comment by poneill21** [comment]
i have tried multiple vpns, and not using a vpn using a new cookie each time. Still receiving the same error message.

**Comment by melithine** [comment]
Are you using your own Wildvine keys, or CDRM? Are you still seeing this issue on the current release?

**Comment by melithine** [comment]
Closing due to lack of feedback.
