### ISSUE TITLE
Unable to DL Full DRM Videos

### ISSUE THREAD

**Issue by NAMCO2000** [sim0n00ps/OF-DL#353]
I can't seem to DL full videos from profiles that have DRM enabled. It doesn't seem to DL more than 5 seconds of any video. There are no problems DL from any profile without DRM.

Don't know if there's any issue with my Config. 

[config.json](https://github.com/sim0n00ps/OF-DL/files/15222759/config.json)

**Comment by MrKikiMoki** [comment]
Same issue!

**Comment by melithine** [comment]
> I can't seem to DL full videos from profiles that have DRM enabled. It doesn't seem to DL more than 5 seconds of any video. There are no problems DL from any profile without DRM.
> 
> Don't know if there's any issue with my Config.
> 
> [config.json](https://github.com/sim0n00ps/OF-DL/files/15222759/config.json)

Config looks good. Do either of you see any errors during the scrape? Check the log file to verify. 

Beyond that, are you folks using CDRM or your own Wildvine keys?

**Comment by NAMCO2000** [comment]
My issue seemed to be VPN related. Was using Windscribe. Changed to CyberGhost & it worked. Have no idea why this was the case.

**Comment by melithine** [comment]
Onlyfans does block some proxies, that's probably why.
