### ISSUE TITLE
Unable to download, exception caught(cdrm-project.com:443)

### ISSUE THREAD

**Issue by Kevswagswag** [sim0n00ps/OF-DL#355]
I'm curently getting this error when i run the program

Exception caught: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (cdrm-project.com:443)

![image](https://github.com/sim0n00ps/OF-DL/assets/169647518/1ac4a663-7f05-40f6-be21-253de3b0bc47)

**Comment by LautaroIbacache** [comment]
Hi sir i can help you add me on telegram  @tg43gsdv

**Comment by Kevswagswag** [comment]
> Hi sir i can help you add me on telegram @tg43gsdv

very sus

**Comment by Kevswagswag** [comment]
> I just want to help, you must generate your cdm files to be able to download files protected by drm https://github.com/sim0n00ps/OF-DRM, it was difficult for me to get it. good luck!

do u have the files already?

**Comment by LautaroIbacache** [comment]
They are unique files for each connection, you must generate your own, this is done by mounting the android test client and then the dumper https://github.com/wvdumper/dumper

**Comment by moodyqw** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/169681930/1387c7fd-9844-44de-bd1b-3c40e6ccfe6f)
hello there guys 
iam having the same problem here did anyone figure out how to fix it ?
thanks in advance

**Comment by melithine** [comment]
Either generate your own keys, or wait for the CDRM Project to come back online.

**Comment by moodyqw** [comment]
> Either generate your own keys, or wait for the CDRM Project to come back online.
how can i do that?

**Comment by milestales** [comment]
I'm also having the same problem. I was using an older version and this error appeared. I updated to the latest version, but the error persists when I try to download a specific post or several posts (including paid ones), as well as messages too.

I'm very inexperienced with computers, can this type of problem be fixed with an updated version of OF-DL? it worked so well not long ago 
![224478825](https://github.com/sim0n00ps/OF-DL/assets/169735293/da6cc572-4a99-45df-8832-d4172971e949)
![222558](https://github.com/sim0n00ps/OF-DL/assets/169735293/4c48f9a4-5ffa-4049-89ce-b073a81e8397)

**Comment by melithine** [comment]
No, OFDL isn't the problem, CDRM is down (again). If you don't generate your own keys, you'll be affected every time CDRM goes down (a fairly common occurrence).

**Comment by milestales** [comment]
> No, OFDL isn't the problem, CDRM is down (again). If you don't generate your own keys, you'll be affected every time CDRM goes down (a fairly common occurrence).

Ah, now I understood. thank you very much for answering me
I hope it doesn't take long for CDRM to return Y_Y

**Comment by melithine** [comment]
I recommend trying to generate your own, https://of-dl.gitbook.io/of-dl/requirements has info on that. It's complicated but you only have to do it once and then you're not reliant on CDRM, which seems pretty flaky IMO.

**Comment by Evolvere1337** [comment]
I followed this guide and generated my own files and placed them in cdm\devices\chrome_1610.
I still receive this error, seems like the tool is still using  CDRM Project even tough my device_client_id_blob and device_private_key files are present.

Any suggestions?

**Comment by Kvothe1970** [comment]
They resolved it on the 16th of May 2024 
![image](https://github.com/sim0n00ps/OF-DL/assets/24984994/6d104c85-27df-4450-b96e-ceec2eb6e051)
