### ISSUE TITLE
"After" Date - not recognized

### ISSUE THREAD

**Issue by soreback** [sim0n00ps/OF-DL#356]
I have the following defined in the config file

  "DownloadOnlySpecificDates": true,
  "DownloadDateSelection": "after",
  "CustomDate": "2024-03-01",

But it still seems to download everything.  Am I doing something wrong here or is there some other issue ?

Thanks

**Comment by Evolvere1337** [comment]
"DownloadOnlySpecificDates": true,

Youre missing the quotation marks on: true
