### ISSUE TITLE
OF.DL keeps crashing

### ISSUE THREAD

**Issue by nero008** [sim0n00ps/OF-DL#359]
my of.dl keeps crashing even tho i followed the tutorial and got the latest version idk what to do

**Comment by melithine** [comment]
Need a lot more info to help. What do the logs show?

**Comment by nero008** [comment]
![_config json - Notepad 5_22_2024 11_24_19 AM](https://github.com/sim0n00ps/OF-DL/assets/170358211/6a0a28d4-8a77-426b-9617-8f338788ae4d)
![_config json - Notepad 5_22_2024 11_24_50 AM](https://github.com/sim0n00ps/OF-DL/assets/170358211/2027e4b6-7d93-448d-8e7e-f8f9b3931eb3)

**Comment by sim0n00ps** [comment]
> ![_config json - Notepad 5_22_2024 11_24_19 AM](https://github.com/sim0n00ps/OF-DL/assets/170358211/6a0a28d4-8a77-426b-9617-8f338788ae4d)
> ![_config json - Notepad 5_22_2024 11_24_50 AM](https://github.com/sim0n00ps/OF-DL/assets/170358211/2027e4b6-7d93-448d-8e7e-f8f9b3931eb3)
> 

In your ffmpeg path you have a ; instead of a :
Hopefully that should fix it

**Comment by whimsical-c4lic0** [comment]
The `c` at the end of the ShowScrapeSize line in the config should also be removed. The line breaks on the X_BC and COOKIE lines in the `auth.json` file should also be removed.

**Comment by nero008** [comment]
i did everything and it still didnt work i quit

**Comment by LittleStuart92** [comment]
Try this delete mostly all text and just leave sess=... and auth_id. My file looks like this and works. 
![obraz](https://github.com/sim0n00ps/OF-DL/assets/165220452/ef3a364b-07dc-4d5f-86ad-156f0fc9bb48)
