### ISSUE TITLE
cdrm-project.com doesn't work

### ISSUE THREAD

**Issue by dx98er** [sim0n00ps/OF-DL#362]
I get this error when I launch OF-DL, do I need to generate my own widevine keys (if so how do I do that/get them?) or is there anything else I can do?
![11](https://github.com/sim0n00ps/OF-DL/assets/170832884/28d7db48-387e-4dc1-8c48-a7a064be82de)

**Comment by melithine** [comment]
No, that's just saying it couldn't connect to OnlyFans, not CDRM related.
