### ISSUE TITLE
Expired subs 

### ISSUE THREAD

**Issue by sixgn** [sim0n00ps/OF-DL#37]
Working for me for free and purchased posts (not unpurchased) including drm - running it on expired subscription accounts doesn’t pull anything at all - how is it intended to treat expired sub content?

**Comment by sim0n00ps** [comment]
It should pull any media which you can view at that moment so in the case of it being an expired sub it should get any message media that is free or paid and also any paid posts as they are tied to your account so you can view them all the time

**Comment by sixgn** [comment]
Interesting - ok I trialed it on a couple smaller expired subs that I had even done purchases on and it didn’t pull those. Was planning on installing on another pc with better storage and see how it goes on there maybe it’s a config issue. Thanks for your work On Jun 13, 2023, at 12:57 PM, sim0n00ps ***@***.***> wrote:﻿
It should pull any media which you can view at that moment so in the case of it being an expired sub it should get any message media that is free or paid and also any paid posts as they are tied to your account so you can view them all the time
