### ISSUE TITLE
DRM issue

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#370]
![1](https://github.com/sim0n00ps/OF-DL/assets/120327768/6cb664d0-1630-4e7f-a93a-313649d70a84)

**Comment by melithine** [comment]
Are you using your own Wildvine keys or CDRM? There seem to be a number of similar reports atm, but I haven't seen this myself

**Comment by bezaaas** [comment]
> Are you using your own Wildvine keys or CDRM? There seem to be a number of similar reports atm, but I haven't seen this myself

I'm not good at this, I downloaded it and launched it, it downloads everything except DRM.

**Comment by sim0n00ps** [comment]
> > Are you using your own Wildvine keys or CDRM? There seem to be a number of similar reports atm, but I haven't seen this myself
> 
> I'm not good at this, I downloaded it and launched it, it downloads everything except DRM.

Please download the latest version where that issue is fixed

**Comment by bezaaas** [comment]
Thank you it works! I just tried with the latest version of your script + latest version of ffmpeg.
