### ISSUE TITLE
unable to download from OF which I've used to download

### ISSUE THREAD

**Issue by shim1346** [sim0n00ps/OF-DL#372]
Could you please find out anything wrong or any issues on the attached images? 
![스크린샷 2024-06-01 215416](https://github.com/sim0n00ps/OF-DL/assets/167332817/dd154b58-1829-4b77-b280-bd5bd0dcef4e)

**Comment by melithine** [comment]
Are you using your own Wildvine keys or CDRM? There seem to be a number of similar reports atm, but I haven't seen this myself

**Comment by allawhime** [comment]
> Are you using your own Wildvine keys or CDRM? There seem to be a number of similar reports atm, but I haven't seen this myself

I get the same error using CDRM.

**Comment by shim1346** [comment]
> Are you using your own Wildvine keys or CDRM? There seem to be a number of similar reports atm, but I haven't seen this myself

I don't think so. I only followed OF-DL instruction (https://of-dl.gitbook.io/of-dl) in order to download video. It have worked well, but since last week, I found and have kept experiencing this issue.

**Comment by sim0n00ps** [comment]
Use the latest version where this issue has been fixed

**Comment by shim1346** [comment]
> Use the latest version where this issue has been fixed

Thank you So much. It works well now. Always appreciate for your supports
