### ISSUE TITLE
A specific user is bugging the app

### ISSUE THREAD

**Issue by joaovoliv** [sim0n00ps/OF-DL#373]
I can use the app just fine with other models, but 1 model gives me the following error.
I guess (but not sure) it has something to do with the captions she used in her posts

Traceback (most recent call last):
  File "L:\OFDL-master\OFDL-master\OFDL.py", line 471, in update_main
    item.setText(2, user_posts[key].caption())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\OFDL-master\OFDL-master\module\snafylno.py", line 317, in caption
    return self.data["rawText"]
           ~~~~~~~~~^^^^^^^^^^^
KeyError: 'rawText

**Comment by melithine** [comment]
I'm confused... OFDL is written in c#, not python.
