### ISSUE TITLE
config.json error

### ISSUE THREAD

**Issue by JarkeldOA** [sim0n00ps/OF-DL#374]
StackTrace:    at OF_DL.Program.Main(String[] args)
2024-06-02 21:26:58.280 +02:00 [ERR] config.json processing failed.
2024-06-02 21:26:58.319 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

JSON online validator indicates that the downloadpath line is the issue:

Invalid JSON!
Error: Parse error on line 17:
...,  "DownloadPath": "c:\",  "PaidPostFi
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

I can't figure out how to fix this.

**Comment by melithine** [comment]
Paste the whole file? And I don't think you can just point at the c drive, as that requires admin permissions (you can probably point to like d:/ or such if you adjust the permissions, but not c:/).

**Comment by JarkeldOA** [comment]
Replaced the config with the default one, pointed it to o:\dl\, same error:
2024-06-04 19:44:04.639 +02:00 [ERR] config.json processing failed.
2024-06-04 19:44:04.681 +02:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.Main(String[] args)

Full config:
{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "O:\dl\",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": "",
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": false,
  "FFmpegPath": "O:\dl\ffmpeg.exe",
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
}

**Comment by melithine** [comment]
Need to change that to `o:/dl` and `o:/dl/ffmpeg.exe`. Backslashes are not valid for paths.
