### ISSUE TITLE
Application crashes after few seconds of opening...

### ISSUE THREAD

**Issue by Uyahya566** [sim0n00ps/OF-DL#375]
I'm on windows 11 and whenever I open the app it stays for a few seconds and crashes right after![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/159292c1-0460-4cff-9a75-d43961c7fb6d)
![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/0f2c87ae-ae29-4ddc-b28d-83b91814204d)![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/56267446-5c17-4767-ad3f-1b6d721aa40d)

**Comment by melithine** [comment]
The last comma before `}` is not correct.

**Comment by Uyahya566** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/75b2c165-60c0-4d76-9efa-a071864d29c6)
Still crashes with a different error log now

**Comment by Uyahya566** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/bfa56675-1a9e-41ad-93bd-e6add2d1feff)
"Config.json processing failed"
"Exception caught: object reference not set to instance of an object"
