### ISSUE TITLE
Videos Downloaded Are Short

### ISSUE THREAD

**Issue by MasterJohan** [sim0n00ps/OF-DL#377]
I have experienced some videos downloaded half or missing. For example, I just downloaded a video of 37 minutes, but it was 32 and I tired downloading it again, this time it downloaded it as 12 minute.

**Comment by Uyahya566** [comment]
Might be caused by the video not fully downloading itself... check your network connection probably

**Comment by melithine** [comment]
Check the log file for errors, too.

**Comment by MasterJohan** [comment]
> Might be caused by the video not fully downloading itself... check your network connection probably

Yes. You are right. The problem with my issue is caused by bad network. My internet is super fast and perfect, but unfortunately OnlyFans is banned in my country. So, it became necesarry for me to use VPN. You know that VPN (even the paid ones) has bad network. Still, thing works perfectly.

**Comment by Uyahya566** [comment]
Yuppp check the log files and send the error code here

**Comment by melithine** [comment]
The logs will tell for sure, but I bet it's either a 403 (because OF blocks and/or rate limits some proxies/VPNs) or (hopefully) it was a timeout. If it's the latter, you can raise that limit in `config.json`. If it's the former, you'd need to try a different provider or decreasing your bandwidth limit in `config.json `.

**Comment by MasterJohan** [comment]
> The logs will tell for sure, but I bet it's either a 403 (because OF blocks and/or rate limits some proxies/VPNs) or (hopefully) it was a timeout. If it's the latter, you can raise that limit in `config.json`. If it's the former, you'd need to try a different provider or decreasing your bandwidth limit in `config.json`.

Strange thing, I can't see any log in the logs file. I deleted it probably by accident. I will try downloading some videos again and if same thing happens, I will post it here with the logs, until then, a bit patience will be needed to clarify.

**Comment by MasterJohan** [comment]
> > The logs will tell for sure, but I bet it's either a 403 (because OF blocks and/or rate limits some proxies/VPNs) or (hopefully) it was a timeout. If it's the latter, you can raise that limit in `config.json`. If it's the former, you'd need to try a different provider or decreasing your bandwidth limit in `config.json`.
> 
> Strange thing, I can't see any log in the logs file. I deleted it probably by accident. I will try downloading some videos again and if same thing happens, I will post it here with the logs, until then, a bit patience will be needed to clarify. However, I can tell this, this thing happens when my connection slows down. Yesterday, I did not have much idea what is going on, but today, I see more clearly. When I try to download that particular video again with another IP through VPN, it succeeds and downloads the whole video, but you got me thinking there. There would be no harm in looking at logs.



> > The logs will tell for sure, but I bet it's either a 403 (because OF blocks and/or rate limits some proxies/VPNs) or (hopefully) it was a timeout. If it's the latter, you can raise that limit in `config.json`. If it's the former, you'd need to try a different provider or decreasing your bandwidth limit in `config.json`.
> 
> Strange thing, I can't see any log in the logs file. I deleted it probably by accident. I will try downloading some videos again and if same thing happens, I will post it here with the logs, until then, a bit patience will be needed to clarify. However, I can tell this, this thing happens when my connection slows down. Yesterday, I did not have much idea what is going on, but today, I see more clearly. When I try to download that particular video again with another IP through VPN, it succeeds and downloads the whole video, but you got me thinking there. There would be no harm in looking at logs.

I checked both log files after use and my download process. I have not encountered any issues. It was certainly a bad connection because of the VPN. I was able to fix it somehow, it took me time though. Trial and error through servers and IPs. Thank you guys for helping out so quickly.
