### ISSUE TITLE
Speed of posts collect & multi-threaded

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#379]
Hello. Your program is amazing. 

Please tell me if I can increase the number of download threads and speed up the getting of posts? for example: getting 2500 posts can take more than half an hour. Thanks

**Comment by melithine** [comment]
OF do rate limiting, so increasing the speed may actually cause it to take even longer. You can try tweaking the bandwidth limits, but you're not going to get massive gains given they will likely flag you and rachet your speed down.
