### ISSUE TITLE
Can't download DRM content from expired subscription

### ISSUE THREAD

**Issue by elastickick** [sim0n00ps/OF-DL#38]
I noticed the list of accounts that it pulls from are only accounts we're subscribed to or Following, which makes sense.

However, I'm running into an issue where I can't download any DRM content (I've purchased) from an expired subscription, since it doesn't come up on the list within the program. In some cases, I can still purchase DM messages from creators even after my subscription expired with them.

I recommend having an option where we can manually type in the OF handle directly on the program if that's possible

Thank you!

**Comment by sim0n00ps** [comment]
You can include the expired subscriptions by modifying the auth.json, by default it's set to false, if you set it to true all of the current and past accounts you have subbed to should be listed. I can't have a search feature as the package I use for the menu stuff doesn't have that as an option.

**Comment by DonaldTPP** [comment]
> You can include the expired subscriptions by modifying the auth.json, by default it's set to false, if you set it to true all of the current and past accounts you have subbed to should be listed. I can't have a search feature as the package I use for the menu stuff doesn't have that as an option.

    "DownloadAvatarHeaderPhoto": "true",
    "DownloadPaidPosts": "true",
    "DownloadPosts": "true",
    "DownloadArchived": "true",
    "DownloadStories": "true",
    "DownloadHighlights": "true",
    "DownloadMessages": "true",
    "DownloadPaidMessages": "true",
    "DownloadImages": "true",
    "DownloadVideos": "true",
    "DownloadAudios": "true"
    
    They are the only options I have in my auth file.

**Comment by elastickick** [comment]
> You can include the expired subscriptions by modifying the auth.json, by default it's set to false, if you set it to true all of the current and past accounts you have subbed to should be listed. I can't have a search feature as the package I use for the menu stuff doesn't have that as an option.

Oh snap! I totally didn't see that in the auth.json file, thank you so much!

**Comment by elastickick** [comment]
Closed
