### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by divakar123** [sim0n00ps/OF-DL#380]
I was using it few hours ago, it was working fine
Now it keeps saying auth failed, I have tried with different browser too

Auth failed, please check the values in auth.json are correct.

If you have previously been able to auth successfully, the most likely cause of this is that your browser has updated,
which will change the values of the USER_AGENT string. The version change to this string is usually very minor and easy
to overlook, but even a slight difference will cause an authentication failure.

If you are struggling to authenticate, you may want to try the browser extension which is documented here:

https://of-dl.gitbook.io/of-dl/auth#browser-extension

Press any key to exit

**Comment by Uyahya566** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/db51a7ae-e292-441b-a032-4472808bbaf8)
Unfortunately me too

**Comment by divakar123** [comment]
> ![image](https://private-user-images.githubusercontent.com/171519158/336944880-db51a7ae-e292-441b-a032-4472808bbaf8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDkyMDksIm5iZiI6MTcxNzYwODkwOSwicGF0aCI6Ii8xNzE1MTkxNTgvMzM2OTQ0ODgwLWRiNTFhN2FlLWUyOTItNDQxYi1hMDMyLTQ0NzI4MDhiYmFmOC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTczNTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAyN2Q4NzYxNmJhMjliOTEyZGY1NGRmYTM0NTBmM2U0ZmZjZWRiZjgxM2RlOTI4OTcwNjMzZTY5ZWIxMDJjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yepP_5TPC7LntWfnGjIsczVRQEmJl8MllfHHUsnEKCc) Unfortunately me too


I tried with some other scraper too
had same issue :/

**Comment by dgtlabs** [comment]
Same issue here, tried setting the auth.json values manually and with the browser extension, no joy on either attempt.

**Comment by Uyahya566** [comment]
Probably they've patched the website

**Comment by Deleteboys** [comment]
Exception caught: Response status code does not indicate success: 400 (Bad Request).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, Auth auth, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetAllSubscriptions(Dictionary`2 getParams, String endpoint, Auth auth, Boolean includeRestricted)
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.DownloadAllData()
   at OF_DL.Program.Main(String[] args)

**Comment by Uyahya566** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/c73a05ea-848c-498a-8668-662a7f80a095)
This is what I get sometimes too

**Comment by badbeezy** [comment]
I think they've patched the site. tried several attempts a updated the values in auth.json and still get the same response.

**Comment by Uyahya566** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/171519158/4374223c-05eb-4705-b696-f6e5bd7c2279)
Logged in successfully but hit with an error...
We'd have to wait on the devs for now

**Comment by sim0n00ps** [comment]
Looking into it now, please be patient

**Comment by Deleteboys** [comment]
it seems like the sign header is wrong

**Comment by sim0n00ps** [comment]
> it seems like the sign header is wrong

Probably just need the up to date dynamic rules which I don't know how to work out sadly

**Comment by Deleteboys** [comment]
> > it seems like the sign header is wrong
> 
> Probably just need the up to date dynamic rules which I don't know how to work out sadly

should i find a way to get them i will let you know

**Comment by sim0n00ps** [comment]
Fixed with this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.59

**Comment by badbeezy** [comment]
> Fixed with this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.59
Amazing. Any ideas for solutions for the DRM?

**Comment by melithine** [comment]
> > Fixed with this release https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.59
> > Amazing. Any ideas for solutions for the DRM?

Try 1.10 if you're using OF-DRM.
