### ISSUE TITLE
Downloading Post stuck at 0%

### ISSUE THREAD

**Issue by men-an-tol** [sim0n00ps/OF-DL#381]
![ofdl](https://github.com/sim0n00ps/OF-DL/assets/171873416/9ae76f4d-cde0-4412-8741-5d3292fc949a)

Trying to download a single video. It's been like this for 2.5 hours.
I'm using the latest version, V1.7.59.

**Comment by melithine** [comment]
Was there something after `https://onlyfans.com` that you redacted in the screenshot? As it stands, it looks like you're trying to scrape the feed as a single post.

**Comment by men-an-tol** [comment]
No, I redacted the URL.

**Comment by melithine** [comment]
Try with/without a VPN.

**Comment by men-an-tol** [comment]
Tried without, and with several different VPN servers, but it still didn't work unfortunately. Also rebooted my system and tried three different networks.

**Comment by melithine** [comment]
Not sure what else to suggest, I tried this after you filed the issue and it worked fine for me.

**Comment by men-an-tol** [comment]
Tried again several times, still nothing. I'll probably have to wait for a new version.

**Comment by melithine** [comment]
Checking in to see if this is resolved, otherwise it will be closed out. If it's not, please change the logging level to verbose and attach a log file here so we can see what's going on.

**Comment by men-an-tol** [comment]
The latest version works, so this issue is obsolete. Thanks for your help.
