### ISSUE TITLE
Auth failed, please check the values in auth.json are correct.

### ISSUE THREAD

**Issue by russell452** [sim0n00ps/OF-DL#383]
Just used this tool the other day w/o any issue, but today im getting this error about my auth.json. I've checked and re-checked 50 times that all the info is correct, i've aso logged in and out of my OF account to refresh the sess, but no dice.

**Comment by russell452** [comment]
saw previous post

**Comment by melithine** [comment]
Are you using today's release? Things changed and @sim0n00ps had to make a fix.
