### ISSUE TITLE
Not working {postedAt} in Messages

### ISSUE THREAD

**Issue by bezaaas** [sim0n00ps/OF-DL#385]
{postedAt} not working for messages. Instead of add a sent date to messages files, it says so in the file name {postedAT}-12839179.mp4

**Comment by melithine** [comment]
https://of-dl.gitbook.io/of-dl/custom-filename-formats shows what macros can be used. `postedAt` is not valid for messages. Try `createdAt` instead.

**Comment by bezaaas** [comment]
thanks
