### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by xxx-uploaded** [sim0n00ps/OF-DL#387]
How to increase the speed of downloading videos and photos?

**Comment by Uyahya566** [comment]
You can increase the speed of downloads in config.json by editing it in notepad....
But bear in mind that OF does rate limiting so if they notice you have an unusual download speed they will flag you down or possibly ban your account...

**Comment by melithine** [comment]
> You can increase the speed of downloads in config.json by editing it in notepad.... But bear in mind that OF does rate limiting so if they notice you have an unusual download speed they will flag you down or possibly ban your account...

Exactly right.

**Comment by xxx-uploaded** [comment]
I downloaded a 1 GB profile for 25 minutes
There are profiles of 100-300GB, how long do you think you will have to wait?

**Comment by sim0n00ps** [comment]
You need to take into consideration how many users are on OF at the same time every day, a lot. So of course OF will have a limit on how quickly they can send data to you across the internet. There's nothing I can do so I will be closing this issue.
