### ISSUE TITLE
downloading from inactive users

### ISSUE THREAD

**Issue by JC02023** [sim0n00ps/OF-DL#389]
Hi is there a way to download the profile picture and banner from inactive users. I am able to add their profile to a list, but am unable to follow them. When I download from list it does not detect them

**Comment by melithine** [comment]
Do you have `IncludeExpiredSubscriptions` enabled?

**Comment by JC02023** [comment]
I tried it with it enabled but i was never subbed to them. I found out they use to do onlyfans after their account was inactive. There is no sub option they have a page but their an inactive user.

**Comment by melithine** [comment]
That's not supported, then.
