### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Doezuu** [sim0n00ps/OF-DL#39]
More options for downloading selectively: e.g. date/time parameters (only download before or after certain video upload dates, etc.); only downloading the DRM enabled videos.

**Comment by topboysyp** [comment]
"only downloading the DRM enabled videos."+1
This should be very helpful.

**Comment by kappakream** [comment]
This is a good idea. I don't wanna download the entire catalog twice if possible. Any work arounds yet?

**Comment by sim0n00ps** [comment]
Made another tool similar to this one with a lot less steps to set up https://github.com/sim0n00ps/OF-DRM. Primarily focuses on the downloading of DRM videos only.
