### ISSUE TITLE
Feature Request: notify of new versions

### ISSUE THREAD

**Issue by melithine** [sim0n00ps/OF-DL#390]
It would be helpful to add a check to see if there is a newer version available to notify users they should probably upgrade.

**Comment by r3arsh** [comment]
i agree with this, there's a github api that allows this. probably could be implemented on startup

**Comment by thatcoderguy** [comment]
Ok, so just to be clear, the expectation is that the software itself will tell you there's a new version?

If so, I'll work on that after the logging levels enhancement.

**Comment by melithine** [comment]
> Ok, so just to be clear, the expectation is that the software itself will tell you there's a new version?
> 
> If so, I'll work on that after the logging levels enhancement.

Hold off just a bit, there's some prep work going on right now that will be needed before this... the version isn't tracked in the app itself currently. whimsical-c4lic0 added the app support for it and I've been working on a GHA to simplify/automate the release process for sim0n00ps.

**Comment by melithine** [comment]
This has been completed with 1.7.75.
