### ISSUE TITLE
Auth failed, please check the values in auth.json are correct, press any key to exit

### ISSUE THREAD

**Issue by ticketmade** [sim0n00ps/OF-DL#391]
auth.json located successfully!
config.json located successfully!
yt-dlp.exe located successfully!
ffmpeg.exe located successfully!
mp4decrypt.exe located successfully!
device_client_id_blob located successfully!
device_private_key located successfully!
Auth failed, please check the values in auth.json are correct, press any key to exit

This just happened yesterday. Was working fine before, looked to see if any changes are within USER_ID/USER_AGENT/COOKIE and there are no changes, regardless I re-copied the values again, still same error. Made no other changes the other day that could have led to the downloader breaking.

Any help?

**Comment by melithine** [comment]
Are you on 1.7.59? OF did some changes recently and Rhys provided an updated release.

**Comment by hoppalotta2** [comment]
Same issue here.  I think they've changed something in their code.

**Comment by ticketmade** [comment]
I am on 1.0.0.0

**Comment by melithine** [comment]
This thread was resolved, see https://github.com/sim0n00ps/OF-DL/issues/397 for the current issue.
