### ISSUE TITLE
Can not download the DRM content 

### ISSUE THREAD

**Issue by jdkcdk** [sim0n00ps/OF-DL#393]
I use the lastest version OF-DL & ffmpeg with CDM files, but the DRM content can not been downloaded successful. This is what the log shown:

2024-06-08 00:53:33.358 +08:00 [ERR] ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[https @ 00000255d183e400] HTTP error 403 Forbidden
[in#0 @ 00000255d183dd00] Error opening input: Server returned 403 Forbidden (access denied)
Error opening input file https://cdn3.onlyfans.com/dash/files/8/8f/8ff958a34592cea3b3eb78c5d82e70e6/0hqfo93rsophah50qagzo.mpd.
Error opening input files: Server returned 403 Forbidden (access denied)

2024-06-08 00:53:33.361 +08:00 [ERR] Exception caught: Could not find file 'D:\OF\G1\ebonymeoww\Posts\Free\Videos\0hqfo93rsophah50qagzo_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String filenameFormat, SinglePost postInfo, Medium postMedia, Author author, Dictionary`2 users)

There is no any issue when try with none DRM content.

**Comment by bezaaas** [comment]
Try to use newest version of ffmpeg. Should help

**Comment by jdkcdk** [comment]
Try ffmpeg version 2024-06-06-git-d55f5cba7b-essentials,newest build, still not working,same issue
[https @ 00000235159d2580] HTTP error 403 Forbidden
[in#0 @ 00000235159d1c00] Error opening input: Server returned 403 Forbidden (access denied)
Error opening input file https://cdn3.onlyfans.com/dash/files/8/8f/8ff958a34592cea3b3eb78c5d82e70e6/0hqfo93rsophah50qagzo.mpd.
Error opening input files: Server returned 403 Forbidden (access denied)

2024-06-09 17:57:11.471 +08:00 [ERR] Exception caught: Could not find file 'D:\OF\G1\ebonymeoww\Posts\Free\Videos\0hqfo93rsophah50qagzo_source.mp4'.

**Comment by lemehub** [comment]
Also having the same issue and error log

**Comment by x64max** [comment]
I can report a similar problem, not sure if it's exact. See following output:

![image](https://github.com/sim0n00ps/OF-DL/assets/172326063/c8ddce17-d3eb-4e6d-9772-35f73de11a04)

It appears that _sometimes_ posts download fine, but others not (403 error)

Some posts with multiple media may successfully download the **first** media, but fail on the **second**. Others may succeed on both.

**Comment by boivinx7** [comment]
Got the same issue also

**Comment by x64max** [comment]
> had the same issue also, but just fixed it by editing the auth.json putting only uth_uid_*= ; auth_id=;st=;sess=; instead of all the rest that the chrome addin gives.

I can confirm it's related to the OF-DL extension, specifically due to CloudFront cookies that it puts there. When I remove the long `CloudFront-Policy` and `CloudFront-Signature`  cookies, the issue is fixed. 

I think only the cookies `auth_id` and `sess` are needed.  Maybe the app can strip away these useless cookies, or the extension would need to be fixed.

**Comment by jasmeralia** [comment]
Sounds like an issue to raise here: https://github.com/whimsical-c4lic0/OF-DL-Auth-Helper/
