### ISSUE TITLE
Weird 404 Message Work Before? :O

### ISSUE THREAD

**Issue by Kuroo2021** [sim0n00ps/OF-DL#396]
I get this. Exception caught: Response status code does not indicate success: 404 (Not Found).

![Screenshot 2024-06-09 214907](https://github.com/sim0n00ps/OF-DL/assets/18900059/a9dcf416-327b-4035-8e73-064a2fa4197e)

It was working before and I have the latest version.....weird

**Comment by melithine** [comment]
> I got the same error message. What solved you this?

Try the most current release, or open a new issue with more details.

**Comment by Kuroo2021** [comment]
> > I got the same error message. What solved you this?
> 
> Try the most current release, or open a new issue with more details.

This!

**Comment by Kuroo2021** [comment]
> I got the same error message. What solved you this?

most current release,
