### ISSUE TITLE
404 Error during startup

### ISSUE THREAD

**Issue by denes44** [sim0n00ps/OF-DL#397]
I tried to run the program today, but I got the following error message:
![image](https://github.com/sim0n00ps/OF-DL/assets/60078357/ba4d8d0c-b7e6-41a1-92dc-17db16bb7d04)

I updated it to the latest release, but the error is the same.

**Comment by aussielimes** [comment]
same here

**Comment by meanjoep92** [comment]
Suddenly just happened to me too! :(

**Comment by JC02023** [comment]
same error

**Comment by NoNotNate** [comment]
just got this too

**Comment by djmarioka** [comment]
Hi,

today I'm receiving this error, as well:

<img width="664" alt="image" src="https://github.com/sim0n00ps/OF-DL/assets/81478245/da3c65bf-74ff-4b19-88b6-b93ef343623e">

Could anybody fix this issue?.

Thanks.

**Comment by Astercholik** [comment]
Hello, I am also getting the same message, yesterday I was still using the program and this morning such an error.
I have the latest version and I noticed that a new version of Firefox came out, so I updated the auth.json file but the error still occurs.

**Comment by booleangit** [comment]
Same here. I'm guessing OF changed their authentication method? Hopefully it doesn't require an extensive rewrite.

![image](https://github.com/sim0n00ps/OF-DL/assets/25500731/25e379cb-0e1b-4905-b33f-19a2c5a96bdc)

**Comment by melithine** [comment]
We're aware of the issue, but it's unclear when a fix might be available, as one of our dependencies was taken down.

**Comment by booleangit** [comment]
> We're aware of the issue, but it's unclear when a fix might be available, as one of our dependencies was taken down.

Just out of curiosity: can I ask which dependency?

**Comment by melithine** [comment]
The dynamic rules, both locations appear to have been taken down by github.

**Comment by ryansilversun** [comment]
We can use wayback machine to retrieve the last saved version of that file
https://web.archive.org/web/20240605235739/https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json

**Comment by sim0n00ps** [comment]
Doesn't require a re-write at all I don't think, just need to host the dynamic rules again, just need to generate them and keep them up to date

**Comment by booleangit** [comment]
> Doesn't require a re-write at all I don't think, just need to host the dynamic rules again, just need to generate them and keep them up to date

If it got deleted by GitHub, maybe it's wise to rename the library/location to something that doesn't contain the full OF name.

**Comment by sim0n00ps** [comment]
> > Doesn't require a re-write at all I don't think, just need to host the dynamic rules again, just need to generate them and keep them up to date
> 
> If it got deleted by GitHub, maybe it's wise to rename the library/location to something that doesn't contain the full OF name.

I wasn't hosting them in the first place but yes I will have to either discreetly host them myself or let someone else do it, ideally I would do it myself

**Comment by ryansilversun** [comment]
Besides the online file, could you implement a fallback to local file in case the online one is nuked somehow? 😂

**Comment by Ragnarok700** [comment]
Ah, thanks @legendaryredfox for mentioning this. Somehow, it escaped my search...
And here I was cloning the project and just about to debug the app!

**Comment by Ragnarok700** [comment]
OK, so I added support for using a local rules.json (as a backup if URI is dead/not working/etc.), but the values I found don't allow me to auth... :P

What values should I be using now?
What I currently have is:
```
{
  "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
  "static_param": "RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y",
  "prefix": "24650",
  "suffix": "666078a0",
  "checksum_constant": 13,
  "checksum_indexes": [4,5,7,9,9,11,13,17,18,19,23,23,23,24,25,26,27,27,28,28,28,28,28,29,30,32,32,33,33,34,34,38]
}
```

**Comment by melithine** [comment]
> @ryansilversun OK, so I added support for using a local rules.json (as a backup if URI is dead/not working/etc.), but the values I found don't allow me to auth... :P (I'll probably make a PR later once I can confirm it works fully)
> 
> What values should I be using now? What I currently have is:
> 
> ```
> {
>   "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
>   "static_param": "RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y",
>   "prefix": "24650",
>   "suffix": "666078a0",
>   "checksum_constant": 13,
>   "checksum_indexes": [4,5,7,9,9,11,13,17,18,19,23,23,23,24,25,26,27,27,28,28,28,28,28,29,30,32,32,33,33,34,34,38]
> }
> ```

That looks absolutely nothing like auth.json should look like. https://of-dl.gitbook.io/of-dl/auth

**Comment by Ragnarok700** [comment]
> That looks absolutely nothing like auth.json should look like. https://of-dl.gitbook.io/of-dl/auth

@melithine Obviously, that is totally true, since it is **not** the contents of my auth.json file. This is the content of my local **rules.json**, not auth.json. I added support for a local rules.json file in case the one online is taken down/unavailable. That being said, I don't know what information should be in there right now (in the rules.json) to be valid.

**Comment by melithine** [comment]
Ah, ok, I misunderstood what you were saying. From the Discord, the values from the Wayback machine worked for at least one person. https://web.archive.org/web/20240605235739/https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json

**Comment by Ragnarok700** [comment]
Those are the ones I posted above. Did not allow me to auth though.

**Comment by melithine** [comment]
There's also some discussion about how to generate it. https://github.com/gravilk/onlyfans-dynamic-rules-documented

**Comment by melithine** [comment]
Also, and this may be obvious, but in case it's not, with any errors during auth, check to see if your session is still valid. They often void the session if they detect something wrong.

**Comment by Ragnarok700** [comment]
Fair point. Even with updated auth.json, still not working for me with those... oh well. I'll have to take a break for this since I'm trying to help a friend and it felt like a fun thing to look at. That being said, I can probably push my modification that adds support to read the local rules.json.

**Comment by melithine** [comment]
> Fair point. Even with updated auth.json, still not working for me with those... oh well. I'll have to take a break for this since I'm trying to help a friend and it felt like a fun thing to look at but I do have other stuff to do today :D. That being said, I can probably push my modification that adds support to read the local rules.json.

That was actually merged into master already, I just tested it with a local build (using `dotnet build`) and it works fine for me. The rules.json looks to be the same, it's in the `OF DL` subfolder of the code in the current master branch.

**Comment by sim0n00ps** [comment]
For now as a temp fix I have created a new release that includes a rules.json file that needs to be in the same directory as OF DL.exe. For now it's fine but going forward this wont be a permanent thing, this is just to keep the ball rolling for you guys

**Comment by scabaa** [comment]
Just FYI I am using the docker version of this new release and I had to download rule.json separately to my config dir for this to work. I got "rule.json file missing" error before. But now its working like a charm

**Comment by JhonKnight** [comment]
does someone can help me ? 
![image](https://github.com/user-attachments/assets/90612a2f-296c-4bd6-bc42-a5a03a9fc5ef)

**Comment by melithine** [comment]
Please elaborate what help you need beyond following those instructions.
