### ISSUE TITLE
Constantly being logged out

### ISSUE THREAD

**Issue by 4DeepThought2** [sim0n00ps/OF-DL#398]
Anyone know of a way to prevent this?  I am logged out within 30-90 seconds of logging in.

Ive tried: 
- email login vs. google login
- different browers
- on vpn, off vpn

This obviously makes the tool impossible to use since the sess changes every time.

**Comment by 4DeepThought2** [comment]
Actually, interestingly it only logs me out when I have the dev console open.  If OF is html5, there is now the ability for sites to ruin certain actions when the dev console is open.  Looks like they might have a new method of trying to block people.

**Comment by melithine** [comment]
Try using the browser extension?

**Comment by 4DeepThought2** [comment]
Yep.  Using that as well.  I logged out of all browsers, deleted cache in all browsers, closed them all, waited about 30 mins and now its working fine.  Certainly some sort of rate limiter on their side.
