### ISSUE TITLE
Stuck at 99% download after hitting DRM video?

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#4]
okay so everything is configured correctly, Everything has been downloaded perfectly, however it seems to be the downloading got stuck at 99% so far at the time of writing this post it's been 15 minutes. as first noticed at 10pm so 

how long should I let this go for?
if I had to cancel and restart will it download duplicates of the same files or just the files that haven't been downloaded?

![image_2023-05-06_221817400](https://user-images.githubusercontent.com/59564520/236654224-761cfe00-2415-415a-b207-b06f18dbaf9b.png)

**Comment by sim0n00ps** [comment]
Latest release should fix this
