### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by hebeebee** [sim0n00ps/OF-DL#402]
I have filled in the correct information, but it still cannot be used.
<img width="726" alt="2024-06-12 231448" src="https://github.com/sim0n00ps/OF-DL/assets/137584090/45dd5cf1-7b45-44d4-b8ae-1ac0f8ff9550">
<img width="321" alt="2024-06-12 231533" src="https://github.com/sim0n00ps/OF-DL/assets/137584090/09177550-0629-4993-ab45-1c64b0fe8b77">

**Comment by jcg9129** [comment]
The file linked by the `DYNAMIC_RULES` url constant was deleted.

**Comment by hebeebee** [comment]
> The file linked by the `DYNAMIC_RULES` url constant was deleted.



> The file linked by the `DYNAMIC_RULES` url constant was deleted.

I didn't delete any files, how can I solve this problem?

**Comment by legendaryredfox** [comment]
> > The file linked by the `DYNAMIC_RULES` url constant was deleted.
> 
> > The file linked by the `DYNAMIC_RULES` url constant was deleted.
> 
> I didn't delete any files, how can I solve this problem?

The file was stored in github and the repo got taken down. you can either replace `rules.json` file and build the project yourself using Visual Studio and .net 7 or wait for the next release, which I guess it shouldn't take long

**Comment by hebeebee** [comment]
> The file was stored in github and the repo got taken down. you can either replace `rules.json` file and build the project yourself using Visual Studio and .net 7 or wait for the next release, which I guess it shouldn't take long
 
I don’t know how to build it, I can only wait for the latest release.

**Comment by legendaryredfox** [comment]
> > The file was stored in github and the repo got taken down. you can either replace `rules.json` file and build the project yourself using Visual Studio and .net 7 or wait for the next release, which I guess it shouldn't take long
> 
> I don’t know how to build it, I can only wait for the latest release.

It's relatively easy, just download Visual Studio (not code) and .net 7, both available for free, open the project on visual studio and press ctrl + shift + b. it should be available under the bin folder inside the cloned repo

**Comment by hebeebee** [comment]
> It's relatively easy, just download Visual Studio (not code) and .net 7, both available for free, open the project on visual studio and press ctrl + shift + b. it should be available under the bin folder inside the cloned repo

Ok, I will try, thanks

**Comment by zevlas** [comment]
Will OF-DRM get the fix too?

**Comment by sim0n00ps** [comment]
If you use the latest version this is now fixed
