### ISSUE TITLE
[REQUEST] Ability to download individual messages

### ISSUE THREAD

**Issue by myacct123** [sim0n00ps/OF-DL#410]
Would it be possible to pull the content from individual messages? This would be similar to the download single post feature.

Message URLs are in the format https://onlyfans.com/my/chats/chat/{id}/?firstId={anotherid}

You can click 'more' on a message and copy the URL

**Comment by thatcoderguy** [comment]
Where did you get that URL from?  I can only seem to find something like: https://onlyfans.com/api2/v2/messages/{MESSAGEID}
And even that wasn't easy to find.

**Comment by myacct123** [comment]
> Where did you get that URL from? I can only seem to find something like: [https://onlyfans.com/api2/v2/messages/{MESSAGEID}](https://onlyfans.com/api2/v2/messages/%7BMESSAGEID%7D) And even that wasn't easy to find.
Copy button 
![image](https://github.com/sim0n00ps/OF-DL/assets/172576956/4cb9da54-47a6-40f1-99f9-b118c71542c9)

**Comment by sim0n00ps** [comment]
Yes this would be possible and something I wanted to do as well

**Comment by thatcoderguy** [comment]
I dont mind writing this feature - but "copy" only seems to copy the content, not a link. I can get a link to the direct message by inspecting the network traffic in the browser... but I'm assuming this is a bit more "advanced" for typical users?
If you guys give me an indication of how you can easily get the message ID, I'll run with that - otherwise I'll just assume the URL [https://onlyfans.com/api2/v2/messages/{MESSAGEID}](https://onlyfans.com/api2/v2/messages/%7BMESSAGEID%7D)

**Comment by sim0n00ps** [comment]
I know what you can append ?firstId to the query string and it will show you that specific message first in the list, not totally sure if it's possible to copy the link the same as a post, but if you think you can do it go for it, just base it off the download single post feature

**Comment by pikatwinky** [comment]
@thatcoderguy In the main window of OF, there is this tab where you can view all the content you have bought at the moment (from both post and messages), is in this tab where you can copy the link to the paid message

**Comment by thatcoderguy** [comment]
@pikatwinky   I'm quite new to OF... can you put a screenshot of where this is?

**Comment by melithine** [comment]
> @pikatwinky I'm quite new to OF... can you put a screenshot of where this is?

![Screenshot_20240624_031023](https://github.com/sim0n00ps/OF-DL/assets/149995425/c6114bbb-654d-497a-a423-bf784c756257)

**Comment by thatcoderguy** [comment]
@myacct123  @melithine   can we assume this feature will be for paid messages?  I've started writing, and I'm going to assume people will obtain the message link via the paid tab...

**Comment by sim0n00ps** [comment]
> @myacct123  @melithine   can we assume this feature will be for paid messages?  I've started writing, and I'm going to assume people will obtain the message link via the paid tab...

Do it for Paid Messages first and we'll go from that point

**Comment by melithine** [comment]
This has been released, closing.

**Comment by papishampooo** [comment]
> I dont mind writing this feature - but "copy" only seems to copy the content, not a link. I can get a link to the direct message by inspecting the network traffic in the browser... but I'm assuming this is a bit more "advanced" for typical users? If you guys give me an indication of how you can easily get the message ID, I'll run with that - otherwise I'll just assume the URL [https://onlyfans.com/api2/v2/messages/{MESSAGEID}](https://onlyfans.com/api2/v2/messages/%7BMESSAGEID%7D)

im having this issue too, a creator sent me 2 videos via DM and the scraper doesn't get to them, any more info on this? can you show me how inspect the network traffic in the browser to get a direct link for the video? do I have to click play then try to locate it in the network browser?
