### ISSUE TITLE
An error occurred while downloading

### ISSUE THREAD

**Issue by hojotis** [sim0n00ps/OF-DL#411]
An error occurred:  Received an unexpected EOF or 0 b

**Comment by thatcoderguy** [comment]
Can you share a copy of the log file?  or even a screenshot

**Comment by melithine** [comment]
That seems like a one off transient error, as it doesn't appear it stopped downloading afterwards.

**Comment by hojotis** [comment]
This happens often now, and the download speed is very slow

**Comment by melithine** [comment]
Nothing changed on our side except the location of the rules.json file. Sounds like a networking issue of some kind, or you're getting rate limited. If using a VPN, try direct, and vice versa.

**Comment by hojotis** [comment]
![QQ截图20240618124123](https://github.com/sim0n00ps/OF-DL/assets/113195193/97659055-3cbd-484a-8316-43cec9a0b6a2)
Pictures can be downloaded normally, but videos are incomplete and cannot be downloaded normally.

**Comment by melithine** [comment]
My previous advice still stands.
