### ISSUE TITLE
auth.json failure

### ISSUE THREAD

**Issue by veezeeee** [sim0n00ps/OF-DL#413]
![of-dl](https://github.com/sim0n00ps/OF-DL/assets/172773001/2fb1bc51-76fd-48f7-9310-cbacad13d014)

I'm using OF.DL.V1.7.59 rn & the OF-DL keeps bringing up this error.
I installed the browser extesnsion & copied the given auth.json to see if it would fix this but its bringing up the same error
I've looked through the other issues to try & figure it out myself but I don't fully understand them,
I've seen 'Use Local Copy of dynamic rules JSON' but I got no clue what to do from the coding info 
I've also tried it on different browsers but still no luck.

**Comment by melithine** [comment]
You need 1.7.60 now.

**Comment by veezeeee** [comment]
> You need 1.7.60 now.

I downloaded OF.DLV1.7.60 & its bringing up the same error

**Comment by veezeeee** [comment]
thru some trial 'n' error, i've managed to get it working now :)
if there's further issues, i'll reach out
