### ISSUE TITLE
General sorting question

### ISSUE THREAD

**Issue by SkylineRcr** [sim0n00ps/OF-DL#416]
Is there a way to have all of the content for one user be in one single folder instead of being under multiple folders under the same user. Like everything in the main folder instead of the posts, messages, avatars, header folders?

**Comment by Astercholik** [comment]
Cool idea to have photos downloaded for photos and videos for videos.

**Comment by melithine** [comment]
https://github.com/sim0n00ps/OF-DL/issues/296 is the request for that, closing as a duplicate.
