### ISSUE TITLE
Queries on what is inside "user_data" 

### ISSUE THREAD

**Issue by ikuiku992** [sim0n00ps/OF-DL#420]
Hi there, out of curiosity

May i know what can i view inside the metadata folder inside each creator's folder after scrapping?

**Comment by melithine** [comment]
The history of what you've downloaded so it doesn't redownload the same content. If you remove that, it will redownload things.

**Comment by melithine** [comment]
If you're asking how to look at it, it's a SQLite database, so tools for that should do the trick.
