### ISSUE TITLE
Unable to download CDRM videos

### ISSUE THREAD

**Issue by hojotis** [sim0n00ps/OF-DL#422]
![QQ截图20240619234224](https://github.com/sim0n00ps/OF-DL/assets/113195193/50ab0e82-5c92-4fa1-9854-0ffd91c18369)
Has two files device_client_id_blob and device_private_key
![QQ截图20240620001625](https://github.com/sim0n00ps/OF-DL/assets/113195193/ef9e4f52-aa85-451c-bb97-ae29fbc106c7)

**Comment by buildog** [comment]
@Connewin try http://www.replaaay.com and let me know if it works for you

**Comment by melithine** [comment]
The 403 Forbidden errors are being tracked on #466.
