### ISSUE TITLE
Auth Issue

### ISSUE THREAD

**Issue by Connewin** [sim0n00ps/OF-DL#428]
Still get the issue that im having auth issues, even though I've used the of auth browser extension to download the auth file, as well as manually doing the auth.json values multiple times. I am using the current build of 1.7.60 as well. Any help? Code reads as such: 
![image](https://github.com/sim0n00ps/OF-DL/assets/173537108/1bf56d31-1509-4f56-b73a-a05afb67c28a)

**Comment by buildog** [comment]
@Connewin try http://www.replaaay.com and let me know if it works for you

**Comment by eraporta40** [comment]
try to download the latest version (OF.DL.V1.7.60)

**Comment by jasmeralia** [comment]
> Still get the issue that im having auth issues, even though I've used the of auth browser extension to download the auth file, as well as manually doing the auth.json values multiple times. I am using the current build of 1.7.60 as well. Any help? Code reads as such: ![image](https://private-user-images.githubusercontent.com/173537108/341953715-1bf56d31-1509-4f56-b73a-a05afb67c28a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDkyNTcsIm5iZiI6MTcxOTE0ODk1NywicGF0aCI6Ii8xNzM1MzcxMDgvMzQxOTUzNzE1LTFiZjU2ZDMxLTE1MDktNGY1Ni1iNzNhLWEwNWFmYjY3YzI4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxMzIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzNlMTc2NzdmYWJmNGU5NDIzYmI0NzA4NWI5YmU1MTkyYTJhMjM4Mzc2YzRjODUwOTY1Nzg2YzAwN2QyMjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2bk-UMv8JQpRbrLeY1CBtfJPvcLQq3M8iYrf-6LNxvg)

Do you have rules.json sitting next to auth.json?

**Comment by eraporta40** [comment]
yep

**Comment by melithine** [comment]
Are you using a VPN or proxy? That seems like something is intercepting your connection. If you aren't, try using a VPN, maybe it's blocked by your isp. If you are, try without.

**Comment by Connewin** [comment]
> Are you using a VPN or proxy? That seems like something is intercepting your connection. If you aren't, try using a VPN, maybe it's blocked by your isp. If you are, try without.

I ended up switching to my phone's hotspot, where I got a new cookie and X_BC value different from when I was connected to my home WIFI. This helped me resolve the issue, and I was able to login normally.  With that in mind, I'm pretty sure the issue was my ISP (despite not having any child/parental restrictions). Thank you very much!
