### ISSUE TITLE
An error occurred: Response status code does not indicate succes 403 Forbidden 

### ISSUE THREAD

**Issue by ronaldvdonald** [sim0n00ps/OF-DL#429]
worked the first time, now keep getting "An error occurred: Response status code does not indicate success 403 Forbidden "

**Comment by buildog** [comment]
Authentication issue, https://www.replaaay.com still works so I guess it's a conifugration on your side as we share the same dynamic rules

**Comment by guarded1** [comment]
I'm getting the same issue, and I followed the tutorial exactly

**Comment by buildog** [comment]
Again, test it on Replaaay and if it fail it's because of OF and this repo will need a fix (and Replaaay as well) but happy to work on both

**Comment by guarded1** [comment]
It seems to be an issue with a VPN.  I was using express vpn, and the earlier builds of this program didn't work with that vpn.  When I changed to a different VPN to PIA, the program starting working fine.  Only I can't just download individual videos, it seems to be set to download all from a particular page

**Comment by guarded1** [comment]
I double checked with the newest version of OF DRM also.  My VPN was the problem.  Once I switched to a PIA, both programs run perfectly with no errors
