### ISSUE TITLE
Error Scraping

### ISSUE THREAD

**Issue by MillerTimeJones** [sim0n00ps/OF-DL#43]
I have been getting this with some models accounts and it ends up not downloading any of the files. (everything passed at beginning so no files missing)

![OF ERROR](https://github.com/sim0n00ps/OF-DL/assets/110180406/f36c706a-9265-4d52-a44c-f5396cb22215)

I noticed this error as well not sure if related or seperate issue

![OF ERROR ALT](https://github.com/sim0n00ps/OF-DL/assets/110180406/2c5b920b-3adb-4bd1-b369-a84a7feef4d6)

**Comment by sim0n00ps** [comment]
Probably down to you being rate limited. Nothing I can do about that, I have implemented it sending requests in batches to get the total size of each scrape but can sometimes still hit the limit and then you get these errors. Nothing more I can do really.

**Comment by MillerTimeJones** [comment]
> Probably down to you being rate limited. Nothing I can do about that, I have implemented it sending requests in batches to get the total size of each scrape but can sometimes still hit the limit and then you get these errors. Nothing more I can do really.


Rate limited doesn't make any sense.

example 10 profiles first 2 come up with this error the other 8 are fine remove log etc to try redownload those two failed profiles again only those two fail each time the others are fine.

is the second error related to first?

I would like to thank you for the program and hard work put into it don't want to come across as someone just moaning.
