### ISSUE TITLE
exception in paid post

### ISSUE THREAD

**Issue by btiplitz** [sim0n00ps/OF-DL#431]
Getting Paid Posts
Exception caught: Specified cast is not valid.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPaidPosts(String endpoint, String folder, String username, IDownloadConfig config, List`1 paid_post_ids)
Found 0 Paid Posts

This is my first time running this code and it's downloading other things.  I'm not sure what else I can capture to help debug this

**Comment by thatcoderguy** [comment]
Could you post a copy of your log file, or a screenshot please?

**Comment by Fishcake21** [comment]
I am getting similiar issues with not just paid but also regular posts. Though the error is different, I noticed this happening this week so I am wondering if something has changed.  These are all DRM videos and randomly works with some and others no.

Exception caught: Response status code does not indicate success: 403 (Forbidden).

                   StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDRMMPDPSSH(String mpdUrl, String policy, String signature, String kvp)
Exception caught: Response status code does not indicate success: 403 (Forbidden).

                                                                                  StackTrace:    at System.Net.Http.HttpResponseMessage.

**Comment by btiplitz** [comment]
[OFDL20240623.txt](https://github.com/user-attachments/files/15963098/OFDL20240623.txt)

not sure if the error matches, but this is yesterday's entire log file

**Comment by melithine** [comment]
That looks like some bad data getting sent to ffmpeg, or ffmpeg having a problem. Maybe try an older version of ffmpeg? I'm on 7.0, not 7.0.1 and I haven't seen this, although lately I've just been running it in Docker.

**Comment by urbanessays** [comment]
I was running for a while, and now I'm getting the same error. I've updated the ffmpeg version as recommended, but still getting the error. 
[OFDL20240821.zip](https://github.com/user-attachments/files/16694518/OFDL20240821.zip)

**Comment by urbanessays** [comment]
After updating to [1.7.74](https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.74) issue is fixed!
