### ISSUE TITLE
Since yesterday, the plugin cannot find X_BC any more...

### ISSUE THREAD

**Issue by peddanet** [sim0n00ps/OF-DL#433]
Did they remove it? Obviously I found out because my session data was outdated again...

I am using Ubuntu22.04 with firefox, cache cleared as well as cookies, VPN activated or deactivated, freshly restarted...

Any help? Manually I didn't manage to find it either....

**Comment by melithine** [comment]
https://github.com/whimsical-c4lic0/OF-DL-Auth-Helper/ is where to report issues with the browser extension. I just tested it under Chrome and it's fine for me. Remember you need to refresh the page and let it fully load before trying to access the extension.

**Comment by peddanet** [comment]
> https://github.com/whimsical-c4lic0/OF-DL-Auth-Helper/ is where to report issues with the browser extension. I just tested it under Chrome and it's fine for me. Remember you need to refresh the page and let it fully load before trying to access the extension.

Good god! You have Karma, nopsw it worked again, after 24 h!! Maybe I shouild not download a video or play it at the same time???

But I have lags in loading the of page, if I remember correctly, very often....Could they limit you in any thing? If using vpn which country shall I prefer over the others??

**Comment by peddanet** [comment]
But  OF DL just says its incorrect!!! Cause I  ran repeatedly into this issue, and I obeyed all steps of your tutorial (I am using this little helper since at least 1 or two years flawlessly!!)....IS anybody facing issues like me on al inux with cyberghost vpn??


What can be the cause else?? The stack trace is like this:
```
StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams) in /home/peddanet/Projects/OF-DL-OFDLV1.7.59/OF DL/Helpers/APIHelper.cs:line 58
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint) in /home/peddanet/Projects/OF-DL-OFDLV1.7.59/OF DL/Helpers/APIHelper.cs:line 103
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint) in /home/peddanet/Projects/OF-DL-OFDLV1.7.59/OF DL/Helpers/APIHelper.cs:line 213
Auth failed, please check the values in auth.json are correct.

If you have previously been able to auth successfully, the most likely cause of 
this is that your browser has updated, which will change the values of the 
USER_AGENT string. The version change to this string is usually very minor and 
easy to overlook, but even a slight difference will cause an authentication 
failure.

If you are struggling to authenticate, you may want to try the browser extension
which is documented here:

https://of-dl.gitbook.io/of-dl/auth#browser-extension

Press any key to exit
```

**Comment by thatcoderguy** [comment]
You need to upgrade to 1.7.60 - that has the auth fix.

**Comment by peddanet** [comment]
@thatcoderguy  It seems a fight against onlyfans, they try to change everyday things to prevent from downloading? Could it?

**Comment by melithine** [comment]
1.7.60 was like a week or two back. But yes they do try to fight scraping, so it's a good idea to keep tabs on new releases. You can do a custom notification on the github repo to get notified of new releases.

![Screenshot_20240624_070740_Chrome](https://github.com/sim0n00ps/OF-DL/assets/149995425/59430812-28ca-4bd0-bd76-86afc6e88659)

**Comment by peddanet** [comment]
@melithine I did! Thanks again!
@thatcoderguy  Is it necessary to give  the path to ffmpeg and so on? Because this is skipped in the plugin?

I mean the pathes to these 3 tools:
```
   "YTDLP_PATH": "/usr/local/bin/yt-dlp_linux",
   "FFMPEG_PATH": "/usr/bin/ffmpeg",
   "MP4DECRYPT_PATH": "/usr/local/bin/mp4decrypt"
```

**Comment by peddanet** [comment]
And last question, do we have a good description drm protected content how to create that blob or private key correctly ?

**Comment by melithine** [comment]
Ytdlp and mp4decrypt are not used anymore. Ffmpeg path can be set in config.json, it no longer needs to be in auth.json. For the cdm keys, it's a complex process (thankfully a one-and-done one), but if you're using Linux you probably have the chops for it. https://of-dl.gitbook.io/of-dl/requirements has the notes about it.

**Comment by peddanet** [comment]
> Ytdlp and mp4decrypt are not used anymore. Ffmpeg path can be set in config.json, it no longer needs to be in auth.json. For the cdm keys, it's a complex process (thankfully a one-and-done one), but if you're using Linux you probably have the chops for it. https://of-dl.gitbook.io/of-dl/requirements has the notes about it.

Let me know if I can help (financially) or with coding ( guess I can develop software, but I am a bit far from the topic of security, but interested). If you need a cleaning "wife"....

**Comment by peddanet** [comment]
@melithine 
I guess, you need somehow a nice app for handling your data base. SO that you can use your downloads as an offline private only fans.... so navigating looking for keywords something like this...
