### ISSUE TITLE
[REQUEST] Ability to download non-paid media in messages

### ISSUE THREAD

**Issue by charlieorwell** [sim0n00ps/OF-DL#441]
would it be possible to scrape content from messages that's non-paid? I just recently tried out the 'download purchased tab' feature and it worked great but there's one specific user that i was after who is deleted and it only had one file in there when i know for sure i received more but it might have been as a normal sent message and not purchased.

**Comment by melithine** [comment]
Once a user is deleted, I believe the only thing that OF preserves is your purchases from that user. I think the rest is simply not there for us to scrape.

**Comment by charlieorwell** [comment]
Ahh that's a shame then, sucks so bad. I had a HDD with a bunch of saved content on there but it died recently and not sure it's worth taking to a data recovery spot for it

**Comment by sim0n00ps** [comment]
I did make the Scrape Purchased tab work with deleted users, it should create a folder "Deleted User - {UserID}"

**Comment by melithine** [comment]
Yeah, PPV unlocks should be safe permanently and work with the purchased tab. But if you had say tipped $20 and then the creator messaged you the content, or there was a goal that was reached and then they sent it out, I believe that disappears when the user is deleted.

**Comment by charlieorwell** [comment]
> I did make the Scrape Purchased tab work with deleted users, it should create a folder "Deleted User - {UserID}"

Yeah no that tab worked great! 
It's more what melithine said, I had tipped and then the content was sent. Sucks that that content is just lost to the ether now but can't dwell on it too much. 
Thanks for making such a great and easy to use tool! :)
