### ISSUE TITLE
Getting error ' FFmpeg failed to download'

### ISSUE THREAD

**Issue by banjobbw** [sim0n00ps/OF-DL#442]
Hi I'm seeing plenty of errors with the last two released versions, OF.DL.V1.7.61 and  OF.DL.V1.7.60

```
FFmpeg failed to download https://cdn3.onlyfans.com/dash/files/0/0c/0c36961b2e25dc1426e044fc04878125/0hqoggvatttnygduoej1r.mpd
Exception caught: Could not find file 'K:\RooT\P2024APRIL\!!!!!OF\OF.DL.V1.7.61\__user_data__\sites\OnlyFans\nikkigotti0\Posts\Free\Videos\0hqoggvatttnygduoej1r_source.mp4'.
```

Any help would be really appreciated

**Comment by melithine** [comment]
Do you have rules.json sitting next to ofdl.exe? If you do, try a different ffmpeg version.

**Comment by bezaaas** [comment]
What do you mean "try a different ffmpeg version" ? i'm using the latest ffmpeg, DRM videos are downloaded fine, but some videos are not.
