### ISSUE TITLE
Different media in a single package is not downloaded correctly.

### ISSUE THREAD

**Issue by MrLast98** [sim0n00ps/OF-DL#445]
While scrapping, i noticed that for messages sent by creators, if they bundle a few pics and then a few videos, it will download only the pictures and not the videos following it.

**Comment by thatcoderguy** [comment]
You mean if they add videos at a later point? Or if they send the pics & videos at the same time?

**Comment by MrLast98** [comment]
@thatcoderguy i received via DMs a single send with both pictures and images in the same message at the same time.
The images are downloaded correctly, the 3 videos are nowhere to be found. I ran the DL multiple times to no luck, it says everything was downloaded.

**Comment by MrLast98** [comment]
Whops. misslick.
I received a single DM with both images and videos in the same send, but it only downloaded the images, not the videos.
Same message, same time.

**Comment by whimsical-c4lic0** [comment]
Is "DownloadVideos" set to true in your config.json?

**Comment by thatcoderguy** [comment]
ok, I got to the bottom of this (I think)... the software does see all of the videos & photos in a message - but if any of those photos or videos are in the creators main media (the free stuff), then it wont download them again, because they have the same media_id

**Comment by MrLast98** [comment]
Oh, perfect. Thanks for the info, sorry for the necrobump
