### ISSUE TITLE
Unlocked/Free messages not downloading from messages

### ISSUE THREAD

**Issue by fastbrick** [sim0n00ps/OF-DL#447]
It doesn't happen on every account but on certain ones the "free" messages in the DM do not download for the creator. There isn't even a FREE folder created. Any ideas to the cause of this?
![issue](https://github.com/sim0n00ps/OF-DL/assets/174265622/bc1aefd3-d5d7-4d53-98ba-721bbd6964bd)
![issues2](https://github.com/sim0n00ps/OF-DL/assets/174265622/95a7e26c-6378-454c-8ae6-90fe85424f20)

**Comment by fastbrick** [comment]
![issue](https://github.com/sim0n00ps/OF-DL/assets/174265622/8043189a-ab00-4935-88c5-e6bff1747c0d)

**Comment by thatcoderguy** [comment]
Can you supply a copy of your log file?

**Comment by fastbrick** [comment]
I tried more than once but here is the log

2024-06-29 11:47:34.137 -05:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)
2024-06-29 12:35:39.130 -05:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)
2024-06-29 12:59:03.523 -05:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)
2024-06-29 13:58:58.536 -05:00 [ERR] ffmpeg version 2023-06-08-git-024c30aa3b-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 12.100 / 58. 12.100
  libavcodec     60. 17.100 / 60. 17.100
  libavformat    60.  6.100 / 60.  6.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  8.101 /  9.  8.101
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Unrecognized option '->\n\n\n'.
Error splitting the argument list: Option not found

2024-06-29 13:58:58.541 -05:00 [ERR] Exception caught: Could not find file 'F:\__user_data__\sites\OnlyFans\labellatl\Posts\Free\Videos\0hqz4pb9qvf13mndmbsht_source.mp4'.

StackTrace:    at System.IO.FileInfo.get_Length()
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String policy, String signature, String kvp, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, ProgressTask task, String filenameFormat, List postInfo, Medium postMedia, Author author, Dictionary`2 users)
2024-06-29 15:49:10.559 -05:00 [ERR] Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)

**Comment by fastbrick** [comment]
Anyone have any ideas? Thank you.

**Comment by thatcoderguy** [comment]
To be honest, there's no much info to go by... there will be a new release shortly, and it will have much better logging so that we can investigate issues like thus.

**Comment by fastbrick** [comment]
Ok, thank you!

**Comment by melithine** [comment]
> Ok, thank you!

The new release is out now.

**Comment by fastbrick** [comment]
I tried it and having same issues as someone mentioned in discord. It says scrape complete but folder is empty. Waiting to see what the replies are there for it.

**Comment by melithine** [comment]
Ok, so try changing the logging level (either verbose or debug) and attach the log file here so we can see if it helps us uncover what's going on.

**Comment by deadbeatdandylyon** [comment]
I believe I am having a similar issue there is a Free account that I subscribed to and the person sent out a Unlocked message containing about 40 video clips, however when I run the scrap its only coming back with two of the 40 videos, I have the latest version of the scraper and I deleted the metadata folder and ran it again and the same issue occurs

**Comment by melithine** [comment]
Please send a debug log and we'll review it.

**Comment by fastbrick** [comment]
Just wanted to say the version 1.7.72 fixed whatever the issue was. It now downloaded all content. I have not tried 1.7.74 yet to make sure it still works.
