### ISSUE TITLE
Convert string to Integer error when running

### ISSUE THREAD

**Issue by purpleemoji** [sim0n00ps/OF-DL#45]
I have been using for weeks and never had an issue and this started all of a sudden this morning.
This happens after login but before retrieving my subscriptions. All cookie information is correct.

![Screenshot 2023-06-24 072600](https://github.com/sim0n00ps/OF-DL/assets/83528088/d8d75d0c-6298-487e-a4d2-8494ee9cfd74)

**Comment by sim0n00ps** [comment]
Update to the latest release.

**Comment by purpleemoji** [comment]
Oh my fault. I'll try the latest release. 
Thanks for all your hard work. Do you have a ko-fi to accept donations?

**Comment by sim0n00ps** [comment]
I will add the ko-fi link to the bottom of the readme. Let me know how you get on with the latest release.

**Comment by purpleemoji** [comment]
hey it worked great with the latest release. thanks
