### ISSUE TITLE
Longer videos not downloading in full?

### ISSUE THREAD

**Issue by DLOI125** [sim0n00ps/OF-DL#450]
Hi there, massive fan of this build and appreciate how you keep it up-to-date. Noticed an issue when I try and download DRM enabled content over about 12+ minutes that the full video doesn't download, only the first third or so. Is this a common issue? Doesn't look like one reported yet at a brief glance of the Issues tab. Note that I'm using the "Download Single Post" function.

**Comment by melithine** [comment]
Any errors / anything in the logs?

**Comment by DLOI125** [comment]
> Any errors / anything in the logs?

I've just re-run the download on the video and my log file hasn't been updated, so assumedly no errors. Issue is persisting.

**Comment by Samu2u** [comment]
> Any errors / anything in the logs?

1.7.61 Same error
No error logs is generated

**Comment by KialSmith0069** [comment]
Iam facing the same issue as well, if it is one.  No error logs, no crashes no nothing. it just downloads like half of the DRM video and says download complete. I suspect it is the omission of the yt-dlp and mp4decrypt from the source casuing this issue

**Comment by melithine** [comment]
I have not seen this at all, and we dropped yt-dl/mp4decrypt some time ago. Can people here post what ffmpeg version you are using?

**Comment by DLOI125** [comment]
> I have not seen this at all, and we dropped yt-dl/mp4decrypt some time ago. Can people here post what ffmpeg version you are using? @thatcoderguy and I have been trying to reproduce it with my creator account.
> 
> My suspicion is it might be tied to #436, but that seems innocuous enough and might depend on the ffmpeg version being used.

Think my ffmpeg is v.7.0.1.

**Comment by KialSmith0069** [comment]
> I have not seen this at all, and we dropped yt-dl/mp4decrypt some time ago. Can people here post what ffmpeg version you are using? @thatcoderguy and I have been trying to reproduce it with my creator account.
> 
> My suspicion is it might be tied to #436, but that seems innocuous enough and might depend on the ffmpeg version being used.

Never had this problem until the recent updates. Even if it is the ffmpeg, what version of it should we be using?
p.s i updated my ffmpeg the same issue still persists

**Comment by Samu2u** [comment]
> I have not seen this at all, and we dropped yt-dl/mp4decrypt some time ago. Can people here post what ffmpeg version you are using? @thatcoderguy and I have been trying to reproduce it with my creator account.
> 
> My suspicion is it might be tied to #436, but that seems innocuous enough and might depend on the ffmpeg version being used.

I use ffmpeg version is 2024-06-21-git-d45e20c37b-full_build
I same got the full video using OF DRM V1.11, but OF DRM V1.11 can't download all the.
The download didn't generate any error logs.

**Comment by melithine** [comment]
Try updating to 1.7.67 and see if it persists. If it does, please change the logging level to debug and attach a log of a run after the level is updated.

**Comment by Samu2u** [comment]
> Try updating to 1.7.67 and see if it persists. If it does, please change the logging level to debug and attach a log of a run after the level is updated.

Version used 1.7.68

DRM enabled for Scraping account
Downloaded 3 videos, 1 long video (09:38) download error
Download error video name is 0hrh1pqrar196vav0wjvg

logs:
[OFDL20240724.txt](https://github.com/user-attachments/files/16353878/OFDL20240724.txt)

**Comment by melithine** [comment]
Are you still experiencing this? We've done a slew of changes since then, including some pretty large ones in the 1.7.75 release today.
