### ISSUE TITLE
Exception caught: Unable to parse license

### ISSUE THREAD

**Issue by booleangit** [sim0n00ps/OF-DL#452]
Since today I get an error regarding a license when trying to download DRM protected content. I've never seen this specific message before and I also haven't made any changes to the client id blob nor the key file. Any idea what is causing this?

![image](https://github.com/sim0n00ps/OF-DL/assets/25500731/a979483c-9b73-41eb-8d7c-563479c46500)

**Comment by melithine** [comment]
@sim0n00ps any idea what might have happened here? This is a new one to me.

**Comment by sim0n00ps** [comment]
I've seen it a few times before but not very often might be the odd request that fails, I wouldn't worry about it. It's more likely it was a server error rather than an error with the tool so deleting the DB probably didn't actually fix it.
