### ISSUE TITLE
Restricted users are skipped

### ISSUE THREAD

**Issue by thawinsor** [sim0n00ps/OF-DL#454]
A couple of days ago I resubscribed to an account I was previously subscribed too, but the account is not showing up.

- Verified that I'm running V1.7.61
- Removed users.db
- Logged out of OF, logged in again and used the new auth parameters
- Subscribed to another (new) user, which does show up in the list
- Account does not show up in the expired list either
- The account is also missing from the users.db, I've tried adding it manually but after startup it gets removed.

Next, I've tried building the latest version from source myself and enable the new debug logs feature.

- Account is present in the `GetAllSubscrptions` list
- Download purchased tab now works and creates the folder for that account too
- Account is still missing from the Custom list
- Account is not included when Select All is used

When checking the returned JSON I noticed this account is listed as restricted. I've enabled that in the config, restarted the app, but the account is still not showing up.

After going through the code, I think there's an issue in the if check when users are added. A closing bracket is missing after the first check, which results in the `includeRestricted` variable never being reached.

```diff
diff --git a/OF DL/Helpers/APIHelper.cs b/OF DL/Helpers/APIHelper.cs
index 221d143..b45a18f 100644
--- a/OF DL/Helpers/APIHelper.cs
+++ b/OF DL/Helpers/APIHelper.cs
@@ -310,9 +310,9 @@ public class APIHelper : IAPIHelper

             foreach (Subscriptions.List subscription in subscriptions.list)
             {
-
-                if ((!subscription.isRestricted ?? false || (subscription.isRestricted ?? false && includeRestricted))
-                    && !users.ContainsKey(subscription.username))
+                if ((!(subscription.isRestricted ?? false) ||
+                     ((subscription.isRestricted ?? false) && includeRestricted)) &&
+                    !users.ContainsKey(subscription.username))
                 {
                     users.Add(subscription.username, subscription.id);
                 }
```

**Comment by melithine** [comment]
Can you submit this as a PR?
