### ISSUE TITLE
Exception caught: Could not find file

### ISSUE THREAD

**Issue by topboysyp** [sim0n00ps/OF-DL#46]
OF.DL.V1.7.12
.NET runtime 7.0.5 x86
ffmpeg 2023-06-21 essentials
OS Windows 10 Enterprise LTSC 1809

I got a lot of this same warnings with different files. I have try re-runing the program but still get those warnings. Seems like the program just can't download those particular videos.

Exception caught: Could not find file 'D:\Program Files\OF DL\__user_data__\sites\OnlyFans\[the creator's account name]\Posts\Free\Videos\0hdif9pjsooq12s0sidin_source.mp4'.

 StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder

![001](https://github.com/sim0n00ps/OF-DL/assets/118795506/524d5588-2c21-493f-9ef4-d7cbb7a2db82)

**Comment by sim0n00ps** [comment]
Have you installed the C++ Redistributable packaged? If not head to https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 and download the C++ Redistributable Packages. This is needed to run mp4decrypt.exe so this is where it might be going wrong.

**Comment by topboysyp** [comment]
> 

I did install it. 

![001](https://github.com/sim0n00ps/OF-DL/assets/118795506/f77a1c32-cf33-4ba2-9db2-0e6732fe2ea7)

**Comment by sim0n00ps** [comment]
Is anything in the folder where the videos are meant to be?

**Comment by topboysyp** [comment]
> Is anything in the folder where the videos are meant to be?

Just videos downloaded by the program. Before that was nothing and all the folders were created by the program.

**Comment by topboysyp** [comment]
Well I deleted the "Metadata" folder under "D:\Program Files\OF DL\__user_data__\sites\OnlyFans\[the creator's account name]\" then re-running the program and everything works fine. No warnings and those missing videos were downloaded and decrypted.
