### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by funand6699** [sim0n00ps/OF-DL#461]
Hello, 

I'm getting this error message when I choose "Download Purchased Tab" 
![image](https://github.com/sim0n00ps/OF-DL/assets/174956722/01f44fce-7b2e-43d9-a1c7-701b7739e407)

Thanks !

**Comment by thatcoderguy** [comment]
Can you post your config file?  I've a feeling I might know what this is... and the config would partially confirm

**Comment by funand6699** [comment]
There you go : 

{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": false,
  "IncludeRestrictedSubscriptions": false,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": null,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "after",
  "CustomDate": "",
  "ShowScrapeSize": false,
  "DownloadPostsIncrementally": false,
  "FFmpegPath": "C:/Users/Ben/DL/OF.DL.V1.7.61/ffmpeg.exe",
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "BypassContentForCreatorsWhoNoLongerExist": false,
  "DownloadDuplicatedMedia": false
}

**Comment by thatcoderguy** [comment]
Try setting 

BypassContentForCreatorsWhoNoLongerExist

To true

If that works, I know where the bug is.

**Comment by funand6699** [comment]
It does work ! Thank you 

So what is the bug ?

**Comment by thatcoderguy** [comment]
Unfortunately it's where I made a change to be able to handle creators who deleted their account (which was causing another bug).

Thankfully I can do a very easy fix... but might have to come up with a longer term fix to handle both scenarios properly.
