### ISSUE TITLE
"Unable to read data from the transport connection: Interruption has been forced"

### ISSUE THREAD

**Issue by JohnMascript** [sim0n00ps/OF-DL#462]
What does it mean? Files aren't downloading fully. How may I able to go about fixing it?
![of dwl](https://github.com/sim0n00ps/OF-DL/assets/174824821/461a316f-ea47-42b8-8f09-225cb12ceded)

**Comment by melithine** [comment]
I'm not familiar with that error, but I suspect that it may be phrased differently in English. My best guess is either antivirus/antimalware is interfering.

**Comment by JohnMascript** [comment]
Thank you very much for your answer! not to tech savy here. Any pointers on how to configure my firewall not to interfere?

**Comment by melithine** [comment]
Sorry, I have no idea, it would depend on the software you're using and I've never seen that kind of behavior before.
