### ISSUE TITLE
feature request, BLACKLIST

### ISSUE THREAD

**Issue by butzen0** [sim0n00ps/OF-DL#464]
~add blacklist function~

As a user, I want the ability to exclude a list of accounts so that I can conserve storage space from being consumed by certain high-volume accounts I am not interested in and scrape all other active subscriptions instead.

**Comment by melithine** [comment]
Elaborated on request that originated from Discord.

**Comment by stranger-danger-zamu** [comment]
A work-around I found is creating a collection on the site that contains just the accounts that are of interest. Then selecting List and then the collection you made with the relevant accounts.

**Comment by melithine** [comment]
That is what I had suggested on Discord, but I can see the potential value in this support as well.

**Comment by butzen0** [comment]
My problem is that I only subscribe for 1 month and I keep switching profiles, I only get promos, and it would be very useful to just restrict some profiles, like suicidegirls, which I once downloaded by accident, and it's more than 1TB

**Comment by whimsical-c4lic0** [comment]
The `IgnoreUsersListName` config option was just added in v1.7.70 (see [the docs](https://sim0n00ps.github.io/OF-DL/docs/config/configuration#ignoreduserslistname) for more information)
