### ISSUE TITLE
Auth fail

### ISSUE THREAD

**Issue by rdonadono** [sim0n00ps/OF-DL#465]
Hi,

I use the tag version OFDLV1.7.59
I built the docker image from this source.

Before updating I had no problem, now instead even using the browser extension to retrieve the configuration parameters I always get this error.

![of-dl](https://github.com/sim0n00ps/OF-DL/assets/323353/48852c6e-2f2b-40e3-8fd2-14703a0085ce)

I also rechecked by hand the data being written by the extension into auth.json and it is correct.

In case I need to use the later version, i.e. OFDLV1.7.61, I also get the missing rules.json file error.

I have searched the documentation but can't find anything about the rules.json file, where can I retrieve an example of the content?

Thanks!

**Comment by melithine** [comment]
You do need 1.7.60+ and the `rules.json` can be found in the release ZIP file or here: https://github.com/sim0n00ps/OF-DL/blob/master/OF%20DL/rules.json (this will likely be moved in the future as a heads up).

You don't have to build the Docker image manually anymore, btw, we publish them on GHCR here: https://github.com/sim0n00ps/OF-DL/pkgs/container/of-dl

**Comment by rdonadono** [comment]
Okay, now it's working!

Thank you!
