### ISSUE TITLE
Post Scraping Failing (Object reference not set to an instance of an object)

### ISSUE THREAD

**Issue by ViRGEdx** [sim0n00ps/OF-DL#468]
It looks like something has changed on the OF end to break post scraping of the most recent release of OF-DL. Attempting to scrape posts returns the same error regardless of the creator:

```
Exception caught: Object reference not set to an instance of an object.
StackTrace: at OF_DL.Helpers.APIHelper.GetPosts(String endpoint, String folder, IDownloadConfig config, List`1 paid_post_ids)
```

Notably, however, directly downloading a single post by providing its URL still works. So it would seem that OF-DL is having trouble building its internal list of posts.

Edit: Per @fendorix, the underlying issue is with the SkipAds feature. Disabling this seems to fix the issue (for now)

**Comment by lukaeber** [comment]
Having the same issue.

**Comment by GrimPrime** [comment]
As am I

**Comment by fendorix** [comment]
I've seen the same error. Can you try to set "SkipAds": false in your config.json? It seems to fail in there.

**Comment by FarmingCrops** [comment]
onlyfans have changed their api must have something to do with that should be fixed in the next update whenever that comes

**Comment by ViRGEdx** [comment]
> I've seen the same error. Can you try to set "SkipAds": false in your config.json? It seems to fail in there.

Thanks. Confirming that this bypasses the issue for now.

**Comment by bobby151037** [comment]
> I've seen the same error. Can you try to set "SkipAds": false in your config.json? It seems to fail in there.

I set "SkipAds" to false but now the program gets stuck on "Getting Posts" and has been for a while now. Is this an issue on my end or part of the problem?

**Comment by fendorix** [comment]
The bug is in APIHelper.cs line 934.

if (post.text != null && (post.text.Contains("#ad") || post.text.Contains("/trial/") || post.rawText.Contains("#announcement")))
should be changed to
if (post.text != null && (post.text.Contains("#ad") || post.text.Contains("/trial/") || post.text.Contains("#announcement")))

post.rawText is already handled in the previous statement and not checked for null here.

**Comment by sim0n00ps** [comment]
> The bug is in APIHelper.cs line 934.
> 
> if (post.text != null && (post.text.Contains("#ad") || post.text.Contains("/trial/") || post.rawText.Contains("#announcement")))
> should be changed to
> if (post.text != null && (post.text.Contains("#ad") || post.text.Contains("/trial/") || post.text.Contains("#announcement")))
> 
> post.rawText is already handled in the previous statement and not checked for null here.

Change has been made and released
