### ISSUE TITLE
Issue docker command

### ISSUE THREAD

**Issue by erosgaspardo** [sim0n00ps/OF-DL#469]
So I was trying to start OF-DL on my mac through Docker instead of relying on UTM and windows. When I paste the command ensuring that the volume "Users" is present in the file sharing menu, after downloading the requirements it returns this:

`docker: Error response from daemon: Mounts denied:
The path /{/Users} is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.`

I tried everything, so maybe someone here can help!
Thanks in advance!

**Comment by melithine** [comment]
Remove the `{` and `}`, those were meant to indicate what you needed to substitute, not taken literally. Also, you don't need file sharing enabled for this at all.
