### ISSUE TITLE
Suggestion manual video DL

### ISSUE THREAD

**Issue by 232344235342** [sim0n00ps/OF-DL#47]
So I tried the app, and it won't download custom videos from messages.
- It says it found 0

Instead of trying to trouble shoot this, could you please just mod the program so we can manually input the video url.
Then have the program remove the DRM from the video?

Update:
Re-running program, it claims to have found 4 messages (not sure about that) but cant dl any of them, 403 forbidden.
Literally only opened the app and done nothing else, so not sure why OF is blocking me?

**Comment by sim0n00ps** [comment]
Well if I wanted to do that then the whole program would have to change and I don't want to do that really. I am currently working on another tool which just focuses on DRM videos which will let you select which posts etc you want to download so this might be better suited to what you want to do.

**Comment by 232344235342** [comment]
Nice! looking forward to trying it
