### ISSUE TITLE
429 (Too Many Requests)

### ISSUE THREAD

**Issue by NotADeveloper323** [sim0n00ps/OF-DL#472]
I'm running the latest version, 1.7.67, although I have been running into this issue for the last several weeks. After running for 5-10 minutes, every request gets the following error. From what I read online, implementing a snooze/sleep function if the server response is 429 is one way to handle it, but I am not a developer and wouldn't know where to add that.

Once the error starts coming, the app continues to try to download every post, resulting in the same error appearing 100s of times. 

Exception caught: Response status code does not indicate success: 429 (Too Many Requests).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary`2 getParams, String endpoint, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetMessages(String endpoint, String folder, IDownloadConfig config)

**Comment by sim0n00ps** [comment]
Well if you're getting 429 errors that means you've been rate limited, I would just kill the app and wait a few hours before trying again

**Comment by NotADeveloper323** [comment]
That was my first thought as well. I tried giving it a few days in between running, but that hasn't helped either.

**Comment by melithine** [comment]
> That was my first thought as well. I tried giving it a few days in between running, but that hasn't helped either.

Are you using a VPN? If so, they may be rate limiting the VPN endpoint IP address. Try connecting directly or from a different location if that's the case.

**Comment by NotADeveloper323** [comment]
No VPN, just a Gig Fiber connection.

**Comment by NotADeveloper323** [comment]
Troubleshooting this further today, I noticed that if I am not providing my own device keys, meaning it's falling back to cdrm-project, it is no longer generating the 429 errors. But as soon as I put my own generated keys back in, it starts going too fast again.

**Comment by melithine** [comment]
Can you post your config.json?

**Comment by NotADeveloper323** [comment]
{
  "DownloadAvatarHeaderPhoto": true,
  "DownloadPaidPosts": true,
  "DownloadPosts": true,
  "DownloadArchived": true,
  "DownloadStreams": true,
  "DownloadStories": true,
  "DownloadHighlights": true,
  "DownloadMessages": true,
  "DownloadPaidMessages": true,
  "DownloadImages": true,
  "DownloadVideos": true,
  "DownloadAudios": true,
  "IncludeExpiredSubscriptions": true,
  "IncludeRestrictedSubscriptions": true,
  "SkipAds": false,
  "DownloadPath": "",
  "PaidPostFileNameFormat": "",
  "PostFileNameFormat": "",
  "PaidMessageFileNameFormat": "",
  "MessageFileNameFormat": "",
  "RenameExistingFilesWhenCustomFormatIsSelected": false,
  "Timeout": -1,
  "FolderPerPaidPost": false,
  "FolderPerPost": false,
  "FolderPerPaidMessage": false,
  "FolderPerMessage": false,
  "LimitDownloadRate": false,
  "DownloadLimitInMbPerSec": 4,
  "DownloadOnlySpecificDates": false,
  "DownloadDateSelection": "before",
  "CustomDate": null,
  "ShowScrapeSize": true,
  "DownloadPostsIncrementally": false,
  "NonInteractiveMode": false,
  "NonInteractiveModeListName": "",
  "NonInteractiveModePurchasedTab": false,
  "FFmpegPath": "C:/ffmpeg/bin/ffmpeg.exe",
  "BypassContentForCreatorsWhoNoLongerExist": false,
  "CreatorConfigs": {},
  "DownloadDuplicatedMedia": false,
  "LoggingLevel": "Error"
}

**Comment by melithine** [comment]
Try setting `LimitDownloadRate` to `true`.
