### ISSUE TITLE
Cannot locate ffmpeg;

### ISSUE THREAD

**Issue by CeciliaWeb** [sim0n00ps/OF-DL#473]
I am trying to run OF-DL in a docker container but I keep getting a "Cannot locate ffmpeg; please modify config.json with correct path" I have placed the path of ffmpeg.exe in my config.json but it still gives me the same error. I am running on macos.

**Comment by melithine** [comment]
When using OFDL in Docker, `FFmpegPath` needs to be pointed at where ffmpeg is inside Docker, which is `/usr/bin/ffmpeg`. Not at a Windows executable under your MacOS host system.
