### ISSUE TITLE
Text not populating for posts

### ISSUE THREAD

**Issue by richardjdunn** [sim0n00ps/OF-DL#475]
In the last few days, when downloading posts the "text" field is not populating in the database, it just remains blank.  Everything else seems to populate fine, including text of messages

**Comment by melithine** [comment]
https://github.com/sim0n00ps/OF-DL/pull/485 might help with that, I think.

**Comment by ddirty830** [comment]
I don't think it will. #485 relies on the `text` to parse `rawText` when missing.
Maybe OF is changing their API. Might need an example creator/post to verify.

**Comment by melithine** [comment]
> In the last few days, when downloading posts the "text" field is not populating in the database, it just remains blank. Everything else seems to populate fine, including text of messages

Can you try 1.7.69 and see if that resolved things for you?
