### ISSUE TITLE
Post already downloaded / But post is not downloaded

### ISSUE THREAD

**Issue by Chepko932** [sim0n00ps/OF-DL#476]
I get the message Post xxx already downloaded, but the post is not downloaded, already tried to delete the userdata folder, but that does not help at all.

![Screenshot 2024-07-16 204548](https://github.com/user-attachments/assets/552834f6-00f5-467b-b1e7-8dfc1d8a6333)

**Comment by dhougie** [comment]
It says it was downloaded, but it doesn't download either. ![Uploading Captura de tela 2024-07-16 230711.png…]()

**Comment by bondo01** [comment]
I have had the same problem. Installing into new directory/folder did not force new download. Is there a DB file hidden on the system?

**Comment by bondo01** [comment]
Is there a way to force it to download. I have several failed downloads that it retains a download complete when the file does not exist or is a partial file that is unplayable.

**Comment by randomfapper** [comment]
I'm getting the same error with certain creators but only when it comes to video files.  I have a feeling OF did something on their back end with some type of new coding/encryption that prevents downloading the video.  If I try to download directly, the file will download and be the full file size but will not open in media player.  I recall something similar happened last year, which is why we needed the cdm folder/files for downloading videos.

**Comment by Chepko932** [comment]
> I'm getting the same error with certain creators but only when it comes to video files. I have a feeling OF did something on their back end with some type of new coding/encryption that prevents downloading the video. If I try to download directly, the file will download and be the full file size but will not open in media player. I recall something similar happened last year, which is why we needed the cdm folder/files for downloading videos.

For me it was for videos too

**Comment by dhougie** [comment]
I did it, edit the OF-DL configuration and mark what needs to be downloaded, posts, messages... Among others. Then it works.

**Comment by qz30233** [comment]
Enter Edit config.json. Almost all of them are turned off by default. Turn on download image/video and you can download it ([x] means on, [ ] means off)

**Comment by melithine** [comment]
The config.json defaults should be fixed in the next release.

**Comment by melithine** [comment]
> I get the message Post xxx already downloaded, but the post is not downloaded, already tried to delete the userdata folder, but that does not help at all.
> 
> ![Screenshot 2024-07-16 204548](https://private-user-images.githubusercontent.com/161015602/349235772-552834f6-00f5-467b-b1e7-8dfc1d8a6333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NzE1NzUsIm5iZiI6MTcyMTc3MTI3NSwicGF0aCI6Ii8xNjEwMTU2MDIvMzQ5MjM1NzcyLTU1MjgzNGY2LTAwZjUtNDY3Yi1iMWU3LThkZmMxZDhhNjMzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QyMTQ3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWEwMGUzZDQ5NGJhYmViN2MxMzRmMDQwYWUwNjU2OTgxMzU5MTU1OTAzZWE1M2RjNTE0OTA4NDRiZmM4MjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0xhxPY2ONj-X7ofW3N0ROGQAX4hcwmr5uZSdgnyANkA)

Can you change the log level to debug and try again and attach the log file?

**Comment by MBR170** [comment]
I have the same issue. I downloaded some posts with normal settings, at 9% I stopped and started again with the FolderPerPost option. It created the per-post folders, but for that 9% it tells me the files are already downloaded and the folders did not populate with files. Those files (the 9%) where all together in a common folder, I erased that but it still tells me the files are already downloaded. Is there a cache to clear so I can force a new download? Even downloading everything again would be an option.

**Comment by melithine** [comment]
> I have the same issue. I downloaded some posts with normal settings, at 9% I stopped and started again with the FolderPerPost option. It created the per-post folders, but for that 9% it tells me the files are already downloaded and the folders did not populate with files. Those files (the 9%) where all together in a common folder, I erased that but it still tells me the files are already downloaded. Is there a cache to clear so I can force a new download? Even downloading everything again would be an option.

If you delete the Metadata folder for that creator, it will redownload the files. That folder has the database that tracks what was already downloaded.

**Comment by MBR170** [comment]
> If you delete the Metadata folder for that creator, it will redownload the files. That folder has the database that tracks what was already downloaded.

It worked flawlessly, thanks!
