### ISSUE TITLE
V.1.7.67 not compatible with 32 bit windows 10?

### ISSUE THREAD

**Issue by badbeezy** [sim0n00ps/OF-DL#477]
I don't think version works with my operating system anymore.
Is there a way to make it work on 32 bit windows 10?

**Comment by melithine** [comment]
Can you post the error/problem you're seeing?

**Comment by badbeezy** [comment]
When clicking on the new version of OF-DL, a windows pop-up says "This app can't run on your PC. To find a version for your PC, check with the software publisher."

I'm currently using 32 bit Windows 10.

**Comment by melithine** [comment]
This should be fixed in the next release, I missed a setting when changing the build process.

**Comment by melithine** [comment]
This should be fixed in 1.7.68.
