### ISSUE TITLE
Getting device_client_id_blob and/or device_private_key missing, https://cdrm-project.com/ will be used instead for DRM protected videos when I open the DL

### ISSUE THREAD

**Issue by avoca21** [sim0n00ps/OF-DL#478]
Hi, I haven't opened it in a month or so and when I opened it, I keep geting this

Valid version of Windows found.
auth.json located successfully!
config.json located successfully!
FFmpeg located successfully
device_client_id_blob and/or device_private_key missing, https://cdrm-project.com/ will be used instead for DRM
protected videos
Exception caught: Response status code does not indicate success: 404 (Not Found).

                                                                                  StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDynamicHeaders(String path, String queryParams, Auth auth)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint, Auth auth)
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint, Auth auth)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Program.Main(String[] args)

Press any key to exit.

I'm pretty new so I don't know what happened. Worked before. Thanks

**Comment by melithine** [comment]
Update to a more recent version.

**Comment by emoAnarchist** [comment]
> Update to a more recent version. There were some things that changed that broke authentication that we had to fix in a new release.

i have this same issue in the newest version, 1.7.67

**Comment by AshySlashy442** [comment]
> Update to a more recent version. There were some things that changed that broke authentication that we had to fix in a new release.

getting the same error using the latest verision

**Comment by avoca21** [comment]
> Update to a more recent version. There were some things that changed that broke authentication that we had to fix in a new release.

I tried that but the new one seems buggy to me? Idk, my computer thought it was malware, the auth file was basically blank, etc. I kinda got it working sort of by mixing old releases with new stuff, but it's still has errors all over the place

**Comment by melithine** [comment]
> > Update to a more recent version. There were some things that changed that broke authentication that we had to fix in a new release.
> 
> I tried that but the new one seems buggy to me? Idk, my computer thought it was malware, the auth file was basically blank, etc. I kinda got it working sort of by mixing old releases with new stuff, but it's still has errors all over the place

I can't say anything about the malware issue besides it's not accurate, but if you post error details we can try to help more. The auth.json/config.json files are not intended to be replaced during an upgrade, I'll note, just the .exe, .dlls, and rules.json.

**Comment by em997nz** [comment]
I am getting this error message in v 1.7.74.  But the downloads still seem to work though?

**Comment by melithine** [comment]
> I am getting this error message in v 1.7.74. But the downloads still seem to work though?

It's a warning, not an error.

**Comment by em997nz** [comment]
Yeah I now getting the same message and some videos won't download.  This worked properly in 1.7.60 (where I generated my own keys) but now doesn't work in 1.7.74.  Basically, this new version doesn't seem to be picking my previous device_client_id_blob and device_private_key files.  Please help if you can. :)

**Comment by melithine** [comment]
You must have moved or forgotten to move the keys, then. It wouldn't be throwing that error if they're in the correct location, and the location hasn't changed.
