### ISSUE TITLE
Scraping Error

### ISSUE THREAD

**Issue by sexydance10sp** [sim0n00ps/OF-DL#48]
Hello! I am currently having two issues:

(1) OF-DL worked like a charm, however, there are videos that it downloaded that had OF's DRM policy applied to it and they are not playing. I'm getting the Windows prompt asking me to sign in to check for usage rights. 

(2) I got this error message line (see attachment) about 12 times in the OF-DL program, which coincides with the amount of videos that have the Windows login prompt for usage rights. 

Also, thank you for this program! Haven't experienced any other issues thus far. 

![ActiveMachineRefuse](https://github.com/sim0n00ps/OF-DL/assets/137744573/cb7e8ead-4aa5-4399-96e6-64ca5b039cd4)

**Comment by sim0n00ps** [comment]
Probably down to your antivirus, it's being blocked as it probably thinks it's something malicious when it isn't, it's safe.

**Comment by sexydance10sp** [comment]
I see. I've added exceptions to my Firewall and Antivirus, restarted my computer, relogged into OF and grabbed a new session ID, and the issue still seems to be persisting. Disabling my Firewall just causes the program to not even download anything. 

And to amend my initial post--it's not 12 videos, it's 12 files corresponding to 6 of the most recent creators videos that are split into a .mp4 and .m4a. It creates two entries:

(1) "Exception caught: Could not find file 'C:\'" 
(2) "Exception caught: No connection would be made because the target machine actively refused it."

So, I'm currently stuck here. Everything prior to videos with the new OF policy applied download just fine, it's the most recent stuff where I'm encountering issues.

**Comment by sim0n00ps** [comment]
Alright, so it's downloading the files correctly which is a start, I'm guessing if you try to play them you will get a black screen, if so then it's an issue with mp4decrypt.exe, some people suggested that installing the C++ redistributable which I linked in the readme helps as mp4decrypt needs that in order to run.

**Comment by booleangit** [comment]
> I see. I've added exceptions to my Firewall and Antivirus, restarted my computer, relogged into OF and grabbed a new session ID, and the issue still seems to be persisting. Disabling my Firewall just causes the program to not even download anything. 
> 
> 
> 
> And to amend my initial post--it's not 12 videos, it's 12 files corresponding to 6 of the most recent creators videos that are split into a .mp4 and .m4a. It creates two entries:
> 
> 
> 
> (1) "Exception caught: Could not find file 'C:\'" 
> 
> (2) "Exception caught: No connection would be made because the target machine actively refused it."
> 
> 
> 
> So, I'm currently stuck here. Everything prior to videos with the new OF policy applied download just fine, it's the most recent stuff where I'm encountering issues. 

Did you use "\" instead of "/" in the JSON config for the path names? I would expect this error message when it's unable to call necessary external apps.

**Comment by sim0n00ps** [comment]
> I do have the C++ Redistributable installed, both x86 and x64. Issue persists. Would it be silly/pointless to download the ARM64 version as well? Apologies, I'm not as knowledgeable in this.

You would only install the ARM64 version if you are running an ARM64 machine which I doubt you are.

**Comment by sexydance10sp** [comment]
I feel real freaking stupid right now with how I got this to work. It was the antivirus blocking things, even though I added the programs and OnlyFans to my whitelist. The videos I was having issues with downloaded once I turned off my antivirus' web protection. That'll just have to be an extra step I do moving forward.

Thank you, thank you, thank you for the help!
