### ISSUE TITLE
Scrape completed but nothing is downloaded

### ISSUE THREAD

**Issue by markbrun21** [sim0n00ps/OF-DL#484]
When I select what I want to download it finds 0 posts, nothing is downloaded, folders for the accounts i subscribed are created but they are empty

![Screenshot_1](https://github.com/user-attachments/assets/4195b87e-989d-4c78-ba70-8a28bf718d44)

What am I doing wrong? Thanks

**Comment by supernova4420** [comment]
I am having the same issues:

- latest version (1.7.68)
- custom generated cdm files
- deleted all .db files

Scrape finds nothing.

**Comment by MarioDittrich** [comment]
Same issue here.

I thinkOF has a new DRM protection since today (at least for me). I can not download with VideoDownloadHelper, which worked perfectly before, i can not record using OBS, right click Menu is hidden.
YouTube-DL never worked.
Right now, i have no idea how to download from OF.

**Comment by JohnMascript** [comment]
Hey, your values for the different download options must all be set to false in the Config.json file! that's why the program thinks it finished after downloading nothing.

Go to the folder where OF DL.exe is, open the Config.json file and change the values of the first options from "false" to "true". A list of what each option does can be found here: [https://of-dl.gitbook.io/of-dl/config](https://of-dl.gitbook.io/of-dl/config) 

The very first options in the list enable the download of paid posts, messages, videos, pictures, etc. Program is working perfectly, but it seems options come set to false on default in the latest release, just gotta check em out and change to true.

**Comment by markbrun21** [comment]
> @markbrun21 @MarioDittrich @supernova4420 Hey, your values for the different download options must all be set to false in the Config.json file! that's why the program thinks it finished after downloading nothing.
> 
> Go to the folder where OF DL.exe is, open the Config.json file and change the values of the first options from "false" to "true". A list of what each option does can be found here: https://of-dl.gitbook.io/of-dl/config
> 
> The very first options in the list enable the download of paid posts, messages, videos, pictures, etc. Program is working perfectly, but it seems options come set to false on default in the latest release, just gotta check em out and change to true.

Thanks, seems like this worked for me

**Comment by melithine** [comment]
> @markbrun21 @MarioDittrich @supernova4420 Hey, your values for the different download options must all be set to false in the Config.json file! that's why the program thinks it finished after downloading nothing.
> 
> Go to the folder where OF DL.exe is, open the Config.json file and change the values of the first options from "false" to "true". A list of what each option does can be found here: https://of-dl.gitbook.io/of-dl/config
> 
> The very first options in the list enable the download of paid posts, messages, videos, pictures, etc. Program is working perfectly, but it seems options come set to false on default in the latest release, just gotta check em out and change to true.

Yeah, we changed build systems recently and that caused the issue. I raised a PR and the defaults should be fixed in the next release.

**Comment by MarioDittrich** [comment]
> @markbrun21 @MarioDittrich @supernova4420 Hey, your values for the different download options must all be set to false in the Config.json file! that's why the program thinks it finished after downloading nothing.
> 
> Go to the folder where OF DL.exe is, open the Config.json file and change the values of the first options from "false" to "true". A list of what each option does can be found here: https://of-dl.gitbook.io/of-dl/config
> 
> The very first options in the list enable the download of paid posts, messages, videos, pictures, etc. Program is working perfectly, but it seems options come set to false on default in the latest release, just gotta check em out and change to true.

Thanks for the answer. I got those settings in config.json:
<img width="456" alt="image" src="https://github.com/user-attachments/assets/a363f152-8143-43c2-9227-07d11b44a0b3">


It downloads images and some videos, but far from all videos. I ran it multiple times, but it doesn't download them.

My logs:
<img width="1620" alt="image" src="https://github.com/user-attachments/assets/0ae38498-76a2-41c8-9ef4-dec4d267edd0">

**Comment by melithine** [comment]
@MarioDittrich that's a separate issue still being looked at here https://github.com/sim0n00ps/OF-DL/issues/466

**Comment by melithine** [comment]
> @markbrun21 @MarioDittrich @supernova4420 Hey, your values for the different download options must all be set to false in the Config.json file! that's why the program thinks it finished after downloading nothing.
> 
> Go to the folder where OF DL.exe is, open the Config.json file and change the values of the first options from "false" to "true". A list of what each option does can be found here: https://of-dl.gitbook.io/of-dl/config
> 
> The very first options in the list enable the download of paid posts, messages, videos, pictures, etc. Program is working perfectly, but it seems options come set to false on default in the latest release, just gotta check em out and change to true.

This should be fixed with 1.7.69, closing.
