### ISSUE TITLE
Exception caught: Response status code does not indicate success: 403 (Forbidden)

### ISSUE THREAD

**Issue by DJ27093** [sim0n00ps/OF-DL#487]
I've made sure I've done the update and put in all the right data and yet I still get this error. Can someone help me please? 
It says the scrap was complete, but the video never downloaded.

![Screenshot 2024-07-24 190801](https://github.com/user-attachments/assets/d10245af-89e6-4964-a034-4718e2b74d2a)

**Comment by aussielimes** [comment]
i am getting this error when trying to download any DRM video

**Comment by melithine** [comment]
Can you folks change logging to debug or verbose, try again, and submit the log file?

**Comment by aussielimes** [comment]
idk this is right but here you go 

`StackTrace:    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at OF_DL.Helpers.DBHelper.CreateUsersDB(Dictionary`2 users)`

**Comment by melithine** [comment]
> idk this is right but here you go
> 
> StackTrace: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool) at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection() at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection) at Microsoft.Data.Sqlite.SqliteConnection.Open() at OF_DL.Helpers.DBHelper.CreateUsersDB(Dictionary`2 users)

That looks like an unrelated error, but close the app, extract the `e_sqlite3.dll` from the release ZIP file, overwrite the copy you currently have, and then try again,

**Comment by melithine** [comment]
The 403 Forbidden is being tracked on #466.
