### ISSUE TITLE
after latest release: cannot locate ffmpeg -OFDL ignores path in config.json

### ISSUE THREAD

**Issue by Kvothe1970** [sim0n00ps/OF-DL#489]
As per the[ change log](https://github.com/sim0n00ps/OF-DL/compare/OFDLV1.7.68...OFDLV1.7.69) and https://of-dl.gitbook.io/of-dl/auth#browser-extension:~:text=the%20dev%20tools.-,Finally,-you%20need%20to 

I have moved the path to the ffmpeg.exe from the auth.json to the config.json

The json file validates via jasonlint
The path is correct. I have also modified the path to be simpler and directly on c:\

 "FFMPEG_PATH": "C:/ffmpeg/ffmpeg.exe"

However, when I run OF-DL

I get "Cannot locate FFmpeg; please modify config.json with the correct path. Press any key to exit." 

The file is there: I can open it, I can browse it. Even running OF-DL as Administrator does not allow it to access. 
This worked just yesterday while I was still on the previous version and the orginal file location, created by Winget for ffmpeg, remaines the same. 

I just saw it opens a second window. It tires to locate ffmpeg in system32

`Version: 1.7.69
Exception caught: Access to the path 'C:\WINDOWS\system32\config.json' is denied.

StackTrace:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at OF_DL.Program.Main(String[] args)

Press any key to exit.`

I would appreciate a hint / help on this. 
Cheers!

**Comment by melithine** [comment]
In config.json, it's `FFmpegPath`, not `FFMPEG_PATH`.

**Comment by Kvothe1970** [comment]
How did I miss that? 
cheers for helping me out! I’ll adjust that
