### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by youssefa0** [sim0n00ps/OF-DL#49]
when i downloaded a paid post unfortunately the video didn't want to play i deleted and download again but getting same issue 

![Screenshot 2023-06-27 025740](https://github.com/sim0n00ps/OF-DL/assets/116003810/b1fb46a7-69e5-4404-9daa-6dfb253df85a)

![Screenshot 2023-06-27 025722](https://github.com/sim0n00ps/OF-DL/assets/116003810/faedf699-f0cf-4a11-b9fb-dfe303b22c15)

**Comment by youssefa0** [comment]
if someone know a way to fix and can help us i will appreciate that

**Comment by sim0n00ps** [comment]
Does the video with _source at the end to the right of the video work?

**Comment by youssefa0** [comment]
Thank you bro for answering i forgot to leave an update here . It worked bro i don’t how it happened i just logout from my account for a while and deleted the model folder , then i come back and do it again and i found that the video has been downloaded correctly without issues
