### ISSUE TITLE
Scrape completed but nothing is downloaded 

### ISSUE THREAD

**Issue by bernzoz** [sim0n00ps/OF-DL#490]
Nothing is downloaded even though I have activated what I wanted in the config.json folder (only 1 message, its weird)

![scrap](https://github.com/user-attachments/assets/d907129c-62d2-4b16-93ec-cddda42bd08d)

I am using the latest version (V1.7.69)

![config](https://github.com/user-attachments/assets/874b24a4-a397-4a44-830e-5a045d9774d6)
![config2](https://github.com/user-attachments/assets/e1e25b34-f4ba-43eb-8d70-3c0917758f8c)

did i do something wrong ?

**Comment by melithine** [comment]
The first screenshot is too abbreviated to see what's going on.

**Comment by bernzoz** [comment]
![scrap](https://github.com/user-attachments/assets/3c655260-0f4d-40ff-ba37-d5748b36a660)
![scrap2](https://github.com/user-attachments/assets/e8ce5303-23a6-483a-9522-3b116e19ef86)

**Comment by melithine** [comment]
It looks like it downloaded 1 message from the first creator and 24 highlights and 14 messages from the second. What's in your `__user_data__/sites/OnlyFans/` folders for those creators? It all looks fine so far.

**Comment by melithine** [comment]
Are you missing content from the creators' timeline? Because you don't have `DownloadPosts` enabled.

**Comment by bernzoz** [comment]
> Are you missing content from the creators' timeline? Because you don't have `DownloadPosts` enabled.

my bad i did not see, its working now
thanks melithine
