### ISSUE TITLE
auth.json file not valid and unexpected character encountered 

### ISSUE THREAD

**Issue by stekgurler115** [sim0n00ps/OF-DL#493]
just updated to version 1.7.69 earlier and after entering the necessary info into the auth.json file, i get an error saying "auth.json is not valid, check your JSON syntax" it also says "After parsing a value an unexpected character was encountered: ". Path 'COOKIE', line 7, position 2." 
I double checked and made sure everything i entered is correct and the most up to date and i even used the browser extension to copy and paste into the auth file. i'll add some screenshots of the error and what my auth and config files look like. i blacked out my auth id, but more than happy to upload an unedited version if needed.

![Screenshot 2024-07-28 134421](https://github.com/user-attachments/assets/6674e7e6-2edb-467d-9a19-ffbc891a17f1)
![Screenshot 2024-07-28 134519](https://github.com/user-attachments/assets/18627ece-ea8a-4eda-8a16-4b16a0a039d9)
![Screenshot 2024-07-28 135824](https://github.com/user-attachments/assets/6be646da-1741-4606-ae16-b6cb07636600)

**Comment by melithine** [comment]
Remove the `FFmpeg_Path` line from `auth.json` (it's not needed there anymore, and you are missing the comma after the double quote on the `COOKIE` line to make it valid JSON... plus in the old setup it would be `FFMPEG_PATH`) and add the path to the `FFmpegPath` line in `config.json` instead.

**Comment by stekgurler115** [comment]
that fixed it thank you. thanks for the quick response!

**Comment by melithine** [comment]
Happy to help!
