### ISSUE TITLE
Can someone explain this error message and how to fix

### ISSUE THREAD

**Issue by mallson1** [sim0n00ps/OF-DL#495]
![Uploading IMG_4317.jpeg…]()

This is a picture of the error any ideas on the issue

**Comment by mallson1** [comment]
> Your machine wasn't able to securely connect to OnlyFans. This is usually due to anti-virus software, firewall, or ISP/government interference.

Government interference like feds?

**Comment by melithine** [comment]
> > Your machine wasn't able to securely connect to OnlyFans. This is usually due to anti-virus software, firewall, or ISP/government interference.
> 
> Government interference like feds?

No, I meant more like countries that have OF banned.
