### ISSUE TITLE
Issue during post scrape & possible not scraping drm

### ISSUE THREAD

**Issue by dpsbrdi** [sim0n00ps/OF-DL#5]
using latest commit

whilst scraping free posts for 1 model

"Object reference not set to an instance of an object."  but it got the next models free posts fine

and as far as i can see it's not getting free messages that have drm content, i deleted the models folder and did a full from scratch scrape with her and it did not grab any of the drm free messages

**Comment by sim0n00ps** [comment]
Would you be able to put the full error message here so I can see what it's trying to reference that Is null

**Comment by sim0n00ps** [comment]
Latest release should fix this
