### ISSUE TITLE
Messages not downloading

### ISSUE THREAD

**Issue by pilotochich** [sim0n00ps/OF-DL#500]
Tried with multiple users and multiple download configs. Posts seem to download normally; however, neither messages nor paid messages download. OF-DL states that there are 0 messages and 0 paid messages despite that not being the case.

![image](https://github.com/user-attachments/assets/334f2fc2-20e7-4f37-80dd-8b1a2dbbd6b7)

Log file:
[OFDL20240731.txt](https://github.com/user-attachments/files/16443791/OFDL20240731.txt)

**Comment by melithine** [comment]
You have `DownloadImages`, `DownloadVideos`, and `DownloadAudios` all set to `false` in `config.json`. There's nothing for it to do since none of those content types are enabled.

**Comment by pilotochich** [comment]
> You have `DownloadImages`, `DownloadVideos`, and `DownloadAudios` all set to `false` in `config.json`. There's nothing for it to do since none of those content types are enabled.

Did not realise that those had to be active in addition to `DownloadMessages` and `DownloadPaidMessages`; working now!
