### ISSUE TITLE
Error Code: Response Status Code Does Not Indicate 

### ISSUE THREAD

**Issue by whoisty14** [sim0n00ps/OF-DL#507]
This error keeps popping up it downloads some post but stops after a while. Im using version 1.7.71

![Screenshot 2024-08-04 180723](https://github.com/user-attachments/assets/5ff729a2-8387-4cdf-8c80-325974dc7a6f)

**Comment by melithine** [comment]
That looks like it's probably a duplicate of #466. Please change your logging level to Debug or Verbose and attach the log on that issue.
