### ISSUE TITLE
Suggestion: Store info about downloaded videos in order to avoid getting them downloaded again

### ISSUE THREAD

**Issue by antonio8909** [sim0n00ps/OF-DL#509]
Hi,

It is possible to introduce a function where if the program recognize that a video has already been downloaded it will be skipped until a new one appears? It could be very helpful.

Thanks!

**Comment by melithine** [comment]
OFDL does not redownload previously downloaded videos, as it tracks that in a database (under the creator's folder, there's a `Metadata` folder that holds that DB). It does need to see what posts/messages/etc. are there to determine what to download, but if you're using `DownloadPostsIncrementally` that scrape looks from your last scrape onwards and greatly speeds things up.
