### ISSUE TITLE
Regarding Amount of Content being downloaded

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#51]
I scraped an account and it completed without any issues. 

but I did notice one thing and I'm not sure what to make of it. 

When I go to this particular creators account and go to the media tab it shows that in total 2976 files and broken down thats 2627 photos, 346 videos, 3 audios 

When after the scraping is completed it does show that it downloaded 3 audio files. 

but for videos it shows 330 and for pictures  2594

so it seems like 16 videos are missing and 33 pictures are missing

I don't know if this is normal or if there is some sort of bug with the scrape, or if some how maybe some pictures/videos are duplicates and during the scraping process its not downloading the duplicates. 

any advice would be great

**Comment by sim0n00ps** [comment]
Any media that is reused is skipped to stop dupes being downloaded
