### ISSUE TITLE
Only 1 Minute of a 5-minute paid video gets downloaded

### ISSUE THREAD

**Issue by ktchanz777** [sim0n00ps/OF-DL#510]
Idk why, but I'm trying to download a 5-minute paid post and the software only downloads 1 minute of it every single time.

I tried downloading the post singularly, and I tried doing the custom paid post route but I'm getting the same issue.

Is there a fix for this?

**Comment by melithine** [comment]
As I mentioned on Discord, you need to change the logging level to Debug or Verbose and attach a log of the scrape for us to determine what's going on.

**Comment by ktchanz777** [comment]
[OFDL20240805.txt](https://github.com/user-attachments/files/16502603/OFDL20240805.txt)

**Comment by melithine** [comment]
Log file looks good, wondering if CDRM Project might be the issue... sent them a set of CDM keys to try.

**Comment by melithine** [comment]
Are you still experiencing this? I'll note the 1.7.75 release has a number of changes that could potentially resolve this as well.

**Comment by ktchanz777** [comment]
> Are you still experiencing this? I'll note the 1.7.75 release has a number of changes that could potentially resolve this as well.

Yeah it's working fine now, Thanks
