### ISSUE TITLE
Subscription not detected

### ISSUE THREAD

**Issue by Cypher4O4** [sim0n00ps/OF-DL#512]
I made a subscription to an account (onlyfans.com/vatuttobene) but it doesn't show up in the list or custom section so i can't download the content.
I even tried to create a bookmark just for the single account, but it results empty

**Comment by melithine** [comment]
Did you subscribe after ofdl was already running? Have you restricted the account in the past? If neither of those, change the logging level to Debug or Verbose, restart the app, and try again and then attach the log file here.

**Comment by Cypher4O4** [comment]
Resolved, in config file i turned on restricted and expired subs.
However for the next time how can i change logging level to Debug or Verbose?

**Comment by melithine** [comment]
> Resolved, in config file i turned on restricted and expired subs. However for the next time how can i change logging level to Debug or Verbose?

It's a menu option ("Change logging level") when running the application, or you can manually edit the `config.json` file.
