### ISSUE TITLE
DRM Download Auth Error

### ISSUE THREAD

**Issue by dagr8boy** [sim0n00ps/OF-DL#518]
Hi I'm getting the following error downloading a DRM protected video post. I am not using my own widevine keys. 

```
Getting Post
                                                              
Downloading Post ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0%
                                                              Exception caught: Response status code does not indicate success: 403 (Forbidden).

                                                              ccessStatusCode()
Downloading Post ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  66%ing policy, String signature, String kvp) in /Users/iag/repos/OF-DL/OF DL/Helpers/APIHelper.cs:line 2493
```

Any idea what could be wrong?

**Comment by melithine** [comment]
I don't think you're doing anything wrong. I assume you don't have your own Widevine keys, in which case OFDL uses the cdrm-project website to handle the decryption. They've been having big problems again lately, which cause that kind of error. If you're on Discord, I can send you a set of Widevine keys, just see my message in `#general` and DM me for the zip.

**Comment by melithine** [comment]
Widevine keys didn't help, marking this as a dupe of #466.
