### ISSUE TITLE
Keeps giving me Auth failed 

### ISSUE THREAD

**Issue by ItsKing-32** [sim0n00ps/OF-DL#52]
when I open of dl.exe it [shows that](https://gyazo.com/2d87704ce2ab7f134ea1decf742a9b0a)  yt-dlp.exe located successfully ffmpeg.exe located successfully mp4decrypt.exe located successfully
but then says Auth failed, please check the values in auth.json are correct. I have put each variable in multiple times and nothing is working

**Comment by deadbeatdandylyon** [comment]
This has happened to me a few times. sometimes you have to log out of OF and log back in and then get the new sess cookie that normally resolves it when i run into that issue.

**Comment by ItsKing-32** [comment]
ive tried that its still now working

**Comment by deadbeatdandylyon** [comment]
then my next suggestion would be to disable any antivirus software incase that might be preventing a connection and or try an alternative browser

**Comment by sim0n00ps** [comment]
Make sure you've entered YOUR session values and haven't copied my example ones. Remove any "" as you only need to have strings between a single " at either end of a string. Also make sure your user-agent is correct as sometimes it can change and it might not look like it's changed from the naked eye but it actually has so always worth copying the user agent again.

**Comment by ItsKing-32** [comment]
I only have 1 set of " for all the values and I copied my user agent and
all the other stuff  from online to the .json each time I didnt reuse any
of it

**Comment by sim0n00ps** [comment]
Alright would you be able to screen record the console so I can see the error?

**Comment by ss132639** [comment]
are you using Chrome? I've never gotten one of these to work on Chrome. Firefox and Edge work just fine.
