### ISSUE TITLE
Exception caught: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by lucacham** [sim0n00ps/OF-DL#532]
Until yesterday, I was still using it normally. But when I used it today, the following error message appeared. What is the reason?

![image](https://github.com/user-attachments/assets/20594bee-af33-4134-b301-aeb8059c04a8)

**Comment by lucacham** [comment]
> They are trying to fix that.

So is this a known issue? I thought it was a configuration error on my end

**Comment by bezaaas** [comment]
> > They are trying to fix that.
> 
> So is this a known issue? I thought it was a configuration error on my end

Yep. https://github.com/sim0n00ps/OF-DL/issues/523

**Comment by sim0n00ps** [comment]
Don't duplicate issues, we're already aware of it and I've fixed it, just ironing a few things out before it's released use #523

**Comment by lucacham** [comment]
> Don't duplicate issues, we're already aware of it and I've fixed it, just ironing a few things out before it's released use #523

Thank you for your timely processing
