### ISSUE TITLE
Can't Download a video that was sent for free in a message

### ISSUE THREAD

**Issue by azbelj** [sim0n00ps/OF-DL#533]
Bought a video, was sent without audio. The creator then sent me the same video with audio as a free message. The downloader ignores/doesnt see that and wont download that

**Comment by melithine** [comment]
Please post or attach your config.json.

**Comment by azbelj** [comment]
[config.json](https://github.com/user-attachments/files/16705603/config.json)

**Comment by azbelj** [comment]
Latest version fixed this issue

**Comment by papishampooo** [comment]
> Bought a video, was sent without audio. The creator then sent me the same video with audio as a free message. The downloader ignores/doesnt see that and wont download that

were you able to download the content? im having this issue too, a creator sent me 2 videos via DM and the scraper doesn't get to them, any more info on this?
