### ISSUE TITLE
Downloading from a specific date?

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#534]
Hello, I know there is a way but not sure how to do it, but is there a way to start a scrape lets say from the start of a month so it doesn't have to scrape the whole account every time?

**Comment by melithine** [comment]
You can specify before a given date or after a given date. But if you've already scraped it, you want the incremental mode to speed up successive scrapes. https://sim0n00ps.github.io/OF-DL/docs/config/configuration#downloadpostsincrementally
