### ISSUE TITLE
Cannot Locate FFMPEG.exe

### ISSUE THREAD

**Issue by edge-evolution** [sim0n00ps/OF-DL#537]
Getting the error:

Cannot locate FFmpeg; please modify config.json with the correct path. Press any key to exit.

Whenever I open it. I have made sure that the path is correct. 

Please advise.

**Comment by Astercholik** [comment]
Check out the video tutorial on the author's home page where he shows everything.
You need to download the program ffmpeg.exe
And then set the location for this exe in config.json

![obraz](https://github.com/user-attachments/assets/eaf27f55-63be-41cd-8dd2-f106d506b1fc)

**Comment by edge-evolution** [comment]
Thanks for the comment, but I’ve been using this program since version 1.7.15 and I’ve never had a problem with finding it until now. Unless it has to be in the same folder as the of-dl.exe. I was last using 1.7.63 and unless it’s changed since then. But the path was in c:/ffmpeg.exe, unless that doesn’t work anymore.

**Comment by melithine** [comment]
Post the relevant bit f4om config.json?

**Comment by Astercholik** [comment]
It all depends on where you have placed the exe file I have shown in the picture that in my case it is where the program is but this location can be different if you have the program on the C drive then the path should be correct.

In other words, it all depends on where you extract the exe file then you have to specify the location in the config.json file.

**Comment by edge-evolution** [comment]
This is the same path I've had since I started using this app a long time ago. This is the first time I'm having this issue. Below is how I have it set up in the config.json
![path](https://github.com/user-attachments/assets/ab63b896-e53f-4f40-b4d2-5e0d913b64a6)

**Comment by edge-evolution** [comment]
I guess there is a permissions based issue when keeping it in the root C: drive. When I put it in my downloads or documents folder it works. I just don't like having it there, but whatever.

**Comment by Astercholik** [comment]
That's why I put it in the OFDL folder and have no problem with it :)

**Comment by melithine** [comment]
> This is the same path I've had since I started using this app a long time ago. This is the first time I'm having this issue. Below is how I have it set up in the config.json ![path](https://private-user-images.githubusercontent.com/5024618/360948640-ab63b896-e53f-4f40-b4d2-5e0d913b64a6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MzQ3NjUsIm5iZiI6MTcyNDQzNDQ2NSwicGF0aCI6Ii81MDI0NjE4LzM2MDk0ODY0MC1hYjYzYjg5Ni1lNTNmLTRmNDAtYjRkMi01ZTBkOTEzYjY0YTYuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTczNDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNiMjliNmJmY2MxZjkyMGMyZTZlNTRiODk4ZWJlOTc5MTJiMTg4NTEwZTUzZWZjZjI0NDYwNTNmM2M5MjI3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.krmPwV4JCS4nQB7t8iOdO3LPOm_hNUvMOQYH_Bul7l4)

In config.json, it's `FFmpegPath`, not `FFMPEG_PATH`. The latter is only valid in auth.json.
