### ISSUE TITLE
Feature request: Download all message items to an account

### ISSUE THREAD

**Issue by Wingzer01** [sim0n00ps/OF-DL#539]
I have several targets that I purchased through messages without subscribing. Some of them pay for the video with the purchase, but some pay for it for free. It would be nice to have a function to receive all the videos purchased or provided to all message targets in my account, rather than a single download for each message item. I am always grateful for the addition of features and bug patches.

**Comment by melithine** [comment]
I'm not sure how you got the content without subscribing. Do you mean you were subscribed but aren't anymore? And were they PPV unlocks? (If so, you could scrape the purchased tab.)

**Comment by Wingzer01** [comment]
> I'm not sure how you got the content without subscribing. Do you mean you were subscribed but aren't anymore? And were they PPV unlocks? (If so, you could scrape the purchased tab.)

It would be correct to say that you did not renew your subscription. Isn't there only a single menu for the purchase tab?

**Comment by melithine** [comment]
You can scrape all messages and paid messages from the creator without scraping their timelines. Expired subs are hidden by default, but there is a.ready an option to enable them. The purchased tab is for all PPV unlocks, so those async messages wouldn't be included anyways. Note that those will be entirely lost if the user deletes their account, as OF only retains PPV unlocks during account deletion.
