### ISSUE TITLE
Exception caught: SQLite Error 19: 'UNIQUE constraint failed: medias.media_id, medias.api_type'.

### ISSUE THREAD

**Issue by djmarioka** [sim0n00ps/OF-DL#540]
Hi,

I'm receiving this error of some subscriptions: **Exception caught: SQLite Error 19: 'UNIQUE constraint failed: medias.media_id, medias.api_type'.** 

![image](https://github.com/user-attachments/assets/42a66869-19d7-4180-9f21-4881ff81832b)

Could anybody fix this issue?.

Thanks.

**Comment by melithine** [comment]
Close OFDL and re-extract `e_sqlite3.dll` from the release ZIP file.

**Comment by djmarioka** [comment]
> Close OFDL and re-extract `e_sqlite3.dll` from the release ZIP file.

I've done it and it happens as well, I'm using the latest version:  1.7.74

**Comment by djmarioka** [comment]
It worked reinstalling again
