### ISSUE TITLE
1.7.74 - Errors when downloading purchased tab

### ISSUE THREAD

**Issue by DJColdCuts5** [sim0n00ps/OF-DL#542]
Receiving the below error when attempting to download the purchased tab.

Exception caught: Specified cast is not valid.

StackTrace:    at OF_DL.Helpers.APIHelper.GetPurchasedTab(String endpoint, String folder, IDownloadConfig config, Dictionary`2 users)
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Program.DownloadAllData(APIHelper m_ApiHelper, Auth Auth, Config Config)
   at OF_DL.Program.Main(String[] args)
[OFDL20240825.txt](https://github.com/user-attachments/files/16740131/OFDL20240825.txt)

**Comment by melithine** [comment]
Please retest under 1.7.75 and provide a debug log if you are still experiencing this.

**Comment by DJColdCuts5** [comment]
[OFDL20240904.txt](https://github.com/user-attachments/files/16883554/OFDL20240904.txt)
Unfortunately still occurring, updated debug log attached.

**Comment by DJColdCuts5** [comment]
Adding logs from 1.7.76
[OFDL20240908.txt](https://github.com/user-attachments/files/16924525/OFDL20240908.txt)

**Comment by DJColdCuts5** [comment]
Logs from 1.7.77
[OFDL20240930.txt](https://github.com/user-attachments/files/17186730/OFDL20240930.txt)

**Comment by sim0n00ps** [comment]
I'll probably need your Auth to debug this as I cannot replicate it.

**Comment by DJColdCuts5** [comment]
Fixed in 1.7.78!
