### ISSUE TITLE
Version: 1.7.74 - 500 (INTERNAL SERVER ERROR) - CDRM - Project 2.0 issue?

### ISSUE THREAD

**Issue by MisnerSpace** [sim0n00ps/OF-DL#544]
Was working fine for my paid posts but then received  this error. First time using OF-DL; as mentioned worked fine initially then an hour later stopped working.

Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)
Exception caught: Object reference not set to an instance of an object.

StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, String folder, DateTime lastModified, Int64 media_id, String api_type, ProgressTask task, String customFileName, String filename, String path)
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostDRMVideo(String policy, String signature, String kvp, String url                                                                      dia_id, String api_type, ProgressTask task, String

Thanks for all the hard work so far on  this software.

**Comment by melithine** [comment]
Yep, cdrm-project is having trouble, just helped another user on Discord. If you drop me a message there I can send you keys.

**Comment by spyjosh** [comment]
> Yep, cdrm-project is having trouble, just helped another user on Discord. If you drop me a message there I can send you keys.

hey there, I'm having the same issues at the moment as well. Would you be able to help me out?
