### ISSUE TITLE
No options appearing when opening the program

### ISSUE THREAD

**Issue by yourarchthebest** [sim0n00ps/OF-DL#546]
Hi, I checked the issue list and didnt find the one I have, so basicly I copied and pasted the things needed, I tried even other browser but it doesnt work, so I had to stay at Mozzila. I did saving content by hand and it took so much time, I was happy I found this program. 
So my issue is, that I open the app and get a screen like this: https://prnt.sc/JNQMD8LYf4S4 I select or chose or do anything. after a time it starts to download random user's videos and pictures (I think it downloads the galery of the latest user I subscribed to) https://prnt.sc/JWXNzpMssO6a . I dont know how I should make it to appear the Select all and other options. Any advice or help? Thanks

**Comment by melithine** [comment]
That sounds like you enabled NonInteractiveMode.
