### ISSUE TITLE
Downloaded filenames are incorrect and include the DownloadPath from the config

### ISSUE THREAD

**Issue by hydr0homiee** [sim0n00ps/OF-DL#549]
I downloaded the newest version and my downloaded files seem to be `{downloadpath}{whatever_nameformat}` instead of just the name format I choose.

If my config looks like this:
```config
  "DownloadPath": "Y:\\Onlyfans_Rips\\_OF_DF\\",
  "PaidPostFileNameFormat": "{username}_{mediaCreatedAt}_{filename}",
  "PostFileNameFormat": "{username}_{mediaCreatedAt}_{filename}",
  "PaidMessageFileNameFormat": "{username}_{mediaCreatedAt}_{filename}",
  "MessageFileNameFormat": "{username}_{mediaCreatedAt}_{filename}",
```

The downloaded file ends up in a folder at the specified `DownloadPath` with a name like `YOnlyfans_Rips_OF_DLusernamehere_2024-09-03_filenamehere.jpg` or something

**Comment by jasmeralia** [comment]
That's strange. I use the following with no trouble:
```
  "DownloadPath": "/data/",
  "PaidPostFileNameFormat": "{username} - PPV Post - {mediaCreatedAt}_{id}_{mediaid}",
  "PostFileNameFormat": "{username} - Post - {mediaCreatedAt}_{id}_{mediaid}",
  "PaidMessageFileNameFormat": "{username} - PPV Message - {mediaCreatedAt}_{id}_{mediaid}",
  "MessageFileNameFormat": "{username} - Message - {mediaCreatedAt}_{id}_{mediaid}",
```
(I run it under Docker, thus why I have it storing in `/data/`.)

I think we'll need a debug log to troubleshoot this, I can't see why your config isn't working correctly off the cuff.

**Comment by melithine** [comment]
That's strange. I use the following with no trouble:
```
  "DownloadPath": "/data/",
  "PaidPostFileNameFormat": "{username} - PPV Post - {mediaCreatedAt}_{id}_{mediaid}",
  "PostFileNameFormat": "{username} - Post - {mediaCreatedAt}_{id}_{mediaid}",
  "PaidMessageFileNameFormat": "{username} - PPV Message - {mediaCreatedAt}_{id}_{mediaid}",
  "MessageFileNameFormat": "{username} - Message - {mediaCreatedAt}_{id}_{mediaid}",
```
(I run it under Docker, thus why I have it storing in `/data/`.)

I think we'll need a debug log to troubleshoot this, I can't see why your config isn't working correctly off the cuff.

**Comment by hydr0homiee** [comment]
Here are the debug logs.

[OFDL20240903.txt](https://github.com/user-attachments/files/16860195/OFDL20240903.txt)

**Comment by FarmingCrops** [comment]
file names im getting is {mediacreatedAt} 0ht45ej42dcoyxqvbi5cc_source instead of 2024-08-08 0hsg8bz79skhkn6980pa5_source

  "PaidPostFileNameFormat": "{} {}",
  "PostFileNameFormat": "{mediacreatedAt} {filename}",
  "PaidMessageFileNameFormat": "{mediaCreatedAt} {filename}",
  "MessageFileNameFormat": "{mediaCreatedAt} {filename}",
  "RenameExistingFilesWhenCustomFormatIsSelected": true,

**Comment by hydr0homiee** [comment]
This issue still persists for me on 1.7.76 as well.

**Comment by Quildar** [comment]
Same issue running 1.7.76 on Windows

**Comment by hydr0homiee** [comment]
Not sure if any changes were made but this seems fixed as of 1.7.79!

**Comment by hydr0homiee** [comment]
Though I am now noticing the `RenameExistingFilesWhenCustomFormatIsSelected` option seems to be broken, not sure if it was always broken or not.

**Comment by jasmeralia** [comment]
> Though I am now noticing the `RenameExistingFilesWhenCustomFormatIsSelected` option seems to be broken, not sure if it was always broken or not.

There's a bug on that already, #345

**Comment by melithine** [comment]
> Though I am now noticing the `RenameExistingFilesWhenCustomFormatIsSelected` option seems to be broken, not sure if it was always broken or not.

There's a bug on that already, #345
