### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by digitalwiz** [sim0n00ps/OF-DL#55]
Model creates posts with short preview videos showing what she sent to active subscribers. She also creates messages with preview videos to pay and unlock. These videos are very short, about 10-15 seconds. Can we specify we only want  to download videos over a specific length to skip these?

**Comment by sim0n00ps** [comment]
As much as I would like to add this I don't really want to add anymore config options as the current list is quite big so I want to keep it as maintainable as possible.
