### ISSUE TITLE
can't find cdm files in widevine folder

### ISSUE THREAD

**Issue by Anes-byte** [sim0n00ps/OF-DL#553]

**Comment by melithine** [comment]
They aren't provided by default. If they were, they would almost certainly get expired once detected. This is why you need to generate your own, or get someone else to generate a pair for you. I give them out on Discord, if you join the OFDL server and drop me a private message, I'll send you a zip file when I'm next available to do so. Thanks to @whimsical-c4lic0, I can generate them in bulk, so I almost always have a number of keys on hand to give out.. I'm coming up on the 45th key that I've given away like this. :)
