### ISSUE TITLE
V1.7.75 gives me a filepath error when attempting to download messages/ message media

### ISSUE THREAD

**Issue by mojgan37** [sim0n00ps/OF-DL#554]
I downloaded posted content, videos and pictures just fine, but with messages I get the follow error. I'm trying to download a video message a creator sent to me. It's a free video she custom sent to me, and I don't have a url for it.
![Capture](https://github.com/user-attachments/assets/0d062640-1d05-47ac-8762-587ee646118e)
[config.json](https://github.com/user-attachments/files/16903776/config.json)

**Comment by mojgan37** [comment]
> In your config you have this on line 38.
> 
> ```json
>     "FFmpegPath": "C:/Users/willd/Desktop/OFDLV1.7.75/ffmpeg.exe",
> ```
> 
> You need to escape the backslashes like it says in the [docs](https://sim0n00ps.github.io/OF-DL/docs/config/configuration#ffmpegpath). It should look like this:
> 
> ```json
>     "FFmpegPath": "C:\\Users\\willd\\Desktop\\OFDLV1.7.75\\ffmpeg.exe",
> ```

**Comment by mojgan37** [comment]
> In your config you have this on line 38.
> 
> ```json
>     "FFmpegPath": "C:/Users/willd/Desktop/OFDLV1.7.75/ffmpeg.exe",
> ```
> 
> You need to escape the backslashes like it says in the [docs](https://sim0n00ps.github.io/OF-DL/docs/config/configuration#ffmpegpath). It should look like this:
> 
> ```json
>     "FFmpegPath": "C:\\Users\\willd\\Desktop\\OFDLV1.7.75\\ffmpeg.exe",
> ```


Changed it to the double backslashed like you wrote but still get the same error. 
[config.json](https://github.com/user-attachments/files/16904493/config.json)

**Comment by melithine** [comment]
Try just setting it to two double quotes. This is a known issue with 1.7.75.

**Comment by randomfapper** [comment]
Getting the same issue here.  Tried with a path and with the double quotes.  Same error, whether doing single post or full rip.

Everything was working fine last night on the newest version and then this morning it wasn't.

![1](https://github.com/user-attachments/assets/be26abb0-d44a-4f7a-8d9d-cfe3215f7b7f)
![2](https://github.com/user-attachments/assets/26cbf30f-70c4-46cd-b606-ded4f9da73c5)

**Comment by Narixv** [comment]
Hello,

I am also having the same issue described here.
This is an odd behavior because 4 out of my 5 content creators I had supported, this error never occurred.
It only occurs on one creator.

I would like to get all the messages I sent but there are some OF-DL are not scrapping I presume because of this issue.
![image](https://github.com/user-attachments/assets/164de54b-811c-44c8-b18a-af3c9f03572b)

Thank you,

**Comment by DonaldTPP** [comment]
Same error message as #541 after the update.

**Comment by Chawklates** [comment]
also getting this error on DRM videos only.

**Comment by ravenashlee123** [comment]
I'm getting the same issue #554 on 1.7.75 on DRM videos only

**Comment by mojgan37** [comment]
Works now! Thanks man!
