### ISSUE TITLE
Exception caught: Response status code does not indicate success: 500 (Internal Server Error).

### ISSUE THREAD

**Issue by booleangit** [sim0n00ps/OF-DL#555]
Since about an hour ago I got this error:

![image](https://github.com/user-attachments/assets/231dd682-7b7e-4090-9952-1b9e8932afc9)

It seems that OF's developers just can't lean back and stop changing stuff...

**EDIT:** It seems that OF currently has some stability issues, so it might be just a result of that. I'll recheck it after a few hours.

**EDIT2:** It was indeed an issue on OF's server side. Everything is working again.

**Comment by melithine** [comment]
Yeah, 500 errors usually just mean server problems. When they make breaking changes, that's not usually the symptom. My first thought was that it was actually a cdrm-project issue (given how common _that_ is), but I see you have your own Widevine keys, so that's not the case.

**Comment by booleangit** [comment]
> Yeah, 500 errors usually just mean server problems. When they make breaking changes, that's not usually the symptom. My first thought was that it was actually a cdrm-project issue (given how common _that_ is), but I see you have your own Widevine keys, so that's not the case.

The 500 was indeed a giveaway. I don't like external dependencies (i.e. cdrm-project) in general, so when I can do things locally I usually will. Since generating keys for Widevine is fairly easy, I don't see a reason to rely on an external source.

**Comment by melithine** [comment]
> > Yeah, 500 errors usually just mean server problems. When they make breaking changes, that's not usually the symptom. My first thought was that it was actually a cdrm-project issue (given how common _that_ is), but I see you have your own Widevine keys, so that's not the case.
> 
> The 500 was indeed a giveaway. I don't like external dependencies (i.e. cdrm-project) in general, so when I can do things locally I usually will. Since generating keys for Widevine is fairly easy, I don't see a reason to rely on an external source.

A lot of people find it very difficult, as someone who has the Support role on Discord. That's why I generate keys in bulk amounts and hand them out over Discord PMs.

**Comment by Leryn** [comment]
i'm having same problem now

**Comment by melithine** [comment]
> i'm having same problem now

Is it showing INTERNAL SERVER ERROR in all caps or the format the op mentioned?

**Comment by Leryn** [comment]
> > i'm having same problem now
> 
> Is it showing INTERNAL SERVER ERROR in all caps or the format the op mentioned?


don't know, sorry i'm not so expert like you guys about this stuff, i only know that i can't download DRM videos. before i had the same identical message in the image of this thread, now i updated ffmpeg and it says even worst

" Exception caught: Cannot find FFmpeg in C:\Users\Emiliano\Documents\OF.DL.V1.7.61 or PATH. This package needs installed FFmpeg. Please add it to your PATH variable or specify path to DIRECTORY with FFmpeg executables in FFmpeg.ExecutablesPath"

don't know why since the path didn't change, i only copied the new ffmpeg.exe to overwrite the old one

**Comment by Leryn** [comment]
> > i'm having same problem now
> 
> Is it showing INTERNAL SERVER ERROR in all caps or the format the op mentioned?


no idea, sorry not so expert about this stuff, but now it's even worst, before i wasn't able to download drm videos, so i updated OF DL with latest version and also i uploaded ffmpeg, and now i got this

Exception caught: ffmpeg version git-2020-08-31-4a11a6f Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200805
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.101.101 / 58.101.101
  libavformat    58. 51.101 / 58. 51.101
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Unrecognized option 'cenc_decryption_key'.
Error splitting the argument list: Option not found

                                                   StackTrace:    at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass14_0.<RunProcess>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Xabe.FFmpeg.Conversion.Start(String parameters, CancellationToken cancellationToken)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, Stri                                                              Time lastModified, Int64 media_id, String api_type, Progre

**Comment by Leryn** [comment]
i think it's a problem with ffmpeg don't know why, is the latest version, config.json path is correct but now it says 

Cannot locate FFmpeg; Attempting to download latest version.Exception caught: Value cannot be null. (Parameter 'path1')

now i can't even try to download

**Comment by Leryn** [comment]
> > i'm having same problem now
> 
> Is it showing INTERNAL SERVER ERROR in all caps or the format the op mentioned?


before i had the same identical message of the pic of the thread, now i tried to update ffmpeg and OF DL and can't even login. now i deleted everything, later i'll try to reinstall everything and let u know

**Comment by Leryn** [comment]
> > i'm having same problem now
> 
> Is it showing INTERNAL SERVER ERROR in all caps or the format the op mentioned?


ok done, i deleted everything and installed everything again. before this i had the same error showed in the pics of the thread, now i have a different error.  i can download pics and video without drm with no problem, but if i try to download a drm video, here is what it says


Exception caught: Cannot find FFmpeg in "C:\Users..."  (my path). This package needs installed FFmpeg. Please add it to your PATH variable or specify path to DIRECTORY with FFmpeg executables in FFmpeg.ExecutablesPath

                                                              StackTrace:    at Xabe.FFmpeg.FFmpeg.ValidateExecutables()   at Xabe.FFmpeg.FFmpeg.FindAndValidateExecutables()
   at Xabe.FFmpeg.FFmpeg..ctor()
   at Xabe.FFmpeg.FFmpegWrapper..ctor()
   at Xabe.FFmpeg.Conversion.Start(String parameters, CancellationToken cancellationToken)
   at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, Stri                                                              Time lastModified, Int64 media_id, String api_type, Progre


that's all, i think it's not a problem of ffmpeg or any path because as i said i can download everything except drm videos. first time i have this problem. obviously all exe are at last version

**Comment by Leryn** [comment]
it's weird but i back to 1.7.74 and it's working now

**Comment by Leryn** [comment]
stilll having some problems with drm videos, i noticed that if u get video from single post is better, if it fails to download, try again the same link and it should download, at least in this way it's working for me

**Comment by melithine** [comment]
> stilll having some problems with drm videos, i noticed that if u get video from single post is better, if it fails to download, try again the same link and it should download, at least in this way it's working for me

The ffmpeg error is a separate issue. Under 1.7.74, when it fails, is it showing the 500 (Internal Server Error) that the op saw, 500 (INTERNAL SERVER ERROR) - that's usually cdrm-project having issues, or is it showing something else instead? Trying to keep these threads on track, so if it's not matching what the original poster reported, it needs to be moved to a different issue instead.

**Comment by Leryn** [comment]
> > stilll having some problems with drm videos, i noticed that if u get video from single post is better, if it fails to download, try again the same link and it should download, at least in this way it's working for me
> 
> The ffmpeg error is a separate issue. Under 1.7.74, when it fails, is it showing the 500 (Internal Server Error) that the op saw, 500 (INTERNAL SERVER ERROR) - that's usually cdrm-project having issues, or is it showing something else instead? Trying to keep these threads on track, so if it's not matching what the original poster reported, it needs to be moved to a different issue instead.

no, now when it fails it's only showing the ffmpeg error, before with 1.7.75 i had the same identical message of the thread, 500 internal server error

**Comment by melithine** [comment]
Please try v1.7.76: https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.76

**Comment by Leryn** [comment]
it seems better now, especially with older videos, with new videos sometimes i still have the same error but i try again and it download, maybe because new videos have more protection

**Comment by btiplitz** [comment]
I also only have seen this recently, so I don't think it's an overloaded server. I suspect something changed on the of side.  Though I'm getting a 403 error

**Comment by melithine** [comment]
> I also only have seen this recently, so I don't think it's an overloaded server. I suspect something changed on the of side. Though I'm getting a 403 error

403s are very different than 500s. 403 is access denied, 500 is the target server is having problems.
