### ISSUE TITLE
says download successful but don't know where to find it

### ISSUE THREAD

**Issue by shitakeyumyum** [sim0n00ps/OF-DL#557]
![image](https://github.com/user-attachments/assets/71ba3d7d-3cda-42bc-bf79-4adb77bb8408)
![image](https://github.com/user-attachments/assets/42f69cbb-78cb-435e-ab56-4679c587c53b)

says post is downloaded but i can't find it in the userdata folder

**Comment by darhanger** [comment]
Same
![image](https://github.com/user-attachments/assets/ba5dd456-b105-486b-8a77-780e47f0fcaf)

**Comment by melithine** [comment]
Those errors indicate it was not successful. Looks like both of you are using cdrm-project and they're having issues. If you hit me up on Discord, I can give you widevine keys so you don't have to rely on them.

**Comment by lexus033** [comment]
> Esos errores indican que no fue un éxito. Parece que ambos están usando cdrm-project y están teniendo problemas. Si me golpeas en Discord, puedo darte llaves anchas para no tener que confiar en ellas.

Hello, sorry, I have the same error, what is your discord so you can help me please?

**Comment by melithine** [comment]
On the OFDL server I'm Melithine. I allow PMs from people who are on that server.
