### ISSUE TITLE
Auth.json??

### ISSUE THREAD

**Issue by JakeSF93** [sim0n00ps/OF-DL#56]
Using Windows 10.

I'm sure I'm overlooking something embarrassingly simple, but...where is auth.json? I downloaded OF-DL-master.zip, extracted, and searched the folder for auth.* and *.json. There's an auth.cs, but no auth.json. In fact, there is no OF DL.exe (or any *.exe) or e_sqlite3.dll, or any *.dll either.

What am I doing wrong?

**Comment by Puk0** [comment]
Bajalo de 'Releases'  > https://github.com/sim0n00ps/OF-DL/releases > Assets > OF.DL.V1.7.12.zip

**Comment by sim0n00ps** [comment]
> Using Windows 10.
> 
> I'm sure I'm overlooking something embarrassingly simple, but...where is auth.json? I downloaded OF-DL-master.zip, extracted, and searched the folder for auth.* and *.json. There's an auth.cs, but no auth.json. In fact, there is no OF DL.exe (or any *.exe) or e_sqlite3.dll, or any *.dll either.
> 
> What am I doing wrong?

You've downloaded the wrong thing, you need to go to https://github.com/sim0n00ps/OF-DL/releases and download the zip file from the latest release, all the files you need are in that zip file

**Comment by JakeSF93** [comment]
Ah, very good. Thank you!

I've got it all configured and running, and it works -- but not on the profiles that use DRM. I verified the ffmpeg and yt-dlp installations and paths myself, and the application says: 

```
yt-dlp.exe located successfully!
ffmpeg.exe located successfully!
mp4decrypt.exe located successfully!
Logged In successfully as [name]
```

Here are the messages I'm getting:

```
Scraping Data for [user]
Created folder for [user]
Getting Paid Posts
Found 0 Paid Posts
Getting Posts
Found 11 Posts

Downloading 11 Posts ----------------------------------------   0% 0.0/177.6 MB --:--:--
                                                                                        Exception caught: Response status code does not indicate success: 403 (Forbidden).

                                                  StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessSta
Downloading 11 Posts ----------------------------------------   0% 0.0/177.6 MB --:--:--dia_id, ProgressTask task)
                                                                                        Exception caught: Response status code does not indicate success: 403 (Forbidden).
```
etc.
 
Followed by:

```
Downloading 11 Posts ----------------------------------------   0% 0.2/177.6 MB 00:48:39 signature, String kvp)
                                                                                        Exception caught: Could not find file 'E:\of dl\OF DL V1.7.12\__user_data__\sites\OnlyFans\[creator]\Posts\Free\Videos\[filename]_source.mp4'.

          StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                        ing decryptionKey, String folder

```

And at the end: 

```
Downloading 11 Posts ----------------------------------------   0% 0.2/177.6 MB 00:48:39dia_id, ProgressTask task)
                                                                                        Exception caught: Response status code does not indicate success: 403 (Forbidden).

                                                  StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessSta
Downloading 11 Posts ----------------------------------------   0% 177.6 MB 00:00:00    re, String kvp)

Posts Already Downloaded: 6 New Posts Downloaded: 2
```

Not sure if I did something wrong (having to do with mp4decrypt, presumably), or if this is related to what I asssume is a rate-limiting feature OF has introduced. The successful test I did earlier (on another profile, not DRM-protected) only had one video to download (I already had the rest). 

Is trying to download multiple files at once causing it to throttle me? When I browse the profile in question in Firefox, the videos don't show up or play. I have had this happen before -- typically after downloading multiple videos (manually), and the problem disappears after 15-20 minutes of inactivity. Or am I just doing something wrong?

**Comment by Puk0** [comment]
Puedes cambiar la ip
y/o
salir y volver a entrar a la cuenta para que genere otra cookie

**Comment by JakeSF93** [comment]
I definitely have enough space on disk. 

I tried signing out and signing back in again. I also tried clearing cookies/restarting browser. Right now, I can't see posts (screenshot below). It did this to me yesterday for a time as well before resolving on its own. I suspect this may be a feature they added to impose rate limits on possible downloaders, and I assume it's related to the problem I'm having with OF-DL, but I really don't know.

![OF screen](https://github.com/sim0n00ps/OF-DL/assets/138366385/23a2a51c-1da1-464f-9ae8-94cb79bba453)

**Comment by Puk0** [comment]
A mi me pasaba eso de las images cuando cambiaba la dirección ip, la volvia a poner la anterior y ya se veian

**Comment by DonaldTPP** [comment]
If you're using a VPN, disable it.

**Comment by sim0n00ps** [comment]
> I definitely have enough space on disk. 
> 
> I tried signing out and signing back in again. I also tried clearing cookies/restarting browser. Right now, I can't see posts (screenshot below). It did this to me yesterday for a time as well before resolving on its own. I suspect this may be a feature they added to impose rate limits on possible downloaders, and I assume it's related to the problem I'm having with OF-DL, but I really don't know.
> 
> ![OF screen](https://github.com/sim0n00ps/OF-DL/assets/138366385/23a2a51c-1da1-464f-9ae8-94cb79bba453)
> 

If none of the media is showing up then you've been rate limited and you probably should wait a few hours before trying again

**Comment by JakeSF93** [comment]
Do you think the VPN could be causing it?

Anyway, I got banned. I'll make a new account and try again tomorrow. Hopefully it was just the throttling. Assuming it works, I'll close the thread.
