### ISSUE TITLE
Cannot find url for OF messages

### ISSUE THREAD

**Issue by thechickencow808** [sim0n00ps/OF-DL#565]
I am able to find the Copy Link button in the Purchases tab. But how do I find the URL of a message NOT in the purchase tab? When I click the three dots, I only see "Copy, Unlike, Reply, Pin, Hide, Report." Thanks so much!

**Comment by melithine** [comment]
Onlyfans doesn't support that, for whatever unknown reason.

**Comment by thechickencow808** [comment]
> Onlyfans doesn't support that, for whatever unknown reason.

Well...that's annoying. Any work around to downloaded media from messages not in the purchase tab? I tried to F12/Inspect and view the page source, but couldn't find usable URL (I'm also not versed in code, so may not have been searching in the right spot).
