### ISSUE TITLE
Program shuts down after locating everything in the auth correctly video of error inside

### ISSUE THREAD

**Issue by mallson1** [sim0n00ps/OF-DL#57]
All the text is green, the program finds my Onlyfans username, then a bunch of white text pops up and the program shuts down, is this Onlyfans fighting back or is there something I need to tweak?

[[](url)

https://github.com/sim0n00ps/OF-DL/assets/74335155/850caa66-724e-457e-a723-82cc1047ee49

**Comment by sim0n00ps** [comment]
Are you on the latest release?

**Comment by sim0n00ps** [comment]
I can see you're folder name, OF DL V1.7.10, the latest release is 1.7.12 which fixes the exact issue you're facing

**Comment by Galrolath123** [comment]
I'm having the same problem and im on 1.7.12.

**Comment by sim0n00ps** [comment]
That's a totally different error, not related to this one the OP was on about, nothing I can do about exceptions like that so it will be down to something you have set up on your hardware

**Comment by mallson1** [comment]
> I can see your folder name, OF DL V1.7.10, the latest release is 1.7.12 which fixes the exact issue you're facing

Thanks, I switched to the other version works fine great work you have done here!

I
