### ISSUE TITLE
Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

### ISSUE THREAD

**Issue by lucacham** [sim0n00ps/OF-DL#570]
I would like to ask what is the cause of this? I was still using it normally an hour ago

Now, the posts of some users I subscribe to can be downloaded normally, but the posts of some users will download errors

![image](https://github.com/user-attachments/assets/85b65421-180f-40fc-b750-c889d49971d8)

**Comment by melithine** [comment]
Usually cdrm-project having issues. Hit me up in Discord for widevine keys, or generate your own.

**Comment by cars11** [comment]
generated my own and still getting this issue. any ideas?
