### ISSUE TITLE
Cannot re-download failed posts

### ISSUE THREAD

**Issue by richardjdunn** [sim0n00ps/OF-DL#579]
While fetching some points, my disk ran out of space, and the app failed to download them.  When I tried to re-download, they didn't, probably because the app thought they'd already downloaded.  I removed the records from the DB (posts, messages, medias) but it still thinks they are already downloaded.  Is there some other data source I am missing?

Thanks

**Comment by melithine** [comment]
In the Metadata folder for each user there's a small database. Remove that and it'll forget things were previously downloaded.

**Comment by richardjdunn** [comment]
Yeah I was trying to avoid downloading everything again, just the stuff
that failed. Deleting those rows in the appropriate tables didn’t seem to
work, I’m not sure why.

**Comment by richardjdunn** [comment]
Needed to delete the underlying files as well
