### ISSUE TITLE
Downloading A Message Post

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#582]
Within the OFDL tool there is an option "Download Single Message" 

However I am not sure how to get the link for the message? is there some sort of guide or is anyone able to provide me the steps on how to download a post in a message? 

Thank you

**Comment by melithine** [comment]
From the Purchased tab, click the three dots and copy link to message.

There is no way currently to get a link to a message that is not in the purchased tab.
