### ISSUE TITLE
Auth failed in docker container due to exception

### ISSUE THREAD

**Issue by jimbo831** [sim0n00ps/OF-DL#587]
When running this on a Mac in a Docker container, I get an exception leading to the auth to fail. I have used the browser extension to build the auth.json file just to be sure.  Here is a redacted version of my auth file with some info randomized:

`{
    "USER_ID": "567895664",
    "USER_AGENT": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
    "X_BC": "5d6f4a6df7498da7f8ea4984",
    "COOKIE": "sess=56df4da654f6d5f; auth_id=567895664;"
  }`

Here is the exception stack trace I see in Docker:

> Exception caught: The format of value '' is invalid.

> StackTrace:    at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at OF_DL.Helpers.APIHelper.BuildHttpRequestMessage(Dictionary`2 getParams, String endpoint) in /src/OF DL/Helpers/APIHelper.cs:line 113
   at OF_DL.Helpers.APIHelper.GetUserInfo(String endpoint) in /src/OF DL/Helpers/APIHelper.cs:line 196
> Auth failed, please check the values in auth.json are correct.

**Comment by melithine** [comment]
That looks like it didn't pick up your actual `auth.json` file and was using the default instead. Can you post your `docker run` command and the complete path to your config files? (Feel free to replace your username with USERNAME if you want to redact that.)

**Comment by jimbo831** [comment]
You were correct. There was a typo in the config path, but I didn't realize it because the log said my config file was detected. I didn't realize it was using a default config file. Thanks for your help!
