### ISSUE TITLE
source file cannot be downloaded

### ISSUE THREAD

**Issue by engomingo** [sim0n00ps/OF-DL#59]
![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/2ccda2f2-f9fd-488d-b967-444799616323)
![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/6158c125-7601-431e-9a5f-b5541fe0583f)

I am getting the above error and the source file cannot be downloaded

**Comment by edge-evolution** [comment]
Having the same issue. Except mine don't even get that far as creating a temp file.

**Comment by sim0n00ps** [comment]
> ![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/2ccda2f2-f9fd-488d-b967-444799616323)
> ![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/6158c125-7601-431e-9a5f-b5541fe0583f)
> 
> I am getting the above error and the source file cannot be downloaded

The top error is the key one to your problem, it's trying to get the decryption key for the video and audio but the site it gets sent to is being blocked by something you have set up, if you have an antivirus or something else blocking access to the site then you need to either turn it off or tell it to ignore https://cdrm-project.com

**Comment by engomingo** [comment]
I started getting this error today. I cannot access the site you sent. I can't even login with vpn

**Comment by sim0n00ps** [comment]
> I started getting this error today. I cannot access the site you sent. I can't even login with vpn

I believe the site is actually down at the moment so you won't be able to download any DRM stuff for now

**Comment by engomingo** [comment]
Is this just for me or for everyone?

**Comment by sim0n00ps** [comment]
> Is this just for me or for everyone?
> 

Everyone

**Comment by engomingo** [comment]
i see mate. I hope you solve the problem as soon as possible

**Comment by sim0n00ps** [comment]
> i see mate. I hope you solve the problem as soon as possible

Nothing I can do on my end sadly so it's just a matter of waiting for the owner to fix the site

**Comment by slmcrs** [comment]
If I have my own decryption keys, is there a drop in replacement I can self host?

**Comment by sim0n00ps** [comment]
> If I have my own decryption keys, is there a drop in replacement I can self host?

Let the script download the encrypted files and then you can use mp4decrypt.exe to decrypt the videos manually.

**Comment by JIREXv1** [comment]
> If I have my own decryption keys, is there a drop in replacement I can self host?

How do i get my own decryption keys? 🤔

**Comment by sim0n00ps** [comment]
> > If I have my own decryption keys, is there a drop in replacement I can self host?
> 
> How do i get my own decryption keys? 🤔

Plenty of tutorials online.

**Comment by hebeebee** [comment]
> If I have my own decryption keys, is there a drop in replacement I can self host?

So do u know how to get decryption keys？
