### ISSUE TITLE
Exception caught: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.

### ISSUE THREAD

**Issue by FTAMonkey** [sim0n00ps/OF-DL#593]
See for below issue. Getting an exception. Able to have it to download but nothing actually downloads and program stops running at 0% downloaded. Thanks fur help!

config.json located successfully!
Valid version of Windows found.
You are running OF-DL version 1.7.78
Latest GitHub Release version: 1.7.78
auth.json located successfully!
rules.json located successfully!
FFmpeg located successfully
device_client_id_blob and/or device_private_key missing, https://cdrm-project.com/ will be used instead for DRM
protected videos
Logged In successfully as [XXX]
Exception caught: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.

StackTrace:    at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at OF_DL.Helpers.DBHelper.CreateUsersDB(Dictionary`2 users)

Inner Exception:
Exception caught: Exception has been thrown by the target of an invocation.

StackTrace:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()

**Comment by sim0n00ps** [comment]
Make sure you copied the .DLL file as well as the EXE from the release ZIP folder
