### ISSUE TITLE
Question: Massage Download.

### ISSUE THREAD

**Issue by Animalm4st3r** [sim0n00ps/OF-DL#596]
Hello friendows, been using this tool for quite sometime now. and the Message function is awesome. However lately i have ran into a problem.  How do i download free massages. The links to paid massages i get from the purchase tab but how do i download videos sent to me via massage for a tip without downloading the creators entire page.

**Comment by melithine** [comment]
You can't get links to free messages, only paid. Onlyfans weird devision. You can shut off Posts and PaidPosts and just scrape your messages with them, though, and then turn them back on.

**Comment by Animalm4st3r** [comment]
thanks! didnt even think about doing it that way

**Comment by Animalm4st3r** [comment]
im gonna necro my own post here. with another question, would this tool work on fansly too? or can anyone point me in the right direction for one cause the one im using is no longer getting updated and basically broke because fansly changed something

**Comment by melithine** [comment]
> im gonna necro my own post here. with another question, would this tool work on fansly too? or can anyone point me in the right direction for one cause the one im using is no longer getting updated and basically broke because fansly changed something

No. It can only work with OF.
