### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by czuo0303** [sim0n00ps/OF-DL#6]
Thanks for the tool! I successfully downloaded one paid message with DRM. 

However, when I tried to download free message with DRM, it showed "Object reference not set to an instance of an object." and later " Could not find file 'D:\OF\__user_data__\sites\OnlyFans\xxx\Messages\Free\Videos\0hdr1wtaed7glyjlc9" so in the end I got an encrypted 0hdr1wtaed7glyjlc9oup.f1.mp4 with a 0hdr1wtaed7glyjlc9oup.f4.m4a. 

I believe the original file name should be "0hdr1wtaed7glyjlc9oup_source.mp4". How do I fix this?

**Comment by sim0n00ps** [comment]
Done some digging and the service I used for getting the decryption keys is having some issues atm, give it a bit and hopefully they can get it fixed.

**Comment by czuo0303** [comment]
Thanks for the reply. The service is fixed now.
