### ISSUE TITLE
Account won't download

### ISSUE THREAD

**Issue by lukaeber** [sim0n00ps/OF-DL#604]
Trying to download an account with 470 posts (144 videos, 381 photos), but downloader will only download 1 photo. I've tried multiple times, with different settings (deleting the account DB and user DB multiple times) and it always only downloads the same single photo. No errors reported and logs look fine. Just will not recognize anything but the one post. There is no DRM on the account and other accounts download fine. Any ideas what is going on or how I can fix it?

**Comment by melithine** [comment]
Can you paste the output of the run?

**Comment by lukaeber** [comment]
Not sure what happened, but after three days of not downloading anything but 1 photo, I tried again tonight and it downloaded the whole account. Didn't change any settings so maybe an issue on the OF side?
