### ISSUE TITLE
Option to download Chat Messages

### ISSUE THREAD

**Issue by hml21619** [sim0n00ps/OF-DL#609]
Hello, this isnt a issue, more so a question. Some content is sent via chat messaging after a tip has been made on a specific campaign. When the creator sends the content after you tip, they send it to your chat message inbox. Hence, its not located in the purchase tab. Its just a stand alone video, with no link to copy. 

An example of the chat message inbox url would be as follows: https://onlyfans.com/my/chats/chat/42336632/ (the number changes when you go to a different inbox/from a different creator). Is there a way i can change the config so it can pull all content sent to a specific chat inbox? Apologies if i posted this question in the wrong section, im having trouble finding a suggestion section.

Thank You

**Comment by melithine** [comment]
This is the regular "Messages" category. You can't do it via single message scrape, since as you pointed out, there's no link. You would have to do a full scrape to get them (but you could turn off Posts, PaidPosts, Streams, Archived, Highlights, and PaidMessages and just scrape Messages for that specific creator).

**Comment by hml21619** [comment]
ok will try thanks

**Comment by hml21619** [comment]
> > ok will try thanks
> 
> where you able to download the content? im having this issue too, a creator sent me 2 videos via DM to stall me out from making me the custom video I paid her for and the scraper doesn't get to them, any more info on this?


yea. if u sent them a tip and then they sent you a video, make sure not to delete the DM they sent you. because if you do, the video will be lost (it wont be in purchase tab, since you paid via tip). After that, load the download, click custom, select creator and download. when u do this, the downloader will just grab everything, including vids sent to DM.  im sure theres a way to edit the config  so if can just download the DMs, but im too lazy to figure out how to change it. so i just rip everything and  delete what i dont want
