### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by miglety** [sim0n00ps/OF-DL#61]
Not entirely sure whats going on here, just happened to catch this after running a new scrape after subbing to someone new. Seems to hang there for a bit then skip past the user its attempting to scrape and continue on. 

![image](https://github.com/sim0n00ps/OF-DL/assets/92947145/68b62750-b58e-4f3a-8585-44e823ea9108)

**Comment by sim0n00ps** [comment]
The site used to get decryption keys is down so that's why you're getting the error, everyone will be facing this issue. Nothing I can I'm afraid.

**Comment by CaptainKoons** [comment]
> The site used to get decryption keys is down so that's why you're getting the error, everyone will be facing this issue. Nothing I can I'm afraid.

As you predicted, I have the same issue.
Is this site down only temporarily or permanent?

Thanks in advance!
CK

**Comment by sim0n00ps** [comment]
> > The site used to get decryption keys is down so that's why you're getting the error, everyone will be facing this issue. Nothing I can I'm afraid.
> 
> As you predicted, I have the same issue.
> Is this site down only temporarily or permanent?
> 
> Thanks in advance!
> CK

The guy just needs to pay for the hosting, it's on a monthly payment plan and he didn't pay for this month so the site went down.

**Comment by CaptainKoons** [comment]
Can we do something to speed up this process?
And is this issue related to issue #70 ?
