### ISSUE TITLE
Response status code does not indicate success: 429 (Too Many Requests)

### ISSUE THREAD

**Issue by BoiseBob** [sim0n00ps/OF-DL#610]
I'm getting this error after I successfully log in to my main account (from which I've previously scraped a lot of content). I do not get this error (and can scrape successfully) on my ALT account. I have tried this with and without specific CDM keys, and with and without a VPN running (IPVanish).

Can an individual account be flagged by OF from using the tool? Would love to get some content off my main account ASAP. As a point of data, since my last scrape I set dozens of OF accounts to blocked and most of the remaining are restricted. I changed the values in CONFIG for "IncludeExpired" and "IncludeRestricted" to FALSE to test and it still doesn't work. I also tried to rate limit in the CONFIG to no avail. Thanks!

Here is the full error string:

StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.BuildHeaderAndExecuteRequests(Dictionary2 getParams, String endpoint, HttpClient client)
   at OF_DL.Helpers.APIHelper.GetAllSubscriptions(Dictionary2 getParams, String endpoint, Boolean includeRestricted, IDownloadConfig config)
Exception caught: Object reference not set to an instance of an object.
StackTrace:    at OF_DL.Program.DownloadAllData(APIHelper m_ApiHelper, Auth Auth, Config Config)
   at OF_DL.Program.Main(String[] args) 

![Screenshot 2024-10-25 112549](https://github.com/user-attachments/assets/b444cd49-364e-41ed-a535-e77b5a776863)

**Comment by sim0n00ps** [comment]
That means you've been rate limited, probably want to wait a few hours or days before trying again, OF are annoying with rate limiting

**Comment by BoiseBob** [comment]
> That means you've been rate limited, probably want to wait a few hours or days before trying again, OF are annoying with rate limiting

Oh, crap, okay. I didn't know that was possible. My account functions normally when I use it, maybe a little balky at times. Is there anything else I can do to alleviate the limit? I tried OF-DL about 24 hours apart and failed both times, should I just not log in at all anywhere for a day or two? Longer?

**Comment by BoiseBob** [comment]
Latest release (1.7.80) appears to have fixed the issue. No clue how but this can be closed for now unless someone wants to elaborate on the issue for the sake of prosperity. Thanks!

**Comment by melithine** [comment]
> Latest release (1.7.80) appears to have fixed the issue. No clue how but this can be closed for now unless someone wants to elaborate on the issue for the sake of prosperity. Thanks!

I suspect the rate limit just expired, unless you can still repro it on 1.7.79. Either way, I'll close this, thanks.

**Comment by BoiseBob** [comment]
> > Latest release (1.7.80) appears to have fixed the issue. No clue how but this can be closed for now unless someone wants to elaborate on the issue for the sake of prosperity. Thanks!
> 
> I suspect the rate limit just expired, unless you can still repro it on 1.7.79. Either way, I'll close this, thanks.

FTR, I tried 1.7.79 immediately before the update and it didn't work. It feels like the update made the difference but nothing in the change log would lead me to know why. Maybe a fresh CONFIG file? But that doesn't make sense since .79 worked with my ALT account with that same altered CONFIG file. It's a mystery, but glad it's solved. Thanks!
