### ISSUE TITLE
 [ERR] Exception caught: Response status code does not indicate success: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by rstein2023** [sim0n00ps/OF-DL#616]
![Screenshot 2024-10-31 082045](https://github.com/user-attachments/assets/ea684e71-f23a-4a26-8f74-bbf28d33b06f)
Getting the following error after successfully logging in, Running 1.7.80 and the prog worked fine yesterday.

**Comment by rstein2023** [comment]
Disregard OF was having issues

**Comment by cars11** [comment]
i have this issue as well.

even went through the huge hassle to make my own drm keys as some other thread said it was because of that.. still didn't fix it
