### ISSUE TITLE
It only downloads a few minutes of video

### ISSUE THREAD

**Issue by gildonmor** [sim0n00ps/OF-DL#618]
I have everything installed correctly. When you select the option to download a video from a single post, it downloads the first few minutes. The remaining 20 minutes of video are not downloaded. I tried 3 videos and it's the same. I will add that the video can be played.

**Comment by deadbeatdandylyon** [comment]
Just curious have you confirmed if the full 20 minutes of the video can be played within the creators site without downloading?

**Comment by gildonmor** [comment]
Oops, I'm surprised. Well, I haven't tried it before... Should I play the whole video on the creator's website first?

**Comment by deadbeatdandylyon** [comment]
It's just a suggestion, but I would, it's rare but sometimes creators have uploaded malfunctioning videos before, i wouldn't say you have to play the whole 20 minutes but go to the 5 minute mark on the video and if it plays longer then that then you know that at least the video is working on the website, then what you can always try and do go to that creators folder on the computer and delete the "metadata" folder and then try to download the video again.

**Comment by gildonmor** [comment]
Great, thank you very much for the tip, I didn't think about that at all. I will write later if this solved the problem.

**Comment by deadbeatdandylyon** [comment]
You're very welcome, yeah not many people do, but yes do keep us posted

**Comment by gildonmor** [comment]
Well, this tip actually solved the problem! Everything is fine, thank you again!

**Comment by deadbeatdandylyon** [comment]
Glad to hear everything is working !
