### ISSUE TITLE
Username doesn't pop up in custom list when they restrict me from chat

### ISSUE THREAD

**Issue by nitroevo** [sim0n00ps/OF-DL#62]
I paid for a custom and the person restricted me from chat right after. Now it does not show their name pop up. How do I get the video now?

**Comment by DonaldTPP** [comment]
Try scraping paid content.

**Comment by nitroevo** [comment]
> Try scraping paid content.

That won't work due to their name not even popping up in the custom list anymore.

**Comment by sim0n00ps** [comment]
> > Try scraping paid content.
> 
> That won't work due to their name not even popping up in the custom list anymore. 

Have you got expired subscriptions set to true?

**Comment by nitroevo** [comment]
> > > Try scraping paid content.
> > 
> > That won't work due to their name not even popping up in the custom list anymore. 
> 
> Have you got expired subscriptions set to true? And by restricted what do you mean? 

Basically a semi-block. They disable you being able to chat with them.
