### ISSUE TITLE
[Minor Bug] When downloading, Media and Message Counts sometimes get mixed up?!

### ISSUE THREAD

**Issue by T3rminat0r** [sim0n00ps/OF-DL#620]
Hi, 

when downloading (via the purchased Tab method), I just came across this snippet:
```
Found 15 Media from 4 Paid Messages
Downloading 15 Paid Messages
```
Either it should be Downloading 15 Media or Downloading 4 Paid Messages ... but as it is, it's just wrong ;)

**Comment by sim0n00ps** [comment]
Looked into this, not really a bug, it is correct as it is downloading 15 pieces of Media which are from "Paid Messages"
