### ISSUE TITLE
the new version has virus

### ISSUE THREAD

**Issue by bike199999** [sim0n00ps/OF-DL#628]
but I replaced the application with the older version and it still works

**Comment by lucacham** [comment]
I permanently disabled Windows Security, which sometimes causes trouble...

**Comment by michi-777** [comment]
Hello,

Thank you for this great tool! I love it!

Starting with version V1.7.81 my Avast Free Antivirus finds a Malware in OF DL.exe. A check on https://www.virustotal.com/ confirms this:
![grafik](https://github.com/user-attachments/assets/9277b689-181b-4f31-9953-5afcc2aa5d6c)

All versions after V1.7.81 seem to be affected. When i roll back to V1.7.80 my AntiVirus doesnt find anything. Also VirusTotal has significantly fewer threats with the older versions. 

Does anyone have an idea what has changed from V1.7.80 to V1.7.81 that triggers alert warnings in AntiVirus programs?

Best regards

**Comment by melithine** [comment]
Nothing major has changed, it's a false positive of some kind. Only thing we can do is recommend you whitelist it. The code is open source and the builds are done through GitHub, so everything is out in the open. Noone's manually infecting a release version.
