### ISSUE TITLE
downloading a message video - get weird 404 error

### ISSUE THREAD

**Issue by morch-uk** [sim0n00ps/OF-DL#633]
works with most videos, even drm videos, that are on there on the purchased tab: so its just a case of videos that dont have a 'copy link' but are still in the messages tab

but a video i created the link for, which works in the browser - doesn't work in OF-DL

![image](https://github.com/user-attachments/assets/1728c206-1b10-4111-8443-925350f9998f)

I got the second chunk id in the link from the video preview as it doesn't appear in purchases as it was just sent to me

perhaps its just a thing the program doesn't get nicely - as not all videos purchased can end up in the purchased tab

**Comment by morch-uk** [comment]
the video is there if i download the ENTIRE account though, which can take a while - so odd - its treated as a free video

**Comment by sim0n00ps** [comment]
The Single Message is only for messages you've unlocked, you can't download free messages
