### ISSUE TITLE
Constant 500 server errors

### ISSUE THREAD

**Issue by Smackdab69** [sim0n00ps/OF-DL#636]
Tested with .79 and .83 versions, neither work

 Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

                                             StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatu

**Comment by melithine** [comment]
Looks like another cdrm-project issue. Hit someone like me up in Discord for Widevine keys so you don't need to use their service.
