### ISSUE TITLE
DRM content can't be downloaded

### ISSUE THREAD

**Issue by c3bb6f719742fd1e5768d6d1361cfb49** [sim0n00ps/OF-DL#638]
Hello,

I still can't download DRM content as I followed procedure to get device_client_id_blob and device_private_key.
There is something I get wrong or missing ? Any update from OF ?

![Capture d’écran 2024-11-16 204319](https://github.com/user-attachments/assets/5928f5d9-a327-4ee6-9f3e-1be2ddb8bfa3)

**Comment by deadbeatdandylyon** [comment]
I'm just a user like yourself, however just out of curiosity, what version of ffmpeg are you using?

**Comment by melithine** [comment]
I recommend 7.0.2 or later for ffmpeg. Earlier versions can cause this.

**Comment by c3bb6f719742fd1e5768d6d1361cfb49** [comment]
It worked !
Thanks a lot
