### ISSUE TITLE
If multiple pictures and/or videos are in one post, only first video/picture is downloaded

### ISSUE THREAD

**Issue by Treasure522** [sim0n00ps/OF-DL#640]
If multiple pictures and/or videos are in  one post, only first video/picture is downloaded and that post will show as already downloaded if you try to download it again. I have seen this occur multiple times on different page's walls (Free posts) and in paid messages and unpaid messages. 
![image](https://github.com/user-attachments/assets/db3b8006-2c75-4936-92dd-555bac73c2b3)
![image](https://github.com/user-attachments/assets/cbe287b4-ff57-4428-9283-198b42f795a1)

**Comment by melithine** [comment]
Are you using custom filename formats? If so, please paste them here for review.

**Comment by Treasure522** [comment]
Yes I am using custom filename formats. Here they are:

"PaidPostFileNameFormat": "{postedAt}_{username}_{id}_{text}",
  "PostFileNameFormat": "{postedAt}_{username}_{id}_{text}",
  "PaidMessageFileNameFormat": "{createdAt}_{username}_{id}_{text}",
  "MessageFileNameFormat": "{createdAt}_{username}_{id}_{text}",

**Comment by melithine** [comment]
It isn't unique enough, that will apply to all files on that message/post. Make sure to include `mediaId` or `filename` in your macro.

**Comment by melithine** [comment]
If you previously had non-unique filename formats, you will need to wipe out the Metadata folder to rescrape them, or the entire creator folder (would be my recommendation).

**Comment by Treasure522** [comment]
The metadata folder is the folder with just the one item that says "user_data" . When you say wipe the entire creator folder, do you mean delete everything that has been downloaded for the creator and then redownload everything?

**Comment by deadbeatdandylyon** [comment]
He means the actual folder that says "metadata" right click on delete, the only file within the "metadata folder" is "user_data" once you do a re-scrape the metadata folder will be a fresh copy.

**Comment by Treasure522** [comment]
oh ok. Yeah deleting the metadata did get it to download things it had not before when I wasn't getting errors, so that's good. It didn't seems to check for what was in the folder though, so I got a lot of duplicates. Maybe because the naming was updated? Just have to go in and delete the old copies. Thank you for the assistance and information! :D

**Comment by melithine** [comment]
That's why I suggested removing the entire creator's folder instead.
