### ISSUE TITLE
500 (INTERNAL SERVER ERROR)

### ISSUE THREAD

**Issue by djmarioka** [sim0n00ps/OF-DL#643]
Hi,

I'm receiving this error:

<img width="844" alt="image" src="https://github.com/user-attachments/assets/d12bb4fc-dd4f-464f-b693-94bb4c979dec">

in some subscriptions:  **500 (INTERNAL SERVER ERROR).** 

Could anybody know how to fix this issue?.

Thanks.

**Comment by milestales** [comment]
I have the same problem Y-Y

**Comment by deadbeatdandylyon** [comment]
I'm just a normal user like you all, I just attempted to run a scrape from my end on an account and it was able to scrape without any issues. 

Some suggestions, Make sure you have the latest version of OF-DL, Make sure your auth.json has the correct information, Also go to the said creators folder and delete the metadata folder and then try running the scrape again.

**Comment by melithine** [comment]
The all caps "internal server error" is a message from cdrm-project and can be solved with cdm, aka Widevine, keys. Several folks on Discord can help you out with providing those.
