### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by xanda971** [sim0n00ps/OF-DL#644]
<img width="586" alt="Screenshot 2024-12-05 at 3 02 20 PM" src="https://github.com/user-attachments/assets/51831786-aa49-4904-adbb-7ede05395de4">

used to be functioning, but now it shows this?

**Comment by BingBongoDingo** [comment]
you have to update auth.json every once in a while, when you get logged out of in your browser. Theres a browser extension to help deal with this (https://sim0n00ps.github.io/OF-DL/docs/config/auth#browser-extension). It's right in front of you there in the screenshot you uploaded. Please check out documentation before asking questions or raising issues

**Comment by deadbeatdandylyon** [comment]
As well as sometimes if the browser updates it will change the Sess Cookies and the user agent

**Comment by BingBongoDingo** [comment]
Right on dandylyon that makes total sense. Regardless this is truly a non-issue and should be closed. The simple solution is to get the browser extension, and that's clearly layed out in the docs and even the screenshot posted (which OP should've read in the first place)

**Comment by devdeviant** [comment]
what's weird is the latest version (as of this writing 1.7.83) application appears to be overwriting my auth file

**Comment by cguweb-com** [comment]
the note about user agent causing an issue seems true.  Chrome updated the other day, now I cannot access, no matter if I manually update the auth file, or use extension to grab it - I cannot authenticate!  

how can I get past the agent issue? or completely reset and start fresh?
