### ISSUE TITLE
HELP !!! : config.json is not valid, check your JSON syntax!

### ISSUE THREAD

**Issue by tekkayutra** [sim0n00ps/OF-DL#646]
Hello, I don't know anything about this, but I followed the tutorial from the video step by step and I get this error. If someone can help me.

![Capture d’écran 2024-12-07 130129](https://github.com/user-attachments/assets/5c5e71ee-0288-48c6-b39d-366d7c784b84)

**Comment by deadbeatdandylyon** [comment]
*note* just a normal user attempting to help.

What it looks like is that there may be something that is not configured correctly in your `config.json` after you have downloaded the `OFDLV1.7.83.zip` and unzipped it. inside the zipped folder you will see a file that says `config` open it up in notepad and double check that where it shows `FFmpegPath` it is showing the correct path to where the FFmpeg file is that you downloaded if you have downloaded it, also you need to replace any "\" to the reverse "/"

**Comment by tekkayutra** [comment]
Thank you, I found my mistake. 
When copying the path "D:\OFDLV1.7.83\ffmpeg.exe", 
I didn't replace the backslash "\" with a forward slash "/"

Thank you for your help.

**Comment by tekkayutra** [comment]
Thank you, I found my mistake.
When copying the path "D:\OFDLV1.7.83\ffmpeg.exe",
I didn't replace the backslash "" with a forward slash "/"

Thank you for your help.
