### ISSUE TITLE
Auth failed in docker container due to exception caught

### ISSUE THREAD

**Issue by greenman88** [sim0n00ps/OF-DL#647]
I am running this on a Mac in a Docker container and I am getting an exception leading to the auth to fail. I have used the browser extension to build the auth.json file to be sure. 

Here is the exception stack trace I see in Docker:

<img width="1081" alt="Screenshot 2024-12-08 at 9 42 33 PM" src="https://github.com/user-attachments/assets/6b09dddb-3db5-4004-bd35-08afe7d2ade1">

Here is a redacted version of my auth file with some info randomized:

{
  "USER_ID": "91506445",
  "USER_AGENT": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
  "X_BC": "804a445972811e03de2421c814b4faf69f1dbbyb",
  "COOKIE": "auth_id=91907645; sess=g9lv7ilkd58o5acc6p7pmjtso4;"
  "FFMPEG_PATH": "/Users/johnsmith/Documents/Library/ffmpeg.exe"
}

**Comment by deadbeatdandylyon** [comment]
I'm not to familar with MAC and I'm just a normal user 

1) I know that within the `config.json` file if you have that as well the correct wordage "FFmpegPath" without the underscore - So you may want to change that. 
2) I would remove the ffmpeg path information from the Auth file to the Config.json file if you have one, 

Then I would test

**Comment by greenman88** [comment]
Hmm that didn't work. 

These to lines seem the be the issue 
"device_client_id_blob and/or device_private_key missing, "
"Exception caught: The format of value '' is invalid."

**Comment by deadbeatdandylyon** [comment]
For the CDM keys, you can do 1 of the following 

1) you can follow the instructions on [here](https://sim0n00ps.github.io/OF-DL/docs/config/cdm) to try to get the keys yourself 

2) you can join the discord [here](https://discord.com/invite/6bUW8EJ53j) and someone can help you get the keys, if you don't feel comfortable attempting it yourself

**Comment by melithine** [comment]
For Docker usage, FFmpegPath should be set to `/usr/bin/ffmpeg` in config.json. For `auth.json `, try generating it using the browser extension. Missing the cdm keys will not affect authentication.

**Comment by melithine** [comment]
What does your docker run command look like and where is your auth.json located?

**Comment by greenman88** [comment]
My docker run command is:

docker run -it -v /{//Users/johnsmith/Documents/Library/Data}/:/data -v /{/Users/johnsmith/Documents/Library/OFDLV1.7.83}/:/config [ghcr.io/sim0n00ps/of-dl:latest](http://ghcr.io/sim0n00ps/of-dl:latest)

auth.json is located in the path:

/Users/johnsmith/Documents/Library/OFDLV1.7.83/auth.json

**Comment by melithine** [comment]
Your syntax is wrong. Try `docker run -it -v /Users/johnsmith/Documents/Library/Data/:/data -v /Users/johnsmith/Documents/Library/OFDLV1.7.83/:/config http://ghcr.io/sim0n00ps/of-dl:latest`

**Comment by greenman88** [comment]
This worked:

docker run -it -v //Users/johnsmith/Documents/Library/Data/:/data -v //Users/johnsmith/Documents/Library/OFDLV1.7.83/:/config ghcr.io/sim0n00ps/of-dl:latest
