### ISSUE TITLE
Program not detecting purchased messages/says DRM wall posts already downloaded

### ISSUE THREAD

**Issue by hhh45444** [sim0n00ps/OF-DL#651]
I have been having trouble for a few weeks downloading anything using the program. My usual fixes (updating ffmpeg, reinstalling, deleting metadata, trying to download again) haven't done anything and I am still receiving the same messages. On paid messages it's not detecting the message and I am receiving "Found 0 paid messages" and for DRM wall posts I am receiving a weird message showing the post was already downloaded. Please help I love this program so much. Thank you!

![ScreenShot_20241211130630](https://github.com/user-attachments/assets/f3741ed1-924b-4d04-8ff8-683ec7bb57db)
![ScreenShot_20241211130900](https://github.com/user-attachments/assets/bbca0882-7c69-417c-84b6-2631486e7771)

**Comment by deadbeatdandylyon** [comment]
Just a normal user

For me, When I do a scrape of any page it always starts off the same as your image above 

![image](https://github.com/user-attachments/assets/b5259094-6135-45c4-b172-94b9de3ef63e)

It's not until the very bottom it may show paid messages 

As far as the found DRM wall post it's possible the creator posted video more then once and it already downloaded, Have you already confirmed in the following two sections that the video wasn't already downloaded 

Creator Name > Posts > Free > Videos 

Messages > Free > Videos > 
Messages > Paid > Videos >

**Comment by hhh45444** [comment]
I'm not doing a scrape. Downloading individual ppv messages and wall posts. Nothing is downloaded when I check the folders. I move the files from the initial download folder so nothing should say already downloaded based on how I use the program and move files

**Comment by melithine** [comment]
> I'm not doing a scrape. Downloading individual ppv messages and wall posts. Nothing is downloaded when I check the folders. I move the files from the initial download folder so nothing should say already downloaded based on how I use the program and move files

That's only true if you delete the Metadata folder for the creator. Otherwise it still knows what you have previously downloaded.

**Comment by hhh45444** [comment]
I've deleted the folders and even deleted then reinstalled the program

**Comment by hhh45444** [comment]
The scrape works, but I really had to play around with the config.json settings. Thank you!
