### ISSUE TITLE
Response status code does not indicate success: 500 (INTERNAL SERVER ERROR)

### ISSUE THREAD

**Issue by gittyup-debug** [sim0n00ps/OF-DL#654]
It was working yesterday. But today I get the following error when I choose "Custom" and select the page to download (any new posts). I closed and restarted, but didn't help.

![OFD2](https://github.com/user-attachments/assets/a62ae60c-a7a3-4d92-9662-2e5ace719033)

Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

                                         StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryp
Downloading 533 Posts ----------------------------------------   0%   api_type, ProgressTask task, String customFileName, SDownloading 533 Posts ----------------------------------------   0%
                                                                   Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

                                                                                                                                                                 StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at OF_DL.Helpers.APIHelper.GetDecryptionKey(Dictionary`2 drmHeaders, String licenceURL, String pssh)
Exception caught: Object reference not set to an instance of an object.

                                                                       StackTrace:    at OF_DL.Helpers.DownloadHelper.DownloadDrmMedia(String user_agent, String policy, String signature, String kvp, String sess, String url, String decryp
Downloading 533 Posts ----------------------------------------   1%ng api_type, ProgressTask task, String customFileName, String filename, String path)
                                                                   Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

                                                                                                                                                                 StackTrace:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCod
Downloading 533 Posts ----------------------------------------   1%ers, String licenceURL, String pssh)
                                                                   Exception caught: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).

**Comment by WolfX2323** [comment]
I am also having this 500 (INTERNAL SERVER ERROR) issue.

**Comment by gittyup-debug** [comment]
Seems to be working fine today (though running much slower than usual)
