### ISSUE TITLE
Release Windows arm64 version

### ISSUE THREAD

**Issue by jk779** [sim0n00ps/OF-DL#656]
Hi,

Although windows 11 is capable of emulating x86 when running on arm64 hardware, It’s very slow and turns the cpu to 100%. 

It’s probably enough to use a compiler flag like `-r win-arm64` but I’m just guessing. Maybe you can try to add a line with this flag here: https://github.com/sim0n00ps/OF-DL/blob/6b823f44e1d2a35192f884ba7632971ba7936fe0/.github/workflows/publish-release.yml#L31 and release this version too? :)

**Comment by melithine** [comment]
ARM builds with .Net on GitHub are painful enough as is for the Docker image, and none of us have a Windows ARM system to test on. You can always compile it yourself, or if Docker Desktop works under Windows for ARM, you could run the ARM Docker container version. Docker ARM images are something I can at least test if needed, where I can't do that with Windows for ARM.

**Comment by jk779** [comment]
I'm using an arm docker image now and it works pretty good. so thats a decent and i'd say more convienient workaround then running it natively :)
