### ISSUE TITLE
Exception caught, everything located succesfully but still error

### ISSUE THREAD

**Issue by Chhleon** [sim0n00ps/OF-DL#661]
Getting Exception caught: Encountered unescaped ']' token at postion 40 etc...
![Screenshot-2024-11-07-11494531f1a9122a2af4f0](https://github.com/user-attachments/assets/dc292e96-3171-4008-958b-eb062c7951fb)

**Comment by melithine** [comment]
What output do you get before the exception? Looks like one of the config files is potentially malformed, but I can't tell which one from the exception itself.

**Comment by Chhleon** [comment]
Everything green and successful
![Screenshot 2024-12-27 034037](https://github.com/user-attachments/assets/b334efc5-014e-4114-91c0-df1c40be7333)

**Comment by melithine** [comment]
Ok, after processing `rules.json`, it goes and tries to look for ffmpeg, so that's where it's failing. What is your `FFmpegPath` set to in `config.json`?

**Comment by Chhleon** [comment]
Same place as before, I didnt change any settings from prior when it was working

**Comment by Chhleon** [comment]
ffmmpeg.exe was corrupted?, replaced.
