### ISSUE TITLE
Lots of errors, and files that seem to be split into audio and video both unreadable

### ISSUE THREAD

**Issue by mediaburnwayne** [sim0n00ps/OF-DL#69]
2% 0.4/12.8 GB 01:42:26
                                                                                         Exception caught: Could not find file 'H:\OF DL\__user_data__\sites\OnlyFans\mymindbreaks\Posts\Free\Videos\0hf5gyp9kmuh634fyz3ge_source.mp4'.

                                                                                                               StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder
Downloading 2091 Posts ----------------------------------------   2% 0.4/12.8 GB 02:51:05

Another error
Error getting file size for URL 'https://cdn2.onlyfans.com/files/c/c2/c2a729dd34b4a72458b350aaf8f12442/2316x3088_c9f954b491333bfdb412708477b83bf6.jpg?Tag=2&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvY1wvYzJcL2MyYTcyOWRkMzRiNGE3MjQ1OGIzNTBhYWY4ZjEyNDQyXC8yMzE2eDMwODhfYzlmOTU0YjQ5MTMzM2JmZGI0MTI3MDg0NzdiODNiZjYuanBnP1RhZz0yIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg4ODg2OTY0fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjE1NC42LjgzLjE0NlwvMzIifX19XX0_&Signature=iW-LBI1aSZHo88Opyl1KzRinenHfULLT2ccwSQJvaknbfz5tKThpuIHPeWa6rM0wmv1bQ0pXXuEc1qiDEFDSHz7UPaWSxkWRDK1mKlWRNs8-msbIV2fDRSZhjRiaQAHtqe55mG4QrIirdD1Z4qxeUu9j9yCy6osG7GZ4bJmmm-v~vrJrNWYvDYg-BlwD1otalMUN6fVjj-xTdJv9TNdV3qqylSutHCV91YEvoCW4W35p-D11HHMahJB-StaZF7bYq~pZYf0-yVUhEXKLENKPUXonlTzOtkb~L6plpsG~NJ3vI~TTj5doqKwQsH1tSGqQjyaJM19rn9eA95houshEBg__&Key-Pair-Id=APKAUSX4CWPPATFK2DGD': An error occurred while sending the request.
Error getting file size for URL 'https://cdn2.onlyfans.com/files/4/4a/4a7dfd71504a42340b7300a60f3c3bd0/2316x2316_9329d818fccf465ac46411eb8b3028d5.jpg?Tag=2&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6XC9cL2NkbjIub25seWZhbnMuY29tXC9maWxlc1wvNFwvNGFcLzRhN2RmZDcxNTA0YTQyMzQwYjczMDBhNjBmM2MzYmQwXC8yMzE2eDIzMTZfOTMyOWQ4MThmY2NmNDY1YWM0NjQxMWViOGIzMDI4ZDUuanBnP1RhZz0yIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg4ODg2OTc5fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjE1NC42LjgzLjE0NlwvMzIifX19XX0_&Signature=VEiaJNhVWZhiwaFnVjGl5hZUYQu~6xs~yjYTsnVPODqSfr4-QU9zbmnN-0c~LmeQQBX4WMb2qgDxsEo5DWVQsr81Fl5vBuoBk9EF5Ap2xVMuCW-yExXqkB1SKOobJMMG~0-tOL~9~8LhHF2pKBRP4lDPcmsAwz9b7GGi33SsEev-v0ydrOQWgEVOId0LqAGeRfGjqJLVHhTcHIT~8Uh-kUY1LgDC8A6bH-EZ~HSQhLnUnilBYV0mxtu3ttiYpVLj4PXNrtjD4lbZSpYsCR7zpwr-xyH2DBQ7FaTN-474ip6nNpo1Evd7POgrKUGgLf91ik91P82Y8IOvRomtl5e0Ww__&Key-Pair-Id=APKAUSX4CWPPATFK2DGD': An error occurred while sending the request.

example broken/ split files

![error2](https://github.com/sim0n00ps/OF-DL/assets/79545392/e7c0df29-ac4b-43ea-8e30-fbc80b6a2233)

**Comment by Alexe-2023** [comment]
I am having the exact same issue it only download non-DRM.

**Comment by purpleemoji** [comment]
OF was down for a very long time yesterday. They were probably pushing updates that disabled the program's functionality. Having issues with other scrapers as well. I was kinda expecting this

**Comment by sim0n00ps** [comment]
It's because cdrm-project is down, nothing I can do
