### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by Cr4zyM0f01** [sim0n00ps/OF-DL#7]
Hi I'm new to all this stuff but I keep getting this message and nothing is downloading. Hoping someone can help me or point me in the right direction. 

Thanks in advance.

![SSL](https://github.com/sim0n00ps/OF-DL/assets/110260684/10347022-dd52-4557-be72-cd2020e82567)

**Comment by sim0n00ps** [comment]
I would maybe try and log out of OF and get a new session, re-enter the auth details such as `sess`

**Comment by Cr4zyM0f01** [comment]
Hi thanks for the reply. I logged out of onlyfans from all my devices changed everything in the auth.json, it logged in fine and can see all my subs but I'm still getting the "The SSL connection could not be established, see inner exception"

**Comment by sim0n00ps** [comment]
I've never seen this error occur in the whole time I've been making the program so hard to help you with this one. I'd say definitely check your auth.json file is correct and make the sure the user_id field doesn't contain a 'u' and is just a number, also make sure cookie field is laid out like auth_id=123356789; sess=your sess cookie;

**Comment by Cr4zyM0f01** [comment]
Would it be possible when printing an exception, the entire chain could be logged??

 Something similar to this:
```
for (var exception = ...; exception != null; exception = exception.InnerException)
    Print(exception.Message);
```
So that I can see if the issue is: actual (socket) connection cannot be established, or connection was established but handshake failed, if so why, etc.

Thanks again.

**Comment by sim0n00ps** [comment]
I can add some more detailed logging when it comes to exceptions being thrown in the next release which I will release soon

**Comment by sim0n00ps** [comment]
Try the latest release and see what is going on when it throws the exceptions

**Comment by Cr4zyM0f01** [comment]
Hi thanks again its giving me this now

```
Exception caught: The SSL connection could not be established, see inner excepti
on.

StackTrace:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslC
lientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async
, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request
, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequest
Message request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queu
eItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCanc
ellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectio
nAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(H
ttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationTok
en cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Bool
ean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage requ
est, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean
 disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken origi
nalCancellationToken)
   at OF_DL.Helpers.DownloadHelper.DownloadAvatarHeader(String avatarUrl, String
 headerUrl, String folder)

Inner Exception:
Exception caught: Authentication failed, see inner exception.

StackTrace:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdap
ter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancel
lationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthent
icationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream str
eam, CancellationToken cancellationToken)
```

**Comment by sim0n00ps** [comment]
I want to help you as much as I can but I have no idea what could be causing this, sorry.

**Comment by Cr4zyM0f01** [comment]
I appreciate all the help bro just wish I knew what was causing this. Maybe I'll just format the laptop and start fresh at some point lol because its frying my brain.

**Comment by Cr4zyM0f01** [comment]
I appreciate all the help bro just wish I knew what was causing this. Maybe I'll just format the laptop and start fresh at some point lol because its frying my brain.

**Comment by Cr4zyM0f01** [comment]
Seems like it was during handshake. I don't know if it's possible to see more exceptions? Because it looks like there was another inner exception.

**Comment by 232344235342** [comment]
@Cr4zyM0f01 Did you ever find a solution. I've got the same issue

**Comment by Tg00174** [comment]
i think it is VPN problem

**Comment by greyhat94** [comment]
I'm encountering the same issue when downloading the content of a model. I experienced such problem even if without using VPN.
