### ISSUE TITLE
Widevine exception

### ISSUE THREAD

**Issue by fendorix** [sim0n00ps/OF-DL#70]
I'm getting an exception when trying to download a drm protected video with 1.7.15 (see screenshot, I've removed my user id with yellow color). 
The drm keys are in correct place.

![drm](https://github.com/sim0n00ps/OF-DL/assets/11406419/2c31fa58-4564-4669-8041-e8dcceb1aecb)

The OF profile is free, the last video on the public feed produces this error.

**Comment by sim0n00ps** [comment]
Just tried a scrape on that profile and all of the post videos were download fine without any issues. I'd probably say run through the guide I linked again and follow everything exactly how he does it. Also make sure the device you create is a Pixel 6 and select Pie as the system image.

**Comment by GitDekTH** [comment]
got the same problem, i will re-re-check every step , but for now i dont see where i can miss a thing on the linked guide.

**Comment by bluman181** [comment]
If you have the bin and pem extensions on the files... remove them...

**Comment by sim0n00ps** [comment]
Just done some debugging and the SessionId is 1 long string of numbers and shouldn't contain any commas so you've definitely done something wrong

**Comment by fendorix** [comment]
Thanks for looking into it. Btw, I've censored what I thought was my user id by mistake. It looked identical but I didn't double check. It's not the user id.
The error is also not the session id, I've quickly stepped through the code and I fear it comes down to some Windows locale settings.

The exception is from
`RequestTime = uint.Parse((DateTime.Now - DateTime.UnixEpoch).TotalSeconds.ToString().Split(".")[0]),`
in CDM.cs line 222. Apparently the timespan on my system contains a comma. Changing the split parameter unfortunately does eventually lead to another exception:

`Exception caught: Could not find file 'F:\Data\src\OF-DL.git\OF DL\bin\Release\net7.0\__user_data__\sites\OnlyFans\lara6683\Posts\Paid\Videos\0hdq78l83qea6u4llwrai_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPurchasedPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, String user_agent, String policy, String signature, String kvp, String sess, String url, String decryptionKey, Stri                                                                                            t\OF DL\Helpers\DownloadHelp`

I don't have the time to debug it further right now, I'll look deeper into it, when I can.

**Comment by sim0n00ps** [comment]
Just commented out both lines 222 and 245 in CDM.cs and it can still get the keys correctly. Try that and see what happens.

**Comment by fendorix** [comment]
Quickly tested that and it still leads to the follow up exception I mentioned above and it does only download drm free videos.

**Comment by sim0n00ps** [comment]
Well what was the change you made to get it to this other exception? Probably best to delete the encrypted videos its probably downloaded and delete the metadata folder

**Comment by fendorix** [comment]
I'm deleting the user data folder every time I test something. I just tried the unchanged 1.7.15 in a windows sandbox with all language settings set to 'United States'. It fixes the original error, so it's really related to different time formats.
I still get the other exception, though. I'll try to debug it tomorrow.

**Comment by sim0n00ps** [comment]
Please do, any help is appreciated. Let me know how you get on

**Comment by gpaulelli** [comment]
having the same problem.
![Screenshot 2023-07-08 203635](https://github.com/sim0n00ps/OF-DL/assets/125941609/c6123d98-4d0d-4f97-b7d9-9be18656c0fc)

**Comment by fendorix** [comment]
So, I had a few more minutes and found the problem:
The language related exception is indeed fixed by removing lines 222 and 245 in CDM.cs.

My download problem was caused by an incomplete yt-dlp installation. Until now it was enough to just extract yt-dlp.exe and use that standalone. Now you need to extract the yt-dlp_win.zip including the Python interpreter that comes with it or yt-dlp fails to download drm videos.
After that I could do a full download of the profile.

Maybe you could extend the checks you do at startup and also look for 'python38.dll'. If that's missing, then probably the yt-dlp is not completely installed.

**Comment by gpaulelli** [comment]
is it working now with drm based videos? considering that cdrm-project sites are pretty much down now

**Comment by fendorix** [comment]
yes, it worked for me with drm videos (at least it did when I last tested it half an hour ago).

**Comment by gpaulelli** [comment]
changed it to yt-dlp_win.zip, no luck,

![Screenshot 2023-07-08 212000](https://github.com/sim0n00ps/OF-DL/assets/125941609/4fde3bd1-2a4d-495d-9bf4-49721b03ad03)

![Screenshot 2023-07-08 212031](https://github.com/sim0n00ps/OF-DL/assets/125941609/eb1530e5-4a5c-4bdb-ad5e-94c4c5581916)


![Screenshot 2023-07-08 212059](https://github.com/sim0n00ps/OF-DL/assets/125941609/effdcff0-190d-405c-9cea-675c78f8abb1)

idk about "The language related exception is indeed fixed by removing lines 222 and 245 in CDM.cs."

**Comment by fendorix** [comment]
> idk about "The language related exception is indeed fixed by removing lines 222 and 245 in CDM.cs."

There's been no new release with this fix included. You would have to compile of-dl yourself to test it now.

**Comment by gpaulelli** [comment]
guess i'll wait then, thanks btw.

**Comment by sim0n00ps** [comment]
I can remove those 2 lines and create a new release. I'm not sure what you're saying about yt-dlp.exe is correct as from the github you just need to download 1 exe file that has everything together, for the latest release you would download https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.exe

**Comment by fendorix** [comment]
> I can remove those 2 lines and create a new release. I'm not sure what you're saying about yt-dlp.exe is correct as from the github you just need to download 1 exe file that has everything together, for the latest release you would download https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.exe

Yes, sorry for the confusion. I just saw today, that during my troubleshooting I downloaded the wrong file. I picked yt-dlp_win.zip and extracted the yt-dlp.exe from that. In that case you need the entire content of the zip. 
Your link is the better one, since everything is packed in a single exe (probably with PyInstaller) and extracted at runtime.
Just ignore this, your documentation is correct and I picked the wrong download.

Thank you!

**Comment by sim0n00ps** [comment]
An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.

**Comment by gpaulelli** [comment]
okay, waiting for updates, rn i'm still cant get over with the issues i have

**Comment by nitroevo** [comment]
> An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.

what is the alternative?

**Comment by sim0n00ps** [comment]
> > An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.
> 
> what is the alternative?

https://keysdb.net/

**Comment by nitroevo** [comment]
> > > An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.
> > 
> > 
> > what is the alternative?
> 
> https://keysdb.net/ It works but I don't know what to make of it just yet as its so new

ok i'll check it out thanks. the other way is too complicated for me because when i follow the steps I keep getting an error when doing the python dump key file saying helper not found or something even though i have all the files in there.

**Comment by nitroevo** [comment]
> > > An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.
> > 
> > 
> > what is the alternative?
> 
> https://keysdb.net/ It works but I don't know what to make of it just yet as its so new

how do i use this along with your program to make it work?

**Comment by sim0n00ps** [comment]
> > > > An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.
> > > 
> > > 
> > > what is the alternative?
> > 
> > https://keysdb.net/ It works but I don't know what to make of it just yet as its so new
> 
> ok i'll check it out thanks. the other way is too complicated for me because when i follow the steps I keep getting an error when doing the python dump key file saying helper not found or something even though i have all the files in there.
> 

Only use that if you know what you're doing. You need to get the videos PSSH and license URL along with the headers sent with the request, if none of that makes any sense to you then I wouldn't bother.

**Comment by nitroevo** [comment]
> > > > > An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.
> > > > 
> > > > 
> > > > what is the alternative?
> > > 
> > > 
> > > https://keysdb.net/ It works but I don't know what to make of it just yet as its so new
> > 
> > 
> > ok i'll check it out thanks. the other way is too complicated for me because when i follow the steps I keep getting an error when doing the python dump key file saying helper not found or something even though i have all the files in there.
> 
> Only use that if you know what you're doing. You need to get the videos PSSH and license URL along with the headers sent with the request, if none of that makes any sense to you then I wouldn't bother.

was thinking i could find that under request headers in chrome but yeah. when i try the other way with command prompt for dump_keys.py i get errors saying "
line 6, in <module>
from Helpers.Scanner import Scan
ModuleNotFoundError: No module named 'Helpers'

**Comment by engomingo** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/c47e9cdb-b6ce-4aea-9353-cecd29f9cf8b)
![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/d9afc583-f286-4bb1-a1af-8860974fd2ba)
![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/410edbd5-9653-4cba-b2b2-cb6c3c150270)

I can't download the source file either.

**Comment by sim0n00ps** [comment]
> ![image](https://user-images.githubusercontent.com/138712352/252161464-c47e9cdb-b6ce-4aea-9353-cecd29f9cf8b.png) ![image](https://user-images.githubusercontent.com/138712352/252161420-d9afc583-f286-4bb1-a1af-8860974fd2ba.png) ![image](https://user-images.githubusercontent.com/138712352/252161452-410edbd5-9653-4cba-b2b2-cb6c3c150270.png)
> 
> I can't download the source file either.

Delete metadata folder for that user and try latest release

**Comment by nitroevo** [comment]
> > > > > An alternative to cdrm-project has been made and it is just an API really but requires you to log into discord to get an API key, I've tried it and it's legit so I'll give it a few days and see what people say about it before I switch back over.
> > > > 
> > > > 
> > > > what is the alternative?
> > > 
> > > https://keysdb.net/ It works but I don't know what to make of it just yet as its so new
> > 
> > ok i'll check it out thanks. the other way is too complicated for me because when i follow the steps I keep getting an error when doing the python dump key file saying helper not found or something even though i have all the files in there.
> > 
> 
> Only use that if you know what you're doing. You need to get the videos PSSH and license URL along with the headers sent with the request, if none of that makes any sense to you then I wouldn't bother.

Can please let me know what I'm doing wrong with the python part.

**Comment by engomingo** [comment]
> > ![image](https://user-images.githubusercontent.com/138712352/252161464-c47e9cdb-b6ce-4aea-9353-cecd29f9cf8b.png) ![image](https://user-images.githubusercontent.com/138712352/252161420-d9afc583-f286-4bb1-a1af-8860974fd2ba.png) ![image](https://user-images.githubusercontent.com/138712352/252161452-410edbd5-9653-4cba-b2b2-cb6c3c150270.png)
> > I can't download the source file either.
> 
> Delete metadata folder for that user and try latest release

the result is still the same.

**Comment by fendorix** [comment]
I can confirm that 1.7.16 fixes the reported problem for me. If you still get "input string was not in a correct format exception" with a comma in between, then you're not running the latest build since this code is gone.

**Comment by ViRGEdx** [comment]
> ModuleNotFoundError: No module named 'Helpers'

If you're still having this issue, make sure you're following the instructions for installing dump_keys. 

> Use pip to install the dependencies:

> pip3 install -r requirements.txt

You'll also need to make sure you unpacked the entire archive (and not just dump_keys.py), as there's a whole directory of additional scripts that dump_keys calls upon.

**Comment by engomingo** [comment]
> > > ![image](https://user-images.githubusercontent.com/138712352/252161464-c47e9cdb-b6ce-4aea-9353-cecd29f9cf8b.png) ![image](https://user-images.githubusercontent.com/138712352/252161420-d9afc583-f286-4bb1-a1af-8860974fd2ba.png) ![image](https://user-images.githubusercontent.com/138712352/252161452-410edbd5-9653-4cba-b2b2-cb6c3c150270.png)
> > > I can't download the source file either.
> > 
> > 
> > Delete metadata folder for that user and try latest release
> 
> the result is still the same.

worked in new version(1.7.16)

**Comment by GitDekTH** [comment]
> got the same problem, i will re-re-check every step , but for now i dont see where i can miss a thing on the linked guide.

problem solved with 1.7.16 release

**Comment by sim0n00ps** [comment]
> Hi @sim0n00ps 
> 
> I have downloaded the new version 1.7.16 and replaced the auth.json with the older one. 
> 
> `{
>     "USER_ID": "<hidden>",
>     "USER_AGENT": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Mobile Safari/537.36",
>     "X_BC": "<hidden>",
>     "COOKIE": "<hidden>",
>     "YTDLP_PATH": "C:/yt-dlp.exe",
>     "FFMPEG_PATH": "C:/ffmpeg.exe",
>     "MP4DECRYPT_PATH": "C:/mp4decrypt.exe",
>     "DownloadAvatarHeaderPhoto": "true",
>     "DownloadPaidPosts": "true",
>     "DownloadPosts": "true",
>     "DownloadArchived": "true",
>     "DownloadStories": "true",
>     "DownloadHighlights": "true",
>     "DownloadMessages": "true",
>     "DownloadPaidMessages": "true",
>     "DownloadImages": "true",
>     "DownloadVideos": "true",
>     "DownloadAudios": "true",
>     "IncludeExpiredSubscriptions": "false"
> }`
> 
> I'm still getting the below error.
> ![image](https://github.com/sim0n00ps/OF-DL/assets/139143413/126ba6ac-8692-4ae4-b9e3-7d212f2ddedb)
> 
> Could you please help? Is there any additional settings I need to do?
> 

Have you got your device_client_id_blob and device_private_key files in the right place and have you removed the file extensions from them?

**Comment by banjobbw** [comment]
> Have you got your device_client_id_blob and device_private_key files in the right place and have you removed the file extensions from them?

Hi @sim0n00ps 

Thanks for that , I missed that step. However I managed to get the two files following the tutorial. However still seeing issues

![image](https://github.com/sim0n00ps/OF-DL/assets/139143413/0f16c68d-c25b-417e-b216-7c7d9fa0c7a4)

I have the device_client_id_blob and device_private_key files in the right place
![image](https://github.com/sim0n00ps/OF-DL/assets/139143413/862fe069-c1b5-4132-9565-aef0e9ed2a22)

**Comment by sim0n00ps** [comment]
> > Have you got your device_client_id_blob and device_private_key files in the right place and have you removed the file extensions from them?
> 
> Hi @sim0n00ps 
> 
> Thanks for that , I missed that step. However I managed to get the two files following the tutorial. However still seeing issues
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/139143413/0f16c68d-c25b-417e-b216-7c7d9fa0c7a4)
> 
> I have the device_client_id_blob and device_private_key files in the right place
> ![image](https://github.com/sim0n00ps/OF-DL/assets/139143413/862fe069-c1b5-4132-9565-aef0e9ed2a22)
> 

Remove the file extensions from both the files and try again

**Comment by banjobbw** [comment]
> Remove the file extensions from both the files and try again

That seems to have done the trick 👍 
Thanks so much.
Not an easy job to get the DRM decryption files though :-)
