### ISSUE TITLE
decryption keys

### ISSUE THREAD

**Issue by engomingo** [sim0n00ps/OF-DL#71]
![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/849a7fdf-6bbf-498a-85c3-2c77cf38b2d8)
![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/4c66ba19-4fd4-4365-ae18-0ffdfcfc1637)

Why is it giving an error on the last command?

**Comment by sim0n00ps** [comment]
Run each command line by line

adb.exe shell
su
mv /sdcard/frida-server-16.1.1-android-x86 /data/local/tmp
chmod +x /data/local/tmp/frida-server-16.1.1-android-x86
/data/local/tmp/frida-server-16.1.1-android-x86

**Comment by sim0n00ps** [comment]
Also you need this version https://github.com/frida/frida/releases/download/16.1.1/frida-server-16.1.1-android-x86.xz as you have downloaded the x86_64 version which won't work

**Comment by engomingo** [comment]
> frida-server-16.1.1-android-x86

![image](https://github.com/sim0n00ps/OF-DL/assets/138712352/877929c3-66ae-4c3e-92a9-ae95b37eedf9)

When I use it, this command does not work this time.

**Comment by sim0n00ps** [comment]
Does that file actually exist in that directory?

**Comment by engomingo** [comment]
Yeap

**Comment by sim0n00ps** [comment]
Did you download this version https://github.com/frida/frida/releases/download/16.1.1/frida-server-16.1.1-android-x86.xz and copy it to C:\Users\yourname\AppData\Local\Android\Sdk\platform-tools

**Comment by engomingo** [comment]
even though i do this i get this error
