### ISSUE TITLE
Dump_keys.py issue. 

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#72]
Okay so I am stuck on the dump keys part of the walkthrough. I opened a new CMD with Administrative privileges and I go to the directory of where the dumper-main is an try to launch "python dump_keys.py" and receive the following error below , I was able to install the requirements successfully - but just can't get past the starting of the dump_keys.py

`C:\Users\<user>\Downloads\dumper-main>pip3 install -r requirements.txt
Requirement already satisfied: frida in c:\users\spudl\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 1)) (16.1.1)
Collecting protobuf (from -r requirements.txt (line 2))
  Downloading protobuf-4.23.4-cp310-abi3-win_amd64.whl (422 kB)
     ---------------------------------------- 422.5/422.5 kB 5.3 MB/s eta 0:00:00
Requirement already satisfied: pycryptodome in c:\users\spudl\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 3)) (3.17)
Installing collected packages: protobuf
Successfully installed protobuf-4.23.4`

`C:\Users\v\Downloads\dumper-main>python dump_keys.py
Traceback (most recent call last):
  File "C:\Users\<user>\Downloads\dumper-main\dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "C:\Users\<user>\Downloads\dumper-main\Helpers\Scanner.py", line 7, in <module>
    from Helpers.wv_proto2_pb2 import SignedLicenseRequest
  File "C:\Users\<user>\Downloads\dumper-main\Helpers\wv_proto2_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

C:\Users\<user>\Downloads\dumper-main>`

**Comment by sim0n00ps** [comment]
pip install protobuf==3.20.3

**Comment by deadbeatdandylyon** [comment]
Thank you very much, that resolved the issue
