### ISSUE TITLE
cant play downloaded  DRM vids

### ISSUE THREAD

**Issue by Garcarius** [sim0n00ps/OF-DL#75]
i just installed the app, and it download all but the vids doesnt work 
![image](https://github.com/sim0n00ps/OF-DL/assets/39957800/825ac3b4-d379-4b50-a85e-8c8f7c278c2a)
 
something wrong with my instalation?

**Comment by SuperPoorMan** [comment]
i get the same issue. drm getting us good

**Comment by sim0n00ps** [comment]
> i just installed the app, and it download all but the vids doesnt work 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/39957800/825ac3b4-d379-4b50-a85e-8c8f7c278c2a)
>  
> something wrong with my instalation?

That indicates that it's failing to decrypt the videos. Have you downloaded mp4decrypt and is the path to it correct? Also make sure you install this for your machine https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by banjobbw** [comment]
Hi @Garcarius , @SuperPoorMan 

You are on the same path that I travelled. If I can be a bit of help, the new version (OF.DL.V1.7.16) requires you to follow this step.

`Finally you will need to get 2 files, device_client_id_blob and device_private_key. These are used to get the decryption keys needed for downloading DRM videos. You can find a tutorial on how to do this here https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio, you need to place device_client_id_blob and device_private_key files in cdm/devices/chrome_1610/.`

Once you do exactly what as it says you should be good

Good luck

Thanks @sim0n00ps

**Comment by SuperPoorMan** [comment]
i did do that.... took a few hours trouble shooting but those files didn't work

**Comment by badbeezy** [comment]
Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.

**Comment by badbeezy** [comment]
> > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> 
> Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe

yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?

**Comment by sim0n00ps** [comment]
> > > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> > 
> > Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe
> 
> yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?

I could but people would just use them and they would just get banned quickly.

**Comment by Garcarius** [comment]
> Hi @Garcarius , @SuperPoorMan
> 
> You are on the same path that I travelled. If I can be a bit of help, the new version (OF.DL.V1.7.16) requires you to follow this step.
> 
> `Finally you will need to get 2 files, device_client_id_blob and device_private_key. These are used to get the decryption keys needed for downloading DRM videos. You can find a tutorial on how to do this here https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio, you need to place device_client_id_blob and device_private_key files in cdm/devices/chrome_1610/.`
> 
> Once you do exactly what as it says you should be good
> 
> Good luck
> 
> Thanks @sim0n00ps

thanks for ur help, but i tried to follow the steps and it gave error, so idk i followed all the steps

**Comment by randomfapper** [comment]
Which phone/OS version are people able to use to get the files?  The suggested Pixel6/PieOS doesn't appear to work.

**Comment by fendorix** [comment]
Pixel 6 / Pie (API 28) worked fine for me.

**Comment by randomfapper** [comment]
When I load up OF using that build, it just shows a "white" home screen with no posts.  I can view my private message list but when I click on a message, it goes back to the main list.  I'm not sure what I'm doing wrong here

**Comment by sim0n00ps** [comment]
> 
> ![Capture](https://github.com/sim0n00ps/OF-DL/assets/138882855/0d1944ad-246b-4bf8-b36c-c1b934cc6e02)
> When I load up OF using that build, it just shows a "white" home screen with no posts.  I can view my private message list but when I click on a message, it goes back to the main list.  I'm not sure what I'm doing wrong here

You don't need to log into OF on the phone. You can just go to https://bitmovin.com/demos/drm and play the video. That should dump the keys if you've set everything up correctly.

**Comment by randomfapper** [comment]
THANK YOU.  OMFG I've been building/rebuilding all night trying to get keys from OF... you may want to put a little blurb about that in the instructions b/c the guide implies that you need keys from specific sites.  Thank you again, much appreciated!  Everything works great now!

**Comment by DonaldTPP** [comment]
> > > > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> > > 
> > > 
> > > Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe
> > 
> > 
> > yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?
> 
> I could but people would just use them and they would just get banned quickly.

Want to generate me those 2 files? My hardware isn't "Compatible" to install certain things to get things running. Tried all sorts of work arounds but no avail.

**Comment by sim0n00ps** [comment]
> > > > > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> > > > 
> > > > 
> > > > Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe
> > > 
> > > 
> > > yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?
> > 
> > I could but people would just use them and they would just get banned quickly.
> 
> Want to generate me those 2 files? My hardware isn't "Compatible" to install certain things to get things running. Tried all sorts of work arounds but no avail.

Drop your discord or telegram here and I can try and help you

**Comment by DonaldTPP** [comment]
Would you believe that after a computer restart and some tinkering on some things it's dumped the keys?

**Comment by badbeezy** [comment]
Would it be possible if i generate the 2 files on a different computer, then transfer the files and use them on a computer with OFDL?

**Comment by sim0n00ps** [comment]
> Would it be possible if i generate the 2 files on a different computer, then transfer the files and use them on a computer with OFDL?

Yes you should be able to do that

**Comment by SuperPoorMan** [comment]
@sim0n00ps Should i try sending you those authentication files so you can see what could be wrong with  them? Or is that a really bad idea to do that?

**Comment by sim0n00ps** [comment]
> @sim0n00ps Should i try sending you those authentication files so you can see what could be wrong with them? Or is that a really bad idea to do that?

Well what errors are you facing with them?

**Comment by badbeezy** [comment]
Yeah trying to follow the directions of how to get these files and i can't help but get stuck on several steps along the way. Can i get these files from someone else? It's really getting frustrating now.

**Comment by SuperPoorMan** [comment]
@sim0n00ps Actually no errors I think? I just run the program and walk away kinda deal. But also just that when I do run the program, either it downloads DRM videos that are either corruputed giving the error of something "this isn't an MP4, but do you want to try running it regrardless", aswell the videos that do run are all green or have no audio. I don't see like massive dead halts or errors that stop anything in particular from happening, non-drm stuff download fine (of course as they should).

@badbeezy 
From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.

**Comment by topboysyp** [comment]
> @badbeezy From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.

I was thinking the same thing. Those files were all dumped from the same virtual device then what is the difference.

**Comment by sim0n00ps** [comment]
> > @badbeezy From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.
> 
> I was thinking the same thing. Those files were all dumped from the same virtual device then what is the difference.
> 

Both the files will be different for each device created so if your files are shared with others and they use them to download videos then they'll more than likely get blocked by Google sooner rather than later. That's why I recommend that you get your own so that they actually last.

**Comment by badbeezy** [comment]
> > > @badbeezy From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.
> > 
> > 
> > I was thinking the same thing. Those files were all dumped from the same virtual device then what is the difference.
> 
> Both the files will be different for each device created so if your files are shared with others and they use them to download videos then they'll more than likely get blocked by Google sooner rather than later. That's why I recommend that you get your own so that they actually last.

yeah i get stuck on the steps when it gets to the “frida” installation. i’m not sure where to open the command prompt or how to install the frida tools or where to install it. they don’t clarify it, but it seems i’m the only one that doesn’t know how to do this. i don’t have much experience with this kind of thing so im having a lot of difficulty with this part.

**Comment by sim0n00ps** [comment]
> > > > @badbeezy From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.
> > > 
> > > 
> > > I was thinking the same thing. Those files were all dumped from the same virtual device then what is the difference.
> > 
> > 
> > Both the files will be different for each device created so if your files are shared with others and they use them to download videos then they'll more than likely get blocked by Google sooner rather than later. That's why I recommend that you get your own so that they actually last.
> 
> yeah i get stuck on the steps when it gets to the “frida” installation. i’m not sure where to open the command prompt or how to install the frida tools or where to install it. they don’t clarify it, but it seems i’m the only one that doesn’t know how to do this. i don’t have much experience with this kind of thing so im having a lot of difficulty with this part.

Drop your discord or telegram here and I'll add you and try to help

**Comment by SuperPoorMan** [comment]
![image](https://github.com/sim0n00ps/OF-DL/assets/108386964/3d9cb73e-e677-4b34-9730-9cc495847f18)
@sim0n00ps This is the error message I get, I screen-recorded it, than took a screenshot of an error message. After the error message pops up, the program instantly shuts down.

**Comment by sim0n00ps** [comment]
> ![image](https://user-images.githubusercontent.com/108386964/253424899-3d9cb73e-e677-4b34-9730-9cc495847f18.png) @sim0n00ps This is the error message I get, I screen-recorded it, than took a screenshot of an error message. After the error message pops up, the program instantly shuts down.

What OS are you running? That's to do with the package that draws the selection prompts and other coloured text.

**Comment by SuperPoorMan** [comment]
Windows 10 22H2, build 19045.3155

**Comment by sim0n00ps** [comment]
> Windows 10 22H2, build 19045.3155

Okay not what I was thinking it was, Windows 10 is fine. I'm yet to get anything like that and I have 0 idea what could cause that or how I would replicate it on my end.

**Comment by SuperPoorMan** [comment]
What do you think is the error in the first place?

**Comment by Davo-cado** [comment]
> > i just installed the app, and it download all but the vids doesnt work
> > ![image](https://user-images.githubusercontent.com/39957800/252530728-825ac3b4-d379-4b50-a85e-8c8f7c278c2a.png)
> > something wrong with my instalation?
> 
> That indicates that it's failing to decrypt the videos. Have you got your device_client_id_blob and device_private_key files and are they in the correct place? Have you downloaded mp4decrypt and is the path to it correct? Also make sure you install this for your machine https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Would say yes to all the above, but getting the same issue. DRM vids come split like that 

Couple things I was unsure of:

- When we rename the keys, we remove the .bin and .pem, correct? 
- Any reason this would be off for Win 11?

**Comment by sim0n00ps** [comment]
> > > i just installed the app, and it download all but the vids doesnt work
> > > ![image](https://user-images.githubusercontent.com/39957800/252530728-825ac3b4-d379-4b50-a85e-8c8f7c278c2a.png)
> > > something wrong with my instalation?
> > 
> > 
> > That indicates that it's failing to decrypt the videos. Have you got your device_client_id_blob and device_private_key files and are they in the correct place? Have you downloaded mp4decrypt and is the path to it correct? Also make sure you install this for your machine https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
> 
> Would say yes to all the above, but getting the same issue. DRM vids come split like that
> 
> Couple things I was unsure of:
> 
> * When we rename the keys, we remove the .bin and .pem, correct?
> * Any reason this would be off for Win 11?

Yes
I don't run Windows 11 so I wouldn't know, shouldn't be any different to Windows 10

**Comment by Davo-cado** [comment]
> 
> Yes I don't run Windows 11 so I wouldn't know, shouldn't be any different to Windows 10

Ran through the process and grabbed keys with a different "phone". Worked this time, not sure why. This time I still had the cmd prompts open but don't know if that's required. If it was, then I would feel silly.

**Comment by SuperPoorMan** [comment]
> > Yes I don't run Windows 11 so I wouldn't know, shouldn't be any different to Windows 10
> 
> Ran through the process and grabbed keys with a different "phone". Worked this time, not sure why. This time I still had the cmd prompts open but don't know if that's required. If it was, then I would feel silly.

What different phone did you use?

**Comment by badbeezy** [comment]
> > > > > @badbeezy From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.
> > > > 
> > > > 
> > > > I was thinking the same thing. Those files were all dumped from the same virtual device then what is the difference.
> > > 
> > > 
> > > Both the files will be different for each device created so if your files are shared with others and they use them to download videos then they'll more than likely get blocked by Google sooner rather than later. That's why I recommend that you get your own so that they actually last.
> > 
> > 
> > yeah i get stuck on the steps when it gets to the “frida” installation. i’m not sure where to open the command prompt or how to install the frida tools or where to install it. they don’t clarify it, but it seems i’m the only one that doesn’t know how to do this. i don’t have much experience with this kind of thing so im having a lot of difficulty with this part.
> 
> Drop your discord or telegram here and I'll add you and try to help

my telegram is @badbeezy

**Comment by badbeezy** [comment]
> > > > > @badbeezy From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.
> > > > 
> > > > 
> > > > I was thinking the same thing. Those files were all dumped from the same virtual device then what is the difference.
> > > 
> > > 
> > > Both the files will be different for each device created so if your files are shared with others and they use them to download videos then they'll more than likely get blocked by Google sooner rather than later. That's why I recommend that you get your own so that they actually last.
> > 
> > 
> > yeah i get stuck on the steps when it gets to the “frida” installation. i’m not sure where to open the command prompt or how to install the frida tools or where to install it. they don’t clarify it, but it seems i’m the only one that doesn’t know how to do this. i don’t have much experience with this kind of thing so im having a lot of difficulty with this part.
> 
> Drop your discord or telegram here and I'll add you and try to help

My telegram is @badboyzo

**Comment by LikeaDize** [comment]
> > > > > > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> > > > > 
> > > > > 
> > > > > Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe
> > > > 
> > > > 
> > > > yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?
> > > 
> > > 
> > > I could but people would just use them and they would just get banned quickly.
> > 
> > 
> > Want to generate me those 2 files? My hardware isn't "Compatible" to install certain things to get things running. Tried all sorts of work arounds but no avail.
> 
> Drop your discord or telegram here and I can try and help you

I havent spent countless hours trying to get the files - but can never get it to work. Can i ask a couple of questions via telegram? @LikeaDize

**Comment by SuperPoorMan** [comment]
@sim0n00ps 
![OF_DL_VTu7CVTUm9](https://github.com/sim0n00ps/OF-DL/assets/108386964/783bbef0-d606-4a49-98c0-b8507cca95c5)
So I am getting some success, I originally had the program running on a external hard drive, now I run it off a 2nd ssd in the computer. Now the program does run without shutting down, except it spits out these errors.

**Comment by sim0n00ps** [comment]
> > > > > > > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> > > > > > 
> > > > > > 
> > > > > > Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe
> > > > > 
> > > > > 
> > > > > yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?
> > > > 
> > > > 
> > > > I could but people would just use them and they would just get banned quickly.
> > > 
> > > 
> > > Want to generate me those 2 files? My hardware isn't "Compatible" to install certain things to get things running. Tried all sorts of work arounds but no avail.
> > 
> > 
> > Drop your discord or telegram here and I can try and help you
> 
> I havent spent countless hours trying to get the files - but can never get it to work. Can i ask a couple of questions via telegram? @LikeaDize

Messaged you

> @sim0n00ps ![OF_DL_VTu7CVTUm9](https://user-images.githubusercontent.com/108386964/253777000-783bbef0-d606-4a49-98c0-b8507cca95c5.png) So I am getting some success, I originally had the program running on a external hard drive, now I run it off a 2nd ssd in the computer. Now the program does run without shutting down, except it spits out these errors.

Could possibly be rate limited, maybe try getting a new sess or waiting a bit before running it again

**Comment by SuperPoorMan** [comment]
> > > > > > > > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> > > > > > > 
> > > > > > > 
> > > > > > > Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe
> > > > > > 
> > > > > > 
> > > > > > yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?
> > > > > 
> > > > > 
> > > > > I could but people would just use them and they would just get banned quickly.
> > > > 
> > > > 
> > > > Want to generate me those 2 files? My hardware isn't "Compatible" to install certain things to get things running. Tried all sorts of work arounds but no avail.
> > > 
> > > 
> > > Drop your discord or telegram here and I can try and help you
> > 
> > 
> > I havent spent countless hours trying to get the files - but can never get it to work. Can i ask a couple of questions via telegram? @LikeaDize
> 
> Messaged you
> 
> > @sim0n00ps ![OF_DL_VTu7CVTUm9](https://user-images.githubusercontent.com/108386964/253777000-783bbef0-d606-4a49-98c0-b8507cca95c5.png) So I am getting some success, I originally had the program running on a external hard drive, now I run it off a 2nd ssd in the computer. Now the program does run without shutting down, except it spits out these errors.
> 
> Could possibly be rate limited, maybe try getting a new sess or waiting a bit before running it again

So I tried that

![image](https://github.com/sim0n00ps/OF-DL/assets/108386964/5fdd2720-d1d7-4ec1-b0b8-63a8b774bd90)

Instead I get this aswell, so i am not sure whats with the error messages, should I be using a vpn doing this?

**Comment by sisabe13** [comment]
the videos with drm do not let them see, they show them to me as an error

**Comment by sasssy2019** [comment]
> > > > @badbeezy From my understanding since the DRM stuff is liked tied to a device in a way, its like a security crap stuff that shouldn't be shared. But also since we are making bootleg devices with bootleg drm file crap, maybe it is ok to share? I dunno, but I know mine don't work for some reason.
> > > 
> > > 
> > > I was thinking the same thing. Those files were all dumped from the same virtual device then what is the difference.
> > 
> > 
> > Both the files will be different for each device created so if your files are shared with others and they use them to download videos then they'll more than likely get blocked by Google sooner rather than later. That's why I recommend that you get your own so that they actually last.
> 
> yeah i get stuck on the steps when it gets to the “frida” installation. i’m not sure where to open the command prompt or how to install the frida tools or where to install it. they don’t clarify it, but it seems i’m the only one that doesn’t know how to do this. i don’t have much experience with this kind of thing so im having a lot of difficulty with this part.

I am also getting stuck at this stage with the command prompt. Did anyone figure out what to type in command etc?

**Comment by sim0n00ps** [comment]
> > > > > > > > > Is there an easier way to obtain those 2 files? the directions to obtain the files require you to download a 64 bit version of the program and I'm still using a 32-bit operating system.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Not to my knowledge. Fairy sure you can download a 32 bit version of Android studio, it mentions it's in the zip file download. It should be called studio.exe
> > > > > > > 
> > > > > > > 
> > > > > > > yeah the 32 bit version is not in the latest download. the one i did find it in, is very different and i don't know how to navigate through it's very different than the one that is described in the thread. you can't just upload those 2 files and make it available for everyone i guess huh?
> > > > > > 
> > > > > > 
> > > > > > I could but people would just use them and they would just get banned quickly.
> > > > > 
> > > > > 
> > > > > Want to generate me those 2 files? My hardware isn't "Compatible" to install certain things to get things running. Tried all sorts of work arounds but no avail.
> > > > 
> > > > 
> > > > Drop your discord or telegram here and I can try and help you
> > > 
> > > 
> > > I havent spent countless hours trying to get the files - but can never get it to work. Can i ask a couple of questions via telegram? @LikeaDize
> > 
> > Messaged you
> > 
> > > @sim0n00ps ![OF_DL_VTu7CVTUm9](https://user-images.githubusercontent.com/108386964/253777000-783bbef0-d606-4a49-98c0-b8507cca95c5.png) So I am getting some success, I originally had the program running on a external hard drive, now I run it off a 2nd ssd in the computer. Now the program does run without shutting down, except it spits out these errors.
> > 
> > Could possibly be rate limited, maybe try getting a new sess or waiting a bit before running it again
> 
> So I tried that
> 
> ![image](https://github.com/sim0n00ps/OF-DL/assets/108386964/5fdd2720-d1d7-4ec1-b0b8-63a8b774bd90)
> 
> Instead I get this aswell, so i am not sure whats with the error messages, should I be using a vpn doing this?
> 

Probably shouldn't be using a VPN

**Comment by harrcc31** [comment]
Getting the same issue. Using OF.DRM.V1.5, and I used a pixel 6/pie to grabs keys(and renamed them correctly and put them in the cdm folder). But still can't download vids properly. This is the error I'm getting:

Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.

StackTrace:    at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw)
   at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw)
   at OF_DRM_Video_Downloader.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: No client id blob found

**Comment by harrcc31** [comment]
Nevermind it works now. Weird. Just kept getting new keys until it worked.

**Comment by purpleemoji** [comment]
The videohelp tutorial tells you to download the frida-server and push it to your virtual phone. The Frida releases page only has frida-core.h as well as header and source files. Am I missing something? Is there a frida server file that needs to be compiled?

**Comment by sim0n00ps** [comment]
> The videohelp tutorial tells you to download the frida-server and push it to your virtual phone. The Frida releases page only has frida-core.h as well as header and source files. Am I missing something? Is there a frida server file that needs to be compiled?

There are around 200+ files in each release so you need to make sure you list them all, to make easier you can just press ctrl+f and search for frida-server, that should get you to the right place

**Comment by purpleemoji** [comment]
> > The videohelp tutorial tells you to download the frida-server and push it to your virtual phone. The Frida releases page only has frida-core.h as well as header and source files. Am I missing something? Is there a frida server file that needs to be compiled?
> 
> There are around 200+ files in each release so you need to make sure you list them all, to make easier you can just press ctrl+f and search for frida-server, that should get you to the right place

lmao. I feel so stupid for not noticing to expand for other files. In my defence, it's early and I haven't had my coffee.

Thanks for the quick reply

**Comment by harrcc31** [comment]
> > > The videohelp tutorial tells you to download the frida-server and push it to your virtual phone. The Frida releases page only has frida-core.h as well as header and source files. Am I missing something? Is there a frida server file that needs to be compiled?
> > 
> > 
> > There are around 200+ files in each release so you need to make sure you list them all, to make easier you can just press ctrl+f and search for frida-server, that should get you to the right place
> 
> lmao. I feel so stupid for not noticing to expand for other files. In my defence, it's early and I haven't had my coffee.
> 
> Thanks for the quick reply

Yeah don't worry, I made the same mistake too 🤦🏽‍♂️

**Comment by sasssy2019** [comment]
> Getting the same issue. Using OF.DRM.V1.5, and I used a pixel 6/pie to grabs keys(and renamed them correctly and put them in the cdm folder). But still can't download vids properly. This is the error I'm getting:
> 
> Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.
> 
> StackTrace: at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw) at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw) at OF_DRM_Video_Downloader.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)
> 
> Inner Exception: Exception caught: No client id blob found

I am also receiving this same error. I have both files, removed the ext and still says No client id blol found. What am I doing wrong?

![image](https://github.com/sim0n00ps/OF-DL/assets/139555218/279e4400-7cce-4810-9ddc-9cf69ffcda7e)
![image](https://github.com/sim0n00ps/OF-DL/assets/139555218/6f922944-8219-49bb-b178-1a6785c847b6)

**Comment by sasssy2019** [comment]
Okay, so I fixed it. I had to start a new session, delete the old folder for that person and it downloaded it correctly! OMG. 5 DAYS OF HARD WORK to finally get this working!

**Comment by purpleemoji** [comment]
sim0n,
once again, thanks for all  your help.
I was able to get frida-server installed and also got dumper main working and the script runs and says Hooks completed, I played the  widevine DRM content and nothing happens. I am just trying with the bitmovin.com/demos/drm link for now.
I used a Pixel 3  and also a Pixel 6 x86_64 for my pc. NO subfolder is created in the dumper main directory like the tutorial says

**Comment by sim0n00ps** [comment]
> sim0n, once again, thanks for all your help. I was able to get frida-server installed and also got dumper main working and the script runs and says Hooks completed, I played the widevine DRM content and nothing happens. I am just trying with the bitmovin.com/demos/drm link for now. I used a Pixel 3 and also a Pixel 6 x86_64 for my pc. NO subfolder is created in the dumper main directory like the tutorial says

Make sure its a Pixel 6 running Android 9 Pie, it should be x86, not x86_64

**Comment by purpleemoji** [comment]
Or alternately is it ok to use the same keys for multiple OF accounts?
