### ISSUE TITLE
Query on redownload or Feature request.

### ISSUE THREAD

**Issue by banjobbw** [sim0n00ps/OF-DL#76]
Hi @sim0n00ps 
I have a query on the tool.
If we stop the download half way and then re-download, will the toll overwrite existing completed files? Or it will skip existing completed files?

If this capability is not there can we request this capability to be added please?

Many Thanks

**Comment by sim0n00ps** [comment]
> Hi @sim0n00ps 
> I have a query on the tool.
> If we stop the download half way and then re-download, will the toll overwrite existing completed files? Or it will skip existing completed files?
> 
> If this capability is not there can we request this capability to be added please?
> 
> Many Thanks

Yes any files that are downloaded are set to downloaded in the metadata database so when it comes to download them it will check if the file has been downloaded in the database and also if the file exists in the directory, so any content currently downloaded will be skipped

**Comment by DonaldTPP** [comment]
> > Hi @sim0n00ps
> > I have a query on the tool.
> > If we stop the download half way and then re-download, will the toll overwrite existing completed files? Or it will skip existing completed files?
> > If this capability is not there can we request this capability to be added please?
> > Many Thanks
> 
> Yes any files that are downloaded are set to downloaded in the metadata database so when it comes to download them it will check if the file has been downloaded in the database and also if the file exists in the directory, so any content currently downloaded will be skipped

Does that also count if say for example a video was posted previously on a wall post, but then sent also in messages and it doesn't download it to the messages folder because it already exists in the main posts?

**Comment by sim0n00ps** [comment]
> > > Hi @sim0n00ps
> > > I have a query on the tool.
> > > If we stop the download half way and then re-download, will the toll overwrite existing completed files? Or it will skip existing completed files?
> > > If this capability is not there can we request this capability to be added please?
> > > Many Thanks
> > 
> > Yes any files that are downloaded are set to downloaded in the metadata database so when it comes to download them it will check if the file has been downloaded in the database and also if the file exists in the directory, so any content currently downloaded will be skipped
> 
> Does that also count if say for example a video was posted previously on a wall post, but then sent also in messages and it doesn't download it to the messages folder because it already exists in the main posts?

No, if they re-use media in both posts and messages then they will both be downloaded in each folder

**Comment by banjobbw** [comment]
Thanks @sim0n00ps
