### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by Goralith** [sim0n00ps/OF-DL#78]
First time running, getting errors. Thank you in advance for all of your hard work.

Downloading 877 Posts ----------------------------------------   0% 0.0/222.6 GB 01:39:00
                                                                                         Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.

StackTrace:    at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw)
   at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: No client id blob found

StackTrace:    at WidevineClient.Widevine.CDMDevice..ctor(String deviceName, Byte[] clientIdBlobBytes, Byte[] privateKey
Downloading 877 Posts ----------------------------------------   0% 0.0/222.6 GB 01:39:00
                                                                                         Exception caught: Could not find file 'G:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0hf6nugmb8ckw2aqsviz9_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder
Downloading 877 Posts ----------------------------------------   0% 0.0/222.6 GB 01:39:00
                                                                                         Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.

StackTrace:    at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw)
   at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw)
   at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh)

Inner Exception:
Exception caught: No client id blob found

StackTrace:    at WidevineClient.Widevine.CDMDevice..ctor(String deviceName, Byte[] clientIdBlobBytes, Byte[] privateKey
Downloading 877 Posts ----------------------------------------   0% 0.0/222.6 GB 01:39:00
                                                                                         Exception caught: Could not find file 'G:\OF\__user_data__\sites\OnlyFans\emily_valentina\Posts\Free\Videos\0heyc47p1xu8idpdpingu_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                         ng decryptionKey, String folder

**Comment by sim0n00ps** [comment]
From the readme:

> Finally you will need to get 2 files, device_client_id_blob and device_private_key. These are used to get the decryption keys needed for downloading DRM videos. You can find a tutorial on how to do this here https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio, you need to place device_client_id_blob and device_private_key files in cdm/devices/chrome_1610/.

Make sure you read the readme in future.

**Comment by Goralith** [comment]
I used it a few ago on my other computer. Did not get any errors. Did not realize the readme changed. Thanks for the quick response.

**Comment by Goralith** [comment]
I have another problem. Following these instructions at 

https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio

"Download The Frida Server for Androïd. and put it on C:\Users\yourname\AppData\Local\Android\Sdk\platfo rm-tools

Verify that the frida-server version you download is the same that the one you have install via pip."

Image attached shows Frida Server for Android without the "XZ" extension. The only file I found is "frida-server-16.1.2-android-x86.xz"

Tried to follow the instructions using it and got an error "frida-server-16.1.2-android-x86.xz not executable"

What file should I use? Thanks for your help.

![Capture6](https://github.com/sim0n00ps/OF-DL/assets/139399288/25728421-6914-49fa-b21e-d5754099c060)

**Comment by topboysyp** [comment]
> I have another problem. Following these instructions at
> 
> https://forum.videohelp.com/threads/408031-Dumping-Your-own-L3-CDM-with-Android-Studio
> 
> "Download The Frida Server for Androïd. and put it on C:\Users\yourname\AppData\Local\Android\Sdk\platfo rm-tools
> 
> Verify that the frida-server version you download is the same that the one you have install via pip."
> 
> Image attached shows Frida Server for Android without the "XZ" extension. The only file I found is "frida-server-16.1.2-android-x86.xz"
> 
> Tried to follow the instructions using it and got an error "frida-server-16.1.2-android-x86.xz not executable"
> 
> What file should I use? Thanks for your help.
> 
> ![Capture6](https://user-images.githubusercontent.com/139399288/253245160-25728421-6914-49fa-b21e-d5754099c060.png)

Unzip the "frida-server-16.1.2-android-x86.xz" file then you got the "frida-server-16.1.2-android-x86" file. Put the "frida-server-16.1.2-android-x86" file into the folder.

**Comment by BluesFanUK** [comment]
> > Blimey did OF make a change recently? Last time I used this was about 3-4 weeks ago to grab some DRM'd vids and it was very easy to get up and running, saved me just before one of my subscriptions expired, but that Android install is a nightmare.
> > Followed the instructions, everything's working, problem is OF just loads on the emulated android (Pixel 6). No way of getting into the site unfortunately.
> > @sim0n00ps - were there any additional steps you took to get it to work?
> 
> You don't need to open OF on the emulated device, you need to open https://bitmovin.com/demos/drm and play the video whilst frida-server is running and whilst the dump_keys.py is running as well

Gotcha, that guide states to open that or any other DRM site, assumed this was like a setting file that required your authenticated login. Files downloaded, renamed and seems to be working, had a couple of connection errors but DRM content is downloading.

For anyone else who is struggling, if you've managed to go through the rigmarole of downloading the necessary files and setting up the Android part, rename both keys as instructed (remove the .bin and .prem extensions). It should then work.

**Comment by Goralith** [comment]
Thank you. I did not realize that xz is an archive.
