### ISSUE TITLE
Crash Upon Opening

### ISSUE THREAD

**Issue by randomfapper** [sim0n00ps/OF-DL#79]
Everything was working fine until about 20 minutes ago. 

Program opens, says successfully logged in, then auto closes.

Running it from the command prompt spits back a bunch of errors.

Possible change on OF's side?

(Running the latest version and didn't have any issues last night or today up until now)

**Comment by Kameshennyn** [comment]
![2023-07-13](https://github.com/sim0n00ps/OF-DL/assets/100891073/5de6a0fe-b83b-4e85-bdc9-674799cae716)

Actually the same issue there x)

**Comment by banjobbw** [comment]
Same issue here :-(
Program opens and then shuts down

**Comment by Puk0** [comment]
A mi también me sale el mismo error y también en el OF-DRM

**Comment by DLurch21** [comment]
Same issue here on Windows 11. Ran it about a week and a half ago, no issues... now get the same error as OP.

**Comment by banjobbw** [comment]
> Easy fix if you guys update `DynamicRules.cs` to make is_current nullable. `public bool? is_current { get; set; }`

But we only have the .exe file 
![image](https://github.com/sim0n00ps/OF-DL/assets/139143413/02122784-1b79-4628-b124-fcf35e111ccd)

**Comment by PrettyLights808** [comment]
> Easy fix if you guys update `DynamicRules.cs` to make is_current nullable. `public bool? is_current { get; set; }`

Can you please elaborate on what specifically needs to be done to do that? Took me like 3 hours just to get the file dumps, so I'm out of my realm with this.

**Comment by deadbeatdandylyon** [comment]
Just went to run the scrape and had the same problem it shows the first 3 file paths as green and then the command screen just vanishes.

**Comment by sim0n00ps** [comment]
I'll make the required change in a bit and create a new release.

**Comment by sim0n00ps** [comment]
Download latest release to fix this issue https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.18

**Comment by PrettyLights808** [comment]
> Download latest release to fix this issue https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.18

Thanks!!! Took me a while last night walking through those emulator steps but learned a lot of new things. This last 1.7.19 version is working for me.
