### ISSUE TITLE
Custom list not populating all user subscriptions

### ISSUE THREAD

**Issue by rstein2023** [sim0n00ps/OF-DL#82]
With the new build I am not seeing all of my subscriptions in the custom list and it does not appear that scraping my lists is working either. I just subbed to someone and after exiting and relaunching the exe is do not see them in the custom list.

**Comment by booleangit** [comment]
Same here! Closer inspection learns that it only shows free subscriptions.

**Comment by rstein2023** [comment]
> Same here! Closer inspection learns that it only shows free subscriptions.
> 
> EDIT: Adding a specific user to a list to circumvent the issue doesn't help; it only grabs the free user accounts from that list.

I can confirm all of this with the exception that even when I add a new free sub it is not showing up in the custom feed for scraping.

**Comment by Chrdvr** [comment]
Same. Missing many active subs. Some are old, some new, some free, some paid. They aren't pulling at all for any of the lists I have them in or showing under custom.

**Comment by sim0n00ps** [comment]
Alright I've found the issue, the requests get 50 accounts each time, you have to have an offset on each request and I was calculating the offset query parameter wrong

**Comment by Kameshennyn** [comment]
Mine's limited to 150 accounts mixed as I can see x)

**Comment by sim0n00ps** [comment]
If you could try https://github.com/sim0n00ps/OF-DL/releases/tag/OFDLV1.7.19 and see if its any better

**Comment by booleangit** [comment]
It's working like a charm! I've picked five random user accounts and they were all listed. Downloading (including DRM) also works as expected. Thank you very much for your awesome support! 🙏
