### ISSUE TITLE
Getting errors after getting the two files needed still

### ISSUE THREAD

**Issue by Samael945** [sim0n00ps/OF-DL#85]
Getting these errors on all paid messages even after getting client blob and private key from tutorial

![Screenshot 2023-07-14 022601](https://github.com/sim0n00ps/OF-DL/assets/58105998/bbb80c24-00f4-4c61-9abd-a1f58e545eef)
![Screenshot 2023-07-14 022633](https://github.com/sim0n00ps/OF-DL/assets/58105998/9a9b3633-f543-4c6a-8179-d71e3fc9bf97)

**Comment by sim0n00ps** [comment]
> Getting these errors on all paid messages even after getting client blob and private key from tutorial
> 
> 
> ![Screenshot 2023-07-14 022601](https://github.com/sim0n00ps/OF-DL/assets/58105998/bbb80c24-00f4-4c61-9abd-a1f58e545eef)
> ![Screenshot 2023-07-14 022633](https://github.com/sim0n00ps/OF-DL/assets/58105998/9a9b3633-f543-4c6a-8179-d71e3fc9bf97)
> 

Remove the file extensions from both of the files and try again

**Comment by Samael945** [comment]
worked, thank you
