### ISSUE TITLE
Question / problem about list

### ISSUE THREAD

**Issue by Sukugojo** [sim0n00ps/OF-DL#88]
Hello
first of all iam not a native english so iam sorry if there is some mistake.
My issue i kind of a question who can maybe be an issue lol 
so in the readme there is this phrase : 
"The List option will show you all of the lists you have created on OF and you can then select 1 or more lists to download the content of the users within those lists."
and my question is do i need to be sub to the OF account in the list to DL the content ? if thats the case my question is answered and feel free to close the issue :) 

If not.. then i cant DL i get the 
**Downloading from List(s): SierraScrape Completed in 0,11 minutes**
and nothing is dowloaded (and its way too fast lol i know all of those GB cant be DL in that time) 
And if you want to know a tried to DL de free OF account and everything was working for that

Ty for reading me !

**Comment by sim0n00ps** [comment]
Simple answer - yes. You need to be subbed to the user in order to download the content.
