### ISSUE TITLE
Question: Rejig the codebase

### ISSUE THREAD

**Issue by ddirty830** [sim0n00ps/OF-DL#89]
Would you be open to a PR if I moved things around in the code base?
When I did the custom download path PR, I noticed a lot of dupe code (e.g. The code to download Posts vs Messages is REALLY similar).

**Comment by sim0n00ps** [comment]
Yeah go for it, probably going to need my spectre_console.dll to be able to debug I imagine, let me know and I'll upload it for you.

**Comment by ddirty830** [comment]
Sure.
Out of curiosity, what did you change in Spectre?

**Comment by sim0n00ps** [comment]
I changed the HandleInput method in in the MultiSelectionPrompt. I just added a new if statement to check if the key pressed was A-Z and it would get the first item in the list of users that started with the letter C for example and then I would set the index of the list to the index of that item. It was something to make it easier to navigate/search the list of users. I have no idea if it's possible to do it without modifying the project.

**Comment by ddirty830** [comment]
Yeah, I can't see a good way to do that as the interfaces stands. If IListPromptStrategy was public instead of internal, it wouldn't take make effort.

Looks like you're not the only one wanting to have a little bit more control:
https://github.com/spectreconsole/spectre.console/discussions/1224

Looks like there a couple of options:
- If you're going to continue with your custom Spectre compile, it would make sense to also promote your custom DLL into a *references* folder or similar, so others can still compile.
-- I personally like the idea of making the interfaces public, because they're smaller changes if you ever need to get an updated copy of the original.
- You could in theory clone/implement your own Prompt. It's a lot of copy/paste code, but then you won't have the fork problem.
- Wait for Spectre maintainers to do something.

**Comment by ddirty830** [comment]
Or another option, though I don't know if it'd work (and it's probably overkill): Use something like [Harmony](https://github.com/pardeike/Harmony) to alter the HandleInput method at runtime. I don't know how easy it'd be since you'd still be dealing with all the internal class types

**Comment by sim0n00ps** [comment]
I'll add a new folder to the repo tomorrow with it in so you can compile it. I'll take a look at Harmony, something I've never looked at before and seems interesting.

**Comment by sim0n00ps** [comment]
Should be in the repo now
