### ISSUE TITLE
Additional option

### ISSUE THREAD

**Issue by deadbeatdandylyon** [sim0n00ps/OF-DL#9]
1) there is a section in _user_data_\sites\onlyfans\creator\ "Profile" is there any way to remove this as i don't think it's necessary to download

2) an option to choose not to download photos

3) An option to go back a screen in the script page, so if you accidently go to "lists" there is a way to go back to the main page without having to close and reopen the script 

other then that everything has been working fantastic, thank you for all the hard work

**Comment by sim0n00ps** [comment]
The next release will include features 1 and 2. The 3rd feature will take a little more time to implement so will feature in a future release.

**Comment by deadbeatdandylyon** [comment]
Two more little things, not that important 

but in the script window it shows "logged in successfully as Username Username - so shows it twice any way to fix that 

secondly, "Posts Already Downloaded: 11 New Posts Downloaded: 475"

any chance to break this down to two lines
Posts Already Downloaded: 11 
New Posts Downloaded: 475  

again nothing major just for aesthetics

**Comment by deadbeatdandylyon** [comment]
Hello since the new release of now being able to download expired subs, is there any way to separate that list out of the "custom" because now all current and past subscriptions are in one list and now I have to search though many users to just find one user. or if you can allow some sort of search functionality where we can type in a letter or two of the person and it populates just those users with the name. 

or 

another route is to go to Lists > Following > and instead of just downloading everyone your following have a sub category of all users you are following and can select 1 user at a time.

**Comment by melithine** [comment]
There is support for scraping lists now. Is anything still outstanding here?

**Comment by melithine** [comment]
Closing due to age.
