### ISSUE TITLE
DRM videos won't download with keys

### ISSUE THREAD

**Issue by wackoip** [sim0n00ps/OF-DL#91]
Managed to get the keys but while I can download all videos, the DRM ones won't download, errors as follows:

 Exception caught: Could not find file 'C:\Users\Owner\Downloads\OF.DL.V1.7.23\__user_data__\sites\OnlyFans\teddyhunter\Posts\Free\Videos\0heaadwqm58ht5kqyulrr_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                        ing decryptionKey, String folder

**Comment by slmcrs** [comment]
Something looks wrong with your file path `...\Downloads\OF.DL.V1.7.23_user_data\...`, im guessing it should be `...\Downloads\OF.DL.V1.7.23\_user_data_\...`

**Comment by Puk0** [comment]
> Something looks wrong with your file path `...\Downloads\OF.DL.V1.7.23_user_data_\...`, im guessing it should be `...\Downloads\OF.DL.V1.7.23\_user_data_\...`

El editor github es el que cambia solo el path ... 
\OF-DRM\__user_data__\sites\OnlyFans\

**Comment by wackoip** [comment]
Thanks for the input.  But I didn't create the path.  It was generated when the download started.  where can I create a download path?

**Comment by Puk0** [comment]
Si no tiene crea la carpeta en la misma del .exe
Sino en el auth.json >"DownloadPath": ""

**Comment by boivinx7** [comment]
Same issue my path is just C:\Users\Odin\Downloads\OF_DL
And not DRM videos work, its just the DRM ones that have issues
and i have my keys

**Comment by Puk0** [comment]
> Same issue my path is just C:\Users\Odin\Downloads\OF_DL

No funciona "DownloadPath"

Si lo dejas en blanco ("DownloadPath": "") te lo baja en la misma carpeta del .exe
![2023-07-18_213332](https://github.com/sim0n00ps/OF-DL/assets/138377242/d44bdd1e-b29f-44eb-980c-48bd9e6e6961)



> And not DRM videos work, its just the DRM ones that have issues
> and i have my keys

Si baja los videos con DRM

¿tienes los 2 archivos device_client_id_blob y device_private_key (sin extension) en la carpeta \cdm\devices\chrome_1610?

**Comment by wackoip** [comment]
Hi I don't read spanish sorry but I managed to translate using google.  Yes we both have the keys in the folder chrome_1610 and they have been renamed correctly as device_client_id_blob and device_private_key.

And I also tried to specify the download path to a separate folder.  I don't thnk the path is the problem.  Still getting the same message.  I have also generated different keys using different virtual phones but still the same errors as follows:

Exception caught: Could not find file 'C:\Users\Owner\downloads\OF\teddyhunter\Posts\Free\Videos\0hfm3cwvxxvdrfu4fxpbh_source.mp4'.

StackTrace:    at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at OF_DL.Helpers.DownloadHelper.DownloadPostDRMVideo(String ytdlppath, String mp4decryptpath, String ffmpegpath, Stri                                                                                        ing decryptionKey, String folder

**Comment by boivinx7** [comment]
The download folder does not seem the be the issue, since non DRM videos work.
FYI, i even tried getting the device_client_id_blob and device_private_key from OF instead of https://bitmovin.com/demos/drm
But from what i understand we just need general keys for M3U8, so should all work.

**Comment by wackoip** [comment]
And where can we get the M3U8 key?  From what web site?

**Comment by wackoip** [comment]
Correct me if Im wrong.  We got them from those web sites running videos using non M3U8 keys (that bitmovin web site) that is why those keys are not useful.  Are there any web sites which runs M3U8 encrypted videos so we can generate the right keys? or am I not talking about the right thing?

**Comment by sim0n00ps** [comment]
All you need is those 2 files, don't need to worry about anything else.

**Comment by boivinx7** [comment]
> Correct me if Im wrong. We got them from those web sites running videos using non M3U8 keys (that bitmovin web site) that is why those keys are not useful. Are there any web sites which runs M3U8 encrypted videos so we can generate the right keys? or am I not talking about the right thing?

Dont think about M3U8, I was just explaining what the files are.
In short it doent matter where you get them from.
But we have them so its not our issue.

**Comment by wackoip** [comment]
I see.  Thanks for explaining sim0n00ps and boivinx7

**Comment by boivinx7** [comment]
Oh found my issue fromt his post
https://github.com/sim0n00ps/OF-DL/issues/94#issuecomment-1641579830

**Comment by wackoip** [comment]
Do you want me to close this one off and leave the other open boivinx and sim0n00ps?

**Comment by Puk0** [comment]
> Managed to get the keys but while I can download all videos, the DRM ones won't download, errors as follows:
> 
> Exception caught: Could not find file 'C:\Users\Owner\Downloads\OF.DL.V1.7.23__user_data__\sites\OnlyFans\teddyhunter\Posts\Free\Videos\0heaadwqm58ht5kqyulrr_source.mp4'.
> 
> StackTrace: at System.IO.FileSystem.OpenHandleToWriteAttributes(String fullPath, Boolean asDirectory) at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 



> Same issue my path is just C:\Users\Odin\Downloads\OF_DL
> And not DRM videos work, its just the DRM ones that have issues
> and i have my keys


Ese error es porque tienen la \ alreves en "DownloadPath" y no encuentra donde guardarlo ...
![2023-07-20_013750](https://github.com/sim0n00ps/OF-DL/assets/138377242/cb0521c5-7e97-4db9-9e3d-3d1ec0c7e926)

Va asi por ejemplo ... "DownloadPath": "D:/aqui" ..
![2023-07-20_015447](https://github.com/sim0n00ps/OF-DL/assets/138377242/282319d2-687d-495a-97d1-1d30c17546b0)
![2023-07-20_015603](https://github.com/sim0n00ps/OF-DL/assets/138377242/dc26c546-2bf7-43d0-b098-f6beece6fe31)

**Comment by onetwosexyho** [comment]
Okay, after some testing I seem to have solved this for myself. I receive this error if there is ANY value for the "DownloadPath" in the auth.json file. I removed any pathing for the downloads and everything works perfectly. Hope this helps for anyone else having this issue.
