### ISSUE TITLE
Unable to download posts

### ISSUE THREAD

**Issue by rando2347** [sim0n00ps/OF-DL#92]
Followed the steps, but I got this error.

Exception caught: The type initializer for 'WidevineClient.Widevine.CDM' threw an exception.

StackTrace: at WidevineClient.Widevine.CDM.OpenSession(String initDataB64, String deviceName, Boolean offline, Boolean raw)
at WidevineClient.Widevine.CDMApi.GetChallenge(String initDataB64, String certDataB64, Boolean offline, Boolean raw)
at OF_DL.Helpers.APIHelper.GetDecryptionKeyNew(Dictionary`2 drmHeaders, String licenceURL, String pssh, Auth auth)

Inner Exception:
Exception caught: No client id blob found
 StackTrace: at WidevineClient.Widevine.CDMDevice..ctor(String deviceName,

**Comment by rando2347** [comment]
> Yes you need to remove the file extensions of the 2 files you got from following the steps.

Thanks for the reply, so I just remove the .mp4 from the file while it's being downloaded?

**Comment by sim0n00ps** [comment]
No you remove the file extensions from the device_client_id_blob.bin and device_private_key.pem files so they become device_client_id_blob and device_private_key

**Comment by sim0n00ps** [comment]
Did you follow all of the steps in the readme?
