### ISSUE TITLE
Dumping keys

### ISSUE THREAD

**Issue by mediaburnwayne** [sim0n00ps/OF-DL#96]
Following the instructions I believe I have everything wired up

![wv1](https://github.com/sim0n00ps/OF-DL/assets/79545392/9693ca9f-1d2a-4fc4-9f96-ea67fc5699fe)

On the emulated device no video loads, I also tried visiting youtube but the private-keys directory never generates

![wv2](https://github.com/sim0n00ps/OF-DL/assets/79545392/fef994c3-b4e5-4a6b-a6e1-ecf987dba80e)

looking for any debug help on this

**Comment by sim0n00ps** [comment]
Did you create a Pixel 6 running Android 9 Pie?

**Comment by mediaburnwayne** [comment]
![wv3](https://github.com/sim0n00ps/OF-DL/assets/79545392/3424f841-fc26-47c3-be27-e9669f86e1c7)

**Comment by boivinx7** [comment]
Update chrome
https://www.inflectra.com/support/knowledgebase/kb276.aspx#:~:text=Uninstall%20old%20version%20of%20Chrome.&text=Restart%20the%20emulator.,that%20you%20want%20to%20install.&text=Then%20install%20it.

Latest x86
https://www.apkmirror.com/apk/google-inc/chrome/
adb -s emulator-5554 install /PATH to APK

that was needed for me

**Comment by mediaburnwayne** [comment]
Thanks will give it a try

**Comment by mediaburnwayne** [comment]
Chrome upgrade worked.
