### ISSUE TITLE
Downloading Purchased content from Deleted Account

### ISSUE THREAD

**Issue by sergheist** [sim0n00ps/OF-DL#97]
Hello! Firs of all, thank you very much for this app.

Second, I have an issue that might be very specific. I want to downloade some content I purchased long ago from an account that has now been deleted. This means the account doesn't show in my subscriptions, bookmarks or anywhere. But the videos are still present in my "Purchased" tab.

Is there any way to dl these videos specifically? Thanks again!

**Comment by sergheist** [comment]
I see you seem to have developed an app for this specifically, I will report back with my findings

**Comment by sergheist** [comment]
The issue persists since there is no Account to be found. If you could whip something up for this specific issue it would be amazing, thank you. 
![image](https://github.com/sim0n00ps/OF-DL/assets/28519799/6950dd8c-8a20-48c7-a224-992bfc223e88)

**Comment by sergheist** [comment]
![Screenshot 2023-07-20 201445](https://github.com/sim0n00ps/OF-DL/assets/28519799/451b64b2-1721-44da-ad95-6ce8226db3fd)

Leaving this here as further proof/explanation that it is content that I already paid for, I have no interest in bypassing any paywalls. Thank you once again.

**Comment by DonaldTPP** [comment]
The content should be in the paid tab unless they have changed that.

**Comment by sergheist** [comment]
It is, but I can't download it with the app. Thanks regardless

**Comment by sim0n00ps** [comment]
Does the account appear anywhere in the subscriptions tab, not even in the expired or action required list?

**Comment by sergheist** [comment]
As I showed in the pictures above, it doesn't appear anywhere. The only place where the content is present is in the "Purchased" tab of my feed.


Close friends shows as if her profile still existed, but when I open it it's empty

**Comment by sim0n00ps** [comment]
Does this content have DRM on it?

**Comment by JC02023** [comment]
better off using the aloha brower on the phone

**Comment by melithine** [comment]
To follow up, recent releases added support to scrape the purchased tab which works even with content from deleted users.
