### ISSUE TITLE
No client ID blob found

### ISSUE THREAD

**Issue by JackGitit** [sim0n00ps/OF-DL#98]
Hey can i get some help here tried everything pretty sure i renamed the files right after getting the keys....
![OF_DL_KwGuvfs6hC](https://github.com/sim0n00ps/OF-DL/assets/134113475/6db5d092-1c12-4a9c-a8e1-27d77f309b01)
![explorer_ppYjpG2O5Q](https://github.com/sim0n00ps/OF-DL/assets/134113475/f3f1344f-fa24-48bf-ac99-8bfe34cd0c08)
I put it in the cdm\devices\chrome_1610 folder... please help thanks!

**Comment by sim0n00ps** [comment]
Remove the file extensions from both of the files

**Comment by JackGitit** [comment]
> Remove the file extensions from both of the files

Brother thank you so much and thank you for the very fast reply it is working great! by the way this my first time getting these keys do u have an idea how long they last for and when I need to get new keys?

**Comment by sim0n00ps** [comment]
As long as you don't share them and let others use them they should last a long time, just as long as they don't get blocked by Google
