### ISSUE TITLE
DRM content is split in audio and video file and both are blank and wont play

### ISSUE THREAD

**Issue by NOWIMTHATBIATCH** [sim0n00ps/OF-DL#99]
I managed to make it work. I'm using OF.DL.V1.7.24. I was able to scrape everything in the messages except DRM protected content. They downloaded but wouldn't work and were split in two files and neither one will play.

**Comment by sim0n00ps** [comment]
Do you have your device_client_id_blob and device_private_key files?
Are the exe files you've downloaded correct and are the paths to those files correct?

**Comment by NOWIMTHATBIATCH** [comment]
I don't have the device client and device private stuff? How do I get them? The exes are correct I believe. I was able to run the program and scrape the messages except the DRM protected videos

> Do you have your device_client_id_blob and device_private_key files? Are the exe files you've downloaded correct and are the paths to those files correct?

**Comment by sim0n00ps** [comment]
> I don't have the device client and device private stuff? How do I get them? The exes are correct I believe. I was able to run the program and scrape the messages except the DRM protected videos
> 
> > Do you have your device_client_id_blob and device_private_key files? Are the exe files you've downloaded correct and are the paths to those files correct?

I linked a guide in the readme, if you get stuck look at some of the other issues people have opened

**Comment by NOWIMTHATBIATCH** [comment]
I gotta download that Android app? I keep freeing up space on my laptop but it stops downloading. I only have 8 gb available now. Is there no other way to get those two files?

**Comment by NOWIMTHATBIATCH** [comment]
> > I don't have the device client and device private stuff? How do I get them? The exes are correct I believe. I was able to run the program and scrape the messages except the DRM protected videos
> > > Do you have your device_client_id_blob and device_private_key files? Are the exe files you've downloaded correct and are the paths to those files correct?
> 
> I linked a guide in the readme, if you get stuck look at some of the other issues people have opened

I have followed it and it still doesnt let me download drm protected stuff. It downloads but it doesnt play and is split in two files

**Comment by sim0n00ps** [comment]
> I gotta download that Android app? I keep freeing up space on my laptop but it stops downloading. I only have 8 gb available now. Is there no other way to get those two files?

I can make them for you but I'd need your discord or telegram in order to send them to you

**Comment by NOWIMTHATBIATCH** [comment]
> > I gotta download that Android app? I keep freeing up space on my laptop but it stops downloading. I only have 8 gb available now. Is there no other way to get those two files?
> 
> I can make them for you but I'd need your discord or telegram in order to send them to you

Thank you so much! My telegram is @thrsamae
